In [1]:
user_input = input("Enter a string:")
for i in user_input:
    print(i)

A
b
h
i
s
h
e
k


In [2]:
string = "Machine Learning"
len(string)

16

In [3]:
string = "Machine Learning"
count1 = 0
for i in string:
    count1 += 1
count1

16

In [4]:
sentence = "This is orange juice"
keyword = "orange"

if keyword in sentence:
    print(f"{keyword} is present in sentence")
else:
    print(f"{keyword} is not present in sentence")

orange is present in sentence


In [5]:
input_string = input("Enter a string:")
vowels = "aeiou"
consonants = "bcdfghjklmnpqrstvwxyz"
digits = "0123456789"
vowel_count = 0 
consonant_count = 0
digit_count = 0
whitespace_count = 0
for i in input_string:
    if i.lower() in vowels:
        vowel_count += 1 
    elif i.lower() in consonants:
        consonant_count += 1
    elif i in digits:
        digit_count += 1
    elif i.isspace():
        whitespace_count += 1
print("Vowels count : ", vowel_count)
print("Consonant count : ", consonant_count)
print("Digit count : ", digit_count)
print("Whitespace count : ", whitespace_count)

Vowels count :  7
Consonant count :  10
Digit count :  0
Whitespace count :  1


In [6]:
input_string = input("Enter a string:")
uppercase_count = 0 
lowercase_count = 0 
special_count = 0
numeric_count = 0
for i in input_string:
    if i.lower() in input_string:
        lowercase_count += 1
    elif i.upper() in input_string:
        uppercase_count += 1
    elif i.isdigit():
        numeric_count += 1
    else:
        special_count += 1
print("Upper case count: ", uppercase_count)
print("Lower case count: ",lowercase_count)
print("Special count: ",special_count)
print("Number of digits: ",numeric_count)

Upper case count:  1
Lower case count:  17
Special count:  0
Number of digits:  0


In [7]:
input_string = "Hello,have a good day"
vowels = "aeiouAEIOU"
new_string = ""
for i in input_string:
    if i.isalpha() and i in vowels:
        new_string += i 
print("original string:",input_string)
print("New string with consonants deleted:",new_string)

original string: Hello,have a good day
New string with consonants deleted: eoaeaooa


In [8]:
input_string = input("Enter a string:")
index = int(input("Enter the index to be removed:"))

if index < 0 or index > len(input_string):
    print("Invalid index")
else:
    new_string = input_string[:index] + input_string[index+1:]
    print("Original string: ", input_string)
    print("New string with index removed: ", new_string)

Original string:  Abhishek Wakchaure
New string with index removed:  Abhshek Wakchaure


In [9]:
input_string = input("Enter the string:")
if len(input_string) < 2:
    print("String should have at least 2 characters")
else:
    new_string = input_string[-1] + input_string[1:-1] + input_string[0]
    print("Original string: ", input_string)
    print("String with first and last characters exchanged: ", new_string)

Original string:  Abhishek Wakchaure
String with first and last characters exchanged:  ebhishek WakchaurA


In [10]:
input_string = input("Enter the string:")
word = ""
for i in input_string:
    word = i 
    count = input_string.count(word)
    print(f"In the given string {word} is been repeated {count} times")

In the given string A is been repeated 1 times
In the given string b is been repeated 1 times
In the given string h is been repeated 3 times
In the given string i is been repeated 1 times
In the given string s is been repeated 1 times
In the given string h is been repeated 3 times
In the given string e is been repeated 2 times
In the given string k is been repeated 2 times
In the given string   is been repeated 1 times
In the given string W is been repeated 1 times
In the given string a is been repeated 2 times
In the given string k is been repeated 2 times
In the given string c is been repeated 1 times
In the given string h is been repeated 3 times
In the given string a is been repeated 2 times
In the given string u is been repeated 1 times
In the given string r is been repeated 1 times
In the given string e is been repeated 2 times


In [13]:
s = str(input("Enter a string:"))
ss = s.split()
for i in ss:
    if i in ss:
        ss.count(i)
        print(f"{i} : {s.count(i)}")
    else:
        print("Word is not repeated")

Abhishek : 1
Wakchaure : 1


In [15]:
input_string = input("Enter a string:")
result = input_string[-10:]
result

' Wakchaure'

In [16]:
input_string = input("Enter a string:")
uppercase_count = 0 
for i in input_string[:4]:
    if i.isupper():
        uppercase_count += 1
if uppercase_count >= 2:
    new_string = input_string.upper()
    print("Uppercase string:", new_string)
else:
    print("No conversion required")
    

No conversion required


In [17]:
input_string = "This is a string with a newline.\n"
result = input_string.replace("\n","")
result

'This is a string with a newline.'

In [19]:
input_string = "32.054,23"
result = input_string.replace(",","*").replace(".",",").replace("*",".")
result

'32,054.23'

In [21]:
input_string = input("Enter a string:")
char_count = {}
for i in input_string:
    if i in char_count:
        print("First repeated character:",i)
        break
    char_count[i] = 1
else:
    print("No repeated character found")

First repeated character: h


In [22]:
input_string = input("Enter a string:")
even_count = 0 
odd_count = 0
for i in input_string:
    if i.isdigit():
        num = int(i)
        if num % 2 == 0:
            even_count += 1
        else:
            odd_count += 1 
print("Even numbers count :",even_count)
print("odd number count :",odd_count)

Even numbers count : 3
odd number count : 3


In [23]:
input_string = input("Enter a string:")
if input_string.isdigit() == True:
    print("String contains only digits")
else:
    print("String contains only alphabetes")

String contains only alphabetes


In [1]:
a = "Abhishek"
k = []
for i in a:
    if a.index(i)%2!=0:
        k.append(i)
k

['b', 'i', 'k']

In [2]:
input_string = input("Enter a string:")
if len(input_string)%5==0:
    result = input_string[::-1]
    print(result)
else:
    print("Length is not a multiple of 5")

Length is not a multiple of 5


In [3]:
input_string = str(input("Enter a string:"))
output_string = []
for i in input_string:
    if i not in output_string:
        output_string.append(i)
output_string

['A', 'b', 'h', 'i', 's', 'e', 'k']

In [4]:
num = eval(input("Enter a number:"))
for i in range(0,num + 1):
    print(i*i)

0
1
4
9
16
25


In [5]:
num = eval(input("ENter a number:"))
for i in range(0,num + 1):
    print(i*i*i)

0
1
8
27
64
125


In [6]:
n = eval(input("Enter a number:"))
for i in range(2,n):
    if n % i == 0:
        print("Not prime")
        break
    else:
        print("Prime number")
        break
    

Prime number


In [1]:
list1 = [1,2,3,4,5]
max(list1)

5

In [2]:
list1 = [4,5,8,9,5,3,7]
list1.sort()
list1

[3, 4, 5, 5, 7, 8, 9]

In [3]:
list1[-1]

9

In [4]:
list1 = [4,5,8,9,5,3,7]
list1.sort(reverse=True)
list1[0]

9

In [7]:
list1 = [1,2,3,4,5]
list1[-1:] + list1[1:-1] + list1[:1]

[5, 2, 3, 4, 1]

In [9]:
list1 = [1,2,3,4,5]
list1[0],list1[1] = list1[1],list1[0]
list1

[2, 1, 3, 4, 5]

In [11]:
list1 = [1,2,3,4,5]
list1.reverse()
list1

[5, 4, 3, 2, 1]

In [13]:
list1 = [1,2,3,4,5]
result = reversed(list1)
list(result)

[5, 4, 3, 2, 1]

In [14]:
list1 = [1,2,1,2,1,1,1,3,4,4]
list1.count(1)

5

In [15]:
list1 = [1,2,1,2,1,1,1,3,4,4]
num = 1
count1 = 0 
for i in list1:
    if i == num:
        count1 += 1
count1

5

In [16]:
list1 = [1,2,3,4,5]
sum1 = 0 
for i in list1:
    sum1 += i
sum1

15

In [18]:
list1 = [1,2,3,4,5]
mul1 = 1
for i in list1:
    mul1 *= i
mul1

120

In [1]:
list1 = [1,2,3,4,5]
len(list1)

5

In [2]:
list1 = [1,2,3,4,5]
print(range(len(list1)))

range(0, 5)


In [3]:
list1 = [1,2,3,4,5]
count1 = 0
for i in list1:
    count1 += 1
count1

5

In [4]:
list1 = []
num1 = int(input("Enter the number of elements you want in the list"))
for i in range(num1):
    item = int(input("Enter the item you want in list"))
    list1.append(item)
print("List is:",list1)

num2 = int(input("Enter the number you want to remove from the list"))
for i in range(len(list1)):
    if num2 == list1[i]:
        list1.remove(i)
        print("Deleted number from the list:",num2)
        print(list1)
        break
    else:
        print("Number not found in the list")

List is: [1, 2, 3, 4]
Number not found in the list
Number not found in the list
Deleted number from the list: 3
[1, 3, 4]


In [5]:
list1 = [2,5,6,12]
list2 = []
for i in list1:
    list2.append(i*i)
list2

[4, 25, 36, 144]

In [6]:
list1 = [2,5,6,12]
list2 = []
list2 = [(i**2) for i in list1]
list2

[4, 25, 36, 144]

In [7]:
even_numbers = []
odd_numbers = []
for i in range(0,152):
    if i % 2 == 0:
        even_numbers.append(i)
    else:
        odd_numbers.append(i)
print("Even numbers: ", even_numbers)
print("*"*380)
print("Odd numbers: ", odd_numbers)

Even numbers:  [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150]
********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Odd numbers:  [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127

In [8]:
even_numbers = []
even_count = 0 
odd_numbers = []
odd_count = 0
for i in range(0,152):
    if i % 2 == 0:
        even_count += 1
        even_numbers.append(i)
    else:
        odd_count += 1
        odd_numbers.append(i)

print("Even numbers:", even_numbers)
print("*"*500)
print("Even count of numbers:", even_count)
print()
print()
print("Odd numbers:", odd_numbers)
print("*"*500)
print("Odd count of numbers:", odd_count)

Even numbers: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150]
********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Even count of numbers: 76


Odd numbers: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61

In [9]:
l1=[1,2,3,"hello","welcome",4.12,5.35]
int_list = []
string_list = []
float_list = []
for i in l1:
    if type(i) == int:
        int_list.append(i)
    elif type(i) == float:
        float_list.append(i)
    elif type(i) == str:
        string_list.append(i)
print("Integer list: ", int_list)
print()
print("Float list: ", float_list)
print()
print("String list: ", string_list)

Integer list:  [1, 2, 3]

Float list:  [4.12, 5.35]

String list:  ['hello', 'welcome']


In [10]:
l1=[1,2,3,4]
l2=[4,5,6,7]
l2.extend(l1)
l2

[4, 5, 6, 7, 1, 2, 3, 4]

In [11]:
l1=[10, 2, 4, 5, 6, 2, 9, 1, 7, 5, 4, 11, 30]
result = sorted(l1,reverse=True)
result[2]

10

In [12]:
l1=[1,2,3,4,1,2,3,4]
l2 = {}
for i in l1:
    if i in l2:
        l2[i] += 1
    else:
        l2[i] = 1
l2

{1: 2, 2: 2, 3: 2, 4: 2}

In [13]:
l1=[[1,2,3,4],1,2,3,4]
l2=[1,2,3,4]
if l2 in l1:
    print("L2 is subset of l1")
else:
    print("L2 is not a subset of l1")

L2 is subset of l1


In [14]:
l1=[10,20,30,40]
l2=[10,20,30,50]
result = set(l1)&set(l2)
result

{10, 20, 30}

In [15]:
l1=[[1,2,3],[4,5,6],[7,8,9]]
from itertools import chain
result = list(chain(*l1))
result

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
tuple1 = (2,5,3,1,6,8,4)
result = sorted(tuple1)
result

[1, 2, 3, 4, 5, 6, 8]

In [18]:
l1 = [11, 33, 50]
for i in l1:
    print(i,end="")

113350

In [19]:
l1 = [1]
if l1 == []:
    print("List is empty")
else:
    print("List is not empty")
    

List is not empty


In [20]:
l1=[1,2,3]
l2=[4,5,6]
l1+l2

[1, 2, 3, 4, 5, 6]

In [21]:
l1=[1,2,3,1,2,3,4,5,6,4,5,6]
l1.count(1)

2

In [22]:
l1=[[1,2,3],[4,5,6],[7,8,9]]
from itertools import chain
result = list(chain(*l1))
result

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [1]:
key_value={'l':11,'o':89,'a':88,'d':42,'p':5}
result = dict(sorted(key_value.items(),key=lambda x : x[0]))
result

{'a': 88, 'd': 42, 'l': 11, 'o': 89, 'p': 5}

In [2]:
dt = {'aa':44, 'bb':6, 'cc':3,'dd':12}
result = dict(sorted(dt.items(),key=lambda x : x[1]))
result

{'cc': 3, 'bb': 6, 'dd': 12, 'aa': 44}

In [3]:
dt = {'aa':44, 'bb':6, 'cc':3,'dd':12}
result = dt.values()
sum(result)

65

In [4]:
dt = {'aa':44, 'bb':6, 'cc':3,'dd':12}
sum1 = 0 
for i in dt.values():
    sum1 += i
sum1

65

In [5]:
test_dict = {"Arushi": 22, "Mani": 21, "Haritha": 21}
del test_dict["Arushi"]

In [6]:
test_dict

{'Mani': 21, 'Haritha': 21}

In [7]:
test_dict = {"Arushi": 22, "Mani": 21, "Haritha": 21}
test_dict.pop("Arushi")

22

In [8]:
test_dict

{'Mani': 21, 'Haritha': 21}

In [9]:
d1= {"Arushi": 22, "Mani": 21, "Haritha": 21,'Leena':32}
d2={'aa':44, 'bb':6, 'cc':3,'dd':12}
result = {**d1,**d2}
result

{'Arushi': 22,
 'Mani': 21,
 'Haritha': 21,
 'Leena': 32,
 'aa': 44,
 'bb': 6,
 'cc': 3,
 'dd': 12}

In [10]:
d1= {"Arushi": 22, "Mani": 21, "Haritha": 21,'Leena':32}
d2={'aa':44, 'bb':6, 'cc':3,'dd':12}
result = {**d2,**d1}
result

{'aa': 44,
 'bb': 6,
 'cc': 3,
 'dd': 12,
 'Arushi': 22,
 'Mani': 21,
 'Haritha': 21,
 'Leena': 32}

In [12]:
d1= {"Arushi": 22, "Mani": 21, "Haritha": 21,'Leena':32}
d2={'aa':44, 'bb':6, 'cc':3,'dd':12}
d1.update(d2)
d1

{'Arushi': 22,
 'Mani': 21,
 'Haritha': 21,
 'Leena': 32,
 'aa': 44,
 'bb': 6,
 'cc': 3,
 'dd': 12}

In [13]:
d1= {"Arushi": 22, "Mani": 21, "Haritha": 21,'Leena':32}
d2={'aa':44, 'bb':6, 'cc':3,'dd':12}
d2.update(d1)
d2

{'aa': 44,
 'bb': 6,
 'cc': 3,
 'dd': 12,
 'Arushi': 22,
 'Mani': 21,
 'Haritha': 21,
 'Leena': 32}

In [15]:
def calc(percent):
    if percent >= 90:
        return "A+"
    elif 80 <= percent < 90:
        return "A"
    elif 70 <= percent < 80:
        return "B"
    elif 60 <= percent < 70:
        return "C"
    elif 50 <= percent < 60:
        return "D"
    else:
        return "Fail"
    
def main():
    total_marks = 0 
    no_of_subjects = int(input("Enter the number of subjects:"))

    for i in range(no_of_subjects):
        marks = eval(input("Enter the marks of the subject:"))
        total_marks += marks

    average_percent = total_marks / no_of_subjects
    grade = calc(average_percent)
    print(f"Percentage recieved by the student is : {average_percent}")
    print(f"Grade recieved by Student is :{grade}")

if __name__ == "__main__":
    main()

Percentage recieved by the student is : 53.0
Grade recieved by Student is :D


In [17]:
words = ["listen", "silent", "enlist", "hello", "world", "act", "cat", "dog", "god"]
anagram_dict = {}
for word in words:
    sorted_word = " ".join(sorted(word))

    if sorted_word in anagram_dict:
        anagram_dict[sorted_word].append(word)
    else:
        anagram_dict[sorted_word] = [word]

anagram_dict

{'e i l n s t': ['listen', 'silent', 'enlist'],
 'e h l l o': ['hello'],
 'd l o r w': ['world'],
 'a c t': ['act', 'cat'],
 'd g o': ['dog', 'god']}

In [18]:
def check_bin(num1,num2):
    binary_num1 = bin(num1)[2:]
    binary_num2 = bin(num2)[2:]

    return sorted(binary_num1) == sorted(binary_num2)
num1 = 10 
num2 = 20 

if check_bin(num1,num2):
    print(f"The binary representation of {num1} and {num2} are anagrams")
else:
    print(f"The binary representation of {num1} and {num2} are not anagrams")

The binary representation of 10 and 20 are not anagrams


In [19]:
from collections import Counter
def largest(words):
    words_count = Counter("".join(sorted(word)) for word in words)

    result = max(words_count.values(),default=0)

    return result

word_list = ["listen", "silent", "enlist", "dog", "god", "good"]
result = largest(word_list)
result

3

In [20]:
list1 = [1, 1, 1, 5, 5, 3, 1, 3, 3, 1,4, 4, 4, 2, 2, 2, 2]
freq = {}
for i in list1:
    if i in freq:
        freq[i] += 1
    else:
        freq[i] = 1
freq

{1: 5, 5: 2, 3: 3, 4: 3, 2: 4}

In [21]:
tups = [("akash", 10), ("gaurav", 12), ("anand", 14), 
    ("suraj", 20), ("akhil", 25), ("ashish", 30)]
result = dict(tups)
result

{'akash': 10,
 'gaurav': 12,
 'anand': 14,
 'suraj': 20,
 'akhil': 25,
 'ashish': 30}

In [22]:
numbers = [2, 3, 4, 5, 6]
result = [(num, num**3) for num in numbers]
result

[(2, 8), (3, 27), (4, 64), (5, 125), (6, 216)]

In [23]:
tuples_list = [(2, 8), (3, 27), (1, 1), (5, 125), (4, 64)]

result = sorted(tuples_list,key=lambda x : x[1])

result

[(1, 1), (2, 8), (3, 27), (4, 64), (5, 125)]

In [3]:
input = "Abhishek Wakchaure"
split1 = input.split()
result = split1[::-1]
final = " ".join(result)
final

'Wakchaure Abhishek'

In [1]:
subject_marks = [("English",88) , ("Science",90) , ("Maths",97) , ("Social sciences",82)]
result = sorted(subject_marks,key=lambda x : x[1])
result

[('Social sciences', 82), ('English', 88), ('Science', 90), ('Maths', 97)]

In [2]:
list1 = [{"name" : "Nandini" , "age" : 20} ,
        {"name" : "Manjeet" , "age" : 20} ,
        {"name" : "Nikhil" , "age" : 19}]
print(sorted(list1,key=lambda x : x["age"]))

[{'name': 'Nikhil', 'age': 19}, {'name': 'Nandini', 'age': 20}, {'name': 'Manjeet', 'age': 20}]


In [3]:
print(sorted(list1,key=lambda x : x["name"]))

[{'name': 'Manjeet', 'age': 20}, {'name': 'Nandini', 'age': 20}, {'name': 'Nikhil', 'age': 19}]


In [4]:
print(sorted(list1,key=lambda x : (x["age"],x["name"])))

[{'name': 'Nikhil', 'age': 19}, {'name': 'Manjeet', 'age': 20}, {'name': 'Nandini', 'age': 20}]


In [5]:
input_numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
result = [(lambda x : x**2)(num) for num in input_numbers]
result

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [6]:
result = [(lambda x : x**3)(num) for num in input_numbers]
result

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [7]:
result = lambda x : True if x.startswith("P") else False
print(result("Python"))

True


In [9]:
result = lambda x : True if x.startswith("n") else False
print(result("Python"))

False


In [10]:
import re
result = (lambda x : re.findall("^p",x))(x = "python")
result

['p']

In [11]:
result = (lambda string : string.isdigit())(string = "1234")
result

True

In [12]:
result = (lambda string : string.isnumeric())(string = "1234")
result

True

In [13]:
result = (lambda string : string.isnumeric())(string = "1234")
result

True

In [15]:
result = (lambda string : re.findall(r"[0-9]{1,}",string))(string = "1234")
result

['1234']

In [16]:
n = 9 
f1 = 0 
f2 = 1
print(f1,f2,end=" ")
for i in range(2,n):
    f3 = f1 + f2
    f1,f2 = f2,f3
    print(f3,end=" ")

0 1 1 2 3 5 8 13 21 

In [17]:
n = 10 
f1 = 0 
f2 = 1
print(f1,f2,end=" ")
for i in range(2,n):
    f3 = f1 + f2
    f1,f2 = f2,f3
    print(f3,end=" ")

0 1 1 2 3 5 8 13 21 34 

In [18]:
list1 = [1,2,3,4]
list2 = [3,4,5,6]
result = list(filter(lambda x : x in list1,list2))
result

[3, 4]

In [20]:
list1 = [-1,2,-3,5,7,8,9,-10]
result = lambda list1 : [x for x in list1 if x >= 0] + [x for x in list1 if x < 0]
result(list1)

[2, 5, 7, 8, 9, -1, -3, -10]

In [21]:
array_nums = [1,2,3,5,7,8,9,10]
result = len(list(filter(lambda x : x%2!=0, array_nums)))
result

5

In [22]:
result = len(list(filter(lambda x : x%2==0, array_nums)))
result

3

In [23]:
list1 = [1,2,3]
list2 = [4,5,6]
result = list(map(lambda x1,x2 : x1+x2, list1, list2))
result

[5, 7, 9]

In [24]:
list1 = [13,26,38,39,57,15,17]
result = list(filter(lambda x : (x%19==0 or x%13==0),list1))
result

[13, 26, 38, 39, 57]

In [25]:
texts = ["php" , "w3r" , "Python" , "abcd" ,"Java" , "aaa"]
result = list(filter(lambda x : (x == "".join(reversed(x))),texts))
result

['php', 'aaa']

In [26]:
texts = ["php" , "w3r" , "Python" , "abcd" ,"Java" , "aaa"]
result = list(filter(lambda x : (x == "".join(reversed(x))),texts))
result

['php', 'aaa']

In [27]:
from collections import Counter
texts = ["bcda","abce","cbda","cbea","adcb"]
str1 = "abcd"
result = list(filter(lambda x : (Counter(str1) == Counter(x)),texts))
result

['bcda', 'cbda', 'adcb']

In [28]:
from collections import Counter
texts = ["bcda","abce","cbda","cbea","adcb"]
str1 = "abcd"
result = list(filter(lambda x : (Counter(str1) == Counter(x)),texts))
result

['bcda', 'cbda', 'adcb']

In [29]:
list1 = [2,3,4,5]
result = list(map(lambda x : x*5,list1))
result

[10, 15, 20, 25]

In [30]:
list1 = [-1,-2,3,4]
result = list(filter(lambda list1 : list1 > 0,list1))
result

[3, 4]

In [31]:
result = list(filter(lambda list1 : list1 < 0,list1))
result

[-1, -2]

In [32]:
result = lambda list1 : list1 == sorted(list1)
sample_list_1 = [1, 2, 3, 4, 5]
sample_list_2 = [5, 3, 1, 4, 2]
result(sample_list_1)

True

In [33]:
result(sample_list_2)

False

In [34]:
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [2,4,6,8]
result = list(filter(lambda x : x not in list2,list1))
result

[1, 3, 5, 7, 9, 10]

In [35]:
tuple_str = (("223","ABCD","33") , ("1416","EFGH","55") , ("2345","WERT","34"))
result = tuple(map(lambda x : (int(x[0]) , int(x[2])),tuple_str))
result

((223, 33), (1416, 55), (2345, 34))

In [36]:
nums = [3,4,5,8,0,3,8,5,0,3,1,5,2,3,4,2]
result = dict(map(lambda x : (x,list(nums).count(x)),nums))
result

{3: 4, 4: 2, 5: 3, 8: 2, 0: 2, 1: 1, 2: 2}

In [37]:
nums = [3,4,5,8,0,3,8,5,0,3,1,5,2,3,4,2]
result = dict(map(lambda x : (x,list(nums).count(x)),nums))
result

{3: 4, 4: 2, 5: 3, 8: 2, 0: 2, 1: 1, 2: 2}

In [38]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]
result = list(map(lambda x1,x2,x3 : x1+x2+x3,l1,l2,l3))
result

[12, 15, 18]

In [39]:
l1 = ["yellow","blue","tricolor"]
result = list(map(list,l1))
result

[['y', 'e', 'l', 'l', 'o', 'w'],
 ['b', 'l', 'u', 'e'],
 ['t', 'r', 'i', 'c', 'o', 'l', 'o', 'r']]

In [40]:
l1 = [12,15,18]
result = list(map(lambda x : x**2,l1))
result

[144, 225, 324]

In [41]:
list1 = [1, 2, 3, 4, 5]
list2 = [5, 4, 3, 2, 1]

result = list(map(lambda x,y : x+y,list1,list2))
result

[6, 6, 6, 6, 6]

In [42]:
result = list(map(lambda x,y : x-y,list1,list2))
result

[-4, -2, 0, 2, 4]

In [43]:
int_list = [1, 2, 3, 4, 5]

# Given tuple of integers
int_tuple = (6, 7, 8, 9, 10)

result = list(map(lambda x : str(x),int_list))
result

['1', '2', '3', '4', '5']

In [44]:
result = list(map(lambda x : str(x),int_tuple))
result

['6', '7', '8', '9', '10']

In [45]:
num_array = [1, 2, 3, 4, 5]

result = sum(map(lambda x : x , num_array))
result

15

In [46]:
list1 = [1, 2, 3, 4, 5]
list2 = [1, 2, 4, 8, 9]

result = sum(map(lambda x,y : x == y,list1,list2))
result

2

In [47]:
str1 = ["python","machine","learning"]
result = list(map(list,str1))
result

[['p', 'y', 't', 'h', 'o', 'n'],
 ['m', 'a', 'c', 'h', 'i', 'n', 'e'],
 ['l', 'e', 'a', 'r', 'n', 'i', 'n', 'g']]

In [48]:
list_tup = [("python","machine"),("learning","data science")]
result = list(map(" ".join,list_tup))
result

['python machine', 'learning data science']

In [49]:
l1 = [1,2,3]
l2 = [1,2,4,5,6]

result = list(filter(lambda x : x not in l1,l2))
result

[4, 5, 6]

In [50]:
l1 = [1,2,3]
l2 = [1,2,4,5,6]

result = list(filter(lambda x : x in l1,l2))
result

[1, 2]

In [51]:
l1 = [1,2,3]
result = list(filter(lambda x : x%2!=0,l1))
result

[1, 3]

In [52]:
l1 = [1,2,3]
result = list(filter(lambda x : x%2==0,l1))
result

[2]

In [1]:
with open("Abhishek.txt","w")as f:
    f.write("""Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.""")
with open("Abhishek.txt","r")as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.


In [2]:
with open("Abhishek.txt","r") as f:
    result = f.readline()
    print(result)

Data Science:



In [3]:
text = """1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing"""
with open("Abhishek.txt","a") as f:
    f.write(text)
    f.close()

In [4]:
with open("Abhishek.txt","r") as f:
    result = f.readlines()
    final = result[-2:]
    print(final)

[' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing']


In [5]:
with open("Abhishek.txt","r")as f:
    result = f.readlines()
    print(result)

['Data Science:\n', '    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge\n', '    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of \n', '    application domains.1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing']


In [6]:
with open("Abhishek.txt","r")as f:
    result = f.readlines()
    print(len(result))

7


In [7]:
with open("Abhishek.txt","r")as f:
    result = f.read()
    print(len(result))

376


In [8]:
from datetime import datetime

current_datetime = datetime.now()
print("Current datetime:",current_datetime)

current_year = current_datetime.year
print("Current year:",current_year)

month_of_year = current_datetime.strftime("%B")
print("Month of the year:",month_of_year)

week_number = current_datetime.strftime("%U")
print("Week number:",week_number)

week_day = current_datetime.strftime("%A")
print("Week day:",week_day)

day_of_year = current_datetime.strftime("%j")
print("Day of the year:",day_of_year)

day_of_month = current_datetime.strftime("%d")
print("Day of the month:",day_of_month)



Current datetime: 2024-05-27 13:41:53.245021
Current year: 2024
Month of the year: May
Week number: 21
Week day: Monday
Day of the year: 148
Day of the month: 27


In [10]:
year = int(input("Enter a year:"))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year")
else:
    print(f"{year} is not a leap year")

2024 is a leap year


In [11]:
date_format = "jan 1 2014 2:43PM"
date1 = "%b %d %Y %I:%M%p"

result = datetime.strptime(date_format,date1)
result

datetime.datetime(2014, 1, 1, 14, 43)

In [12]:
from datetime import timedelta
current_datetime = datetime.now()
result = current_datetime + timedelta(days=-5)
result

datetime.datetime(2024, 5, 22, 14, 41, 20, 793277)

In [13]:
result = datetime.now() + timedelta(days=-1)
print("Date of yesterday:",result)

result = datetime.now() + timedelta(days=0)
print("Date of today:",result)

result = datetime.now() + timedelta(days=+1)
print("Date of tommorrow:",result)

Date of yesterday: 2024-05-26 15:06:31.702538
Date of today: 2024-05-27 15:06:31.702538
Date of tommorrow: 2024-05-28 15:06:31.702538


In [14]:
current_datetime = datetime.now().date()
print(current_datetime)

2024-05-27


In [15]:
for i in range(5):
    result = current_datetime + timedelta(days=i)
    print(result)

2024-05-27
2024-05-28
2024-05-29
2024-05-30
2024-05-31


In [16]:
current_datetime = datetime.now()
print(current_datetime)
result = current_datetime.replace(microsecond=0)
print(result)

2024-05-27 15:09:09.741477
2024-05-27 15:09:09


In [17]:
import os 
os.rename("Abhishek.txt","Abhi.txt")


In [18]:
os.getcwd()

'd:\\Assignment'

In [19]:
os.listdir()

['.git',
 'Abhi.txt',
 'Assignment_1.ipynb',
 'Assignment_10.ipynb',
 'Assignment_11.ipynb',
 'Assignment_12.ipynb',
 'Assignment_2.ipynb',
 'Assignment_3.ipynb',
 'Assignment_4.ipynb',
 'Assignment_6.ipynb',
 'Assignment_7.ipynb',
 'Assignment_8.ipynb',
 'Assignment_9.ipynb',
 'python_1.ipynb',
 'README.md']

In [1]:
import re 
string = "Python and Machine Learning 7741 is syllabus of Data Science."
result = re.findall("[a-zA-Z0-9]",string)
result

['P',
 'y',
 't',
 'h',
 'o',
 'n',
 'a',
 'n',
 'd',
 'M',
 'a',
 'c',
 'h',
 'i',
 'n',
 'e',
 'L',
 'e',
 'a',
 'r',
 'n',
 'i',
 'n',
 'g',
 '7',
 '7',
 '4',
 '1',
 'i',
 's',
 's',
 'y',
 'l',
 'l',
 'a',
 'b',
 'u',
 's',
 'o',
 'f',
 'D',
 'a',
 't',
 'a',
 'S',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e']

In [2]:
string = "Python and Machine Learning is syllabus of data science and deep learning."
result = re.split(r"and",string)
result

['Python ',
 ' Machine Learning is syllabus of data science ',
 ' deep learning.']

In [3]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\bab*[a-z]*\b",str1)
result

['and']

In [4]:
sample_string = "There are 123 45 678 90 2345 67 12 345 6789 0123 three-digit"
result = re.findall(r"\b\d{3}\s\d{2}\b",sample_string)
result

['123 45', '678 90']

In [5]:
str1= "python and data pytthon science pythonnn pyyth annd pythh"
result = re.findall(r"p+",str1)
result

['p', 'p', 'p', 'p', 'p']

In [6]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
if result:
    print("Text is present")
else:
    print("Text is not present")

Text is present


In [7]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py?",str1)
result

['py', 'py']

In [8]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [10]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"\b\w*[b]{2,3}\w*\b",str1)
result

['abbbs', 'abbbsolutely', 'abbrivation']

In [11]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [12]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [13]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [14]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [15]:
str1 = 'Suceess is a jurney not a desti9nation.'
result = re.findall(r"Suceess",str1)
result

['Suceess']

In [16]:
str1 = 'new begening of LIFE .'
result = re.findall(r"LIFE.",str1)
result

['LIFE ']

In [17]:
str1 = "today is the very lazy day"
result = re.findall(r"\b\w*z\w\b",str1)
result

['lazy']

In [19]:
str1 = "we have a lazy cat"
result = re.findall(r"\b\w*z\w\b",str1)
result

['lazy']

In [20]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [21]:
str1 = "9821 maya"
result = re.findall(r"^\d*",str1)
result

['9821']

In [22]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [23]:
str1="Python is required for data science version 3.2"
result = re.findall(r"\d.\d",str1)
result

['3.2']

In [24]:
str1 = "Exercises number 1, 12, 13, and 345 are important"
result = re.findall(r"[0-9]+",str1)
result

['1', '12', '13', '345']

In [25]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for word in Searched_words:
    result = re.findall(word , Sample_text)
    print(result)

['fox']
['dog']
[]


In [26]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search(r"fox",sample_text)
result

<re.Match object; span=(16, 19), match='fox'>

In [27]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [28]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
print(len(result))
result = re.search(r"exercises",Sample_text)
print(result)

3
<re.Match object; span=(7, 16), match='exercises'>


In [29]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","_",str1)
print(result)
result = re.sub(r"[_]"," ",str1)
print(result)

The_quick_brown_fox_jumps_over_the_lazy_dog.
The quick brown fox jumps over the lazy dog.


In [30]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","",str1)
result

'Thequickbrownfoxjumpsoverthelazydog.'

In [32]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [33]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*",str1)
result

['and', 'every', 'evening']

In [34]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [35]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[., ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [36]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[., ]{2}",":",text)
result

'Python: is a general purpose interpreted.'

In [37]:
text ="""123 Python is a general-purpose, interpreted,
high-level programming language popularly used for
website development, data analytics 78 and automation."""

result = re.findall(r"\b\D{3,5}\b",text)
result

[' is a', 'high-', 'level', ' used', ' for\n', 'data ', ' and ']

In [1]:
import numpy as np 
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
arr1.nbytes

80

In [3]:
arr1 = np.zeros(10)
arr1
arr1[4] = 1
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [4]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [5]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [7]:
arr2 = list(reversed(arr1))
arr2

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [9]:
arr1 = np.random.randint(10,20,size=(2,2))
print("Array 1 :\n",arr1)
arr2 = np.random.randint(20,30,size=(2,2))
print("Array 2 :\n",arr2)

Array 1 :
 [[15 16]
 [12 13]]
Array 2 :
 [[28 20]
 [26 27]]


In [10]:
add1 = arr1 + arr2
add1

array([[43, 36],
       [38, 40]])

In [11]:
sub1 = arr1 - arr2
sub1

array([[-13,  -4],
       [-14, -14]])

In [12]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
print(arr1)
arr1.round()

[1.3 1.8 2.3 3.9 1.  4.  1.9 9.  0.3]


array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [13]:
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [14]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [15]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
result = np.mean(arr1,axis=1)
print("Mean across row >>",result)
result = np.mean(arr1,axis=0)
print("Mean across column >>",result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean across row >> [2. 5. 8.]
Mean across column >> [4. 5. 6.]


In [16]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [17]:
arr1 = np.arange(9).reshape(3,3)
print("Matrix :\n",arr1)

Matrix :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array is:\n",arr1)
arr1[:: , ::-1]

Array is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [20]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array is:\n",arr1)
arr1[::-1]

Array is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [21]:
result = np.nonzero([1,2,0,0,4,0])
result

(array([0, 1, 4], dtype=int64),)

In [22]:
arr1 = np.array([[1,2],[3,4]])
print("Array is:\n",arr1)
result = np.linalg.det(arr1)
print(result)

Array is:
 [[1 2]
 [3 4]]
-2.0000000000000004


In [23]:
arr1 = np.array([[2,3],[3,9]])
print("Array is:\n",arr1)
result = np.linalg.inv(arr1)
result

Array is:
 [[2 3]
 [3 9]]


array([[ 1.        , -0.33333333],
       [-0.33333333,  0.22222222]])

In [24]:
arr1 = np.random.randint(10,30,size=(30))
print("Array is:\n",arr1)
result = np.mean(arr1)
result

Array is:
 [16 28 16 14 19 13 20 29 17 10 19 28 15 10 14 16 25 16 15 10 20 20 25 15
 21 19 16 25 19 23]


18.433333333333334

In [25]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array :\n",arr1)
result = np.where(arr1 > 5)
print("Result :\n",result)

Array :
 [ 1  2  3  4  5  6  7  8  9 10]
Result :
 (array([5, 6, 7, 8, 9], dtype=int64),)


In [26]:
arr1 = np.random.random((3,3,3))
print("Array :\n",arr1)

Array :
 [[[0.89426464 0.52680348 0.15860701]
  [0.84564866 0.00415103 0.98939588]
  [0.09714773 0.77178772 0.79202417]]

 [[0.4380911  0.96256178 0.0102635 ]
  [0.75105657 0.09443937 0.4353997 ]
  [0.51092176 0.82350932 0.51147477]]

 [[0.27701513 0.56091573 0.24862029]
  [0.28812328 0.98151775 0.13146615]
  [0.99610581 0.00641703 0.88087299]]]


In [27]:
arr1 = np.random.rand(10,10)
print("Array:\n",arr1)
print("Maximum value:",np.max(arr1))
print("Minimum value:",np.min(arr1))

Array:
 [[0.28955669 0.36500959 0.52076947 0.65617391 0.7803091  0.00552527
  0.35774601 0.70255522 0.90296644 0.86299399]
 [0.42650031 0.79939802 0.01885559 0.71941592 0.88948431 0.57008562
  0.57385462 0.26224475 0.93218346 0.61091759]
 [0.15473166 0.36383118 0.10606985 0.97028158 0.08084232 0.46796767
  0.06753869 0.18821831 0.40475575 0.22003702]
 [0.13642278 0.30634443 0.59341459 0.91200028 0.24063951 0.59967818
  0.699294   0.41296624 0.83748057 0.8434114 ]
 [0.36182913 0.65794456 0.71764439 0.22881552 0.89998589 0.59327395
  0.36267363 0.13014727 0.14132181 0.40316848]
 [0.30291137 0.53250442 0.12831634 0.75532944 0.03122489 0.85865682
  0.7708957  0.61876903 0.99634386 0.84132793]
 [0.87451065 0.42851706 0.0413137  0.77075983 0.75411505 0.86452397
  0.42488741 0.40881821 0.62516932 0.29820192]
 [0.41863024 0.01530623 0.90499494 0.97954509 0.99069559 0.09382218
  0.67347862 0.12047924 0.38858971 0.87748423]
 [0.8916221  0.20673075 0.87683741 0.70402398 0.28996546 0.27147066
  0.

In [28]:
arr1 = np.ones((10,10))
print("Array:\n",arr1)
arr1[1:-1 , 1:-1] = 0
arr1

Array:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4])
print(arr1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [30]:
arr1 = np.eye(3,3)
print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
arr1 = np.random.randint(1,9,size=(5,3))
arr2 = np.random.randint(1,9,size=(3,2))
result = np.dot(arr1, arr2)
result

array([[ 89,  51],
       [ 68,  33],
       [ 80,  36],
       [101,  57],
       [ 60,  40]])

In [32]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
result = np.where((arr1>=3) & (arr1<=8),-1*arr1,arr1)
result

array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [33]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
rounded_up = np.ceil(arr1)
rounded_down = np.floor(arr1)
print("Original array :" , arr1)
print("Rounded up :\n" , rounded_up)
print("Rounded down :\n" , rounded_down)

Original array : [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]
Rounded up :
 [[2. 3.]
 [4. 6.]]
Rounded down :
 [[1. 2.]
 [3. 5.]]


In [34]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1, arr2)
result

array([4, 5, 6])

In [35]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [36]:
arr1 = np.random.randint(1,10,size=10)
print("Array:",arr1)
result = np.sort(arr1)
print("Result:",result)

Array: [1 7 6 8 1 6 9 4 7 8]
Result: [1 1 4 6 6 7 7 8 8 9]


In [37]:
arr1 = np.zeros((5,5))
print("Array:\n",arr1)
arr2 = arr1 + np.arange(5)
arr2

Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [38]:
arr1 = np.random.randint(0,5,size=(5))
arr2 = np.random.randint(0,5,size=(5))
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [39]:
np.allclose(arr1, arr2)

False

In [40]:
arr1 = np.random.randint(1,10,size=(10))
print("Array:\n",arr1)
result = np.where(arr1 == np.max(arr1) , 0 , arr1)
result

Array:
 [8 6 3 9 8 2 8 1 9 1]


array([8, 6, 3, 0, 8, 2, 8, 1, 0, 1])

In [41]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr1):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

In [42]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

(0, 0) index has 1 values
(0, 1) index has 2 values
(0, 2) index has 3 values
(1, 0) index has 4 values
(1, 1) index has 5 values
(1, 2) index has 6 values
(2, 0) index has 7 values
(2, 1) index has 8 values
(2, 2) index has 9 values


In [43]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array :\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array :
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [44]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.mean(arr1)
result

5.5

In [45]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.median(arr1))

5.5


In [46]:
arr1 = np.random.randint(1,10,size=10)
print(arr1)
print(np.std(arr1))

[8 1 2 9 8 6 9 6 7 9]
2.7294688127912363


In [47]:
from scipy.stats import mode
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = mode(arr1)
result

ModeResult(mode=1, count=1)

In [48]:
result = np.around(5.43224 , 3)
result

5.432

In [49]:
arr1 = np.array([[2,3],[3,4]])
result = np.linalg.inv(arr1)
result

array([[-4.,  3.],
       [ 3., -2.]])

In [50]:
x = np.array([1,2,3])
y = np.array([4,5,6])
result = np.cov(x,y)
result

array([[1., 1.],
       [1., 1.]])

In [51]:
arr1 = np.array([1,1,2,2,3,4,5,6,7,8,9,6,4,3,6,7])
result = mode(arr1)
result

ModeResult(mode=6, count=3)

In [53]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:",arr1)
arr2 = np.reshape(arr1 , (2,5,1))
print("Array:\n",arr2)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Array:
 [[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]


In [54]:
arr1 = np.random.randint(1,10,size=(1,2,3,4))
print("Array:\n",arr1)
arr2 = np.reshape(arr1 , (6,4))
print("Array:\n",arr2)

Array:
 [[[[5 8 6 2]
   [9 3 4 9]
   [4 6 8 5]]

  [[6 2 3 5]
   [6 5 1 4]
   [9 2 4 1]]]]
Array:
 [[5 8 6 2]
 [9 3 4 9]
 [4 6 8 5]
 [6 2 3 5]
 [6 5 1 4]
 [9 2 4 1]]


In [55]:
arr1 = np.zeros(10,dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [56]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
arr1.shape

(3, 4)

In [1]:
import numpy as np
import pandas as pd
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [2]:
list1 = [[1,2,3],[4,5,6]]
pd.DataFrame(list1)

0  1  2
0  1  2  3
1  4  5  6

In [3]:
df = pd.DataFrame(columns=list("ABC"),index=list("PQR"))
df

A    B    C
P  NaN  NaN  NaN
Q  NaN  NaN  NaN
R  NaN  NaN  NaN

In [4]:
df = pd.DataFrame(columns=list("ABC"),index=list("PQR"))
if df.isnull:
    print("Dataframe is null")
else:
    print("Dataframe is not null")

Dataframe is null


In [5]:
arr1 = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(arr1)
df

0  1  2
0  1  2  3
1  4  5  6

In [6]:
list1 = [[1,2,3],[4,5,6]]
df = pd.DataFrame(list1)
df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
tuple1 = (1,2,3,4,5,6)
df = pd.DataFrame(tuple1)
df

0
0  1
1  2
2  3
3  4
4  5
5  6

In [8]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [9]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]
df = pd.DataFrame(l1,columns=list("ABC"))
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [10]:
df = pd.DataFrame(np.random.randint(10,30,size=(5,6)))
df

0   1   2   3   4   5
0  15  16  23  25  16  24
1  18  20  21  28  29  19
2  20  14  21  22  23  14
3  23  18  22  13  25  10
4  20  10  17  18  13  12

In [11]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(arr1)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [14]:
s1 = pd.Series([1,2,3,4,5,6])
print(s1)
s2 = s1.copy()
s2[0] = 50
print(s2)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
0    50
1     2
2     3
3     4
4     5
5     6
dtype: int64


In [15]:
df = pd.DataFrame(np.full((4,5),6))
df

0  1  2  3  4
0  6  6  6  6  6
1  6  6  6  6  6
2  6  6  6  6  6
3  6  6  6  6  6

In [16]:
df["5"] = [1,2,3,4]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4

In [17]:
df.loc[4] = [1,2,3,4,5,6]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4
4  1  2  3  4  5  6

In [18]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(arr1,index=list("ABC"))
df

0  1  2
A  1  2  3
B  4  5  6
C  7  8  9

In [19]:
arr1 = np.random.randint(0,20,size=(4,4))
df = pd.DataFrame(arr1,columns=list("ABCD"),index=list("PQRS"))
print(df)
df.rename({"A":"a","B":"b","C":"c","D":"d"},axis=1,inplace=True)
df.rename({"P":"p","Q":"q","R":"r","S":"s"},axis=0,inplace=True)
df

   A   B   C   D
P  7   1  15  11
Q  0  13   6  10
R  3   3  13  13
S  2   9  19  15


a   b   c   d
p  7   1  15  11
q  0  13   6  10
r  3   3  13  13
s  2   9  19  15

In [20]:
for i in df.items():
    print(i)

('a', p    7
q    0
r    3
s    2
Name: a, dtype: int32)
('b', p     1
q    13
r     3
s     9
Name: b, dtype: int32)
('c', p    15
q     6
r    13
s    19
Name: c, dtype: int32)
('d', p    11
q    10
r    13
s    15
Name: d, dtype: int32)


In [21]:
for i in df.iterrows():
    print(i)

('p', a     7
b     1
c    15
d    11
Name: p, dtype: int32)
('q', a     0
b    13
c     6
d    10
Name: q, dtype: int32)
('r', a     3
b     3
c    13
d    13
Name: r, dtype: int32)
('s', a     2
b     9
c    19
d    15
Name: s, dtype: int32)


In [22]:
df = pd.DataFrame(np.random.randint(1,10,size=(4,4)))
print(df)
arr1 = df.values
arr1

   0  1  2  3
0  5  8  3  2
1  4  8  5  8
2  1  3  7  6
3  7  5  2  2


array([[5, 8, 3, 2],
       [4, 8, 5, 8],
       [1, 3, 7, 6],
       [7, 5, 2, 2]])

In [23]:
df = pd.DataFrame(np.random.randint(1,10,size=(4,4)))
arr1 = df.values
arr1.tolist()

[[9, 3, 9, 8], [3, 9, 6, 1], [1, 3, 8, 2], [5, 8, 1, 6]]

In [24]:
df

0  1  2  3
0  9  3  9  8
1  3  9  6  1
2  1  3  8  2
3  5  8  1  6

In [25]:
df.reset_index(drop=True)

0  1  2  3
0  9  3  9  8
1  3  9  6  1
2  1  3  8  2
3  5  8  1  6

In [26]:
df = pd.DataFrame(np.random.randint(1,10,size=(4,4)))
print(df)
df.shape

   0  1  2  3
0  9  4  9  1
1  2  6  3  2
2  5  1  1  1
3  6  8  3  7


(4, 4)

In [27]:
df.shape[1]

4

In [28]:
s1 = pd.Series(np.arange(50,60))
s2 = pd.Series(np.arange(25,35))
result = s1 + s2
result

0    75
1    77
2    79
3    81
4    83
5    85
6    87
7    89
8    91
9    93
dtype: int32

In [29]:
result = s1 - s2
result

0    25
1    25
2    25
3    25
4    25
5    25
6    25
7    25
8    25
9    25
dtype: int32

In [30]:
result = s1 * s2
result

0    1250
1    1326
2    1404
3    1484
4    1566
5    1650
6    1736
7    1824
8    1914
9    2006
dtype: int32

In [31]:
result = s1 / s2
result

0    2.000000
1    1.961538
2    1.925926
3    1.892857
4    1.862069
5    1.833333
6    1.806452
7    1.781250
8    1.757576
9    1.735294
dtype: float64

In [32]:
df = pd.read_excel("Sample1.xlsx")
df

Unnamed: 0 First Name   Last Name  Gender        Country  Age  \
0             1      Dulce       Abril  Female  United States   32   
1             2       Mara   Hashimoto  Female  Great Britain   25   
2             3     Philip        Gent    Male         France   36   
3             4   Kathleen      Hanner  Female  United States   25   
4             5    Nereida     Magwood  Female  United States   58   
..          ...        ...         ...     ...            ...  ...   
995         996       Roma  Lafollette  Female  United States   34   
996         997     Felisa        Cail  Female  United States   28   
997         998   Demetria       Abbey  Female  United States   32   
998         999     Jeromy        Danz    Male  United States   39   
999        1000   Rasheeda      Alkire  Female  United States   29   

           Date    Id  
0    15/10/2017  1562  
1    16/08/2016  1582  
2    21/05/2015  2587  
3    15/10/2017  3549  
4    16/08/2016  2468  
..          ...   ...  
995  15/10/2017  2654  
996  16/08/2016  6525  
997  21/05/2015  3265  
998  15/10/2017  3265  
999  16/08/2016  6125  

[1000 rows x 8 columns]

In [33]:
df.columns

Index(['Unnamed: 0', 'First Name', 'Last Name', 'Gender', 'Country', 'Age',
       'Date', 'Id'],
      dtype='object')

In [34]:
df[['First Name', 'Last Name']]

First Name   Last Name
0        Dulce       Abril
1         Mara   Hashimoto
2       Philip        Gent
3     Kathleen      Hanner
4      Nereida     Magwood
..         ...         ...
995       Roma  Lafollette
996     Felisa        Cail
997   Demetria       Abbey
998     Jeromy        Danz
999   Rasheeda      Alkire

[1000 rows x 2 columns]

In [35]:
df["Age"].mean()

33.26

In [36]:
df["Age"].median()

32.0

In [37]:
df["Age"].sum()

33260

In [38]:
df["Age"].min()

21

In [39]:
df["Age"].max()

58

In [40]:
df = pd.read_csv("titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [41]:
df.groupby(df["Embarked"]).get_group("S")

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
..           ...       ...     ...   
883          884         0       2   
884          885         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   

                                             Name  Gender   Age  SibSp  Parch  \
0                         Braund, Mr. Owen Harris    male  22.0      1      0   
2                          Heikkinen, Miss. Laina  female   NaN      0      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1      0   
4                        Allen, Mr. William Henry    male   NaN      0      0   
6                         McCarthy, Mr. Timothy J    male  54.0      0      0   
..                                            ...     ...   ...    ...    ...   
883                 Banfield, Mr. Frederick James    male  28.0      0      0   
884                        Sutehall, Mr. Henry Jr    male  25.0      0      0   
886                         Montvila, Rev. Juozas    male  27.0      0      0   
887                  Graham, Miss. Margaret Edith  female  19.0      0      0   
888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500   NaN        S  
2    STON/O2. 3101282   7.9250   NaN        S  
3              113803  53.1000  C123        S  
4              373450   8.0500   NaN        S  
6               17463  51.8625   E46        S  
..                ...      ...   ...      ...  
883  C.A./SOTON 34068  10.5000   NaN        S  
884   SOTON/OQ 392076   7.0500   NaN        S  
886            211536  13.0000   NaN        S  
887            112053  30.0000   B42        S  
888        W./C. 6607  23.4500   NaN        S  

[644 rows x 12 columns]

In [42]:
arr1 = np.random.randint(1,20,size=(4,2))
df = pd.DataFrame(arr1)
print(df)
df.apply(np.sqrt)

    0   1
0  15  11
1  19   9
2  19   2
3  19  12


0         1
0  3.872983  3.316625
1  4.358899  3.000000
2  4.358899  1.414214
3  4.358899  3.464102

In [43]:
df = pd.DataFrame(np.random.randint(1,9,size=(3,4)))
df

0  1  2  3
0  4  6  6  5
1  5  3  5  1
2  7  2  4  7

In [44]:
df.apply(lambda x : x**2)

0   1   2   3
0  16  36  36  25
1  25   9  25   1
2  49   4  16  49

In [45]:
df

0  1  2  3
0  4  6  6  5
1  5  3  5  1
2  7  2  4  7

In [46]:
df.apply(lambda x : x**3)

0    1    2    3
0   64  216  216  125
1  125   27  125    1
2  343    8   64  343

In [47]:
df = pd.read_csv("diabetes.csv")
df.head(3)

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   52        1

In [48]:
df.tail(3)

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
765      121             72             23      112  26.2   
766      126             60              0        0  30.1   
767       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Glucose                   768 non-null    int64  
 1   BloodPressure             768 non-null    int64  
 2   SkinThickness             768 non-null    int64  
 3   Insulin                   768 non-null    int64  
 4   BMI                       768 non-null    float64
 5   DiabetesPedigreeFunction  768 non-null    float64
 6   Age                       768 non-null    int64  
 7   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 48.1 KB


In [50]:
df.describe()

Glucose  BloodPressure  SkinThickness     Insulin         BMI  \
count  768.000000     768.000000     768.000000  768.000000  768.000000   
mean   121.117188      69.076823      20.536458   79.799479   31.992578   
std     31.805091      19.367794      15.952218  115.244002    7.884160   
min      0.000000       0.000000       0.000000    0.000000    0.000000   
25%     99.000000      62.000000       0.000000    0.000000   27.300000   
50%    117.000000      72.000000      23.000000   30.500000   32.000000   
75%    142.000000      80.000000      32.000000  127.250000   36.600000   
max    199.000000     122.000000      99.000000  846.000000   67.100000   

       DiabetesPedigreeFunction         Age     Outcome  
count                768.000000  768.000000  768.000000  
mean                   0.471876   33.243490    0.348958  
std                    0.331329   11.758182    0.476951  
min                    0.078000   21.000000    0.000000  
25%                    0.243750   24.000000    0.000000  
50%                    0.372500   29.000000    0.000000  
75%                    0.626250   41.000000    1.000000  
max                    2.420000   81.000000    1.000000

In [51]:
data1 = {"NAME" : ["Rudranshi","Sanvi","Swati","Shiva"]}
df = pd.DataFrame(data1)
df["NAME"].apply(lambda x : x.istitle())

0    True
1    True
2    True
3    True
Name: NAME, dtype: bool

In [52]:
d1 = {"Employee":["Saniya","Sara","Alexa","Jenny"]}
df = pd.DataFrame(d1)
d2 = {"Saniya": "Software Developer" , "Sara":"Developer" , "Alexa":"Assistant"}
df["Designation"] = df["Employee"].map(d2)
df

Employee         Designation
0   Saniya  Software Developer
1     Sara           Developer
2    Alexa           Assistant
3    Jenny                 NaN

In [53]:
arr1 = np.random.randint(1,10,size=(5,5))
df = pd.DataFrame(arr1,columns=list("ABCDE"))
df

A  B  C  D  E
0  2  7  3  3  7
1  6  4  5  9  3
2  4  6  1  2  3
3  7  4  3  8  8
4  9  9  6  2  1

In [54]:
df["I"] = [1,2,3,4,5]
df

A  B  C  D  E  I
0  2  7  3  3  7  1
1  6  4  5  9  3  2
2  4  6  1  2  3  3
3  7  4  3  8  8  4
4  9  9  6  2  1  5

In [55]:
df

A  B  C  D  E  I
0  2  7  3  3  7  1
1  6  4  5  9  3  2
2  4  6  1  2  3  3
3  7  4  3  8  8  4
4  9  9  6  2  1  5

In [56]:
df.insert(1,"H",[1,1,2,2,1])
df

A  H  B  C  D  E  I
0  2  1  7  3  3  7  1
1  6  1  4  5  9  3  2
2  4  2  6  1  2  3  3
3  7  2  4  3  8  8  4
4  9  1  9  6  2  1  5

In [57]:
df.drop("A",axis=1,inplace=True)

In [58]:
df

H  B  C  D  E  I
0  1  7  3  3  7  1
1  1  4  5  9  3  2
2  2  6  1  2  3  3
3  2  4  3  8  8  4
4  1  9  6  2  1  5

In [59]:
df.drop(2,axis=0,inplace=True)
df

H  B  C  D  E  I
0  1  7  3  3  7  1
1  1  4  5  9  3  2
3  2  4  3  8  8  4
4  1  9  6  2  1  5

In [60]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([4,5,6,7,8])
s11 = set(s1)
s22 = set(s2)
result = s11.symmetric_difference(s22)
result

{1, 2, 3, 6, 7, 8}

In [61]:
s1 = pd.Series([1,2,3,4,5])
print("Median:",s1.median())
print("Minimum:",s1.min())
print("25th percentile:",s1.quantile(0.25))
print("75th percentile:",s1.quantile(0.75))
print("Maximum:",s1.max())

Median: 3.0
Minimum: 1
25th percentile: 2.0
75th percentile: 4.0
Maximum: 5


In [62]:
df = pd.DataFrame(np.random.randint(10,50,size=(4,4)) , columns=list("CABD") , index=list("xzvs"))
df

C   A   B   D
x  29  14  17  46
z  46  42  36  19
v  11  31  33  14
s  18  36  41  47

In [63]:
df.sort_index()

C   A   B   D
s  18  36  41  47
v  11  31  33  14
x  29  14  17  46
z  46  42  36  19

In [64]:
df.sort_index(axis=1)

A   B   C   D
x  14  17  29  46
z  42  36  46  19
v  31  33  11  14
s  36  41  18  47

In [65]:
df.sort_values("D")

C   A   B   D
v  11  31  33  14
z  46  42  36  19
x  29  14  17  46
s  18  36  41  47

In [66]:
df = pd.DataFrame({"A" : [1,1,3,4,5],
                   "B" : [1,1,3,4,5],
                   "C" : [1,1,3,4,5],
                   "D" : [1,1,3,4,5]})
df

A  B  C  D
0  1  1  1  1
1  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [67]:
df.drop_duplicates()

A  B  C  D
0  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [68]:
data = {'Full Name': ['John Doe', 'Jane Smith', 'Bob Johnson']}
df = pd.DataFrame(data)
print(df)
df[["First Name","Last Name"]] = df["Full Name"].str.split(expand=True)
df

     Full Name
0     John Doe
1   Jane Smith
2  Bob Johnson


Full Name First Name Last Name
0     John Doe       John       Doe
1   Jane Smith       Jane     Smith
2  Bob Johnson        Bob   Johnson