In [1]:
with open("Abhishek.txt","r")as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing


In [2]:
with open("Abhishek.txt","r")as f:
    result = f.readline()
    print(result)

Data Science:



In [3]:
text = """1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing"""
with open("Abhishek.txt","a")as f:
    f.write(text)
    f.close()


In [4]:
with open("Abhishek.txt","r")as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing


In [5]:
with open("Abhishek.txt","r")as f:
    result = f.readlines()
    final = result[-2:]
    print(final)

[' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing']


In [6]:
with open("Abhishek.txt","r")as f:
    result = f.readlines()
    print(result)

['Data Science:\n', '    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge\n', '    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of \n', '    application domains.1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing']


In [7]:
with open("Abhishek.txt","r")as f:
    result = f.readlines()
    print(len(result))

19


In [8]:
with open("Abhishek.txt","r")as f:
    result = f.read()
    print(len(result))

768


In [9]:
import shutil
shutil.copy("Abhishek.txt","Abhi.txt")

'Abhi.txt'

In [11]:
with open("Abhi.txt","r") as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing


In [12]:
from datetime import datetime

current_datetime = datetime.now()
print("Current datetime: ",current_datetime)

current_year = current_datetime.year
print("Current year: ",current_year)

month_of_year = current_datetime.strftime("%B")
print("Month of year: ",month_of_year)

week_number = current_datetime.strftime("%U")
print("Week number: ",week_number)

weekday = current_datetime.strftime("%A")
print("Week day: ",weekday)

day_of_year = current_datetime.strftime("%j")
print("Day of year: ",day_of_year)

day_of_month = current_datetime.strftime("%d")
print("Day of month: ",day_of_month)



Current datetime:  2024-07-08 07:18:02.759697
Current year:  2024
Month of year:  July
Week number:  27
Week day:  Monday
Day of year:  190
Day of month:  08


In [13]:
year = int(input("Enter a year:"))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year")
else:
    print(f"{year} is not a leap year")

2026 is not a leap year


In [15]:
date_format = "jan 1 2014 2:43PM"
date1 = "%b %d %Y %I:%M%p"
result = datetime.strptime(date_format,date1)
print(result)

2014-01-01 14:43:00


In [16]:
from datetime import timedelta

In [18]:
current_datetime = datetime.now()
result = current_datetime + timedelta(days=-5)
print(result)

2024-07-03 07:44:16.256132


In [20]:
result = datetime.now() + timedelta(days=-1)
print("Date of yesterday: ", result)
result = datetime.now() + timedelta(days=0)
print("Date of Today: ", result)
result = datetime.now() + timedelta(days=+1)
print("Date of tomorrow: ", result)

Date of yesterday:  2024-07-07 07:47:03.575357
Date of Today:  2024-07-08 07:47:03.575866
Date of tomorrow:  2024-07-09 07:47:03.575866


In [21]:
current_datetime = datetime.now().date()
print("Current date: ", current_datetime)

Current date:  2024-07-08


In [22]:
for i in range(5):
    result = current_datetime + timedelta(days=i)
    print("Next 5 days starting from now: ", result)

Next 5 days starting from now:  2024-07-08
Next 5 days starting from now:  2024-07-09
Next 5 days starting from now:  2024-07-10
Next 5 days starting from now:  2024-07-11
Next 5 days starting from now:  2024-07-12


In [23]:
current_datetime = datetime.now()
print("Current date: ", current_datetime)
result = current_datetime.replace(microsecond=0)
print("Date without microsecond: ", result)

Current date:  2024-07-08 07:52:13.879273
Date without microsecond:  2024-07-08 07:52:13


In [24]:
result = datetime(2024,8,12)
print(result)
final = result.strftime("%a %d %b %Y %U")
print(final)

2024-08-12 00:00:00
Mon 12 Aug 2024 32


In [25]:
import os 
with open("Pablo.txt","w")as f:
    f.write("He is a smart boy")
    f.close()

with open("Pablo.txt","r")as f:
    result = f.read()
    print(result)

He is a smart boy


In [26]:
os.rename("Pablo.txt","Escobar.txt")

In [27]:
os.getcwd()

'd:\\Assignment'

In [28]:
os.listdir()

['.git',
 'Abhi.txt',
 'Abhishek.txt',
 'Adaboost_Ass.ipynb',
 'Assignment_1.ipynb',
 'Assignment_10.ipynb',
 'Assignment_11.ipynb',
 'Assignment_12.ipynb',
 'Assignment_2.ipynb',
 'Assignment_3.ipynb',
 'Assignment_4.ipynb',
 'Assignment_6.ipynb',
 'Assignment_7.ipynb',
 'Assignment_8.ipynb',
 'Assignment_9.ipynb',
 'Assignment_DT.ipynb',
 'Assignment_KNN.ipynb',
 'autos_dataset.csv',
 'Bengaluru_House_Data.csv',
 'Book2.csv',
 'Boston.csv',
 'deadshot.txt',
 'diabetes.csv',
 'Emp_data.csv',
 'Emp_Records.xlsx',
 'emp_test1.csv',
 'Escobar.txt',
 'heart.csv',
 'Iris.csv',
 'Linear_reg_theory.ipynb',
 'loan_data.csv',
 'Logistic_reg_assignment.ipynb',
 'movies_data.csv',
 'NLP_lec2.ipynb',
 'python_1.ipynb',
 'Python_2.ipynb',
 'python_3.ipynb',
 'Python_4.ipynb',
 'README.md',
 'Sample1.xlsx',
 'Social_Network_Ads.csv',
 'student.csv',
 'titanic.csv',
 'weather.csv']

In [29]:
try:
    print("hello")
except:
    print("Bye")

hello


In [1]:
import re
string = "Python and Machine Learning 7741 is syllabus of Data Science."
result = re.findall(r"[a-zA-Z0-9]",string)
result

['P',
 'y',
 't',
 'h',
 'o',
 'n',
 'a',
 'n',
 'd',
 'M',
 'a',
 'c',
 'h',
 'i',
 'n',
 'e',
 'L',
 'e',
 'a',
 'r',
 'n',
 'i',
 'n',
 'g',
 '7',
 '7',
 '4',
 '1',
 'i',
 's',
 's',
 'y',
 'l',
 'l',
 'a',
 'b',
 'u',
 's',
 'o',
 'f',
 'D',
 'a',
 't',
 'a',
 'S',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e']

In [2]:
string = "Python and Machine Learning is syllabus of data science and deep learning."
result = re.split(r"and",string)
result

['Python ',
 ' Machine Learning is syllabus of data science ',
 ' deep learning.']

In [3]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\ba..\b",str1)
result

['and']

In [4]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\bab*[a-z]*\b",str1)
result

['and']

In [5]:
sample_string = "There are 123 45 678 90 2345 67 12 345 6789 0123 three-digit"
result = re.findall(r"\b\d{3}\s\d{2}\b",sample_string)
result

['123 45', '678 90']

In [6]:
str1= "python and data pytthon science pythonnn pyyth annd pythh"
result = re.findall(r"p+",str1)
result

['p', 'p', 'p', 'p', 'p']

In [7]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
result

['INFORM', 'inform']

In [8]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py?",str1)
result

['py', 'py']

In [9]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [10]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"\b\w*[b]{2,3}\w*\b",str1)
result

['abbbs', 'abbbsolutely', 'abbrivation']

In [11]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [12]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [13]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [14]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [15]:
str1 = 'Suceess is a jurney not a desti9nation.'
result = re.findall(r"Suceess",str1)
result

['Suceess']

In [16]:
str1 = 'new begening of LIFE .'
result = re.findall(r"LIFE .",str1)
result

['LIFE .']

In [17]:
str1 = "today is the very lazy day"
result = re.findall(r"\b\w*z\w\b",str1)
result

['lazy']

In [18]:
str1 = "we have a lazy cat"
result = re.findall(r"[a-y]*z[a-y]",str1)
result

['lazy']

In [19]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [20]:
str1 = "9821 maya"
result = re.findall(r"^9",str1)
result

['9']

In [21]:
str1 = "9821 maya"
result = re.findall(r"^\d*",str1)
result

['9821']

In [22]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [29]:
str1="Python is required for data science version 3.2"
result = re.findall(r"\d..\b",str1)
result

['3.2']

In [30]:
str1 = "Exercises number 1, 12, 13, and 345 are important"
result = re.findall(r"[0-9]+",str1)
result

['1', '12', '13', '345']

In [31]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for word in Searched_words:
    result = re.findall(word,Sample_text)
    print(result)

['fox']
['dog']
[]


In [32]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search(r"fox",sample_text)
result

<re.Match object; span=(16, 19), match='fox'>

In [33]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [34]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
print(len(result))
result = re.search(r"exercises",Sample_text)
print(result)

3
<re.Match object; span=(7, 16), match='exercises'>


In [35]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","_",str1)
print(result)
result = re.sub(r"[_]","",result)
print(result)

The_quick_brown_fox_jumps_over_the_lazy_dog.
Thequickbrownfoxjumpsoverthelazydog.


In [36]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","",str1)
result

'Thequickbrownfoxjumpsoverthelazydog.'

In [37]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [38]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*",str1)
result

['and', 'every', 'evening']

In [39]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [40]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[,. ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [41]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[,. ]{2}",":",text)
result

'Python: is a general purpose interpreted.'

In [42]:
text ="""123 Python is a general-purpose, interpreted,
high-level programming language popularly used for
website development, data analytics 78 and automation."""

result = re.findall(r"\b\D{3,5}\b",text)
result

[' is a', 'high-', 'level', ' used', ' for\n', 'data ', ' and ']

In [1]:
import numpy as np 
import pandas as pd


In [4]:
df = pd.read_table("Restaurant_Reviews.tsv")
df

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [5]:
df["Review"]

0                               Wow... Loved this place.
1                                     Crust is not good.
2              Not tasty and the texture was just nasty.
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
                             ...                        
995    I think food should have flavor and texture an...
996                             Appetite instantly gone.
997    Overall I was not impressed and would not go b...
998    The whole experience was underwhelming, and I ...
999    Then, as if I hadn't wasted enough of my life ...
Name: Review, Length: 1000, dtype: object

In [6]:
lower_casing = [word.lower() for word in df["Review"]]
lower_casing

['wow... loved this place.',
 'crust is not good.',
 'not tasty and the texture was just nasty.',
 'stopped by during the late may bank holiday off rick steve recommendation and loved it.',
 'the selection on the menu was great and so were the prices.',
 'now i am getting angry and i want my damn pho.',
 "honeslty it didn't taste that fresh.)",
 'the potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer.',
 'the fries were great too.',
 'a great touch.',
 'service was very prompt.',
 'would not go back.',
 'the cashier had no care what so ever on what i had to say it still ended up being wayyy overpriced.',
 'i tried the cape cod ravoli, chicken, with cranberry...mmmm!',
 'i was disgusted because i was pretty sure that was human hair.',
 'i was shocked because no signs indicate cash only.',
 'highly recommended.',
 'waitress was a little slow in service.',
 'this place is not worth your time, let alone vegas.',
 'did not like at all.

In [7]:
from nltk.corpus import stopwords
Stopwords = stopwords.words("english")
Stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [8]:
len(Stopwords)

179

In [9]:
new_text_after_stopwords = []
for word in lower_casing:
    if word not in Stopwords:
        new_text_after_stopwords.append(word)
new_text_after_stopwords

['wow... loved this place.',
 'crust is not good.',
 'not tasty and the texture was just nasty.',
 'stopped by during the late may bank holiday off rick steve recommendation and loved it.',
 'the selection on the menu was great and so were the prices.',
 'now i am getting angry and i want my damn pho.',
 "honeslty it didn't taste that fresh.)",
 'the potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer.',
 'the fries were great too.',
 'a great touch.',
 'service was very prompt.',
 'would not go back.',
 'the cashier had no care what so ever on what i had to say it still ended up being wayyy overpriced.',
 'i tried the cape cod ravoli, chicken, with cranberry...mmmm!',
 'i was disgusted because i was pretty sure that was human hair.',
 'i was shocked because no signs indicate cash only.',
 'highly recommended.',
 'waitress was a little slow in service.',
 'this place is not worth your time, let alone vegas.',
 'did not like at all.

In [13]:
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer

In [14]:
Lemma = WordNetLemmatizer()
stem = PorterStemmer()

1. Data Gathering 
2. Preprocessing 
   1. lowercasing
   2. stopwords, domain specific stopwords
   3. contraction mapping
   4. lemmatization,Stemming
   5. spell check
   6. removing punctations
   7. laveshtian distance
3. Text representation
   1. Count Vectorizer 
   2. TF - IDF 
   3. Word2vec
   4. Fasttext
   5. Glove
4. Use of Algorithms
   1. Naive Bayes
   2. RNN 
   3. LSTM
5. Evaluation
   1. COnfusion matrix
   2. Classification report
   3. AUC - ROC curve
   

In [1]:
import numpy as np

In [2]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr1.nbytes

80

In [5]:
arr1 = np.zeros(10)
arr1
arr1[4] = 1
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [7]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [9]:
arr2 = reversed(arr1)
list(arr2)

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [10]:
arr1 = np.random.randint(1,10,size=(2,2))
print("Array 1:\n",arr1)
arr2 = np.random.randint(20,30,size=(2,2))
print("Array 2:\n",arr2)

Array 1:
 [[8 5]
 [3 5]]
Array 2:
 [[27 24]
 [20 26]]


In [11]:
add = arr1 + arr2
add

array([[35, 29],
       [23, 31]])

In [12]:
sub = arr1 - arr2
sub

array([[-19, -19],
       [-17, -21]])

In [13]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [14]:
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [15]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [16]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array :\n",arr1)
mean_row = np.mean(arr1,axis=1)
print("Mean across rows :",mean_row)
mean_col = np.mean(arr1,axis=0)
print("Mean across columns :",mean_col)

Array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean across rows : [2. 5. 8.]
Mean across columns : [4. 5. 6.]


In [17]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [18]:
arr1 = np.arange(9).reshape(3,3)
print("Array :\n",arr1)

Array :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array :\n",arr1)
arr1[:: , ::-1]

Array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [20]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr1[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [22]:
result = np.nonzero([1,2,0,0,4,0])
result

(array([0, 1, 4], dtype=int64),)

In [23]:
arr1 = np.array([[1,2],[3,4]])
print("Array :\n",arr1)
result = np.linalg.det(arr1)
result

Array :
 [[1 2]
 [3 4]]


-2.0000000000000004

In [24]:
arr1

array([[1, 2],
       [3, 4]])

In [25]:
result = np.linalg.inv(arr1)
result

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [26]:
arr1 = np.random.randint(1,10,size=(30))
print("Array :\n",arr1)
result = np.mean(arr1)
result

Array :
 [6 4 7 9 9 2 3 8 4 1 8 8 3 9 8 4 5 1 8 3 4 3 5 1 9 5 8 8 1 7]


5.366666666666666

In [27]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array :\n",arr1)
result = np.where(arr1 > 5)
result

Array :
 [ 1  2  3  4  5  6  7  8  9 10]


(array([5, 6, 7, 8, 9], dtype=int64),)

In [28]:
arr1 = np.random.random((3,3,3))
print("Array :\n",arr1)

Array :
 [[[0.4741754  0.61338741 0.34267948]
  [0.07365331 0.54792035 0.95446653]
  [0.8763885  0.77081324 0.03847026]]

 [[0.61085631 0.37096675 0.06858381]
  [0.73267909 0.09863887 0.1292516 ]
  [0.3420986  0.76183414 0.79958009]]

 [[0.43467136 0.05912593 0.01755935]
  [0.08344712 0.10032393 0.16034869]
  [0.36646472 0.26444025 0.09906588]]]


In [30]:
arr1 = np.random.rand(10,10)
print("Array :\n",arr1)
print("Maximum :",np.max(arr1))
print("Minimum :",np.min(arr1))

Array :
 [[0.97132006 0.48304303 0.3851227  0.78350675 0.34392007 0.39383662
  0.02222404 0.72462964 0.5859613  0.80284726]
 [0.91606004 0.11272656 0.18571598 0.60692281 0.01676893 0.81871929
  0.21479829 0.76634486 0.4468287  0.8349704 ]
 [0.3515856  0.09967324 0.01247895 0.74935674 0.29100608 0.27992913
  0.45330098 0.66841167 0.78199609 0.49896228]
 [0.97846541 0.20383806 0.91107091 0.76037941 0.50281297 0.85017567
  0.62584348 0.16812155 0.85260172 0.1172363 ]
 [0.09951709 0.73769067 0.44354901 0.943424   0.54209621 0.07454408
  0.06991675 0.69217006 0.03545471 0.24983634]
 [0.55218767 0.5642437  0.30185151 0.72019874 0.82007075 0.99182286
  0.12272339 0.53526174 0.77201683 0.88512969]
 [0.55682375 0.35505102 0.11459045 0.15827047 0.12557667 0.79242143
  0.23331405 0.29753678 0.44757632 0.12055803]
 [0.77030516 0.51279797 0.43396564 0.11515102 0.69705184 0.01825491
  0.86764756 0.63666881 0.32311392 0.64887162]
 [0.53262002 0.5787348  0.99502849 0.50089525 0.41076727 0.75504967
  0

In [31]:
arr1 = np.ones((10,10))
print("Array:\n",arr1)
arr1[1:-1,1:-1] = 0
arr1

Array:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [32]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4])
arr1

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [33]:
arr1 = np.eye(3,3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
arr1 = np.random.randint(1,9,size=(5,3))
arr2 = np.random.randint(1,9,size=(3,2))
result = np.dot(arr1,arr2)
print("Array 1 :\n",arr1)
print("Array 2 :\n",arr2)
print("Multiplication array :\n",result)

Array 1 :
 [[5 2 7]
 [1 3 5]
 [7 3 4]
 [6 1 8]
 [5 6 5]]
Array 2 :
 [[3 3]
 [7 1]
 [6 7]]
Multiplication array :
 [[71 66]
 [54 41]
 [66 52]
 [73 75]
 [87 56]]


In [35]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
result = np.where((arr1 >= 3) & (arr1 <= 8), -1*arr1 , arr1)
result

array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [36]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Array:\n",arr1)
result = np.around(arr1,1)
result

Array:
 [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]


array([[1.2, 2.7],
       [3.5, 5.2]])

In [37]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1,arr2)
result

array([4, 5, 6])

In [38]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [39]:
arr1 = np.random.randint(1,10,size=(10))
print("Array:",arr1)
result = np.sort(arr1)
result

Array: [4 6 7 1 1 4 6 7 4 5]


array([1, 1, 4, 4, 4, 5, 6, 6, 7, 7])

In [40]:
arr1 = np.zeros((5,5))
print("Array:",arr1)
arr2 = arr1 + np.arange(5)
arr2

Array: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [41]:
arr1 = np.random.randint(0,5,size=(5))
arr2 = np.random.randint(0,5,size=(5))
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [42]:
result = np.allclose(arr1,arr2)
result

False

In [43]:
arr1 = np.random.randint(1,10,size=(10))
print("Array:",arr1)
result = np.where((np.max(arr1) == arr1),0,arr1)
result

Array: [5 6 8 5 7 5 9 2 2 6]


array([5, 6, 8, 5, 7, 5, 0, 2, 2, 6])

In [44]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr1):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

In [45]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

(0, 0) index has 1 values
(0, 1) index has 2 values
(0, 2) index has 3 values
(1, 0) index has 4 values
(1, 1) index has 5 values
(1, 2) index has 6 values
(2, 0) index has 7 values
(2, 1) index has 8 values
(2, 2) index has 9 values


In [46]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array:\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array:
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [47]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.mean(arr1)
result

5.5

In [48]:
result = np.median(arr1)
result

5.5

In [49]:
arr1 = np.random.randint(1,10,size=(10))
print("Array:\n",arr1)
result = np.std(arr1)
result

Array:
 [3 6 2 4 4 8 6 5 6 3]


1.7349351572897473

In [50]:
from scipy.stats import mode
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = mode(arr1)
result

ModeResult(mode=1, count=1)

In [51]:
result = np.around(5.3245,2)
result

5.32

In [52]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr1 = np.array([[2,3],[3,4]])
result = np.linalg.inv(arr1)
result

array([[-4.,  3.],
       [ 3., -2.]])

In [55]:
x = np.array([1,2,3])
y = np.array([4,5,6])
result = np.cov(x,y)
result

array([[1., 1.],
       [1., 1.]])

In [56]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:",arr1)
arr2 = np.reshape(arr1,(2,5,1))
arr2

Array: [ 1  2  3  4  5  6  7  8  9 10]


array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [57]:
arr1 = np.random.randint(1,10,size=(1,2,3,4))
print("Array:\n",arr1)
arr2 = np.reshape(arr1,(6,4))
arr2

Array:
 [[[[4 2 3 8]
   [7 3 6 9]
   [9 1 1 3]]

  [[1 8 9 1]
   [7 7 6 4]
   [2 7 4 1]]]]


array([[4, 2, 3, 8],
       [7, 3, 6, 9],
       [9, 1, 1, 3],
       [1, 8, 9, 1],
       [7, 7, 6, 4],
       [2, 7, 4, 1]])

In [58]:
arr1 = np.zeros(10,dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
arr1.shape

(3, 4)