In [1]:
import re 
string = "Python and Machine Learning 7741 is syllabus of Data Science."
result = re.findall(r"[a-zA-Z0-9]",string)
if result:
    print("Contains characters")
else:
    print("No characters found")

Contains characters


In [2]:
string = "Python and Machine Learning is syllabus of data science and deep learning."
result = re.split(r"and",string)
result

['Python ',
 ' Machine Learning is syllabus of data science ',
 ' deep learning.']

In [4]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\bab*[a-z]*\b",str1)
result

['and']

In [5]:
sample_string = "There are 123 45 678 90 2345 67 12 345 6789 0123 three-digit"
result = re.findall(r"\b\d{3}\s\d{2}\b",sample_string)
result

['123 45', '678 90']

In [6]:
str1= "python and data pytthon science pythonnn pyyth annd pythh"
result = re.findall(r"p+",str1)
result

['p', 'p', 'p', 'p', 'p']

In [7]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
result

['INFORM', 'inform']

In [8]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py?",str1)
result

['py', 'py']

In [9]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [10]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"\b\w*[b]{2,3}\w*\b",str1)
result

['abbbs', 'abbbsolutely', 'abbrivation']

In [11]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [12]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [13]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [14]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [15]:
str1 = 'Suceess is a jurney not a desti9nation.'
result = re.findall(r"Suceess",str1)
result

['Suceess']

In [17]:
str1 = 'new begening of LIFE .'
result = re.findall(r"LIFE .",str1)
result

['LIFE .']

In [19]:
str1 = "today is the very lazy day"
result = re.findall(r"\b\w*[z].\b",str1)
result

['lazy']

In [2]:
import re
str1 = "we have a lazy cat"
result = re.findall(r"[a-y]*z[a-y]",str1)
result

['lazy']

In [3]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [5]:
str1 = "9821 maya"
result = re.findall(r"\d{1,}",str1)
result

['9821']

In [6]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [10]:
str1="Python is required for data science version 3.2"
result = re.findall(r"\d..\b",str1)
result

['3.2']

In [11]:
str1 = "Exercises number 1, 12, 13, and 345 are important"
result = re.findall(r"[0-9]+",str1)
result

['1', '12', '13', '345']

In [12]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for word in Searched_words:
    result = re.findall(word,Sample_text)
    print(result)

['fox']
['dog']
[]


In [13]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search(r"fox",sample_text)
print(result)

<re.Match object; span=(16, 19), match='fox'>


In [14]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [15]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
print(len(result))
result = re.search(r"exercises",Sample_text)
print(result)

3
<re.Match object; span=(7, 16), match='exercises'>


In [16]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","_",str1)
print(result)
result = re.sub(r"[_]","",result)
print(result)

The_quick_brown_fox_jumps_over_the_lazy_dog.
Thequickbrownfoxjumpsoverthelazydog.


In [17]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","",str1)
result

'Thequickbrownfoxjumpsoverthelazydog.'

In [18]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [19]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*",str1)
result

['and', 'every', 'evening']

In [20]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [21]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[,. ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [22]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[,. ]{2}",":",text)
result

'Python: is a general purpose interpreted.'

In [23]:
text ="""123 Python is a general-purpose, interpreted,
high-level programming language popularly used for
website development, data analytics 78 and automation."""

result = re.findall(r"\b\D{3,5}\b",text)
result

[' is a', 'high-', 'level', ' used', ' for\n', 'data ', ' and ']

In [1]:
import numpy as np
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
arr1.nbytes

80

In [3]:
arr1 = np.zeros(10)
arr1 
arr1[4] = 1 
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [4]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [5]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [6]:
result = list(reversed(arr1))
result

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [8]:
arr1 = np.random.randint(10,20,size=(2,2))
print("Array1 :\n",arr1)
arr2 = np.random.randint(20,30,size=(2,2))
print("Array2 :\n",arr2)

Array1 :
 [[12 16]
 [19 18]]
Array2 :
 [[26 25]
 [20 21]]


In [9]:
add = arr1 + arr2
add

array([[38, 41],
       [39, 39]])

In [10]:
sub1 = arr1 - arr2
sub1

array([[-14,  -9],
       [ -1,  -3]])

In [11]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [12]:
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [13]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [14]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mean_row = np.mean(arr1,axis=1)
print("mean_row :\n",mean_row)
mean_col = np.mean(arr1,axis=0)
print("mean_col :\n",mean_col)

mean_row :
 [2. 5. 8.]
mean_col :
 [4. 5. 6.]


In [15]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [16]:
arr1 = np.arange(9).reshape(3,3)
print("arr1 :\n",arr1)

arr1 :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("arr1 :\n",arr1)
arr1[:: , ::-1]


arr1 :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [18]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
arr1[::-1]

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [19]:
result = np.nonzero([1,2,0,0,4,0])
result

(array([0, 1, 4], dtype=int64),)

In [20]:
arr1 = np.array([[1,2],[3,4]])
print("Array:\n",arr1)
result = np.linalg.det(arr1)
result

Array:
 [[1 2]
 [3 4]]


-2.0000000000000004

In [21]:
arr1 = np.array([[2,3],[3,9]])
print("Array:\n",arr1)
result = np.linalg.inv(arr1)
result

Array:
 [[2 3]
 [3 9]]


array([[ 1.        , -0.33333333],
       [-0.33333333,  0.22222222]])

In [22]:
arr1 = np.random.randint(10,30,size=(30))
print("Array:\n",arr1)
result = np.mean(arr1)
result

Array:
 [10 26 23 23 19 19 15 20 16 11 22 15 16 20 21 23 25 16 13 14 27 22 25 16
 20 21 24 16 10 20]


18.933333333333334

In [23]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:\n",arr1)
result = np.where(arr1 > 5)
result

Array:
 [ 1  2  3  4  5  6  7  8  9 10]


(array([5, 6, 7, 8, 9], dtype=int64),)

In [24]:
arr1 = np.random.random((3,3,3))
print("Array:\n",arr1)

Array:
 [[[0.73270108 0.72402719 0.98941704]
  [0.82535175 0.65036759 0.71177355]
  [0.41889998 0.86963668 0.74488526]]

 [[0.21579368 0.34520066 0.50602003]
  [0.11558611 0.74484786 0.6539474 ]
  [0.87698842 0.29447042 0.70152613]]

 [[0.47548032 0.21630018 0.17502375]
  [0.56357073 0.59114329 0.2397674 ]
  [0.0669284  0.33299622 0.14751913]]]


In [25]:
arr1 = np.random.rand(10,10)
print("Array:\n",arr1)
result = np.max(arr1)
result

Array:
 [[0.45905014 0.78056234 0.05589051 0.02918809 0.3688544  0.32097062
  0.12884569 0.32111215 0.6478248  0.82034279]
 [0.8331973  0.9712659  0.77871551 0.8197925  0.28946006 0.25648816
  0.09154261 0.90317231 0.72984555 0.00603084]
 [0.6363631  0.20685244 0.86070016 0.7385614  0.62869833 0.30837191
  0.82676947 0.68826013 0.06127709 0.27184328]
 [0.1776687  0.47664165 0.47559298 0.17164661 0.26554762 0.25676048
  0.69920546 0.48083367 0.69519458 0.04941819]
 [0.0600249  0.28378623 0.26099442 0.10929278 0.09720211 0.07072975
  0.21913149 0.41887041 0.75678487 0.06384883]
 [0.61436169 0.40132531 0.97538105 0.67772692 0.90817641 0.51446867
  0.67083001 0.15749467 0.57274216 0.56658017]
 [0.64488636 0.63713958 0.82894056 0.96278211 0.55344417 0.80132355
  0.40361997 0.07204367 0.62515249 0.42336134]
 [0.31550865 0.37985757 0.57396069 0.89926929 0.21357829 0.32464229
  0.29183556 0.29416823 0.3074777  0.49146568]
 [0.07469995 0.18389807 0.7930634  0.50952836 0.29040155 0.66669675
  0.

0.975381049351017

In [26]:
result = np.min(arr1)
result

0.006030843384223439

In [27]:
arr1 = np.ones((10,10))
arr1[1:-1 , 1:-1] = 0 
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4])
arr1

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [29]:
arr1 = np.eye(3,3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
arr1 = np.random.randint(1,9,size=(5,3))
arr2 = np.random.randint(1,9,size=(3,2))
result = np.dot(arr1,arr2)
print("Array 1 :\n",arr1)
print("Array 2 :\n",arr2)
print("Multiplication array :\n",result)

Array 1 :
 [[6 4 7]
 [3 5 3]
 [6 1 4]
 [7 3 2]
 [8 5 5]]
Array 2 :
 [[8 2]
 [8 5]
 [8 2]]
Multiplication array :
 [[136  46]
 [ 88  37]
 [ 88  25]
 [ 96  33]
 [144  51]]


In [31]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
print("Array 1 :\n",arr1)
result = np.where((arr1 >= 3) & (arr1 <= 8) , arr1*-1,arr1)
result

Array 1 :
 [ 1  2  3  4  5  6  7  8 44  9 33  6  5 10]


array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [32]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Array 1 :\n",arr1)
result = np.around(arr1,1)
result

Array 1 :
 [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]


array([[1.2, 2.7],
       [3.5, 5.2]])

In [33]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
result = np.ceil(arr1)
result

array([[2., 3.],
       [4., 6.]])

In [34]:
result = np.floor(arr1)
result

array([[1., 2.],
       [3., 5.]])

In [35]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1,arr2)
result

array([4, 5, 6])

In [38]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [39]:
arr1 = np.random.randint(1,10,size=10)
print("Array:",arr1)
result = np.sort(arr1)
result

Array: [3 8 1 2 1 8 7 3 7 3]


array([1, 1, 2, 3, 3, 3, 7, 7, 8, 8])

In [40]:
arr1 = np.zeros((5,5))
print("Array:\n",arr1)
arr2 = arr1 + np.arange(5)
print("Array:\n",arr2)

Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Array:
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [41]:
arr1 = np.random.randint(0,5,size=5)
arr2 = np.random.randint(0,5,size=5)
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [42]:
arr1 = np.random.randint(0,5,size=5)
arr2 = np.random.randint(0,5,size=5)
result = np.allclose(arr1, arr2)
result

False

In [43]:
arr1 = np.random.randint(1,10,size=10)
print("Array:\n",arr1)
result = np.where((arr1 == np.max(arr1)),0,arr1)
result

Array:
 [8 3 7 1 9 9 3 6 8 3]


array([8, 3, 7, 1, 0, 0, 3, 6, 8, 3])

In [45]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr1):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

In [46]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

(0, 0, 0) index has 1 values
(0, 0, 1) index has 2 values
(0, 0, 2) index has 3 values
(0, 1, 0) index has 4 values
(0, 1, 1) index has 5 values
(0, 1, 2) index has 6 values
(0, 2, 0) index has 7 values
(0, 2, 1) index has 8 values
(0, 2, 2) index has 9 values


In [48]:
arr1 = np.random.randint(1,10,size=(3,3))
print("Array:\n",arr1)
result = (arr1[arr1[:,2].argsort()])
result

Array:
 [[4 8 3]
 [8 9 7]
 [3 8 7]]


array([[4, 8, 3],
       [8, 9, 7],
       [3, 8, 7]])

In [49]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array:\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array:
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [50]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.mean(arr1)
result

5.5

In [51]:
result = np.median(arr1)
result

5.5

In [52]:
result = np.std(arr1)
result

2.8722813232690143

In [53]:
from scipy.stats import mode
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = mode(arr1)
result

ModeResult(mode=1, count=1)

In [54]:
result = np.around(5.3245,2)
result

5.32

In [55]:
arr1 = np.array([[2,3],[3,4]])
print("Array:\n",arr1)
result = np.linalg.inv(arr1)
result

Array:
 [[2 3]
 [3 4]]


array([[-4.,  3.],
       [ 3., -2.]])

In [56]:
x = np.array([1,2,3])
y = np.array([4,5,6])
result = np.cov(x,y)
result

array([[1., 1.],
       [1., 1.]])

In [57]:
arr1 = np.array([1,1,2,2,3,4,5,6,7,8,9,6,4,3,6,7])
result = mode(arr1)
result

ModeResult(mode=6, count=3)

In [58]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:\n",arr1)
arr1.shape
arr2 = np.reshape(arr1,(2,5,1))
print("Array:\n",arr2)
arr2.ndim

Array:
 [ 1  2  3  4  5  6  7  8  9 10]
Array:
 [[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]


3

In [59]:
arr1 = np.random.randint(1,20,size=(1,2,3,4))
print("Array:\n",arr1)
print(arr1.ndim)
arr2 = np.reshape(arr1 , (6,4))
print("Array:\n",arr2)
print(arr2.ndim)

Array:
 [[[[ 4 19 12  8]
   [ 5  4  6  4]
   [15  9  8  2]]

  [[ 7  8 11  4]
   [16 10  9  6]
   [11  7 17  3]]]]
4
Array:
 [[ 4 19 12  8]
 [ 5  4  6  4]
 [15  9  8  2]
 [ 7  8 11  4]
 [16 10  9  6]
 [11  7 17  3]]
2


In [60]:
arr1 = np.zeros(10,dtype=int)
print("Array:\n",arr1)

Array:
 [0 0 0 0 0 0 0 0 0 0]


In [61]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
print("Array:",arr1)
print(arr1.shape)

Array: [[1 2 3 4]
 [5 6 8 7]
 [3 4 5 6]]
(3, 4)


In [1]:
import numpy as np 
import pandas as pd
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [2]:
list1 = [[1,2,3],[4,5,6]]
pd.DataFrame(list1)

0  1  2
0  1  2  3
1  4  5  6

In [3]:
df = pd.DataFrame(columns=list("ABC"),index=list("PQR"))
df

A    B    C
P  NaN  NaN  NaN
Q  NaN  NaN  NaN
R  NaN  NaN  NaN

In [4]:
df = pd.DataFrame(columns=list("ABC"),index=list("PQR"))
if df.isnull:
    print("Datframe is empty")
else:
    print("dataframe is not empty")

Datframe is empty


In [5]:
arr1 = np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr1)
df = pd.DataFrame(arr1)
df

Array:
 [[1 2 3]
 [4 5 6]]


0  1  2
0  1  2  3
1  4  5  6

In [6]:
list1 = [[1,2,3],[4,5,6]]
df = pd.DataFrame(list1)
df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
tuple1 = (1,2,3,4,5,6)
df = pd.DataFrame(tuple1)
df

0
0  1
1  2
2  3
3  4
4  5
5  6

In [8]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [9]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]
df = pd.DataFrame(l1,columns=list("ABC"))
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [10]:
df = pd.DataFrame(np.random.randint(1,10,size=(5,6)))
df

0  1  2  3  4  5
0  3  2  7  7  9  5
1  4  7  9  1  9  9
2  5  6  8  8  7  1
3  2  2  4  6  6  2
4  1  8  3  1  4  6

In [11]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
df = pd.DataFrame(arr1)
df

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [13]:
s1 = pd.Series([1,2,3,4,5,6])
print(s1)
s2 = s1.copy()
print(s2)
s2[0] = 50 
print("Original Series :\n",s1)
print("Copied Series :\n",s2)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
Original Series :
 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
Copied Series :
 0    50
1     2
2     3
3     4
4     5
5     6
dtype: int64


In [14]:
df = pd.DataFrame(np.full((4,5),6))
df

0  1  2  3  4
0  6  6  6  6  6
1  6  6  6  6  6
2  6  6  6  6  6
3  6  6  6  6  6

In [15]:
df["5"] = [1,2,3,4]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4

In [17]:
df.loc[4] = [1,2,3,4,5,6]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4
4  1  2  3  4  5  6

In [18]:
arr1 = np.random.randint(1,10,size=(4,4))
print(arr1)
df = pd.DataFrame(arr1,columns=list("ABCD"),index=list("PQRS"))
print(df)
df.rename({"P":"p","Q":"q","R":"r","S":"s"},axis=0,inplace=True)
df.rename({"A":"a","B":"b","C":"c","D":"d"},axis=1,inplace=True)
df

[[1 2 1 2]
 [7 1 3 7]
 [7 1 3 7]
 [5 3 6 5]]
   A  B  C  D
P  1  2  1  2
Q  7  1  3  7
R  7  1  3  7
S  5  3  6  5


a  b  c  d
p  1  2  1  2
q  7  1  3  7
r  7  1  3  7
s  5  3  6  5

In [19]:
for i in df.items():
    print(i)

('a', p    1
q    7
r    7
s    5
Name: a, dtype: int32)
('b', p    2
q    1
r    1
s    3
Name: b, dtype: int32)
('c', p    1
q    3
r    3
s    6
Name: c, dtype: int32)
('d', p    2
q    7
r    7
s    5
Name: d, dtype: int32)


In [20]:
for i in df.iterrows():
    print(i)

('p', a    1
b    2
c    1
d    2
Name: p, dtype: int32)
('q', a    7
b    1
c    3
d    7
Name: q, dtype: int32)
('r', a    7
b    1
c    3
d    7
Name: r, dtype: int32)
('s', a    5
b    3
c    6
d    5
Name: s, dtype: int32)


In [22]:
df = pd.DataFrame(np.random.randint(1,10,size=(4,4)))
print(df)
arr1 = df.values
arr1

   0  1  2  3
0  7  4  8  5
1  8  9  9  4
2  4  2  8  1
3  5  3  8  6


array([[7, 4, 8, 5],
       [8, 9, 9, 4],
       [4, 2, 8, 1],
       [5, 3, 8, 6]])

In [23]:
df = pd.DataFrame(np.random.randint(1,10,size=(4,4)))
print(df)
arr1 = df.values
arr1.tolist()

   0  1  2  3
0  9  5  4  4
1  1  9  5  3
2  5  8  2  7
3  2  3  6  7


[[9, 5, 4, 4], [1, 9, 5, 3], [5, 8, 2, 7], [2, 3, 6, 7]]

In [24]:
df

0  1  2  3
0  9  5  4  4
1  1  9  5  3
2  5  8  2  7
3  2  3  6  7

In [25]:
df.reset_index(drop=True)

0  1  2  3
0  9  5  4  4
1  1  9  5  3
2  5  8  2  7
3  2  3  6  7

In [26]:
df = pd.DataFrame(np.random.randint(1,10,size=(4,4)))
print(df)
print(df.shape[0])
print(df.shape[1])

   0  1  2  3
0  6  3  9  8
1  1  4  7  7
2  2  5  1  1
3  8  6  8  6
4
4


In [27]:
s1 = pd.Series(np.arange(10,20))
s2 = pd.Series(np.arange(20,30))
print(s1+s2)

0    30
1    32
2    34
3    36
4    38
5    40
6    42
7    44
8    46
9    48
dtype: int32


In [28]:
print(s1-s2)

0   -10
1   -10
2   -10
3   -10
4   -10
5   -10
6   -10
7   -10
8   -10
9   -10
dtype: int32


In [30]:
df = pd.read_excel("Sample1.xlsx")
df

Unnamed: 0 First Name   Last Name  Gender        Country  Age  \
0             1      Dulce       Abril  Female  United States   32   
1             2       Mara   Hashimoto  Female  Great Britain   25   
2             3     Philip        Gent    Male         France   36   
3             4   Kathleen      Hanner  Female  United States   25   
4             5    Nereida     Magwood  Female  United States   58   
..          ...        ...         ...     ...            ...  ...   
995         996       Roma  Lafollette  Female  United States   34   
996         997     Felisa        Cail  Female  United States   28   
997         998   Demetria       Abbey  Female  United States   32   
998         999     Jeromy        Danz    Male  United States   39   
999        1000   Rasheeda      Alkire  Female  United States   29   

           Date    Id  
0    15/10/2017  1562  
1    16/08/2016  1582  
2    21/05/2015  2587  
3    15/10/2017  3549  
4    16/08/2016  2468  
..          ...   ...  
995  15/10/2017  2654  
996  16/08/2016  6525  
997  21/05/2015  3265  
998  15/10/2017  3265  
999  16/08/2016  6125  

[1000 rows x 8 columns]

In [31]:
df.columns

Index(['Unnamed: 0', 'First Name', 'Last Name', 'Gender', 'Country', 'Age',
       'Date', 'Id'],
      dtype='object')

In [32]:
df[['First Name', 'Last Name']]

First Name   Last Name
0        Dulce       Abril
1         Mara   Hashimoto
2       Philip        Gent
3     Kathleen      Hanner
4      Nereida     Magwood
..         ...         ...
995       Roma  Lafollette
996     Felisa        Cail
997   Demetria       Abbey
998     Jeromy        Danz
999   Rasheeda      Alkire

[1000 rows x 2 columns]

In [33]:
df["Age"].mean()

33.26

In [34]:
df["Age"].min()

21

In [35]:
df["Age"].max()

58

In [36]:
df["Age"].sum()

33260

In [37]:
df = pd.read_csv("titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [38]:
df.groupby(df["Embarked"]).get_group("S")

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
..           ...       ...     ...   
883          884         0       2   
884          885         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   

                                             Name  Gender   Age  SibSp  Parch  \
0                         Braund, Mr. Owen Harris    male  22.0      1      0   
2                          Heikkinen, Miss. Laina  female   NaN      0      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1      0   
4                        Allen, Mr. William Henry    male   NaN      0      0   
6                         McCarthy, Mr. Timothy J    male  54.0      0      0   
..                                            ...     ...   ...    ...    ...   
883                 Banfield, Mr. Frederick James    male  28.0      0      0   
884                        Sutehall, Mr. Henry Jr    male  25.0      0      0   
886                         Montvila, Rev. Juozas    male  27.0      0      0   
887                  Graham, Miss. Margaret Edith  female  19.0      0      0   
888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500   NaN        S  
2    STON/O2. 3101282   7.9250   NaN        S  
3              113803  53.1000  C123        S  
4              373450   8.0500   NaN        S  
6               17463  51.8625   E46        S  
..                ...      ...   ...      ...  
883  C.A./SOTON 34068  10.5000   NaN        S  
884   SOTON/OQ 392076   7.0500   NaN        S  
886            211536  13.0000   NaN        S  
887            112053  30.0000   B42        S  
888        W./C. 6607  23.4500   NaN        S  

[644 rows x 12 columns]

In [40]:
arr1 = np.random.randint(1,10,size=(4,2))
df = pd.DataFrame(arr1)
print(df)
df.apply(np.sqrt)

   0  1
0  3  6
1  3  1
2  1  2
3  1  1


0         1
0  1.732051  2.449490
1  1.732051  1.000000
2  1.000000  1.414214
3  1.000000  1.000000

In [41]:
df = pd.DataFrame(np.random.randint(1,9,size=(3,4)))
df

0  1  2  3
0  3  3  7  1
1  8  8  5  2
2  6  3  2  4

In [42]:
df.apply(lambda x : x**2)

0   1   2   3
0   9   9  49   1
1  64  64  25   4
2  36   9   4  16

In [43]:
df = pd.read_csv("diabetes.csv")
df.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   
3      150             66             23       94  28.1   
4      150             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   52        1  
3                     0.167   21        0  
4                     2.288   33        1

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Glucose                   768 non-null    int64  
 1   BloodPressure             768 non-null    int64  
 2   SkinThickness             768 non-null    int64  
 3   Insulin                   768 non-null    int64  
 4   BMI                       768 non-null    float64
 5   DiabetesPedigreeFunction  768 non-null    float64
 6   Age                       768 non-null    int64  
 7   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 48.1 KB


In [45]:
df.describe()

Glucose  BloodPressure  SkinThickness     Insulin         BMI  \
count  768.000000     768.000000     768.000000  768.000000  768.000000   
mean   121.117188      69.076823      20.536458   79.799479   31.992578   
std     31.805091      19.367794      15.952218  115.244002    7.884160   
min      0.000000       0.000000       0.000000    0.000000    0.000000   
25%     99.000000      62.000000       0.000000    0.000000   27.300000   
50%    117.000000      72.000000      23.000000   30.500000   32.000000   
75%    142.000000      80.000000      32.000000  127.250000   36.600000   
max    199.000000     122.000000      99.000000  846.000000   67.100000   

       DiabetesPedigreeFunction         Age     Outcome  
count                768.000000  768.000000  768.000000  
mean                   0.471876   33.243490    0.348958  
std                    0.331329   11.758182    0.476951  
min                    0.078000   21.000000    0.000000  
25%                    0.243750   24.000000    0.000000  
50%                    0.372500   29.000000    0.000000  
75%                    0.626250   41.000000    1.000000  
max                    2.420000   81.000000    1.000000

In [46]:
data1 = {"NAME" : ["Rudranshi","Sanvi","Swati","Shiva"]}
df = pd.DataFrame(data1)
print(df)
df["NAME"].apply(lambda x : x.istitle())


        NAME
0  Rudranshi
1      Sanvi
2      Swati
3      Shiva


0    True
1    True
2    True
3    True
Name: NAME, dtype: bool

In [2]:
import numpy as np
import pandas as pd

In [4]:
d1 = {"Employee":["Saniya","Sara","Alexa","Jenny"]}
df = pd.DataFrame(d1)
print(df)
d2 = {"Saniya": "Software Developer" , "Sara":"Developer" , "Alexa":"Assistant"}
df["designation"] = df["Employee"].map(d2)
df

  Employee
0   Saniya
1     Sara
2    Alexa
3    Jenny


Employee         designation
0   Saniya  Software Developer
1     Sara           Developer
2    Alexa           Assistant
3    Jenny                 NaN

In [5]:
arr1 = np.random.randint(1,10,size=(5,5))
df = pd.DataFrame(arr1,columns=list("ABCDE"))
df

A  B  C  D  E
0  6  5  4  7  6
1  8  2  1  5  1
2  2  3  1  7  3
3  3  2  2  3  8
4  5  8  8  9  7

In [6]:
df["I"] = [1,2,3,4,5]
df

A  B  C  D  E  I
0  6  5  4  7  6  1
1  8  2  1  5  1  2
2  2  3  1  7  3  3
3  3  2  2  3  8  4
4  5  8  8  9  7  5

In [7]:
arr1 = np.random.randint(1,10,size=(5,5))
df = pd.DataFrame(arr1,columns=list("ABCDE"))
print(df)
df.insert(1,"H",[1,2,1,2,1])
df

   A  B  C  D  E
0  7  7  3  4  1
1  7  7  1  6  8
2  9  2  5  9  9
3  2  6  1  5  7
4  8  6  4  6  8


A  H  B  C  D  E
0  7  1  7  3  4  1
1  7  2  7  1  6  8
2  9  1  2  5  9  9
3  2  2  6  1  5  7
4  8  1  6  4  6  8

In [8]:
df.drop("A",axis=1,inplace=True)
df

H  B  C  D  E
0  1  7  3  4  1
1  2  7  1  6  8
2  1  2  5  9  9
3  2  6  1  5  7
4  1  6  4  6  8

In [9]:
df.drop(2 , axis=0,inplace=True)
df

H  B  C  D  E
0  1  7  3  4  1
1  2  7  1  6  8
3  2  6  1  5  7
4  1  6  4  6  8

In [10]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([4,5,6,7,8])
s11 = set(s1)
s22 = set(s2)
result = s11.symmetric_difference(s22)
result

{1, 2, 3, 6, 7, 8}

In [11]:
s1 = pd.Series([1,2,3,4,5])
print(s1)
print(s1.median())
print(s1.mean())
print(s1.quantile(0.25))
print(s1.quantile(0.75))

0    1
1    2
2    3
3    4
4    5
dtype: int64
3.0
3.0
2.0
4.0


In [12]:
df = pd.DataFrame(np.random.randint(10,50,size=(4,4)) , columns=list("CABD") , index=list("xzvs"))
df

C   A   B   D
x  39  43  44  11
z  38  27  19  19
v  11  28  39  27
s  47  44  11  19

In [13]:
df.sort_index()

C   A   B   D
s  47  44  11  19
v  11  28  39  27
x  39  43  44  11
z  38  27  19  19

In [14]:
df.sort_index(axis=1)

A   B   C   D
x  43  44  39  11
z  27  19  38  19
v  28  39  11  27
s  44  11  47  19

In [15]:
df.sort_values("D")

C   A   B   D
x  39  43  44  11
z  38  27  19  19
s  47  44  11  19
v  11  28  39  27

In [16]:
df = pd.DataFrame({"A" : [1,1,3,4,5],
                   "B" : [1,1,3,4,5],
                   "C" : [1,1,3,4,5],
                   "D" : [1,1,3,4,5]})

df

A  B  C  D
0  1  1  1  1
1  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [17]:
df.drop_duplicates()

A  B  C  D
0  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [18]:
data = {'Full Name': ['John Doe', 'Jane Smith', 'Bob Johnson']}
df = pd.DataFrame(data)
print(df)
df[['First Name', 'Last Name']] = df["Full Name"].str.split(expand=True)
df

     Full Name
0     John Doe
1   Jane Smith
2  Bob Johnson


Full Name First Name Last Name
0     John Doe       John       Doe
1   Jane Smith       Jane     Smith
2  Bob Johnson        Bob   Johnson

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [2]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            180
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [3]:
df["Age"].fillna(df["Age"].mean(),inplace=True)
df["Age"].isna().sum()

0

In [4]:
movie_dict = {"Movies":["Interstellar","Avengers","Dhoom","Interstellar"],
"Genre":["fiction","Fiction","Comedy","fiction"],
"Actors":["American","French","Indian","American"]}
index_labels = ["a","b","c","d"]
df = pd.DataFrame(movie_dict,index=index_labels)
df

Movies    Genre    Actors
a  Interstellar  fiction  American
b      Avengers  Fiction    French
c         Dhoom   Comedy    Indian
d  Interstellar  fiction  American

In [5]:
df.head(3)

Movies    Genre    Actors
a  Interstellar  fiction  American
b      Avengers  Fiction    French
c         Dhoom   Comedy    Indian

In [6]:
df = pd.read_csv("titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [7]:
df.loc[:1 , ["Name","Age","Gender"]]


Name   Age  Gender
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female

In [8]:
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [9]:
df.loc[[0,1,3,5,7,9,11] , ["Name","Age","Gender"]]

Name   Age  Gender
0                             Braund, Mr. Owen Harris  22.0    male
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)   NaN  female
5                                    Moran, Mr. James   NaN    male
7                      Palsson, Master. Gosta Leonard   2.0    male
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0  female
11                           Bonnell, Miss. Elizabeth  58.0  female

In [10]:
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [11]:
df.isna()

PassengerId  Survived  Pclass   Name  Gender    Age  SibSp  Parch  \
0          False     False   False  False   False  False  False  False   
1          False     False   False  False   False  False  False  False   
2          False     False   False  False   False   True  False  False   
3          False     False   False  False   False   True  False  False   
4          False     False   False  False   False   True  False  False   
..           ...       ...     ...    ...     ...    ...    ...    ...   
886        False     False   False  False   False  False  False  False   
887        False     False   False  False   False  False  False  False   
888        False     False   False  False   False   True  False  False   
889        False     False   False  False   False  False  False  False   
890        False     False   False  False   False  False  False  False   

     Ticket   Fare  Cabin  Embarked  
0     False  False   True     False  
1     False  False  False     False  
2     False  False   True     False  
3     False  False  False     False  
4     False  False   True     False  
..      ...    ...    ...       ...  
886   False  False   True     False  
887   False  False  False     False  
888   False  False   True     False  
889   False  False  False     False  
890   False  False   True     False  

[891 rows x 12 columns]

In [12]:
df.isna().sum().to_dict()

{'PassengerId': 0,
 'Survived': 0,
 'Pclass': 0,
 'Name': 0,
 'Gender': 0,
 'Age': 180,
 'SibSp': 0,
 'Parch': 0,
 'Ticket': 0,
 'Fare': 0,
 'Cabin': 687,
 'Embarked': 2}

In [13]:
df.isnull().sum().to_dict()

{'PassengerId': 0,
 'Survived': 0,
 'Pclass': 0,
 'Name': 0,
 'Gender': 0,
 'Age': 180,
 'SibSp': 0,
 'Parch': 0,
 'Ticket': 0,
 'Fare': 0,
 'Cabin': 687,
 'Embarked': 2}

In [14]:
df.dropna()

PassengerId  Survived  Pclass  \
1              2         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
21            22         1       2   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name  Gender   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
21                               Beesley, Mr. Lawrence    male  34.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
21       0    248698  13.0000          D56        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[182 rows x 12 columns]

In [15]:
df.isna().sum().to_dict()

{'PassengerId': 0,
 'Survived': 0,
 'Pclass': 0,
 'Name': 0,
 'Gender': 0,
 'Age': 180,
 'SibSp': 0,
 'Parch': 0,
 'Ticket': 0,
 'Fare': 0,
 'Cabin': 687,
 'Embarked': 2}

In [16]:
df.isna().sum().sum()

869

In [17]:
df["Age"] = df["Age"].fillna(40)
df["Age"].isna().sum()

0

In [18]:
df = pd.read_csv("titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [19]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            180
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [20]:
df["Age"].fillna(df["Age"].mean(),inplace=True)
df["Age"].isna().sum()

0

In [21]:
df = pd.read_csv("titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [22]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            180
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [23]:
df["Age"].isna().to_numpy().nonzero()

(array([  2,   3,   4,   5,  17,  19,  26,  28,  29,  31,  32,  36,  42,
         45,  46,  47,  48,  55,  64,  65,  76,  77,  82,  87,  95, 101,
        107, 109, 121, 126, 128, 140, 154, 158, 159, 166, 168, 176, 180,
        181, 185, 186, 196, 198, 201, 214, 223, 229, 235, 240, 241, 250,
        256, 260, 264, 270, 274, 277, 284, 295, 298, 300, 301, 303, 304,
        306, 324, 330, 334, 335, 347, 351, 354, 358, 359, 364, 367, 368,
        375, 384, 388, 409, 410, 411, 413, 415, 420, 425, 428, 431, 444,
        451, 454, 457, 459, 464, 466, 468, 470, 475, 481, 485, 490, 495,
        497, 502, 507, 511, 517, 522, 524, 527, 531, 533, 538, 547, 552,
        557, 560, 563, 564, 568, 573, 578, 584, 589, 593, 596, 598, 601,
        602, 611, 612, 613, 629, 633, 639, 643, 648, 650, 653, 656, 667,
        669, 674, 680, 692, 697, 709, 711, 718, 727, 732, 738, 739, 740,
        760, 766, 768, 773, 776, 778, 783, 790, 792, 793, 815, 825, 826,
        828, 832, 837, 839, 846, 849, 859, 863, 868

In [24]:
df = pd.read_csv("titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [25]:
female = df.groupby(df["Gender"]).get_group("female")
female

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
880          881         1       2   
882          883         0       3   
885          886         0       3   
887          888         1       1   
888          889         0       3   

                                                  Name  Gender   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female   NaN      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
880      1            230433  26.0000   NaN        S  
882      0              7552  10.5167   NaN        S  
885      5            382652  29.1250   NaN        Q  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  

[314 rows x 12 columns]

In [26]:
s = df.groupby(df["Embarked"]).get_group("S")
s

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
..           ...       ...     ...   
883          884         0       2   
884          885         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   

                                             Name  Gender   Age  SibSp  Parch  \
0                         Braund, Mr. Owen Harris    male  22.0      1      0   
2                          Heikkinen, Miss. Laina  female   NaN      0      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1      0   
4                        Allen, Mr. William Henry    male   NaN      0      0   
6                         McCarthy, Mr. Timothy J    male  54.0      0      0   
..                                            ...     ...   ...    ...    ...   
883                 Banfield, Mr. Frederick James    male  28.0      0      0   
884                        Sutehall, Mr. Henry Jr    male  25.0      0      0   
886                         Montvila, Rev. Juozas    male  27.0      0      0   
887                  Graham, Miss. Margaret Edith  female  19.0      0      0   
888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500   NaN        S  
2    STON/O2. 3101282   7.9250   NaN        S  
3              113803  53.1000  C123        S  
4              373450   8.0500   NaN        S  
6               17463  51.8625   E46        S  
..                ...      ...   ...      ...  
883  C.A./SOTON 34068  10.5000   NaN        S  
884   SOTON/OQ 392076   7.0500   NaN        S  
886            211536  13.0000   NaN        S  
887            112053  30.0000   B42        S  
888        W./C. 6607  23.4500   NaN        S  

[644 rows x 12 columns]

In [27]:
df = pd.read_csv("diabetes.csv")
df.head(3)

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   52        1

In [28]:
df.loc[ : , ["Age","Outcome","BMI","Glucose"]]

Age  Outcome   BMI  Glucose
0     50        1  33.6      148
1     31        0  26.6       85
2     52        1  23.3      183
3     21        0  28.1      150
4     33        1  43.1      150
..   ...      ...   ...      ...
763   63        0  32.9      101
764   27        0  36.8      122
765   30        0  26.2      121
766   47        1  30.1      126
767   23        0  30.4       93

[768 rows x 4 columns]

In [29]:
df.reindex(["Age","Outcome","BMI"],axis=1)

Age  Outcome   BMI
0     50        1  33.6
1     31        0  26.6
2     52        1  23.3
3     21        0  28.1
4     33        1  43.1
..   ...      ...   ...
763   63        0  32.9
764   27        0  36.8
765   30        0  26.2
766   47        1  30.1
767   23        0  30.4

[768 rows x 3 columns]

In [30]:
df = pd.read_csv("student.csv")
df

id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [31]:
df.loc[35] = [36,"Honny","five",45,"male"]
df

id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female
35  36        Honny   five    45    male

In [32]:
df.head(3)

id      name  class  mark  gender
0   1  John Deo   Four    75  female
1   2  Max Ruin  Three    85    male
2   3    Arnold  Three    55    male

In [33]:
df.drop((df.loc[(df["mark"] < 50)]).index)

id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [34]:
df

id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female
35  36        Honny   five    45    male

In [35]:
df.iloc[[5],]

id       name class  mark gender
5   6  Alex John  Four    55   male

In [36]:
df.iloc[:5]

id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [37]:
df.head(3)

id      name  class  mark  gender
0   1  John Deo   Four    75  female
1   2  Max Ruin  Three    85    male
2   3    Arnold  Three    55    male

In [38]:
result = {class1 : len(class1) for class1 in df["class"]}
result

{'Four': 4,
 'Three': 5,
 'Fifth': 5,
 'Five': 4,
 'Six': 3,
 'Seven': 5,
 'Nine': 4,
 'Eight': 5,
 'five': 4}

In [39]:
df.head(3)

id      name  class  mark  gender
0   1  John Deo   Four    75  female
1   2  Max Ruin  Three    85    male
2   3    Arnold  Three    55    male

In [40]:
df["name"] = pd.DataFrame(df["name"].apply(lambda x : x.swapcase()))
df

id         name  class  mark  gender
0    1     jOHN dEO   Four    75  female
1    2     mAX rUIN  Three    85    male
2    3       aRNOLD  Three    55    male
3    4   kRISH sTAR   Four    60  female
4    5    jOHN mIKE   Four    60  female
5    6    aLEX jOHN   Four    55    male
6    7  mY jOHN rOB  Fifth    78    male
7    8       aSRUID   Five    85    male
8    9      tES qRY    Six    78    male
9   10     bIG jOHN   Four    55  female
10  11       rONALD    Six    89  female
11  12        rECKY    Six    94  female
12  13          kTY  Seven    88  female
13  14         bIGY  Seven    88  female
14  15     tADE rOW   Four    88    male
15  16        gIMMY   Four    88    male
16  17        tUMYU    Six    54    male
17  18        hONNY   Five    75    male
18  19        tINNY   Nine    18    male
19  20       jACKLY   Nine    65  female
20  21   bABBY jOHN   Four    69  female
21  22       rEGGID  Seven    55  female
22  23        hEROD  Eight    79    male
23  24    tIDDY nOW  Seven    78    male
24  25     gIFF tOW  Seven    88    male
25  26       cRELEA  Seven    79    male
26  27     bIG nOSE  Three    81  female
27  28    rOJJ bASE  Seven    86  female
28  29  tESS pLAYED  Seven    55    male
29  30    rEPPY rED    Six    79  female
30  31  mARRY tOEEY   Four    88    male
31  32    bINN rOTT  Seven    90  female
32  33    kENN rEIN    Six    96  female
33  34     gAIN tOE  Seven    69    male
34  35   rOWS nOUMP    Six    88  female
35  36        hONNY   five    45    male

In [41]:
df["name"] = df["name"].apply(lambda x : x.lower())
df

id         name  class  mark  gender
0    1     john deo   Four    75  female
1    2     max ruin  Three    85    male
2    3       arnold  Three    55    male
3    4   krish star   Four    60  female
4    5    john mike   Four    60  female
5    6    alex john   Four    55    male
6    7  my john rob  Fifth    78    male
7    8       asruid   Five    85    male
8    9      tes qry    Six    78    male
9   10     big john   Four    55  female
10  11       ronald    Six    89  female
11  12        recky    Six    94  female
12  13          kty  Seven    88  female
13  14         bigy  Seven    88  female
14  15     tade row   Four    88    male
15  16        gimmy   Four    88    male
16  17        tumyu    Six    54    male
17  18        honny   Five    75    male
18  19        tinny   Nine    18    male
19  20       jackly   Nine    65  female
20  21   babby john   Four    69  female
21  22       reggid  Seven    55  female
22  23        herod  Eight    79    male
23  24    tiddy now  Seven    78    male
24  25     giff tow  Seven    88    male
25  26       crelea  Seven    79    male
26  27     big nose  Three    81  female
27  28    rojj base  Seven    86  female
28  29  tess played  Seven    55    male
29  30    reppy red    Six    79  female
30  31  marry toeey   Four    88    male
31  32    binn rott  Seven    90  female
32  33    kenn rein    Six    96  female
33  34     gain toe  Seven    69    male
34  35   rows noump    Six    88  female
35  36        honny   five    45    male

In [42]:
list1 = ['Amir ',' Ashwin',' Bhakti ',' Amol','Aishwarya ','Satyam ']
s1 = pd.Series(list1)
s1

0         Amir 
1        Ashwin
2       Bhakti 
3          Amol
4    Aishwarya 
5       Satyam 
dtype: object

In [43]:
s1 = s1.apply(lambda x : x.strip())
s1

0         Amir
1       Ashwin
2       Bhakti
3         Amol
4    Aishwarya
5       Satyam
dtype: object

In [44]:
data = {'year': [1700, 1850, 2000, 2300, 1950]}
df = pd.DataFrame(data)
print(df)
result = df[(df["year"] >= 1800) & (df["year"] <= 2200)]
result

   year
0  1700
1  1850
2  2000
3  2300
4  1950


year
1  1850
2  2000
4  1950

In [45]:
df1 = pd.DataFrame(np.random.randint(1,10,(3,3)),columns=list('ABC'),index=list('pqr'))
df2 = pd.DataFrame(np.random.randint(100,1000,(4,4)),columns=list('ABCD'),index=list('pqrs'))
df1

A  B  C
p  7  6  8
q  7  5  1
r  3  9  7

In [46]:
df2

A    B    C    D
p  137  899  514  333
q  539  473  268  148
r  523  136  303  723
s  583  264  566  380

In [48]:
result = pd.concat([df1,df2])
result

A    B    C      D
p    7    6    8    NaN
q    7    5    1    NaN
r    3    9    7    NaN
p  137  899  514  333.0
q  539  473  268  148.0
r  523  136  303  723.0
s  583  264  566  380.0

In [49]:
result = pd.concat([df1,df2],axis=1)
result

A    B    C    A    B    C    D
p  7.0  6.0  8.0  137  899  514  333
q  7.0  5.0  1.0  539  473  268  148
r  3.0  9.0  7.0  523  136  303  723
s  NaN  NaN  NaN  583  264  566  380

In [50]:
df1=pd.DataFrame({"Name":["Aarathi","Veena","Lakshmipriya","Sriyan"],
"Age":[23,54,34,67],
"Location":["Pune","Bangalore","Pune","Kochi"]})
df2=pd.DataFrame({"Name":["Aara","Anupama","Robin","Dilsha","Ramya"],
"Age":[23,54,34,67,45],
"Maths":[34,45,50,49,46],
"English":[50,49,48,34,89],
"Hindi":[40,45,50,34,67]})
df3=pd.DataFrame({"Name":["Aarathi","Veena","Sriyan","Dilsha","Arohi"],
"Salary":[80000,70000,90000,780000,90000]})
df1

Name  Age   Location
0       Aarathi   23       Pune
1         Veena   54  Bangalore
2  Lakshmipriya   34       Pune
3        Sriyan   67      Kochi

In [51]:
df2

Name  Age  Maths  English  Hindi
0     Aara   23     34       50     40
1  Anupama   54     45       49     45
2    Robin   34     50       48     50
3   Dilsha   67     49       34     34
4    Ramya   45     46       89     67

In [52]:
df3

Name  Salary
0  Aarathi   80000
1    Veena   70000
2   Sriyan   90000
3   Dilsha  780000
4    Arohi   90000

In [53]:
result = pd.concat([df1,df2])
result

Name  Age   Location  Maths  English  Hindi
0       Aarathi   23       Pune    NaN      NaN    NaN
1         Veena   54  Bangalore    NaN      NaN    NaN
2  Lakshmipriya   34       Pune    NaN      NaN    NaN
3        Sriyan   67      Kochi    NaN      NaN    NaN
0          Aara   23        NaN   34.0     50.0   40.0
1       Anupama   54        NaN   45.0     49.0   45.0
2         Robin   34        NaN   50.0     48.0   50.0
3        Dilsha   67        NaN   49.0     34.0   34.0
4         Ramya   45        NaN   46.0     89.0   67.0

In [54]:
final = pd.merge(result,df3,on="Name")
final

Name  Age   Location  Maths  English  Hindi  Salary
0  Aarathi   23       Pune    NaN      NaN    NaN   80000
1    Veena   54  Bangalore    NaN      NaN    NaN   70000
2   Sriyan   67      Kochi    NaN      NaN    NaN   90000
3   Dilsha   67        NaN   49.0     34.0   34.0  780000

In [55]:
df1 = pd.DataFrame({"Name":["Aarathi","Veena","Lakshmipriya","Amit","Sriyan"],
"ID_card":['BSL004','BSL006','BSL010','BSL003','BSL007'],
"Physics":[94,86,73,96,75],
"Cemistry":[85,91,89,78,81]})
df2 = pd.DataFrame({"Name":["Aarathi","Veena","Manoj","Lakshmipriya","Sriyan"],
"ID_card":['BSL001','BSL005','BSL009','BSL008','BSL002'],
"Maths":[88,72,69,97,45],
"Biology":[98,75,86,61,64]})
df1

Name ID_card  Physics  Cemistry
0       Aarathi  BSL004       94        85
1         Veena  BSL006       86        91
2  Lakshmipriya  BSL010       73        89
3          Amit  BSL003       96        78
4        Sriyan  BSL007       75        81

In [56]:
df2

Name ID_card  Maths  Biology
0       Aarathi  BSL001     88       98
1         Veena  BSL005     72       75
2         Manoj  BSL009     69       86
3  Lakshmipriya  BSL008     97       61
4        Sriyan  BSL002     45       64

In [57]:
result = pd.merge(df1,df2,on="Name",suffixes=["_df1","_df2"])
result

Name ID_card_df1  Physics  Cemistry ID_card_df2  Maths  Biology
0       Aarathi      BSL004       94        85      BSL001     88       98
1         Veena      BSL006       86        91      BSL005     72       75
2  Lakshmipriya      BSL010       73        89      BSL008     97       61
3        Sriyan      BSL007       75        81      BSL002     45       64

In [58]:
result = pd.merge(df1,df2,on="Name",how="left",suffixes=["_df1","_df2"])
result

Name ID_card_df1  Physics  Cemistry ID_card_df2  Maths  Biology
0       Aarathi      BSL004       94        85      BSL001   88.0     98.0
1         Veena      BSL006       86        91      BSL005   72.0     75.0
2  Lakshmipriya      BSL010       73        89      BSL008   97.0     61.0
3          Amit      BSL003       96        78         NaN    NaN      NaN
4        Sriyan      BSL007       75        81      BSL002   45.0     64.0

In [59]:
result = pd.merge(df1,df2,on="Name",how="right",suffixes=["_df1","_df2"])
result

Name ID_card_df1  Physics  Cemistry ID_card_df2  Maths  Biology
0       Aarathi      BSL004     94.0      85.0      BSL001     88       98
1         Veena      BSL006     86.0      91.0      BSL005     72       75
2         Manoj         NaN      NaN       NaN      BSL009     69       86
3  Lakshmipriya      BSL010     73.0      89.0      BSL008     97       61
4        Sriyan      BSL007     75.0      81.0      BSL002     45       64

In [60]:
english_df = pd.DataFrame({'Name':['Amir','Salman','Maaz','Tanvir','Fahad'],
'Surname':['Arkar','Mulla','Surve','Kadvekar','Antule'],
'Marks':[94,86,91,93,88]})
maths_df = pd.DataFrame({'Name':['Amir','Salman','Maaz','Tanvir','Fahad'],
'Surname':['Khan','Mulla','Hafiz','Kadvekar','Shaikh'],
'Marks':[91,89,93,87,84]})
english_df

Name   Surname  Marks
0    Amir     Arkar     94
1  Salman     Mulla     86
2    Maaz     Surve     91
3  Tanvir  Kadvekar     93
4   Fahad    Antule     88

In [61]:
maths_df

Name   Surname  Marks
0    Amir      Khan     91
1  Salman     Mulla     89
2    Maaz     Hafiz     93
3  Tanvir  Kadvekar     87
4   Fahad    Shaikh     84

In [62]:
result = pd.merge(english_df,maths_df,on=["Name","Surname"],how="inner",suffixes=["_english","_maths"])
result

Name   Surname  Marks_english  Marks_maths
0  Salman     Mulla             86           89
1  Tanvir  Kadvekar             93           87

In [63]:
physics_df = pd.DataFrame({'Name_1':['Amir','Salman','Maaz','Karim','Fahad'],
'Surname':['Arkar','Mulla','Surve','Kadvekar','Antule'],
'Marks':[94,86,91,93,88]})
chemistry_df = pd.DataFrame({'Name_2':['Asif','Salman','Maaz','Tanvir','Fahad'],
'Surname':['Khan','Mulla','Hafiz','Rawal','Shaikh'],
'Marks':[91,89,93,87,84]})
physics_df

Name_1   Surname  Marks
0    Amir     Arkar     94
1  Salman     Mulla     86
2    Maaz     Surve     91
3   Karim  Kadvekar     93
4   Fahad    Antule     88

In [64]:
chemistry_df

Name_2 Surname  Marks
0    Asif    Khan     91
1  Salman   Mulla     89
2    Maaz   Hafiz     93
3  Tanvir   Rawal     87
4   Fahad  Shaikh     84

In [66]:
result = pd.merge(physics_df,chemistry_df,how="inner",left_on="Name_1",right_on="Name_2",suffixes=["_1","_2"])
result

Name_1 Surname_1  Marks_1  Name_2 Surname_2  Marks_2
0  Salman     Mulla       86  Salman     Mulla       89
1    Maaz     Surve       91    Maaz     Hafiz       93
2   Fahad    Antule       88   Fahad    Shaikh       84

In [67]:
df = pd.read_csv("movies_data.csv")
df.head(3)

star_rating                     title content_rating  genre  duration  \
0          9.3  The Shawshank Redemption              R  Crime       142   
1          9.2             The Godfather              R  Crime       175   
2          9.1    The Godfather: Part II              R  Crime       200   

                                         actors_list  
0  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1    [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...

In [68]:
result = df.sort_values("duration",ignore_index=True,ascending=False)
result

star_rating                              title content_rating      genre  \
0            7.8                             Hamlet          PG-13      Drama   
1            8.2                 Gone with the Wind              G      Drama   
2            8.4        Once Upon a Time in America              R      Crime   
3            8.3  Lagaan: Once Upon a Time in India             PG  Adventure   
4            7.9               The Ten Commandments       APPROVED  Adventure   
..           ...                                ...            ...        ...   
974          8.1                          Duck Soup         PASSED     Comedy   
975          8.4                            The Kid      NOT RATED     Comedy   
976          8.1        The Cabinet of Dr. Caligari        UNRATED      Crime   
977          8.0                Battleship Potemkin        UNRATED    History   
978          8.0                             Freaks        UNRATED      Drama   

     duration                                        actors_list  
0         242  [u'Kenneth Branagh', u'Julie Christie', u'Dere...  
1         238  [u'Clark Gable', u'Vivien Leigh', u'Thomas Mit...  
2         229  [u'Robert De Niro', u'James Woods', u'Elizabet...  
3         224  [u'Aamir Khan', u'Gracy Singh', u'Rachel Shell...  
4         220  [u'Charlton Heston', u'Yul Brynner', u'Anne Ba...  
..        ...                                                ...  
974        68    [u'Groucho Marx', u'Harpo Marx', u'Chico Marx']  
975        68  [u'Charles Chaplin', u'Edna Purviance', u'Jack...  
976        67  [u'Werner Krauss', u'Conrad Veidt', u'Friedric...  
977        66  [u'Aleksandr Antonov', u'Vladimir Barsky', u'G...  
978        64  [u'Wallace Ford', u'Leila Hyams', u'Olga Bacla...  

[979 rows x 6 columns]

In [69]:
result = df["duration"].max()
result

242

In [70]:
result = df["duration"].min()
result

64

In [71]:
result = df.loc[(df["genre"] == "Action") | (df["genre"] == "Crime")].reset_index(drop=True)
result

star_rating                                            title  \
0            9.3                         The Shawshank Redemption   
1            9.2                                    The Godfather   
2            9.1                           The Godfather: Part II   
3            9.0                                  The Dark Knight   
4            8.9                                     Pulp Fiction   
..           ...                                              ...   
255          7.4                                  La Femme Nikita   
256          7.4                                         The Rock   
257          7.4                              Law Abiding Citizen   
258          7.4  Master and Commander: The Far Side of the World   
259          7.4                                      Wall Street   

    content_rating   genre  duration  \
0                R   Crime       142   
1                R   Crime       175   
2                R   Crime       200   
3            PG-13  Action       152   
4                R   Crime       154   
..             ...     ...       ...   
255              R  Action       118   
256              R  Action       136   
257              R   Crime       109   
258          PG-13  Action       138   
259              R   Crime       126   

                                           actors_list  
0    [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1      [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2    [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3    [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4    [u'John Travolta', u'Uma Thurman', u'Samuel L....  
..                                                 ...  
255  [u'Anne Parillaud', u'Marc Duret', u'Patrick F...  
256   [u'Sean Connery', u'Nicolas Cage', u'Ed Harris']  
257  [u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']  
258  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...  
259  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...  

[260 rows x 6 columns]

In [72]:
city_df = pd.DataFrame({'Name':['Amir','Shaibaz','Suhel','Fahad','Adil','Muzaffar','Shuaib','Asif','Awez','Muzammil'],
'City':['Georgia','California','Los Angeles','California','Los Angeles','Georgia','Los Angeles',
'California','Los Angeles','California']})
city_df

Name         City
0      Amir      Georgia
1   Shaibaz   California
2     Suhel  Los Angeles
3     Fahad   California
4      Adil  Los Angeles
5  Muzaffar      Georgia
6    Shuaib  Los Angeles
7      Asif   California
8      Awez  Los Angeles
9  Muzammil   California

In [73]:
city_df.groupby(city_df["City"]).size().reset_index(name = "Number of people")

City  Number of people
0   California                 4
1      Georgia                 2
2  Los Angeles                 4

In [74]:
df = pd.read_csv("Bengaluru_House_Data.csv")
df.head(3)

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00

In [75]:
df.fillna(40)

area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II   
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society total_sqft  bath  balcony   price  
0          2 BHK  Coomee        1056   2.0      1.0   39.07  
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00  
2          3 BHK       40       1440   2.0      3.0   62.00  
3          3 BHK  Soiewre       1521   3.0      1.0   95.00  
4          2 BHK       40       1200   2.0      1.0   51.00  
...          ...      ...        ...   ...      ...     ...  
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00  
13316      4 BHK       40       3600   5.0     40.0  400.00  
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00  
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00  
13319      1 BHK       40        550   1.0      1.0   17.00  

[13320 rows x 9 columns]

In [76]:
df.replace({np.nan:0})

area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II   
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society total_sqft  bath  balcony   price  
0          2 BHK  Coomee        1056   2.0      1.0   39.07  
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00  
2          3 BHK        0       1440   2.0      3.0   62.00  
3          3 BHK  Soiewre       1521   3.0      1.0   95.00  
4          2 BHK        0       1200   2.0      1.0   51.00  
...          ...      ...        ...   ...      ...     ...  
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00  
13316      4 BHK        0       3600   5.0      0.0  400.00  
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00  
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00  
13319      1 BHK        0        550   1.0      1.0   17.00  

[13320 rows x 9 columns]

In [77]:
df = pd.DataFrame({'col1':[1,4,3,4,5],
'col2':[4,5,6,7,8],
'col3':[7,8,9,0,1]})
df

col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1

In [78]:
df.drop([0,2,4],inplace=True)
df

col1  col2  col3
1     4     5     8
3     4     7     0