In [1]:
with open("Abhishek.txt","r")as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing


In [2]:
with open("Abhishek.txt","r")as f:
    result = f.readline()
    print(result)

Data Science:



In [3]:
text = """1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing"""
with open("Abhishek.txt","a")as f:
    f.write(text)
    f.close()


In [4]:
with open("Abhishek.txt","r")as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing


In [5]:
with open("Abhishek.txt","r")as f:
    result = f.readlines()
    final = result[-2:]
    print(final)

[' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing']


In [6]:
with open("Abhishek.txt","r")as f:
    result = f.readlines()
    print(result)

['Data Science:\n', '    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge\n', '    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of \n', '    application domains.1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing']


In [7]:
with open("Abhishek.txt","r")as f:
    result = f.readlines()
    print(len(result))

19


In [8]:
with open("Abhishek.txt","r")as f:
    result = f.read()
    print(len(result))

768


In [9]:
import shutil
shutil.copy("Abhishek.txt","Abhi.txt")

'Abhi.txt'

In [11]:
with open("Abhi.txt","r") as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing


In [12]:
from datetime import datetime

current_datetime = datetime.now()
print("Current datetime: ",current_datetime)

current_year = current_datetime.year
print("Current year: ",current_year)

month_of_year = current_datetime.strftime("%B")
print("Month of year: ",month_of_year)

week_number = current_datetime.strftime("%U")
print("Week number: ",week_number)

weekday = current_datetime.strftime("%A")
print("Week day: ",weekday)

day_of_year = current_datetime.strftime("%j")
print("Day of year: ",day_of_year)

day_of_month = current_datetime.strftime("%d")
print("Day of month: ",day_of_month)



Current datetime:  2024-07-08 07:18:02.759697
Current year:  2024
Month of year:  July
Week number:  27
Week day:  Monday
Day of year:  190
Day of month:  08


In [13]:
year = int(input("Enter a year:"))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year")
else:
    print(f"{year} is not a leap year")

2026 is not a leap year


In [15]:
date_format = "jan 1 2014 2:43PM"
date1 = "%b %d %Y %I:%M%p"
result = datetime.strptime(date_format,date1)
print(result)

2014-01-01 14:43:00


In [16]:
from datetime import timedelta

In [18]:
current_datetime = datetime.now()
result = current_datetime + timedelta(days=-5)
print(result)

2024-07-03 07:44:16.256132


In [20]:
result = datetime.now() + timedelta(days=-1)
print("Date of yesterday: ", result)
result = datetime.now() + timedelta(days=0)
print("Date of Today: ", result)
result = datetime.now() + timedelta(days=+1)
print("Date of tomorrow: ", result)

Date of yesterday:  2024-07-07 07:47:03.575357
Date of Today:  2024-07-08 07:47:03.575866
Date of tomorrow:  2024-07-09 07:47:03.575866


In [21]:
current_datetime = datetime.now().date()
print("Current date: ", current_datetime)

Current date:  2024-07-08


In [22]:
for i in range(5):
    result = current_datetime + timedelta(days=i)
    print("Next 5 days starting from now: ", result)

Next 5 days starting from now:  2024-07-08
Next 5 days starting from now:  2024-07-09
Next 5 days starting from now:  2024-07-10
Next 5 days starting from now:  2024-07-11
Next 5 days starting from now:  2024-07-12


In [23]:
current_datetime = datetime.now()
print("Current date: ", current_datetime)
result = current_datetime.replace(microsecond=0)
print("Date without microsecond: ", result)

Current date:  2024-07-08 07:52:13.879273
Date without microsecond:  2024-07-08 07:52:13


In [24]:
result = datetime(2024,8,12)
print(result)
final = result.strftime("%a %d %b %Y %U")
print(final)

2024-08-12 00:00:00
Mon 12 Aug 2024 32


In [25]:
import os 
with open("Pablo.txt","w")as f:
    f.write("He is a smart boy")
    f.close()

with open("Pablo.txt","r")as f:
    result = f.read()
    print(result)

He is a smart boy


In [26]:
os.rename("Pablo.txt","Escobar.txt")

In [27]:
os.getcwd()

'd:\\Assignment'

In [28]:
os.listdir()

['.git',
 'Abhi.txt',
 'Abhishek.txt',
 'Adaboost_Ass.ipynb',
 'Assignment_1.ipynb',
 'Assignment_10.ipynb',
 'Assignment_11.ipynb',
 'Assignment_12.ipynb',
 'Assignment_2.ipynb',
 'Assignment_3.ipynb',
 'Assignment_4.ipynb',
 'Assignment_6.ipynb',
 'Assignment_7.ipynb',
 'Assignment_8.ipynb',
 'Assignment_9.ipynb',
 'Assignment_DT.ipynb',
 'Assignment_KNN.ipynb',
 'autos_dataset.csv',
 'Bengaluru_House_Data.csv',
 'Book2.csv',
 'Boston.csv',
 'deadshot.txt',
 'diabetes.csv',
 'Emp_data.csv',
 'Emp_Records.xlsx',
 'emp_test1.csv',
 'Escobar.txt',
 'heart.csv',
 'Iris.csv',
 'Linear_reg_theory.ipynb',
 'loan_data.csv',
 'Logistic_reg_assignment.ipynb',
 'movies_data.csv',
 'NLP_lec2.ipynb',
 'python_1.ipynb',
 'Python_2.ipynb',
 'python_3.ipynb',
 'Python_4.ipynb',
 'README.md',
 'Sample1.xlsx',
 'Social_Network_Ads.csv',
 'student.csv',
 'titanic.csv',
 'weather.csv']

In [29]:
try:
    print("hello")
except:
    print("Bye")

hello


In [1]:
import re
string = "Python and Machine Learning 7741 is syllabus of Data Science."
result = re.findall(r"[a-zA-Z0-9]",string)
result

['P',
 'y',
 't',
 'h',
 'o',
 'n',
 'a',
 'n',
 'd',
 'M',
 'a',
 'c',
 'h',
 'i',
 'n',
 'e',
 'L',
 'e',
 'a',
 'r',
 'n',
 'i',
 'n',
 'g',
 '7',
 '7',
 '4',
 '1',
 'i',
 's',
 's',
 'y',
 'l',
 'l',
 'a',
 'b',
 'u',
 's',
 'o',
 'f',
 'D',
 'a',
 't',
 'a',
 'S',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e']

In [2]:
string = "Python and Machine Learning is syllabus of data science and deep learning."
result = re.split(r"and",string)
result

['Python ',
 ' Machine Learning is syllabus of data science ',
 ' deep learning.']

In [3]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\ba..\b",str1)
result

['and']

In [4]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\bab*[a-z]*\b",str1)
result

['and']

In [5]:
sample_string = "There are 123 45 678 90 2345 67 12 345 6789 0123 three-digit"
result = re.findall(r"\b\d{3}\s\d{2}\b",sample_string)
result

['123 45', '678 90']

In [6]:
str1= "python and data pytthon science pythonnn pyyth annd pythh"
result = re.findall(r"p+",str1)
result

['p', 'p', 'p', 'p', 'p']

In [7]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
result

['INFORM', 'inform']

In [8]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py?",str1)
result

['py', 'py']

In [9]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [10]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"\b\w*[b]{2,3}\w*\b",str1)
result

['abbbs', 'abbbsolutely', 'abbrivation']

In [11]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [12]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [13]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [14]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [15]:
str1 = 'Suceess is a jurney not a desti9nation.'
result = re.findall(r"Suceess",str1)
result

['Suceess']

In [16]:
str1 = 'new begening of LIFE .'
result = re.findall(r"LIFE .",str1)
result

['LIFE .']

In [17]:
str1 = "today is the very lazy day"
result = re.findall(r"\b\w*z\w\b",str1)
result

['lazy']

In [18]:
str1 = "we have a lazy cat"
result = re.findall(r"[a-y]*z[a-y]",str1)
result

['lazy']

In [19]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [20]:
str1 = "9821 maya"
result = re.findall(r"^9",str1)
result

['9']

In [21]:
str1 = "9821 maya"
result = re.findall(r"^\d*",str1)
result

['9821']

In [22]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [29]:
str1="Python is required for data science version 3.2"
result = re.findall(r"\d..\b",str1)
result

['3.2']

In [30]:
str1 = "Exercises number 1, 12, 13, and 345 are important"
result = re.findall(r"[0-9]+",str1)
result

['1', '12', '13', '345']

In [31]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for word in Searched_words:
    result = re.findall(word,Sample_text)
    print(result)

['fox']
['dog']
[]


In [32]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search(r"fox",sample_text)
result

<re.Match object; span=(16, 19), match='fox'>

In [33]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [34]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
print(len(result))
result = re.search(r"exercises",Sample_text)
print(result)

3
<re.Match object; span=(7, 16), match='exercises'>


In [35]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","_",str1)
print(result)
result = re.sub(r"[_]","",result)
print(result)

The_quick_brown_fox_jumps_over_the_lazy_dog.
Thequickbrownfoxjumpsoverthelazydog.


In [36]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","",str1)
result

'Thequickbrownfoxjumpsoverthelazydog.'

In [37]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [38]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*",str1)
result

['and', 'every', 'evening']

In [39]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [40]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[,. ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [41]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[,. ]{2}",":",text)
result

'Python: is a general purpose interpreted.'

In [42]:
text ="""123 Python is a general-purpose, interpreted,
high-level programming language popularly used for
website development, data analytics 78 and automation."""

result = re.findall(r"\b\D{3,5}\b",text)
result

[' is a', 'high-', 'level', ' used', ' for\n', 'data ', ' and ']

In [1]:
import numpy as np 
import pandas as pd


In [4]:
df = pd.read_table("Restaurant_Reviews.tsv")
df

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [5]:
df["Review"]

0                               Wow... Loved this place.
1                                     Crust is not good.
2              Not tasty and the texture was just nasty.
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
                             ...                        
995    I think food should have flavor and texture an...
996                             Appetite instantly gone.
997    Overall I was not impressed and would not go b...
998    The whole experience was underwhelming, and I ...
999    Then, as if I hadn't wasted enough of my life ...
Name: Review, Length: 1000, dtype: object

In [6]:
lower_casing = [word.lower() for word in df["Review"]]
lower_casing

['wow... loved this place.',
 'crust is not good.',
 'not tasty and the texture was just nasty.',
 'stopped by during the late may bank holiday off rick steve recommendation and loved it.',
 'the selection on the menu was great and so were the prices.',
 'now i am getting angry and i want my damn pho.',
 "honeslty it didn't taste that fresh.)",
 'the potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer.',
 'the fries were great too.',
 'a great touch.',
 'service was very prompt.',
 'would not go back.',
 'the cashier had no care what so ever on what i had to say it still ended up being wayyy overpriced.',
 'i tried the cape cod ravoli, chicken, with cranberry...mmmm!',
 'i was disgusted because i was pretty sure that was human hair.',
 'i was shocked because no signs indicate cash only.',
 'highly recommended.',
 'waitress was a little slow in service.',
 'this place is not worth your time, let alone vegas.',
 'did not like at all.

In [7]:
from nltk.corpus import stopwords
Stopwords = stopwords.words("english")
Stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [8]:
len(Stopwords)

179

In [9]:
new_text_after_stopwords = []
for word in lower_casing:
    if word not in Stopwords:
        new_text_after_stopwords.append(word)
new_text_after_stopwords

['wow... loved this place.',
 'crust is not good.',
 'not tasty and the texture was just nasty.',
 'stopped by during the late may bank holiday off rick steve recommendation and loved it.',
 'the selection on the menu was great and so were the prices.',
 'now i am getting angry and i want my damn pho.',
 "honeslty it didn't taste that fresh.)",
 'the potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer.',
 'the fries were great too.',
 'a great touch.',
 'service was very prompt.',
 'would not go back.',
 'the cashier had no care what so ever on what i had to say it still ended up being wayyy overpriced.',
 'i tried the cape cod ravoli, chicken, with cranberry...mmmm!',
 'i was disgusted because i was pretty sure that was human hair.',
 'i was shocked because no signs indicate cash only.',
 'highly recommended.',
 'waitress was a little slow in service.',
 'this place is not worth your time, let alone vegas.',
 'did not like at all.

In [13]:
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer

In [14]:
Lemma = WordNetLemmatizer()
stem = PorterStemmer()

1. Data Gathering 
2. Preprocessing 
   1. lowercasing
   2. stopwords, domain specific stopwords
   3. contraction mapping
   4. lemmatization,Stemming
   5. spell check
   6. removing punctations
   7. laveshtian distance
3. Text representation
   1. Count Vectorizer 
   2. TF - IDF 
   3. Word2vec
   4. Fasttext
   5. Glove
4. Use of Algorithms
   1. Naive Bayes
   2. RNN 
   3. LSTM
5. Evaluation
   1. COnfusion matrix
   2. Classification report
   3. AUC - ROC curve
   

In [1]:
import numpy as np

In [2]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr1.nbytes

80

In [5]:
arr1 = np.zeros(10)
arr1
arr1[4] = 1
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [7]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [9]:
arr2 = reversed(arr1)
list(arr2)

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [10]:
arr1 = np.random.randint(1,10,size=(2,2))
print("Array 1:\n",arr1)
arr2 = np.random.randint(20,30,size=(2,2))
print("Array 2:\n",arr2)

Array 1:
 [[8 5]
 [3 5]]
Array 2:
 [[27 24]
 [20 26]]


In [11]:
add = arr1 + arr2
add

array([[35, 29],
       [23, 31]])

In [12]:
sub = arr1 - arr2
sub

array([[-19, -19],
       [-17, -21]])

In [13]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [14]:
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [15]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [16]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array :\n",arr1)
mean_row = np.mean(arr1,axis=1)
print("Mean across rows :",mean_row)
mean_col = np.mean(arr1,axis=0)
print("Mean across columns :",mean_col)

Array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean across rows : [2. 5. 8.]
Mean across columns : [4. 5. 6.]


In [17]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [18]:
arr1 = np.arange(9).reshape(3,3)
print("Array :\n",arr1)

Array :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array :\n",arr1)
arr1[:: , ::-1]

Array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [20]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr1[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [22]:
result = np.nonzero([1,2,0,0,4,0])
result

(array([0, 1, 4], dtype=int64),)

In [23]:
arr1 = np.array([[1,2],[3,4]])
print("Array :\n",arr1)
result = np.linalg.det(arr1)
result

Array :
 [[1 2]
 [3 4]]


-2.0000000000000004

In [24]:
arr1

array([[1, 2],
       [3, 4]])

In [25]:
result = np.linalg.inv(arr1)
result

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [26]:
arr1 = np.random.randint(1,10,size=(30))
print("Array :\n",arr1)
result = np.mean(arr1)
result

Array :
 [6 4 7 9 9 2 3 8 4 1 8 8 3 9 8 4 5 1 8 3 4 3 5 1 9 5 8 8 1 7]


5.366666666666666

In [27]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array :\n",arr1)
result = np.where(arr1 > 5)
result

Array :
 [ 1  2  3  4  5  6  7  8  9 10]


(array([5, 6, 7, 8, 9], dtype=int64),)

In [28]:
arr1 = np.random.random((3,3,3))
print("Array :\n",arr1)

Array :
 [[[0.4741754  0.61338741 0.34267948]
  [0.07365331 0.54792035 0.95446653]
  [0.8763885  0.77081324 0.03847026]]

 [[0.61085631 0.37096675 0.06858381]
  [0.73267909 0.09863887 0.1292516 ]
  [0.3420986  0.76183414 0.79958009]]

 [[0.43467136 0.05912593 0.01755935]
  [0.08344712 0.10032393 0.16034869]
  [0.36646472 0.26444025 0.09906588]]]


In [30]:
arr1 = np.random.rand(10,10)
print("Array :\n",arr1)
print("Maximum :",np.max(arr1))
print("Minimum :",np.min(arr1))

Array :
 [[0.97132006 0.48304303 0.3851227  0.78350675 0.34392007 0.39383662
  0.02222404 0.72462964 0.5859613  0.80284726]
 [0.91606004 0.11272656 0.18571598 0.60692281 0.01676893 0.81871929
  0.21479829 0.76634486 0.4468287  0.8349704 ]
 [0.3515856  0.09967324 0.01247895 0.74935674 0.29100608 0.27992913
  0.45330098 0.66841167 0.78199609 0.49896228]
 [0.97846541 0.20383806 0.91107091 0.76037941 0.50281297 0.85017567
  0.62584348 0.16812155 0.85260172 0.1172363 ]
 [0.09951709 0.73769067 0.44354901 0.943424   0.54209621 0.07454408
  0.06991675 0.69217006 0.03545471 0.24983634]
 [0.55218767 0.5642437  0.30185151 0.72019874 0.82007075 0.99182286
  0.12272339 0.53526174 0.77201683 0.88512969]
 [0.55682375 0.35505102 0.11459045 0.15827047 0.12557667 0.79242143
  0.23331405 0.29753678 0.44757632 0.12055803]
 [0.77030516 0.51279797 0.43396564 0.11515102 0.69705184 0.01825491
  0.86764756 0.63666881 0.32311392 0.64887162]
 [0.53262002 0.5787348  0.99502849 0.50089525 0.41076727 0.75504967
  0

In [31]:
arr1 = np.ones((10,10))
print("Array:\n",arr1)
arr1[1:-1,1:-1] = 0
arr1

Array:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [32]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4])
arr1

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [33]:
arr1 = np.eye(3,3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
arr1 = np.random.randint(1,9,size=(5,3))
arr2 = np.random.randint(1,9,size=(3,2))
result = np.dot(arr1,arr2)
print("Array 1 :\n",arr1)
print("Array 2 :\n",arr2)
print("Multiplication array :\n",result)

Array 1 :
 [[5 2 7]
 [1 3 5]
 [7 3 4]
 [6 1 8]
 [5 6 5]]
Array 2 :
 [[3 3]
 [7 1]
 [6 7]]
Multiplication array :
 [[71 66]
 [54 41]
 [66 52]
 [73 75]
 [87 56]]


In [35]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
result = np.where((arr1 >= 3) & (arr1 <= 8), -1*arr1 , arr1)
result

array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [36]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Array:\n",arr1)
result = np.around(arr1,1)
result

Array:
 [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]


array([[1.2, 2.7],
       [3.5, 5.2]])

In [37]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1,arr2)
result

array([4, 5, 6])

In [38]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [39]:
arr1 = np.random.randint(1,10,size=(10))
print("Array:",arr1)
result = np.sort(arr1)
result

Array: [4 6 7 1 1 4 6 7 4 5]


array([1, 1, 4, 4, 4, 5, 6, 6, 7, 7])

In [40]:
arr1 = np.zeros((5,5))
print("Array:",arr1)
arr2 = arr1 + np.arange(5)
arr2

Array: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [41]:
arr1 = np.random.randint(0,5,size=(5))
arr2 = np.random.randint(0,5,size=(5))
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [42]:
result = np.allclose(arr1,arr2)
result

False

In [43]:
arr1 = np.random.randint(1,10,size=(10))
print("Array:",arr1)
result = np.where((np.max(arr1) == arr1),0,arr1)
result

Array: [5 6 8 5 7 5 9 2 2 6]


array([5, 6, 8, 5, 7, 5, 0, 2, 2, 6])

In [44]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr1):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

In [45]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

(0, 0) index has 1 values
(0, 1) index has 2 values
(0, 2) index has 3 values
(1, 0) index has 4 values
(1, 1) index has 5 values
(1, 2) index has 6 values
(2, 0) index has 7 values
(2, 1) index has 8 values
(2, 2) index has 9 values


In [46]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array:\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array:
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [47]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.mean(arr1)
result

5.5

In [48]:
result = np.median(arr1)
result

5.5

In [49]:
arr1 = np.random.randint(1,10,size=(10))
print("Array:\n",arr1)
result = np.std(arr1)
result

Array:
 [3 6 2 4 4 8 6 5 6 3]


1.7349351572897473

In [50]:
from scipy.stats import mode
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = mode(arr1)
result

ModeResult(mode=1, count=1)

In [51]:
result = np.around(5.3245,2)
result

5.32

In [52]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr1 = np.array([[2,3],[3,4]])
result = np.linalg.inv(arr1)
result

array([[-4.,  3.],
       [ 3., -2.]])

In [55]:
x = np.array([1,2,3])
y = np.array([4,5,6])
result = np.cov(x,y)
result

array([[1., 1.],
       [1., 1.]])

In [56]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:",arr1)
arr2 = np.reshape(arr1,(2,5,1))
arr2

Array: [ 1  2  3  4  5  6  7  8  9 10]


array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [57]:
arr1 = np.random.randint(1,10,size=(1,2,3,4))
print("Array:\n",arr1)
arr2 = np.reshape(arr1,(6,4))
arr2

Array:
 [[[[4 2 3 8]
   [7 3 6 9]
   [9 1 1 3]]

  [[1 8 9 1]
   [7 7 6 4]
   [2 7 4 1]]]]


array([[4, 2, 3, 8],
       [7, 3, 6, 9],
       [9, 1, 1, 3],
       [1, 8, 9, 1],
       [7, 7, 6, 4],
       [2, 7, 4, 1]])

In [58]:
arr1 = np.zeros(10,dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
arr1.shape

(3, 4)

In [1]:
import numpy as np
import pandas as pd

In [2]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
list1 = [[1,2,3],[4,5,6]]
pd.DataFrame(list1)

0  1  2
0  1  2  3
1  4  5  6

In [4]:
df = pd.DataFrame(columns=list("ABCD"),index=list("PQRS"))
df

A    B    C    D
P  NaN  NaN  NaN  NaN
Q  NaN  NaN  NaN  NaN
R  NaN  NaN  NaN  NaN
S  NaN  NaN  NaN  NaN

In [5]:
if df.isnull:
    print("Dataframe is empty")
else:
    print("Dataframe is not null")

Dataframe is empty


In [6]:
arr1 = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(arr1)
df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
list1 = [[1,2,3],[4,5,6]]
df = pd.DataFrame(list1)
df

0  1  2
0  1  2  3
1  4  5  6

In [8]:
tuple1 = (1,2,3,4,5,6)
df = pd.DataFrame(tuple1)
df

0
0  1
1  2
2  3
3  4
4  5
5  6

In [9]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [10]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]
df = pd.DataFrame(l1,columns=list("ABC"))
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [11]:
df = pd.DataFrame(np.random.randint(10,40,size=(5,6)))
df

0   1   2   3   4   5
0  36  36  11  32  12  33
1  11  37  36  23  36  24
2  34  36  27  16  20  35
3  38  10  14  21  26  30
4  22  20  31  11  21  35

In [12]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(arr1)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [13]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [14]:
s1 = pd.Series([1,2,3,4,5,6])
print(s1)
s2 = s1.copy()
s2[0] = 50
print(s2)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
0    50
1     2
2     3
3     4
4     5
5     6
dtype: int64


In [15]:
df = pd.DataFrame(np.full((4,5),6))
df

0  1  2  3  4
0  6  6  6  6  6
1  6  6  6  6  6
2  6  6  6  6  6
3  6  6  6  6  6

In [16]:
df["5"] = [1,2,3,4]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4

In [17]:
df.loc[4] = [1,2,3,4,5,6]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4
4  1  2  3  4  5  6

In [18]:
arr1 = np.random.randint(0,20,size=(4,4))
df = pd.DataFrame(arr1,columns=list("PQRS"),index=list("ABCD"))
print(df)

    P   Q   R  S
A  17  11  11  3
B   4  13   7  3
C  15  19  15  8
D  19   1   2  8


In [20]:
df.rename({"P":"p","Q":"q","R":"r","S":"s"},axis=1,inplace=True)
df.rename({"A":"a","B":"b","C":"c","D":"d"},axis=0,inplace=True)
df

p   q   r  s
a  17  11  11  3
b   4  13   7  3
c  15  19  15  8
d  19   1   2  8

In [21]:
for i in df.items():
    print(i)

('p', a    17
b     4
c    15
d    19
Name: p, dtype: int32)
('q', a    11
b    13
c    19
d     1
Name: q, dtype: int32)
('r', a    11
b     7
c    15
d     2
Name: r, dtype: int32)
('s', a    3
b    3
c    8
d    8
Name: s, dtype: int32)


In [22]:
for i in df.iterrows():
    print(i)

('a', p    17
q    11
r    11
s     3
Name: a, dtype: int32)
('b', p     4
q    13
r     7
s     3
Name: b, dtype: int32)
('c', p    15
q    19
r    15
s     8
Name: c, dtype: int32)
('d', p    19
q     1
r     2
s     8
Name: d, dtype: int32)


In [23]:
df = pd.DataFrame(np.random.randint(1,10,size=(4,4)))
print(df)
arr1 = df.values
arr1

   0  1  2  3
0  7  8  9  7
1  2  4  6  6
2  9  9  6  2
3  3  4  3  5


array([[7, 8, 9, 7],
       [2, 4, 6, 6],
       [9, 9, 6, 2],
       [3, 4, 3, 5]])

In [24]:
arr1 = df.values
arr1.tolist()

[[7, 8, 9, 7], [2, 4, 6, 6], [9, 9, 6, 2], [3, 4, 3, 5]]

In [25]:
df.reset_index(drop=True)

0  1  2  3
0  7  8  9  7
1  2  4  6  6
2  9  9  6  2
3  3  4  3  5

In [26]:
df = pd.DataFrame(np.random.randint(1,10,size=(4,5)))
print(df)
print(df.shape[0])
print(df.shape[1])

   0  1  2  3  4
0  1  6  9  1  6
1  2  9  2  5  4
2  7  8  7  6  6
3  9  2  6  9  1
4
5


In [27]:
s1 = pd.Series(np.arange(10,20))
s2 = pd.Series(np.arange(20,30))
print("Addition:",s1+s2)
print("Subtraction:",s1-s2)
print("Multiplication:",s1*s2)
print("Division:",s1/s2)

Addition: 0    30
1    32
2    34
3    36
4    38
5    40
6    42
7    44
8    46
9    48
dtype: int32
Subtraction: 0   -10
1   -10
2   -10
3   -10
4   -10
5   -10
6   -10
7   -10
8   -10
9   -10
dtype: int32
Multiplication: 0    200
1    231
2    264
3    299
4    336
5    375
6    416
7    459
8    504
9    551
dtype: int32
Division: 0    0.500000
1    0.523810
2    0.545455
3    0.565217
4    0.583333
5    0.600000
6    0.615385
7    0.629630
8    0.642857
9    0.655172
dtype: float64


In [28]:
df = pd.read_excel("Sample1.xlsx")
df

Unnamed: 0 First Name   Last Name  Gender        Country  Age  \
0             1      Dulce       Abril  Female  United States   32   
1             2       Mara   Hashimoto  Female  Great Britain   25   
2             3     Philip        Gent    Male         France   36   
3             4   Kathleen      Hanner  Female  United States   25   
4             5    Nereida     Magwood  Female  United States   58   
..          ...        ...         ...     ...            ...  ...   
995         996       Roma  Lafollette  Female  United States   34   
996         997     Felisa        Cail  Female  United States   28   
997         998   Demetria       Abbey  Female  United States   32   
998         999     Jeromy        Danz    Male  United States   39   
999        1000   Rasheeda      Alkire  Female  United States   29   

           Date    Id  
0    15/10/2017  1562  
1    16/08/2016  1582  
2    21/05/2015  2587  
3    15/10/2017  3549  
4    16/08/2016  2468  
..          ...   ...  
995  15/10/2017  2654  
996  16/08/2016  6525  
997  21/05/2015  3265  
998  15/10/2017  3265  
999  16/08/2016  6125  

[1000 rows x 8 columns]

In [29]:
df.columns

Index(['Unnamed: 0', 'First Name', 'Last Name', 'Gender', 'Country', 'Age',
       'Date', 'Id'],
      dtype='object')

In [30]:
df[['First Name', 'Last Name']]

First Name   Last Name
0        Dulce       Abril
1         Mara   Hashimoto
2       Philip        Gent
3     Kathleen      Hanner
4      Nereida     Magwood
..         ...         ...
995       Roma  Lafollette
996     Felisa        Cail
997   Demetria       Abbey
998     Jeromy        Danz
999   Rasheeda      Alkire

[1000 rows x 2 columns]

In [31]:
df["Age"].mean()

33.26

In [32]:
df["Age"].max()

58

In [33]:
df["Age"].min()

21

In [34]:
df["Age"].sum()

33260

In [35]:
df = pd.read_csv("titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [36]:
df.groupby(df["Embarked"]).get_group("S")


PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
..           ...       ...     ...   
883          884         0       2   
884          885         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   

                                             Name  Gender   Age  SibSp  Parch  \
0                         Braund, Mr. Owen Harris    male  22.0      1      0   
2                          Heikkinen, Miss. Laina  female   NaN      0      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1      0   
4                        Allen, Mr. William Henry    male   NaN      0      0   
6                         McCarthy, Mr. Timothy J    male  54.0      0      0   
..                                            ...     ...   ...    ...    ...   
883                 Banfield, Mr. Frederick James    male  28.0      0      0   
884                        Sutehall, Mr. Henry Jr    male  25.0      0      0   
886                         Montvila, Rev. Juozas    male  27.0      0      0   
887                  Graham, Miss. Margaret Edith  female  19.0      0      0   
888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500   NaN        S  
2    STON/O2. 3101282   7.9250   NaN        S  
3              113803  53.1000  C123        S  
4              373450   8.0500   NaN        S  
6               17463  51.8625   E46        S  
..                ...      ...   ...      ...  
883  C.A./SOTON 34068  10.5000   NaN        S  
884   SOTON/OQ 392076   7.0500   NaN        S  
886            211536  13.0000   NaN        S  
887            112053  30.0000   B42        S  
888        W./C. 6607  23.4500   NaN        S  

[644 rows x 12 columns]

In [37]:
arr1 = np.random.randint(1,10,size=(4,2))
df = pd.DataFrame(arr1)
df.apply(np.sqrt)

0         1
0  2.449490  1.414214
1  2.236068  2.236068
2  2.645751  2.828427
3  1.000000  2.645751

In [38]:
df.apply(lambda x : x**2)

0   1
0  36   4
1  25  25
2  49  64
3   1  49

In [39]:
df.apply(lambda x : x**3)

0    1
0  216    8
1  125  125
2  343  512
3    1  343

In [40]:
df = pd.read_csv("diabetes.csv")
df.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   
3      150             66             23       94  28.1   
4      150             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   52        1  
3                     0.167   21        0  
4                     2.288   33        1

In [41]:
df.tail()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763      101             76             48      180  32.9   
764      122             70             27        0  36.8   
765      121             72             23      112  26.2   
766      126             60              0        0  30.1   
767       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Glucose                   768 non-null    int64  
 1   BloodPressure             768 non-null    int64  
 2   SkinThickness             768 non-null    int64  
 3   Insulin                   768 non-null    int64  
 4   BMI                       768 non-null    float64
 5   DiabetesPedigreeFunction  768 non-null    float64
 6   Age                       768 non-null    int64  
 7   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 48.1 KB


In [43]:
df.describe()

Glucose  BloodPressure  SkinThickness     Insulin         BMI  \
count  768.000000     768.000000     768.000000  768.000000  768.000000   
mean   121.117188      69.076823      20.536458   79.799479   31.992578   
std     31.805091      19.367794      15.952218  115.244002    7.884160   
min      0.000000       0.000000       0.000000    0.000000    0.000000   
25%     99.000000      62.000000       0.000000    0.000000   27.300000   
50%    117.000000      72.000000      23.000000   30.500000   32.000000   
75%    142.000000      80.000000      32.000000  127.250000   36.600000   
max    199.000000     122.000000      99.000000  846.000000   67.100000   

       DiabetesPedigreeFunction         Age     Outcome  
count                768.000000  768.000000  768.000000  
mean                   0.471876   33.243490    0.348958  
std                    0.331329   11.758182    0.476951  
min                    0.078000   21.000000    0.000000  
25%                    0.243750   24.000000    0.000000  
50%                    0.372500   29.000000    0.000000  
75%                    0.626250   41.000000    1.000000  
max                    2.420000   81.000000    1.000000

In [44]:
data1 = {"NAME" : ["Rudranshi","Sanvi","Swati","Shiva"]}
df = pd.DataFrame(data1)
df

NAME
0  Rudranshi
1      Sanvi
2      Swati
3      Shiva

In [45]:
df["NAME"].apply(lambda x : x.istitle())

0    True
1    True
2    True
3    True
Name: NAME, dtype: bool

In [46]:
d1 = {"Employee":["Saniya","Sara","Alexa","Jenny"]}
df = pd.DataFrame(d1)
d2 = {"Saniya": "Software Developer" , "Sara":"Developer" , "Alexa":"Assistant"}
df["Designation"] = df["Employee"].map(d2)
df

Employee         Designation
0   Saniya  Software Developer
1     Sara           Developer
2    Alexa           Assistant
3    Jenny                 NaN

In [47]:
arr1 = np.random.randint(1,10,size=(5,5))
df = pd.DataFrame(arr1,columns=list("ABCDE"))
df

A  B  C  D  E
0  9  7  6  7  5
1  4  4  1  3  4
2  2  7  9  1  6
3  3  3  9  2  2
4  5  1  2  4  4

In [48]:
df["I"] = [1,2,3,4,5]
df

A  B  C  D  E  I
0  9  7  6  7  5  1
1  4  4  1  3  4  2
2  2  7  9  1  6  3
3  3  3  9  2  2  4
4  5  1  2  4  4  5

In [49]:
df.insert(1,"H",[1,2,1,2,1])
df

A  H  B  C  D  E  I
0  9  1  7  6  7  5  1
1  4  2  4  1  3  4  2
2  2  1  7  9  1  6  3
3  3  2  3  9  2  2  4
4  5  1  1  2  4  4  5

In [50]:
df.drop("A",axis=1,inplace=True)
df

H  B  C  D  E  I
0  1  7  6  7  5  1
1  2  4  1  3  4  2
2  1  7  9  1  6  3
3  2  3  9  2  2  4
4  1  1  2  4  4  5

In [51]:
df.drop(2,axis=0,inplace=True)
df

H  B  C  D  E  I
0  1  7  6  7  5  1
1  2  4  1  3  4  2
3  2  3  9  2  2  4
4  1  1  2  4  4  5

In [52]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([4,5,6,7,8])
s11 = set(s1)
s22 = set(s2)
result = s11.symmetric_difference(s22)
final = pd.Series(list(result))
final

0    1
1    2
2    3
3    6
4    7
5    8
dtype: int64

In [53]:
s1 = pd.Series([1,2,3,4,5])
print("Median:",s1.median())
print("Minimum:",s1.min())
print("25th percentile:",s1.quantile(0.25))
print("75th percentile:",s1.quantile(0.75))
print("Maximum:",s1.max())

Median: 3.0
Minimum: 1
25th percentile: 2.0
75th percentile: 4.0
Maximum: 5


In [54]:
df = pd.DataFrame(np.random.randint(10,50,size=(4,4)) , columns=list("CABD") , index=list("xzvs"))
df

C   A   B   D
x  49  30  30  41
z  16  45  10  28
v  16  20  27  31
s  16  35  12  17

In [55]:
df = pd.DataFrame(np.random.randint(10,50,size=(4,4)) , columns=list("CABD") , index=list("xzvs"))
df

C   A   B   D
x  47  47  23  33
z  37  10  25  22
v  25  36  27  20
s  41  24  41  20

In [56]:
df.sort_index()

C   A   B   D
s  41  24  41  20
v  25  36  27  20
x  47  47  23  33
z  37  10  25  22

In [57]:
df.sort_index(axis=1)

A   B   C   D
x  47  23  47  33
z  10  25  37  22
v  36  27  25  20
s  24  41  41  20

In [58]:
df.sort_values("D")

C   A   B   D
v  25  36  27  20
s  41  24  41  20
z  37  10  25  22
x  47  47  23  33

In [59]:
df = pd.DataFrame({"A" : [1,1,3,4,5],
                   "B" : [1,1,3,4,5],
                   "C" : [1,1,3,4,5],
                   "D" : [1,1,3,4,5]})
df

A  B  C  D
0  1  1  1  1
1  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [60]:
df.drop_duplicates()

A  B  C  D
0  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [61]:
df.drop("A",axis=1,inplace=True)

In [62]:
df

B  C  D
0  1  1  1
1  1  1  1
2  3  3  3
3  4  4  4
4  5  5  5

In [63]:
data = {'Full Name': ['John Doe', 'Jane Smith', 'Bob Johnson']}
df = pd.DataFrame(data)
df[["First Name","Last Name"]] = df["Full Name"].str.split(expand=True)
df

Full Name First Name Last Name
0     John Doe       John       Doe
1   Jane Smith       Jane     Smith
2  Bob Johnson        Bob   Johnson

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1   
4                           Allen, Mr. William Henry    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            180
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
df["Age"].fillna(df["Age"].mean(),inplace=True)
df["Age"].isna().sum()

0

In [5]:
movie_dict = {"Movies":["Interstellar","Avengers","Dhoom","Interstellar"],
"Genre":["fiction","Fiction","Comedy","fiction"],
"Actors":["American","French","Indian","American"]}
index_labels = ["a","b","c","d"]

df = pd.DataFrame(movie_dict,index=index_labels)
df

Movies    Genre    Actors
a  Interstellar  fiction  American
b      Avengers  Fiction    French
c         Dhoom   Comedy    Indian
d  Interstellar  fiction  American

In [6]:
df.head(3)

Movies    Genre    Actors
a  Interstellar  fiction  American
b      Avengers  Fiction    French
c         Dhoom   Comedy    Indian

In [7]:
df = pd.read_csv("titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [8]:
df.loc[:1 , ["Name","Age","Gender"]]

Name   Age  Gender
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female

In [9]:
df.loc[[0,2,4,6,8,10] , ["Name","Age","Gender"]]

Name   Age  Gender
0                             Braund, Mr. Owen Harris  22.0    male
2                              Heikkinen, Miss. Laina   NaN  female
4                            Allen, Mr. William Henry   NaN    male
6                             McCarthy, Mr. Timothy J  54.0    male
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0  female
10                    Sandstrom, Miss. Marguerite Rut   4.0  female

In [10]:
df.isna()

PassengerId  Survived  Pclass   Name  Gender    Age  SibSp  Parch  \
0          False     False   False  False   False  False  False  False   
1          False     False   False  False   False  False  False  False   
2          False     False   False  False   False   True  False  False   
3          False     False   False  False   False   True  False  False   
4          False     False   False  False   False   True  False  False   
..           ...       ...     ...    ...     ...    ...    ...    ...   
886        False     False   False  False   False  False  False  False   
887        False     False   False  False   False  False  False  False   
888        False     False   False  False   False   True  False  False   
889        False     False   False  False   False  False  False  False   
890        False     False   False  False   False  False  False  False   

     Ticket   Fare  Cabin  Embarked  
0     False  False   True     False  
1     False  False  False     False  
2     False  False   True     False  
3     False  False  False     False  
4     False  False   True     False  
..      ...    ...    ...       ...  
886   False  False   True     False  
887   False  False  False     False  
888   False  False   True     False  
889   False  False  False     False  
890   False  False   True     False  

[891 rows x 12 columns]

In [11]:
df.isna().sum().to_dict()

{'PassengerId': 0,
 'Survived': 0,
 'Pclass': 0,
 'Name': 0,
 'Gender': 0,
 'Age': 180,
 'SibSp': 0,
 'Parch': 0,
 'Ticket': 0,
 'Fare': 0,
 'Cabin': 687,
 'Embarked': 2}

In [12]:
df.isnull().sum().to_dict()

{'PassengerId': 0,
 'Survived': 0,
 'Pclass': 0,
 'Name': 0,
 'Gender': 0,
 'Age': 180,
 'SibSp': 0,
 'Parch': 0,
 'Ticket': 0,
 'Fare': 0,
 'Cabin': 687,
 'Embarked': 2}

In [13]:
df.dropna()

PassengerId  Survived  Pclass  \
1              2         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
21            22         1       2   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name  Gender   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
21                               Beesley, Mr. Lawrence    male  34.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
21       0    248698  13.0000          D56        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[182 rows x 12 columns]

In [14]:
df.isna().sum().sum()

869

In [16]:
df["Age"].fillna(40,inplace=True)
df["Age"].isna().sum()

0

In [17]:
df = pd.read_csv("titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1   
4                           Allen, Mr. William Henry    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [18]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            180
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [19]:
df["Age"].fillna(df["Age"].mean(),inplace=True)
df["Age"].isna().sum()

0

In [20]:
df = pd.read_csv("titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1   
4                           Allen, Mr. William Henry    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [21]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            180
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [23]:
result = df["Age"].isna().to_numpy().nonzero()
result

(array([  2,   3,   4,   5,  17,  19,  26,  28,  29,  31,  32,  36,  42,
         45,  46,  47,  48,  55,  64,  65,  76,  77,  82,  87,  95, 101,
        107, 109, 121, 126, 128, 140, 154, 158, 159, 166, 168, 176, 180,
        181, 185, 186, 196, 198, 201, 214, 223, 229, 235, 240, 241, 250,
        256, 260, 264, 270, 274, 277, 284, 295, 298, 300, 301, 303, 304,
        306, 324, 330, 334, 335, 347, 351, 354, 358, 359, 364, 367, 368,
        375, 384, 388, 409, 410, 411, 413, 415, 420, 425, 428, 431, 444,
        451, 454, 457, 459, 464, 466, 468, 470, 475, 481, 485, 490, 495,
        497, 502, 507, 511, 517, 522, 524, 527, 531, 533, 538, 547, 552,
        557, 560, 563, 564, 568, 573, 578, 584, 589, 593, 596, 598, 601,
        602, 611, 612, 613, 629, 633, 639, 643, 648, 650, 653, 656, 667,
        669, 674, 680, 692, 697, 709, 711, 718, 727, 732, 738, 739, 740,
        760, 766, 768, 773, 776, 778, 783, 790, 792, 793, 815, 825, 826,
        828, 832, 837, 839, 846, 849, 859, 863, 868

In [24]:
df = pd.read_csv("titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1   
4                           Allen, Mr. William Henry    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [26]:
female = df.groupby(df["Gender"]).get_group("female")
female

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
880          881         1       2   
882          883         0       3   
885          886         0       3   
887          888         1       1   
888          889         0       3   

                                                  Name  Gender   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female   NaN      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
880      1            230433  26.0000   NaN        S  
882      0              7552  10.5167   NaN        S  
885      5            382652  29.1250   NaN        Q  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  

[314 rows x 12 columns]

In [28]:
s = df.groupby(df["Embarked"]).get_group("S")
s

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
..           ...       ...     ...   
883          884         0       2   
884          885         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   

                                             Name  Gender   Age  SibSp  Parch  \
0                         Braund, Mr. Owen Harris    male  22.0      1      0   
2                          Heikkinen, Miss. Laina  female   NaN      0      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1      0   
4                        Allen, Mr. William Henry    male   NaN      0      0   
6                         McCarthy, Mr. Timothy J    male  54.0      0      0   
..                                            ...     ...   ...    ...    ...   
883                 Banfield, Mr. Frederick James    male  28.0      0      0   
884                        Sutehall, Mr. Henry Jr    male  25.0      0      0   
886                         Montvila, Rev. Juozas    male  27.0      0      0   
887                  Graham, Miss. Margaret Edith  female  19.0      0      0   
888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500   NaN        S  
2    STON/O2. 3101282   7.9250   NaN        S  
3              113803  53.1000  C123        S  
4              373450   8.0500   NaN        S  
6               17463  51.8625   E46        S  
..                ...      ...   ...      ...  
883  C.A./SOTON 34068  10.5000   NaN        S  
884   SOTON/OQ 392076   7.0500   NaN        S  
886            211536  13.0000   NaN        S  
887            112053  30.0000   B42        S  
888        W./C. 6607  23.4500   NaN        S  

[644 rows x 12 columns]

In [29]:
df = pd.read_csv("diabetes.csv")
df.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   
3      150             66             23       94  28.1   
4      150             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   52        1  
3                     0.167   21        0  
4                     2.288   33        1

In [30]:
df.loc[: , ["Age","Outcome","BMI","Glucose"]]

Age  Outcome   BMI  Glucose
0     50        1  33.6      148
1     31        0  26.6       85
2     52        1  23.3      183
3     21        0  28.1      150
4     33        1  43.1      150
..   ...      ...   ...      ...
763   63        0  32.9      101
764   27        0  36.8      122
765   30        0  26.2      121
766   47        1  30.1      126
767   23        0  30.4       93

[768 rows x 4 columns]

In [31]:
df.reindex(["Age","Outcome","BMI","Glucose"],axis=1)

Age  Outcome   BMI  Glucose
0     50        1  33.6      148
1     31        0  26.6       85
2     52        1  23.3      183
3     21        0  28.1      150
4     33        1  43.1      150
..   ...      ...   ...      ...
763   63        0  32.9      101
764   27        0  36.8      122
765   30        0  26.2      121
766   47        1  30.1      126
767   23        0  30.4       93

[768 rows x 4 columns]

In [33]:
df = pd.read_csv("student.csv")
df

id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [34]:
df.loc[35] = [36 , "Honny" , "five" ,45 , "male"]
df

id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female
35  36        Honny   five    45    male

In [35]:
df.drop((df.loc[(df["mark"] < 50)]).index)

id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [36]:
df.iloc[[5],]

id       name class  mark gender
5   6  Alex John  Four    55   male

In [37]:
df.iloc[:5]

id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [38]:
result = {class1 : len(class1) for class1 in df["class"]}
result

{'Four': 4,
 'Three': 5,
 'Fifth': 5,
 'Five': 4,
 'Six': 3,
 'Seven': 5,
 'Nine': 4,
 'Eight': 5,
 'five': 4}

In [39]:
df["name"] = df["name"].apply(lambda x : x.swapcase())
df

id         name  class  mark  gender
0    1     jOHN dEO   Four    75  female
1    2     mAX rUIN  Three    85    male
2    3       aRNOLD  Three    55    male
3    4   kRISH sTAR   Four    60  female
4    5    jOHN mIKE   Four    60  female
5    6    aLEX jOHN   Four    55    male
6    7  mY jOHN rOB  Fifth    78    male
7    8       aSRUID   Five    85    male
8    9      tES qRY    Six    78    male
9   10     bIG jOHN   Four    55  female
10  11       rONALD    Six    89  female
11  12        rECKY    Six    94  female
12  13          kTY  Seven    88  female
13  14         bIGY  Seven    88  female
14  15     tADE rOW   Four    88    male
15  16        gIMMY   Four    88    male
16  17        tUMYU    Six    54    male
17  18        hONNY   Five    75    male
18  19        tINNY   Nine    18    male
19  20       jACKLY   Nine    65  female
20  21   bABBY jOHN   Four    69  female
21  22       rEGGID  Seven    55  female
22  23        hEROD  Eight    79    male
23  24    tIDDY nOW  Seven    78    male
24  25     gIFF tOW  Seven    88    male
25  26       cRELEA  Seven    79    male
26  27     bIG nOSE  Three    81  female
27  28    rOJJ bASE  Seven    86  female
28  29  tESS pLAYED  Seven    55    male
29  30    rEPPY rED    Six    79  female
30  31  mARRY tOEEY   Four    88    male
31  32    bINN rOTT  Seven    90  female
32  33    kENN rEIN    Six    96  female
33  34     gAIN tOE  Seven    69    male
34  35   rOWS nOUMP    Six    88  female
35  36        hONNY   five    45    male

In [40]:
df["name"] = df["name"].apply(lambda x : x.lower())
df

id         name  class  mark  gender
0    1     john deo   Four    75  female
1    2     max ruin  Three    85    male
2    3       arnold  Three    55    male
3    4   krish star   Four    60  female
4    5    john mike   Four    60  female
5    6    alex john   Four    55    male
6    7  my john rob  Fifth    78    male
7    8       asruid   Five    85    male
8    9      tes qry    Six    78    male
9   10     big john   Four    55  female
10  11       ronald    Six    89  female
11  12        recky    Six    94  female
12  13          kty  Seven    88  female
13  14         bigy  Seven    88  female
14  15     tade row   Four    88    male
15  16        gimmy   Four    88    male
16  17        tumyu    Six    54    male
17  18        honny   Five    75    male
18  19        tinny   Nine    18    male
19  20       jackly   Nine    65  female
20  21   babby john   Four    69  female
21  22       reggid  Seven    55  female
22  23        herod  Eight    79    male
23  24    tiddy now  Seven    78    male
24  25     giff tow  Seven    88    male
25  26       crelea  Seven    79    male
26  27     big nose  Three    81  female
27  28    rojj base  Seven    86  female
28  29  tess played  Seven    55    male
29  30    reppy red    Six    79  female
30  31  marry toeey   Four    88    male
31  32    binn rott  Seven    90  female
32  33    kenn rein    Six    96  female
33  34     gain toe  Seven    69    male
34  35   rows noump    Six    88  female
35  36        honny   five    45    male

In [41]:
list1 = ['Amir ',' Ashwin',' Bhakti ',' Amol','Aishwarya ','Satyam ']
s1 = pd.Series(list1)
s1

0         Amir 
1        Ashwin
2       Bhakti 
3          Amol
4    Aishwarya 
5       Satyam 
dtype: object

In [42]:
s1 = s1.apply(lambda x : x.strip())
s1

0         Amir
1       Ashwin
2       Bhakti
3         Amol
4    Aishwarya
5       Satyam
dtype: object

In [43]:
data = {'year': [1700, 1850, 2000, 2300, 1950]}
df = pd.DataFrame(data)
df

year
0  1700
1  1850
2  2000
3  2300
4  1950

In [44]:
result = df[(df["year"] >= 1800) & (df["year"] <= 2200)]
result

year
1  1850
2  2000
4  1950

In [45]:
df1 = pd.DataFrame(np.random.randint(1,10,(3,3)),columns=list('ABC'),index=list('pqr'))
df2 = pd.DataFrame(np.random.randint(100,1000,(4,4)),columns=list('ABCD'),index=list('pqrs'))
df1

A  B  C
p  7  7  1
q  3  3  3
r  4  1  1

In [46]:
df2

A    B    C    D
p  416  489  401  156
q  298  266  359  526
r  320  770  764  607
s  644  165  379  614

In [47]:
pd.concat([df1,df2])

A    B    C      D
p    7    7    1    NaN
q    3    3    3    NaN
r    4    1    1    NaN
p  416  489  401  156.0
q  298  266  359  526.0
r  320  770  764  607.0
s  644  165  379  614.0

In [48]:
pd.concat([df1,df2],axis=1)

A    B    C    A    B    C    D
p  7.0  7.0  1.0  416  489  401  156
q  3.0  3.0  3.0  298  266  359  526
r  4.0  1.0  1.0  320  770  764  607
s  NaN  NaN  NaN  644  165  379  614

In [49]:
df1=pd.DataFrame({"Name":["Aarathi","Veena","Lakshmipriya","Sriyan"],
"Age":[23,54,34,67],
"Location":["Pune","Bangalore","Pune","Kochi"]})
df2=pd.DataFrame({"Name":["Aara","Anupama","Robin","Dilsha","Ramya"],
"Age":[23,54,34,67,45],
"Maths":[34,45,50,49,46],
"English":[50,49,48,34,89],
"Hindi":[40,45,50,34,67]})
df3=pd.DataFrame({"Name":["Aarathi","Veena","Sriyan","Dilsha","Arohi"],
"Salary":[80000,70000,90000,780000,90000]})
df1

Name  Age   Location
0       Aarathi   23       Pune
1         Veena   54  Bangalore
2  Lakshmipriya   34       Pune
3        Sriyan   67      Kochi

In [50]:
df2

Name  Age  Maths  English  Hindi
0     Aara   23     34       50     40
1  Anupama   54     45       49     45
2    Robin   34     50       48     50
3   Dilsha   67     49       34     34
4    Ramya   45     46       89     67

In [51]:
df3

Name  Salary
0  Aarathi   80000
1    Veena   70000
2   Sriyan   90000
3   Dilsha  780000
4    Arohi   90000

In [52]:
result = pd.concat([df1,df2])
result

Name  Age   Location  Maths  English  Hindi
0       Aarathi   23       Pune    NaN      NaN    NaN
1         Veena   54  Bangalore    NaN      NaN    NaN
2  Lakshmipriya   34       Pune    NaN      NaN    NaN
3        Sriyan   67      Kochi    NaN      NaN    NaN
0          Aara   23        NaN   34.0     50.0   40.0
1       Anupama   54        NaN   45.0     49.0   45.0
2         Robin   34        NaN   50.0     48.0   50.0
3        Dilsha   67        NaN   49.0     34.0   34.0
4         Ramya   45        NaN   46.0     89.0   67.0

In [54]:
final = pd.merge(result , df3 , on="Name")
final

Name  Age   Location  Maths  English  Hindi  Salary
0  Aarathi   23       Pune    NaN      NaN    NaN   80000
1    Veena   54  Bangalore    NaN      NaN    NaN   70000
2   Sriyan   67      Kochi    NaN      NaN    NaN   90000
3   Dilsha   67        NaN   49.0     34.0   34.0  780000

In [55]:
df1 = pd.DataFrame({"Name":["Aarathi","Veena","Lakshmipriya","Amit","Sriyan"],
"ID_card":['BSL004','BSL006','BSL010','BSL003','BSL007'],
"Physics":[94,86,73,96,75],
"Cemistry":[85,91,89,78,81]})
df2 = pd.DataFrame({"Name":["Aarathi","Veena","Manoj","Lakshmipriya","Sriyan"],
"ID_card":['BSL001','BSL005','BSL009','BSL008','BSL002'],
"Maths":[88,72,69,97,45],
"Biology":[98,75,86,61,64]})
df1

Name ID_card  Physics  Cemistry
0       Aarathi  BSL004       94        85
1         Veena  BSL006       86        91
2  Lakshmipriya  BSL010       73        89
3          Amit  BSL003       96        78
4        Sriyan  BSL007       75        81

In [56]:
df2

Name ID_card  Maths  Biology
0       Aarathi  BSL001     88       98
1         Veena  BSL005     72       75
2         Manoj  BSL009     69       86
3  Lakshmipriya  BSL008     97       61
4        Sriyan  BSL002     45       64

In [57]:
result = pd.merge(df1,df2,on="Name",suffixes=["_df1","_df2"])
result

Name ID_card_df1  Physics  Cemistry ID_card_df2  Maths  Biology
0       Aarathi      BSL004       94        85      BSL001     88       98
1         Veena      BSL006       86        91      BSL005     72       75
2  Lakshmipriya      BSL010       73        89      BSL008     97       61
3        Sriyan      BSL007       75        81      BSL002     45       64

In [58]:
result = pd.merge(df1,df2,on="Name",how="left",suffixes=["_df1","_df2"])
result

Name ID_card_df1  Physics  Cemistry ID_card_df2  Maths  Biology
0       Aarathi      BSL004       94        85      BSL001   88.0     98.0
1         Veena      BSL006       86        91      BSL005   72.0     75.0
2  Lakshmipriya      BSL010       73        89      BSL008   97.0     61.0
3          Amit      BSL003       96        78         NaN    NaN      NaN
4        Sriyan      BSL007       75        81      BSL002   45.0     64.0

In [59]:
result = pd.merge(df1,df2,on="Name",how="right",suffixes=["_df1","_df2"])
result

Name ID_card_df1  Physics  Cemistry ID_card_df2  Maths  Biology
0       Aarathi      BSL004     94.0      85.0      BSL001     88       98
1         Veena      BSL006     86.0      91.0      BSL005     72       75
2         Manoj         NaN      NaN       NaN      BSL009     69       86
3  Lakshmipriya      BSL010     73.0      89.0      BSL008     97       61
4        Sriyan      BSL007     75.0      81.0      BSL002     45       64

In [60]:
english_df = pd.DataFrame({'Name':['Amir','Salman','Maaz','Tanvir','Fahad'],
'Surname':['Arkar','Mulla','Surve','Kadvekar','Antule'],
'Marks':[94,86,91,93,88]})
maths_df = pd.DataFrame({'Name':['Amir','Salman','Maaz','Tanvir','Fahad'],
'Surname':['Khan','Mulla','Hafiz','Kadvekar','Shaikh'],
'Marks':[91,89,93,87,84]})
english_df

Name   Surname  Marks
0    Amir     Arkar     94
1  Salman     Mulla     86
2    Maaz     Surve     91
3  Tanvir  Kadvekar     93
4   Fahad    Antule     88

In [61]:
maths_df

Name   Surname  Marks
0    Amir      Khan     91
1  Salman     Mulla     89
2    Maaz     Hafiz     93
3  Tanvir  Kadvekar     87
4   Fahad    Shaikh     84

In [62]:
result = pd.merge(english_df,maths_df,on=["Name","Surname"],how="inner",suffixes=["_eng","math"])
result

Name   Surname  Marks_eng  Marksmath
0  Salman     Mulla         86         89
1  Tanvir  Kadvekar         93         87

In [63]:
physics_df = pd.DataFrame({'Name_1':['Amir','Salman','Maaz','Karim','Fahad'],
'Surname':['Arkar','Mulla','Surve','Kadvekar','Antule'],
'Marks':[94,86,91,93,88]})
chemistry_df = pd.DataFrame({'Name_2':['Asif','Salman','Maaz','Tanvir','Fahad'],
'Surname':['Khan','Mulla','Hafiz','Rawal','Shaikh'],
'Marks':[91,89,93,87,84]})
physics_df

Name_1   Surname  Marks
0    Amir     Arkar     94
1  Salman     Mulla     86
2    Maaz     Surve     91
3   Karim  Kadvekar     93
4   Fahad    Antule     88

In [64]:
chemistry_df

Name_2 Surname  Marks
0    Asif    Khan     91
1  Salman   Mulla     89
2    Maaz   Hafiz     93
3  Tanvir   Rawal     87
4   Fahad  Shaikh     84

In [65]:
result = pd.merge(physics_df,chemistry_df,how="inner",left_on="Name_1",right_on="Name_2",suffixes=["_1","_2"])
result

Name_1 Surname_1  Marks_1  Name_2 Surname_2  Marks_2
0  Salman     Mulla       86  Salman     Mulla       89
1    Maaz     Surve       91    Maaz     Hafiz       93
2   Fahad    Antule       88   Fahad    Shaikh       84

In [66]:
df = pd.read_csv("movies_data.csv")
df.head(3)

star_rating                     title content_rating  genre  duration  \
0          9.3  The Shawshank Redemption              R  Crime       142   
1          9.2             The Godfather              R  Crime       175   
2          9.1    The Godfather: Part II              R  Crime       200   

                                         actors_list  
0  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1    [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...

In [68]:
result = df.sort_values("duration",ignore_index=True,ascending=False)
result

star_rating                              title content_rating      genre  \
0            7.8                             Hamlet          PG-13      Drama   
1            8.2                 Gone with the Wind              G      Drama   
2            8.4        Once Upon a Time in America              R      Crime   
3            8.3  Lagaan: Once Upon a Time in India             PG  Adventure   
4            7.9               The Ten Commandments       APPROVED  Adventure   
..           ...                                ...            ...        ...   
974          8.1                          Duck Soup         PASSED     Comedy   
975          8.4                            The Kid      NOT RATED     Comedy   
976          8.1        The Cabinet of Dr. Caligari        UNRATED      Crime   
977          8.0                Battleship Potemkin        UNRATED    History   
978          8.0                             Freaks        UNRATED      Drama   

     duration                                        actors_list  
0         242  [u'Kenneth Branagh', u'Julie Christie', u'Dere...  
1         238  [u'Clark Gable', u'Vivien Leigh', u'Thomas Mit...  
2         229  [u'Robert De Niro', u'James Woods', u'Elizabet...  
3         224  [u'Aamir Khan', u'Gracy Singh', u'Rachel Shell...  
4         220  [u'Charlton Heston', u'Yul Brynner', u'Anne Ba...  
..        ...                                                ...  
974        68    [u'Groucho Marx', u'Harpo Marx', u'Chico Marx']  
975        68  [u'Charles Chaplin', u'Edna Purviance', u'Jack...  
976        67  [u'Werner Krauss', u'Conrad Veidt', u'Friedric...  
977        66  [u'Aleksandr Antonov', u'Vladimir Barsky', u'G...  
978        64  [u'Wallace Ford', u'Leila Hyams', u'Olga Bacla...  

[979 rows x 6 columns]

In [69]:
result = df["duration"].max()
result

242

In [70]:
result = df["duration"].min()
result

64

In [71]:
result = df.loc[(df["genre"] == "Action") | (df["genre"] == "Crime")].reset_index(drop=True)
result

star_rating                                            title  \
0            9.3                         The Shawshank Redemption   
1            9.2                                    The Godfather   
2            9.1                           The Godfather: Part II   
3            9.0                                  The Dark Knight   
4            8.9                                     Pulp Fiction   
..           ...                                              ...   
255          7.4                                  La Femme Nikita   
256          7.4                                         The Rock   
257          7.4                              Law Abiding Citizen   
258          7.4  Master and Commander: The Far Side of the World   
259          7.4                                      Wall Street   

    content_rating   genre  duration  \
0                R   Crime       142   
1                R   Crime       175   
2                R   Crime       200   
3            PG-13  Action       152   
4                R   Crime       154   
..             ...     ...       ...   
255              R  Action       118   
256              R  Action       136   
257              R   Crime       109   
258          PG-13  Action       138   
259              R   Crime       126   

                                           actors_list  
0    [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1      [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2    [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3    [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4    [u'John Travolta', u'Uma Thurman', u'Samuel L....  
..                                                 ...  
255  [u'Anne Parillaud', u'Marc Duret', u'Patrick F...  
256   [u'Sean Connery', u'Nicolas Cage', u'Ed Harris']  
257  [u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']  
258  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...  
259  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...  

[260 rows x 6 columns]

In [72]:
city_df = pd.DataFrame({'Name':['Amir','Shaibaz','Suhel','Fahad','Adil','Muzaffar','Shuaib','Asif','Awez','Muzammil'],
'City':['Georgia','California','Los Angeles','California','Los Angeles','Georgia','Los Angeles',
'California','Los Angeles','California']})
city_df

Name         City
0      Amir      Georgia
1   Shaibaz   California
2     Suhel  Los Angeles
3     Fahad   California
4      Adil  Los Angeles
5  Muzaffar      Georgia
6    Shuaib  Los Angeles
7      Asif   California
8      Awez  Los Angeles
9  Muzammil   California

In [73]:
city_df.groupby(city_df["City"]).size().reset_index(name = "Number of People")

City  Number of People
0   California                 4
1      Georgia                 2
2  Los Angeles                 4

In [74]:
df = pd.read_csv("Bengaluru_House_Data.csv")
df.head(3)

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00

In [75]:
df.fillna(0)

area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II   
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society total_sqft  bath  balcony   price  
0          2 BHK  Coomee        1056   2.0      1.0   39.07  
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00  
2          3 BHK        0       1440   2.0      3.0   62.00  
3          3 BHK  Soiewre       1521   3.0      1.0   95.00  
4          2 BHK        0       1200   2.0      1.0   51.00  
...          ...      ...        ...   ...      ...     ...  
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00  
13316      4 BHK        0       3600   5.0      0.0  400.00  
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00  
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00  
13319      1 BHK        0        550   1.0      1.0   17.00  

[13320 rows x 9 columns]

In [76]:
df.replace({np.nan : 0})

area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II   
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society total_sqft  bath  balcony   price  
0          2 BHK  Coomee        1056   2.0      1.0   39.07  
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00  
2          3 BHK        0       1440   2.0      3.0   62.00  
3          3 BHK  Soiewre       1521   3.0      1.0   95.00  
4          2 BHK        0       1200   2.0      1.0   51.00  
...          ...      ...        ...   ...      ...     ...  
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00  
13316      4 BHK        0       3600   5.0      0.0  400.00  
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00  
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00  
13319      1 BHK        0        550   1.0      1.0   17.00  

[13320 rows x 9 columns]

In [77]:
df = pd.DataFrame({'col1':[1,4,3,4,5],
'col2':[4,5,6,7,8],
'col3':[7,8,9,0,1]})
df

col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1

In [78]:
result = df.drop([0,2,4])
result

col1  col2  col3
1     4     5     8
3     4     7     0