In [1]:
import re

In [2]:
str1= "python and data pytthon science pythonnn pyyth annd pythh"
result = re.findall(r"p+",str1)
result

['p', 'p', 'p', 'p', 'p']

In [3]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
result

['INFORM', 'inform']

In [4]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py?",str1)
result

['py', 'py']

In [5]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [6]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"\b\w*[b]{2,3}\w*\b",str1)
result

['abbbs', 'abbbsolutely', 'abbrivation']

In [7]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [8]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [9]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [10]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [11]:
str1 = 'Suceess is a jurney not a desti9nation.'
result = re.findall(r"Suceess",str1)
result

['Suceess']

In [12]:
str1 = 'new begening of LIFE .'
result = re.findall(r"LIFE .",str1)
result

['LIFE .']

In [13]:
str1 = "today is the very lazy day"
result = re.findall(r"\w*z\w",str1)
result

['lazy']

In [14]:
str1 = "we have a lazy cat"
result = re.findall(r"[a-y]*z[a-y]",str1)
result

['lazy']

In [15]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [16]:
str1 = "9821 maya"
result = re.findall(r"^\d*",str1)
result

['9821']

In [17]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [18]:
str1="Python is required for data science version 3.2"
result = re.findall(r"\d\b",str1)
result

['3', '2']

In [19]:
str1 = "Exercises number 1, 12, 13, and 345 are important"
result = re.findall(r"\d+",str1)
result

['1', '12', '13', '345']

In [20]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for word in Searched_words:
    result = re.findall(word,Sample_text)
    print(result)

['fox']
['dog']
[]


In [21]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search(r"fox",sample_text)
print(result)

<re.Match object; span=(16, 19), match='fox'>


In [22]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [23]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
print(len(result))
result = re.search(r"exercises",Sample_text)
print(result)

3
<re.Match object; span=(7, 16), match='exercises'>


In [26]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","[_]",str1)
print(result)
result = re.sub(r"[_]","",result)
result

The[_]quick[_]brown[_]fox[_]jumps[_]over[_]the[_]lazy[_]dog.


'The[]quick[]brown[]fox[]jumps[]over[]the[]lazy[]dog.'

In [27]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","",str1)
result

'Thequickbrownfoxjumpsoverthelazydog.'

In [28]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [29]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*",str1)
result

['and', 'every', 'evening']

In [30]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [31]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[,. ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [32]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[,. ]{2}",":",text)
result

'Python: is a general purpose interpreted.'

In [33]:
text ="""123 Python is a general-purpose, interpreted,
high-level programming language popularly used for
website development, data analytics 78 and automation."""
result = re.findall(r"\b\D{3,5}\b",text)
result

[' is a', 'high-', 'level', ' used', ' for\n', 'data ', ' and ']

In [1]:
import numpy as np

In [2]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr1.nbytes

80

In [4]:
arr1 = np.zeros(10)
print(arr1)
arr1[4] = 1
arr1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [5]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [6]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [8]:
arr2 = reversed(arr1)
list(arr2)

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [9]:
arr1 = np.random.randint(1,10,size=(2,2))
print("arr1 :\n",arr1)
arr2 = np.random.randint(10,20,size=(2,2))
print("arr2 :\n",arr2)

arr1 :
 [[6 8]
 [7 2]]
arr2 :
 [[15 14]
 [15 16]]


In [10]:
add1 = arr1 + arr2
add1

array([[21, 22],
       [22, 18]])

In [11]:
sub1 = arr1 - arr2
sub1

array([[ -9,  -6],
       [ -8, -14]])

In [12]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [13]:
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [14]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [15]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mean_row = np.mean(arr1,axis=1)
print("Mean row: ",mean_row)
mean_col = np.mean(arr1,axis=0)
print("Mean column: ",mean_col)

Mean row:  [2. 5. 8.]
Mean column:  [4. 5. 6.]


In [17]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [18]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
arr1[:: , ::-1]

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [20]:
print("Array:\n",arr1)
arr1[::-1]

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [21]:
result = np.nonzero([1,2,0,0,4,0])
result

(array([0, 1, 4], dtype=int64),)

In [22]:
arr1 = np.array([[1,2],[3,4]])
print("Array:\n",arr1)
result = np.linalg.det(arr1)
result

Array:
 [[1 2]
 [3 4]]


-2.0000000000000004

In [23]:
arr1 = np.array([[1,2],[3,4]])
print("Array:\n",arr1)
result = np.linalg.inv(arr1)
result

Array:
 [[1 2]
 [3 4]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [24]:
arr1 = np.random.randint(1,10,size=(30))
print("Array:\n",arr1)
result = np.mean(arr1)
result

Array:
 [2 1 5 9 9 4 6 9 4 9 9 4 7 1 7 9 2 7 1 9 9 1 7 7 6 7 3 9 6 4]


5.766666666666667

In [25]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:\n",arr1)
result = np.where(arr1 > 5)
result

Array:
 [ 1  2  3  4  5  6  7  8  9 10]


(array([5, 6, 7, 8, 9], dtype=int64),)

In [26]:
arr1 = np.random.random((3,3,3))
arr1

array([[[0.32875764, 0.71513747, 0.29484518],
        [0.17936533, 0.00807091, 0.20601486],
        [0.92902262, 0.30944116, 0.08835122]],

       [[0.773526  , 0.00376974, 0.63239143],
        [0.84774233, 0.80748857, 0.28904745],
        [0.79350665, 0.74964332, 0.40354038]],

       [[0.19979577, 0.01172885, 0.93079204],
        [0.08703772, 0.17922896, 0.04944275],
        [0.76056961, 0.29004157, 0.04040826]]])

In [27]:
arr1 = np.random.rand(10,10)
print("Array:\n",arr1)
print(np.max(arr1))
print(np.min(arr1))

Array:
 [[0.45682126 0.17114655 0.29805147 0.56195245 0.56376326 0.85755339
  0.17129428 0.20880677 0.46310791 0.5137336 ]
 [0.68093984 0.64538467 0.13300986 0.53522825 0.24610047 0.35485416
  0.0950659  0.52506621 0.16056512 0.05001169]
 [0.77490163 0.99361575 0.24669237 0.4536274  0.06841772 0.51154733
  0.47804647 0.77925045 0.47891349 0.05980325]
 [0.6021134  0.15424003 0.94319708 0.48278949 0.06718523 0.33865686
  0.39154032 0.80916242 0.14809688 0.10813525]
 [0.02647192 0.68539235 0.26308397 0.56533493 0.12337902 0.74221915
  0.64530073 0.48091463 0.37700761 0.05049265]
 [0.14217272 0.82710211 0.67073433 0.00102323 0.55183498 0.32002598
  0.84629269 0.06509777 0.26281462 0.64906044]
 [0.41351197 0.48839387 0.58339475 0.04892601 0.37553724 0.9767245
  0.1820088  0.87381273 0.34935743 0.06447287]
 [0.2189207  0.36300084 0.74500205 0.37932755 0.86767893 0.24420718
  0.48628615 0.84779028 0.97342814 0.06058671]
 [0.71872279 0.56276    0.56232699 0.96963091 0.91883828 0.17095411
  0.7

In [28]:
arr1 = np.ones((10,10))
arr1[1:-1,1:-1] = 0
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4])
print("Array:\n",arr1)

Array:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [30]:
arr1 = np.eye(3,3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr1 = np.random.randint(1,9,size=(5,3))
arr2 = np.random.randint(1,9,size=(3,2))
result = np.dot(arr1,arr2)
result

array([[68, 75],
       [43, 48],
       [52, 67],
       [28, 36],
       [45, 57]])

In [32]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
result = np.where((arr1 >= 3) & (arr1 <= 8), -1*arr1,arr1)
result

array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [33]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Array:\n",arr1)
result = np.around(arr1,1)
result

Array:
 [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]


array([[1.2, 2.7],
       [3.5, 5.2]])

In [34]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1, arr2)
result

array([4, 5, 6])

In [35]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [36]:
arr1 = np.random.randint(1,10,size=(10))
print("Array:\n",arr1)
result = np.sort(arr1)
result

Array:
 [8 5 9 2 8 9 6 4 4 2]


array([2, 2, 4, 4, 5, 6, 8, 8, 9, 9])

In [37]:
arr1 = np.zeros((5,5))
print("Array:\n",arr1)
arr2 = arr1 + np.arange(5)
arr2

Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [38]:
A = np.random.randint(0,5,size=5)
B = np.random.randint(0,5,size=5)
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [39]:
np.allclose(arr1, arr2)

False

In [40]:
arr1 = np.random.randint(1,10,size=10)
print(arr1)
result = np.where(arr1 == np.max(arr1) , 0,arr1)
result

[4 5 3 1 7 2 6 2 5 9]


array([4, 5, 3, 1, 7, 2, 6, 2, 5, 0])

In [41]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr1):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

In [42]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

(0, 0) index has 1 values
(0, 1) index has 2 values
(0, 2) index has 3 values
(1, 0) index has 4 values
(1, 1) index has 5 values
(1, 2) index has 6 values
(2, 0) index has 7 values
(2, 1) index has 8 values
(2, 2) index has 9 values


In [43]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array:\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array:
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [44]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.mean(arr1)
result

5.5

In [45]:
np.median(arr1)

5.5

In [46]:
np.std(arr1)

2.8722813232690143

In [47]:
from scipy.stats import mode
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = mode(arr1)
result

ModeResult(mode=1, count=1)

In [48]:
result = np.around(5.8758,2)
result

5.88

In [49]:
arr1 = np.array([[2,3],[3,4]])
result = np.linalg.inv(arr1)
result

array([[-4.,  3.],
       [ 3., -2.]])

In [50]:
x = np.array([1,2,3])
y = np.array([4,5,6])
result = np.cov(x,y)
result

array([[1., 1.],
       [1., 1.]])

In [51]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
arr1.shape
arr2 = np.reshape(arr1,(2,5,1))
arr2

[ 1  2  3  4  5  6  7  8  9 10]


array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [52]:
arr1 = np.random.randint(1,10,size=(1,2,3,4))
print(arr1)
arr2 = np.reshape(arr1 , (6,4))
print(arr2)

[[[[8 2 6 7]
   [2 2 5 2]
   [9 2 9 4]]

  [[6 5 2 6]
   [6 1 5 9]
   [7 8 5 1]]]]
[[8 2 6 7]
 [2 2 5 2]
 [9 2 9 4]
 [6 5 2 6]
 [6 1 5 9]
 [7 8 5 1]]


In [53]:
arr1 = np.zeros(10,dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
print("Array:\n",arr1)
arr1.shape

Array:
 [[1 2 3 4]
 [5 6 8 7]
 [3 4 5 6]]


(3, 4)

In [1]:
import numpy as np
import pandas as pd

In [2]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
list1 = [[1,2,3],[4,5,6]]
pd.DataFrame(list1)

0  1  2
0  1  2  3
1  4  5  6

In [4]:
df = pd.DataFrame(columns=list("ABC"),index=list("PQR"))
df

A    B    C
P  NaN  NaN  NaN
Q  NaN  NaN  NaN
R  NaN  NaN  NaN

In [6]:
if df.isnull:
    print("Dataframe is empty")
else:
    print("Dataframe is not empty")

Dataframe is empty


In [7]:
arr1 = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(arr1)
df

0  1  2
0  1  2  3
1  4  5  6

In [8]:
list1 = [[1,2,3],[4,5,6]]
df = pd.DataFrame(list1)
df

0  1  2
0  1  2  3
1  4  5  6

In [9]:
tuple1 = (1,2,3,4,5,6)
df = pd.DataFrame(tuple1)
df

0
0  1
1  2
2  3
3  4
4  5
5  6

In [10]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [11]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]
df = pd.DataFrame(l1,columns=list("ABC"))
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
df = pd.DataFrame(np.random.randint(1,10,size=(5,6)))
df

0  1  2  3  4  5
0  1  9  7  6  3  2
1  1  2  6  3  4  1
2  3  2  8  9  4  5
3  8  2  3  8  2  2
4  5  4  9  5  6  7

In [13]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(arr1)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [14]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [15]:
s1 = pd.Series([1,2,3,4,5])
print(s1)
s2 = s1.copy()
s2[0] = 50
print("Original Series :\n",s1)
print("Copied Series :\n",s2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
Original Series :
 0    1
1    2
2    3
3    4
4    5
dtype: int64
Copied Series :
 0    50
1     2
2     3
3     4
4     5
dtype: int64


In [16]:
df = pd.DataFrame(np.full((4,5),6))
print(df)

   0  1  2  3  4
0  6  6  6  6  6
1  6  6  6  6  6
2  6  6  6  6  6
3  6  6  6  6  6


In [17]:
df["5"] = [1,2,3,4]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4

In [19]:
df.loc[4] = [1,2,3,4,5,6]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4
4  1  2  3  4  5  6

In [20]:
arr1 = np.random.randint(1,10,size=(4,4))
df = pd.DataFrame(arr1,columns=list("ABCD"),index=list("PQRS"))
df.rename({"A":"a","B":"b","C":"c","D":"d"},axis=1,inplace=True)
df.rename({"P":"p","Q":"q","R":"r","S":"s"},axis=0,inplace=True)
df

a  b  c  d
p  5  4  7  9
q  2  5  9  5
r  4  5  6  6
s  4  4  2  8

In [21]:
for i in df.items():
    print(i)

('a', p    5
q    2
r    4
s    4
Name: a, dtype: int32)
('b', p    4
q    5
r    5
s    4
Name: b, dtype: int32)
('c', p    7
q    9
r    6
s    2
Name: c, dtype: int32)
('d', p    9
q    5
r    6
s    8
Name: d, dtype: int32)


In [22]:
for i in df.iterrows():
    print(i)

('p', a    5
b    4
c    7
d    9
Name: p, dtype: int32)
('q', a    2
b    5
c    9
d    5
Name: q, dtype: int32)
('r', a    4
b    5
c    6
d    6
Name: r, dtype: int32)
('s', a    4
b    4
c    2
d    8
Name: s, dtype: int32)


In [23]:
df

a  b  c  d
p  5  4  7  9
q  2  5  9  5
r  4  5  6  6
s  4  4  2  8

In [25]:
arr1 = df.values
arr1

array([[5, 4, 7, 9],
       [2, 5, 9, 5],
       [4, 5, 6, 6],
       [4, 4, 2, 8]])

In [26]:
arr1.tolist()

[[5, 4, 7, 9], [2, 5, 9, 5], [4, 5, 6, 6], [4, 4, 2, 8]]

In [27]:
df

a  b  c  d
p  5  4  7  9
q  2  5  9  5
r  4  5  6  6
s  4  4  2  8

In [28]:
df.reset_index(drop=True)

a  b  c  d
0  5  4  7  9
1  2  5  9  5
2  4  5  6  6
3  4  4  2  8

In [29]:
df = pd.DataFrame(np.random.randint(10,20,size=(4,5)))
print(df)
print(df.shape[0])
print(df.shape[1])

    0   1   2   3   4
0  14  14  12  14  15
1  11  17  17  13  10
2  12  19  13  13  10
3  15  16  13  18  13
4
5


In [30]:
s1 = pd.Series(np.arange(50,60))
s2 = pd.Series(np.arange(25,35))
print(s1+s2)
print(s1-s2)
print(s1*s2)
print(s1/s2)

0    75
1    77
2    79
3    81
4    83
5    85
6    87
7    89
8    91
9    93
dtype: int32
0    25
1    25
2    25
3    25
4    25
5    25
6    25
7    25
8    25
9    25
dtype: int32
0    1250
1    1326
2    1404
3    1484
4    1566
5    1650
6    1736
7    1824
8    1914
9    2006
dtype: int32
0    2.000000
1    1.961538
2    1.925926
3    1.892857
4    1.862069
5    1.833333
6    1.806452
7    1.781250
8    1.757576
9    1.735294
dtype: float64


In [31]:
df = pd.read_excel("Sample1.xlsx")
df.head()

Unnamed: 0 First Name  Last Name  Gender        Country  Age        Date  \
0           1      Dulce      Abril  Female  United States   32  15/10/2017   
1           2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016   
2           3     Philip       Gent    Male         France   36  21/05/2015   
3           4   Kathleen     Hanner  Female  United States   25  15/10/2017   
4           5    Nereida    Magwood  Female  United States   58  16/08/2016   

     Id  
0  1562  
1  1582  
2  2587  
3  3549  
4  2468

In [32]:
df.columns

Index(['Unnamed: 0', 'First Name', 'Last Name', 'Gender', 'Country', 'Age',
       'Date', 'Id'],
      dtype='object')

In [33]:
df[['First Name', 'Last Name']]

First Name   Last Name
0        Dulce       Abril
1         Mara   Hashimoto
2       Philip        Gent
3     Kathleen      Hanner
4      Nereida     Magwood
..         ...         ...
995       Roma  Lafollette
996     Felisa        Cail
997   Demetria       Abbey
998     Jeromy        Danz
999   Rasheeda      Alkire

[1000 rows x 2 columns]

In [34]:
df["Age"].mean()

33.26

In [35]:
df["Age"].median()

32.0

In [36]:
df["Age"].min()

21

In [37]:
df["Age"].max()

58

In [38]:
df = pd.read_csv("titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1   
4                           Allen, Mr. William Henry    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [39]:
df.groupby(df["Embarked"]).get_group("S")

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
..           ...       ...     ...   
883          884         0       2   
884          885         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   

                                             Name  Gender   Age  SibSp  Parch  \
0                         Braund, Mr. Owen Harris    male  22.0      1      0   
2                          Heikkinen, Miss. Laina  female   NaN      0      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1      0   
4                        Allen, Mr. William Henry    male   NaN      0      0   
6                         McCarthy, Mr. Timothy J    male  54.0      0      0   
..                                            ...     ...   ...    ...    ...   
883                 Banfield, Mr. Frederick James    male  28.0      0      0   
884                        Sutehall, Mr. Henry Jr    male  25.0      0      0   
886                         Montvila, Rev. Juozas    male  27.0      0      0   
887                  Graham, Miss. Margaret Edith  female  19.0      0      0   
888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500   NaN        S  
2    STON/O2. 3101282   7.9250   NaN        S  
3              113803  53.1000  C123        S  
4              373450   8.0500   NaN        S  
6               17463  51.8625   E46        S  
..                ...      ...   ...      ...  
883  C.A./SOTON 34068  10.5000   NaN        S  
884   SOTON/OQ 392076   7.0500   NaN        S  
886            211536  13.0000   NaN        S  
887            112053  30.0000   B42        S  
888        W./C. 6607  23.4500   NaN        S  

[644 rows x 12 columns]

In [40]:
arr1 = np.random.randint(1,10,size=(4,2))
df = pd.DataFrame(arr1)
print(df)
df.apply(np.sqrt)

   0  1
0  5  7
1  9  2
2  4  3
3  3  8


0         1
0  2.236068  2.645751
1  3.000000  1.414214
2  2.000000  1.732051
3  1.732051  2.828427

In [41]:
df.apply(lambda x : x**2)

0   1
0  25  49
1  81   4
2  16   9
3   9  64

In [42]:
df.apply(lambda x : x**3)

0    1
0  125  343
1  729    8
2   64   27
3   27  512

In [43]:
df = pd.read_csv("diabetes.csv")
df.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   
3      150             66             23       94  28.1   
4      150             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   52        1  
3                     0.167   21        0  
4                     2.288   33        1

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Glucose                   768 non-null    int64  
 1   BloodPressure             768 non-null    int64  
 2   SkinThickness             768 non-null    int64  
 3   Insulin                   768 non-null    int64  
 4   BMI                       768 non-null    float64
 5   DiabetesPedigreeFunction  768 non-null    float64
 6   Age                       768 non-null    int64  
 7   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 48.1 KB


In [45]:
df.describe()

Glucose  BloodPressure  SkinThickness     Insulin         BMI  \
count  768.000000     768.000000     768.000000  768.000000  768.000000   
mean   121.117188      69.076823      20.536458   79.799479   31.992578   
std     31.805091      19.367794      15.952218  115.244002    7.884160   
min      0.000000       0.000000       0.000000    0.000000    0.000000   
25%     99.000000      62.000000       0.000000    0.000000   27.300000   
50%    117.000000      72.000000      23.000000   30.500000   32.000000   
75%    142.000000      80.000000      32.000000  127.250000   36.600000   
max    199.000000     122.000000      99.000000  846.000000   67.100000   

       DiabetesPedigreeFunction         Age     Outcome  
count                768.000000  768.000000  768.000000  
mean                   0.471876   33.243490    0.348958  
std                    0.331329   11.758182    0.476951  
min                    0.078000   21.000000    0.000000  
25%                    0.243750   24.000000    0.000000  
50%                    0.372500   29.000000    0.000000  
75%                    0.626250   41.000000    1.000000  
max                    2.420000   81.000000    1.000000

In [46]:
df.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   
3      150             66             23       94  28.1   
4      150             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   52        1  
3                     0.167   21        0  
4                     2.288   33        1

In [47]:
df.tail()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763      101             76             48      180  32.9   
764      122             70             27        0  36.8   
765      121             72             23      112  26.2   
766      126             60              0        0  30.1   
767       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [48]:
data1 = {"NAME" : ["Rudranshi","Sanvi","Swati","Shiva"]}
df = pd.DataFrame(data1)
df["NAME"].apply(lambda x : x.istitle())

0    True
1    True
2    True
3    True
Name: NAME, dtype: bool

In [49]:
d1 = {"Employee":["Saniya","Sara","Alexa","Jenny"]}
df = pd.DataFrame(d1)
d2 = {"Saniya": "Software Developer" , "Sara":"Developer" , "Alexa":"Assistant"}
df["Designation"] = df["Employee"].map(d2)
df

Employee         Designation
0   Saniya  Software Developer
1     Sara           Developer
2    Alexa           Assistant
3    Jenny                 NaN

In [50]:
arr1 = np.random.randint(1,10,size=(5,5))
df = pd.DataFrame(arr1,columns=list("ABCDE"))
df

A  B  C  D  E
0  2  2  6  1  2
1  5  3  9  2  7
2  1  6  6  5  8
3  5  8  1  5  5
4  9  2  5  3  5

In [51]:
df["I"] = [1,2,3,4,5]
df

A  B  C  D  E  I
0  2  2  6  1  2  1
1  5  3  9  2  7  2
2  1  6  6  5  8  3
3  5  8  1  5  5  4
4  9  2  5  3  5  5

In [52]:
df.insert(1,"H",[1,2,1,2,1])
df

A  H  B  C  D  E  I
0  2  1  2  6  1  2  1
1  5  2  3  9  2  7  2
2  1  1  6  6  5  8  3
3  5  2  8  1  5  5  4
4  9  1  2  5  3  5  5

In [53]:
df.drop("A",axis=1,inplace=True)
df

H  B  C  D  E  I
0  1  2  6  1  2  1
1  2  3  9  2  7  2
2  1  6  6  5  8  3
3  2  8  1  5  5  4
4  1  2  5  3  5  5

In [54]:
df.drop(2,axis=0,inplace=True)
df

H  B  C  D  E  I
0  1  2  6  1  2  1
1  2  3  9  2  7  2
3  2  8  1  5  5  4
4  1  2  5  3  5  5

In [55]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([4,5,6,7,8])
s11 = set(s1)
s22 = set(s2)
result = s11.symmetric_difference(s22)
result

{1, 2, 3, 6, 7, 8}

In [56]:
s1 = pd.Series([1,2,3,4,5])
print("Median:",s1.median())
print("Mean:",s1.mean())
print("25th percentile:",s1.quantile(0.25))
print("75th percentile:",s1.quantile(0.75))
print("Minimum:",s1.min())
print("Maximum:",s1.max())

Median: 3.0
Mean: 3.0
25th percentile: 2.0
75th percentile: 4.0
Minimum: 1
Maximum: 5


In [57]:
df = pd.DataFrame(np.random.randint(10,50,size=(4,4)) , columns=list("CABD") , index=list("xzvs"))
df

C   A   B   D
x  49  43  20  46
z  45  26  12  21
v  37  13  39  48
s  28  38  46  27

In [58]:
df.sort_index()

C   A   B   D
s  28  38  46  27
v  37  13  39  48
x  49  43  20  46
z  45  26  12  21

In [59]:
df.sort_index(axis=1)

A   B   C   D
x  43  20  49  46
z  26  12  45  21
v  13  39  37  48
s  38  46  28  27

In [60]:
df.sort_values("D")

C   A   B   D
z  45  26  12  21
s  28  38  46  27
x  49  43  20  46
v  37  13  39  48

In [61]:
df = pd.DataFrame({"A" : [1,1,3,4,5],
                   "B" : [1,1,3,4,5],
                   "C" : [1,1,3,4,5],
                   "D" : [1,1,3,4,5]})
df

A  B  C  D
0  1  1  1  1
1  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [62]:
df.drop_duplicates()

A  B  C  D
0  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [63]:
data = {'Full Name': ['John Doe', 'Jane Smith', 'Bob Johnson']}
df = pd.DataFrame(data)
df[["First Name","Last Name"]] = df["Full Name"].str.split(expand=True)
df

Full Name First Name Last Name
0     John Doe       John       Doe
1   Jane Smith       Jane     Smith
2  Bob Johnson        Bob   Johnson