In [1]:
import re

In [2]:
string = "Python and Machine Learning 7741 is syllabus of Data Science."
result = re.findall(r"[a-zA-Z0-9]",string)
result

['P',
 'y',
 't',
 'h',
 'o',
 'n',
 'a',
 'n',
 'd',
 'M',
 'a',
 'c',
 'h',
 'i',
 'n',
 'e',
 'L',
 'e',
 'a',
 'r',
 'n',
 'i',
 'n',
 'g',
 '7',
 '7',
 '4',
 '1',
 'i',
 's',
 's',
 'y',
 'l',
 'l',
 'a',
 'b',
 'u',
 's',
 'o',
 'f',
 'D',
 'a',
 't',
 'a',
 'S',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e']

In [3]:
string = "Python and Machine Learning is syllabus of data science and deep learning."
result = re.split(r"and",string)
result

['Python ',
 ' Machine Learning is syllabus of data science ',
 ' deep learning.']

In [4]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\bab*[a-z]*\b",str1)
result

['and']

In [5]:
sample_string = "There are 123 45 678 90 2345 67 12 345 6789 0123 three-digit"
result = re.findall(r"\b\d{3}\s\d{2}\b",sample_string)
result

['123 45', '678 90']

In [6]:
str1= "python and data pytthon science pythonnn pyyth annd pythh"
result = re.findall(r"p+",str1)
result

['p', 'p', 'p', 'p', 'p']

In [7]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
result

['INFORM', 'inform']

In [8]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py?",str1)
result

['py', 'py']

In [9]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [10]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"\b\w*[b]{2,3}\w*\b",str1)
result

['abbbs', 'abbbsolutely', 'abbrivation']

In [11]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [12]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [14]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [15]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [16]:
str1 = 'Suceess is a jurney not a desti9nation.'
result = re.findall(r"Suceess",str1)
result

['Suceess']

In [17]:
str1 = 'new begening of LIFE .'
result = re.findall(r"LIFE .",str1)
result

['LIFE .']

In [18]:
str1 = "today is the very lazy day"
result = re.findall(r"\w*z\w",str1)
result

['lazy']

In [19]:
str1 = "we have a lazy cat"
result = re.findall(r"[a-y]*z[a-y]",str1)
result

['lazy']

In [20]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [21]:
str1 = "9821 maya"
result = re.findall(r"^9",str1)
result

['9']

In [22]:
str1 = "9821 maya"
result = re.findall(r"^\d*",str1)
result

['9821']

In [23]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [25]:
str1="Python is required for data science version 3.2"
result = re.findall(r"\d\b",str1)
result

['3', '2']

In [26]:
str1 = "Exercises number 1, 12, 13, and 345 are important"
result = re.findall(r"\d+",str1)
result

['1', '12', '13', '345']

In [27]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for word in Searched_words:
    result = re.findall(word,Sample_text)
    print(result)

['fox']
['dog']
[]


In [28]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search("fox",sample_text)
result

<re.Match object; span=(16, 19), match='fox'>

In [29]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [30]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
print(len(result))
result = re.search("exercises",Sample_text)
print(result)

3
<re.Match object; span=(7, 16), match='exercises'>


In [31]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","_",str1)
print(result)
result = re.sub(r"[_]"," ",str1)
result

The_quick_brown_fox_jumps_over_the_lazy_dog.


'The quick brown fox jumps over the lazy dog.'

In [32]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","",str1)
result

'Thequickbrownfoxjumpsoverthelazydog.'

In [33]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [34]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*",str1)
result

['and', 'every', 'evening']

In [35]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [37]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[., ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [38]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[., ]{2}",":",text)
result

'Python: is a general purpose interpreted.'

In [39]:
text ="""123 Python is a general-purpose, interpreted,
high-level programming language popularly used for
website development, data analytics 78 and automation."""

result = re.findall(r"\b\D{3,5}\b",text)
result

[' is a', 'high-', 'level', ' used', ' for\n', 'data ', ' and ']

In [40]:
text1 = '"Python", "Data", "Science"'
result = re.findall('""(.+?)""',text1)
result

[]

1. Employees (ID, Name)
2. Salaries (ID, EmployeeID, Salary)
Givequery to find third highest salary

In [ ]:
df1 >> Employess(Id,Name)
df2 >> Salaries(ID,EmployeeID, Salary)


In [1]:
import numpy as np

In [2]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr1.nbytes

80

In [4]:
arr1 = np.zeros(10)
print(arr1)
arr1[4] = 1
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [6]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [8]:
arr2 = reversed(arr1)
list(arr2)

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [9]:
arr1 = np.random.randint(1,10,size=(2,2))
print("Array 1:\n",arr1)
arr2 = np.random.randint(10,20,size=(2,2))
print("Array 2:\n",arr2)

Array 1:
 [[6 9]
 [4 8]]
Array 2:
 [[12 10]
 [15 10]]


In [10]:
add1 = arr1 + arr2
add1

array([[18, 19],
       [19, 18]])

In [11]:
sub1 = arr1 - arr2
sub1

array([[ -6,  -1],
       [-11,  -2]])

In [12]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [13]:
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [14]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [15]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array 1:\n",arr1)
mean_row = np.mean(arr1,axis=1)
print("mean_row:\n",mean_row)
mean_col = np.mean(arr1,axis=0)
print("mean_col:\n",mean_col)

Array 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
mean_row:
 [2. 5. 8.]
mean_col:
 [4. 5. 6.]


In [16]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [18]:
arr1 = np.arange(9).reshape(3,3)
print("Array:\n",arr1)

Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
arr1[:: , ::-1]

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [20]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr1[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [22]:
result = np.nonzero([1,2,0,0,4,0])
result

(array([0, 1, 4], dtype=int64),)

In [23]:
arr1 = np.array([[1,2],[3,4]])
print("Array:\n",arr1)
result = np.linalg.det(arr1)
result

Array:
 [[1 2]
 [3 4]]


-2.0000000000000004

In [24]:
arr1 = np.array([[2,3],[3,9]])
print("Array:\n",arr1)
result = np.linalg.inv(arr1)
result

Array:
 [[2 3]
 [3 9]]


array([[ 1.        , -0.33333333],
       [-0.33333333,  0.22222222]])

In [25]:
arr1 = np.random.randint(1,10,size=(30))
print("Array:\n",arr1)
result = np.mean(arr1)
result

Array:
 [4 8 7 5 8 4 2 7 6 6 2 5 3 4 9 9 3 3 7 5 6 1 5 7 6 3 6 8 2 2]


5.1

In [27]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:\n",arr1)
result = np.where(arr1 > 5)
result

Array:
 [ 1  2  3  4  5  6  7  8  9 10]


(array([5, 6, 7, 8, 9], dtype=int64),)

In [28]:
arr1 = np.random.random((3,3,3))
print("Array:\n",arr1)

Array:
 [[[0.57307661 0.89460307 0.68308705]
  [0.89876096 0.73287018 0.12487674]
  [0.81891687 0.10239401 0.90846163]]

 [[0.84543455 0.38803618 0.62816404]
  [0.65488595 0.37033795 0.09129177]
  [0.00157917 0.01403287 0.95541213]]

 [[0.44203435 0.54786398 0.72276343]
  [0.96043252 0.34233747 0.94501412]
  [0.21621936 0.1465995  0.07905874]]]


In [29]:
arr1 = np.random.rand(10,10)
print("Array:\n",arr1)
result = np.max(arr1)
result

Array:
 [[0.36481707 0.67856368 0.95176247 0.38238907 0.89619541 0.59662026
  0.59685643 0.59061008 0.77584196 0.83150866]
 [0.71313898 0.07927792 0.89280827 0.38696606 0.2152263  0.67964407
  0.06645161 0.07256513 0.55569085 0.50544835]
 [0.79482048 0.97530213 0.9178706  0.00177172 0.98587065 0.57140925
  0.84367859 0.13015604 0.71996918 0.38085302]
 [0.6843209  0.22317914 0.56271179 0.9673463  0.61754263 0.78857177
  0.01788446 0.61876513 0.59233923 0.97072072]
 [0.4077482  0.53199988 0.18380807 0.39031726 0.88785415 0.32226221
  0.53583555 0.78168897 0.10287611 0.83703317]
 [0.1786474  0.9544824  0.35813901 0.11912051 0.85096942 0.33423536
  0.66440222 0.70340755 0.088419   0.9949557 ]
 [0.87521346 0.2003247  0.12754188 0.7795376  0.45674043 0.91463597
  0.57805643 0.6949259  0.1848071  0.79019032]
 [0.37926215 0.02939574 0.60317873 0.75323803 0.16169931 0.42030303
  0.28784286 0.14598463 0.13056894 0.54515163]
 [0.61154361 0.65321047 0.85260887 0.46179547 0.89152848 0.21568588
  0.

0.9949557020742884

In [30]:
result = np.min(arr1)
result

0.0017717196606302776

In [31]:
arr1 = np.ones((10,10))
arr1[1:-1,1:-1] = 0
print("Array:\n",arr1)

Array:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [32]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4])
print("Array:\n",arr1)

Array:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [33]:
arr1 = np.eye(3,3)
print("Array:\n",arr1)

Array:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
arr1 = np.random.randint(1,10,size=(5,3))
arr2 = np.random.randint(1,10,size=(3,2))
result = np.dot(arr1, arr2)
result

array([[48, 32],
       [74, 63],
       [67, 48],
       [74, 65],
       [35, 26]])

In [35]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
result = np.where((arr1 >= 3) & (arr1 <= 8), -1*arr1,arr1)
result

array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [36]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
result = np.round(arr1,1)
result

array([[1.2, 2.7],
       [3.5, 5.2]])

In [37]:
np.ceil(arr1)

array([[2., 3.],
       [4., 6.]])

In [38]:
np.floor(arr1)

array([[1., 2.],
       [3., 5.]])

In [39]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1, arr2)
result

array([4, 5, 6])

In [40]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [41]:
arr1 = np.random.randint(1,10,size=(10))
print(arr1)
result = np.sort(arr1)
result

[4 9 6 6 8 1 4 4 6 9]


array([1, 4, 4, 4, 6, 6, 6, 8, 9, 9])

In [42]:
arr1 = np.zeros((5,5))
print("Array :\n",arr1)
arr2 = arr1 + np.arange(5)
print("Array :\n",arr2)

Array :
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Array :
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [43]:
arr1 = np.random.randint(1,10,size=(5))
arr2 = np.random.randint(1,10,size=(5))
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [44]:
np.allclose(arr1, arr2)

False

In [45]:
arr1 = np.random.randint(1,10,size=(10))
print("Array:\n",arr1)
result = np.where((arr1 == np.max(arr1)) , 0 , arr1)
result

Array:
 [7 1 4 7 3 4 7 7 9 3]


array([7, 1, 4, 7, 3, 4, 7, 7, 0, 3])

In [47]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("Array:\n",arr1)
for i in np.nditer(arr1):
    print(i,end=" ")

Array:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
1 2 3 4 5 6 7 8 9 

In [48]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} value")

(0, 0, 0) index has 1 value
(0, 0, 1) index has 2 value
(0, 0, 2) index has 3 value
(0, 1, 0) index has 4 value
(0, 1, 1) index has 5 value
(0, 1, 2) index has 6 value
(0, 2, 0) index has 7 value
(0, 2, 1) index has 8 value
(0, 2, 2) index has 9 value


In [49]:
arr1 = np.random.randint(1,10,size=(3,3))
print("Array:\n",arr1)
result = (arr1[arr1[:,2].argsort()])
result

Array:
 [[4 2 2]
 [3 2 6]
 [8 4 9]]


array([[4, 2, 2],
       [3, 2, 6],
       [8, 4, 9]])

In [50]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array:\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array:
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [51]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.mean(arr1)
result

5.5

In [52]:
np.median(arr1)

5.5

In [53]:
arr1 = np.random.randint(1,10,size=(10))
print(arr1)
result = np.std(arr1)
result

[9 9 9 4 7 4 1 4 3 2]


2.891366458960192

In [54]:
from scipy.stats import mode
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = mode(arr1)
result

ModeResult(mode=1, count=1)

In [55]:
result = np.round(5.98697,2)
result

5.99

In [56]:
arr1 = np.array([[2,3],[3,4]])
print("Array:\n",arr1)
result = np.linalg.inv(arr1)
result

Array:
 [[2 3]
 [3 4]]


array([[-4.,  3.],
       [ 3., -2.]])

In [57]:
x = np.array([1,2,3])
y = np.array([4,5,6])
result = np.cov(x,y)
result

array([[1., 1.],
       [1., 1.]])

In [58]:
arr1 = np.array([1,1,2,2,3,4,5,6,7,8,9,6,4,3,6,7])
result = mode(arr1)
result

ModeResult(mode=6, count=3)

In [59]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
arr1.shape
arr2 = np.reshape(arr1,(2,5,1))
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]


In [60]:
arr1 = np.random.randint(1,10,size=(1,2,3,4))
print("Array:\n",arr1)
arr2 = np.reshape(arr1,(6,4))
arr2

Array:
 [[[[5 7 2 4]
   [6 5 6 4]
   [8 8 8 9]]

  [[6 7 7 3]
   [8 5 2 3]
   [2 2 1 2]]]]


array([[5, 7, 2, 4],
       [6, 5, 6, 4],
       [8, 8, 8, 9],
       [6, 7, 7, 3],
       [8, 5, 2, 3],
       [2, 2, 1, 2]])

In [61]:
arr1 = np.zeros(10,dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
print(arr1)
arr1.shape


[[1 2 3 4]
 [5 6 8 7]
 [3 4 5 6]]


(3, 4)