In [1]:
import re

In [2]:
str1= "python and data pytthon science pythonnn pyyth annd pythh"
result = re.findall(r"p+",str1)
result

['p', 'p', 'p', 'p', 'p']

In [3]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
result

['INFORM', 'inform']

In [4]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py?",str1)
result

['py', 'py']

In [5]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [6]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"\b\w*[b]{2,3}\w*\b",str1)
result

['abbbs', 'abbbsolutely', 'abbrivation']

In [7]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [8]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [9]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [10]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [11]:
str1 = 'Suceess is a jurney not a desti9nation.'
result = re.findall(r"Suceess",str1)
result

['Suceess']

In [12]:
str1 = 'new begening of LIFE .'
result = re.findall(r"LIFE .",str1)
result

['LIFE .']

In [13]:
str1 = "today is the very lazy day"
result = re.findall(r"\w*z\w",str1)
result

['lazy']

In [14]:
str1 = "we have a lazy cat"
result = re.findall(r"[a-y]*z[a-y]",str1)
result

['lazy']

In [15]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [16]:
str1 = "9821 maya"
result = re.findall(r"^\d*",str1)
result

['9821']

In [17]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [18]:
str1="Python is required for data science version 3.2"
result = re.findall(r"\d\b",str1)
result

['3', '2']

In [19]:
str1 = "Exercises number 1, 12, 13, and 345 are important"
result = re.findall(r"\d+",str1)
result

['1', '12', '13', '345']

In [20]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for word in Searched_words:
    result = re.findall(word,Sample_text)
    print(result)

['fox']
['dog']
[]


In [21]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search(r"fox",sample_text)
print(result)

<re.Match object; span=(16, 19), match='fox'>


In [22]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [23]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
print(len(result))
result = re.search(r"exercises",Sample_text)
print(result)

3
<re.Match object; span=(7, 16), match='exercises'>


In [26]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","[_]",str1)
print(result)
result = re.sub(r"[_]","",result)
result

The[_]quick[_]brown[_]fox[_]jumps[_]over[_]the[_]lazy[_]dog.


'The[]quick[]brown[]fox[]jumps[]over[]the[]lazy[]dog.'

In [27]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","",str1)
result

'Thequickbrownfoxjumpsoverthelazydog.'

In [28]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [29]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*",str1)
result

['and', 'every', 'evening']

In [30]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [31]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[,. ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [32]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[,. ]{2}",":",text)
result

'Python: is a general purpose interpreted.'

In [33]:
text ="""123 Python is a general-purpose, interpreted,
high-level programming language popularly used for
website development, data analytics 78 and automation."""
result = re.findall(r"\b\D{3,5}\b",text)
result

[' is a', 'high-', 'level', ' used', ' for\n', 'data ', ' and ']

In [1]:
import numpy as np

In [2]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr1.nbytes

80

In [4]:
arr1 = np.zeros(10)
print(arr1)
arr1[4] = 1
arr1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [5]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [6]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [8]:
arr2 = reversed(arr1)
list(arr2)

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [9]:
arr1 = np.random.randint(1,10,size=(2,2))
print("arr1 :\n",arr1)
arr2 = np.random.randint(10,20,size=(2,2))
print("arr2 :\n",arr2)

arr1 :
 [[6 8]
 [7 2]]
arr2 :
 [[15 14]
 [15 16]]


In [10]:
add1 = arr1 + arr2
add1

array([[21, 22],
       [22, 18]])

In [11]:
sub1 = arr1 - arr2
sub1

array([[ -9,  -6],
       [ -8, -14]])

In [12]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [13]:
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [14]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [15]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mean_row = np.mean(arr1,axis=1)
print("Mean row: ",mean_row)
mean_col = np.mean(arr1,axis=0)
print("Mean column: ",mean_col)

Mean row:  [2. 5. 8.]
Mean column:  [4. 5. 6.]


In [17]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [18]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
arr1[:: , ::-1]

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [20]:
print("Array:\n",arr1)
arr1[::-1]

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [21]:
result = np.nonzero([1,2,0,0,4,0])
result

(array([0, 1, 4], dtype=int64),)

In [22]:
arr1 = np.array([[1,2],[3,4]])
print("Array:\n",arr1)
result = np.linalg.det(arr1)
result

Array:
 [[1 2]
 [3 4]]


-2.0000000000000004

In [23]:
arr1 = np.array([[1,2],[3,4]])
print("Array:\n",arr1)
result = np.linalg.inv(arr1)
result

Array:
 [[1 2]
 [3 4]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [24]:
arr1 = np.random.randint(1,10,size=(30))
print("Array:\n",arr1)
result = np.mean(arr1)
result

Array:
 [2 1 5 9 9 4 6 9 4 9 9 4 7 1 7 9 2 7 1 9 9 1 7 7 6 7 3 9 6 4]


5.766666666666667

In [25]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:\n",arr1)
result = np.where(arr1 > 5)
result

Array:
 [ 1  2  3  4  5  6  7  8  9 10]


(array([5, 6, 7, 8, 9], dtype=int64),)

In [26]:
arr1 = np.random.random((3,3,3))
arr1

array([[[0.32875764, 0.71513747, 0.29484518],
        [0.17936533, 0.00807091, 0.20601486],
        [0.92902262, 0.30944116, 0.08835122]],

       [[0.773526  , 0.00376974, 0.63239143],
        [0.84774233, 0.80748857, 0.28904745],
        [0.79350665, 0.74964332, 0.40354038]],

       [[0.19979577, 0.01172885, 0.93079204],
        [0.08703772, 0.17922896, 0.04944275],
        [0.76056961, 0.29004157, 0.04040826]]])

In [27]:
arr1 = np.random.rand(10,10)
print("Array:\n",arr1)
print(np.max(arr1))
print(np.min(arr1))

Array:
 [[0.45682126 0.17114655 0.29805147 0.56195245 0.56376326 0.85755339
  0.17129428 0.20880677 0.46310791 0.5137336 ]
 [0.68093984 0.64538467 0.13300986 0.53522825 0.24610047 0.35485416
  0.0950659  0.52506621 0.16056512 0.05001169]
 [0.77490163 0.99361575 0.24669237 0.4536274  0.06841772 0.51154733
  0.47804647 0.77925045 0.47891349 0.05980325]
 [0.6021134  0.15424003 0.94319708 0.48278949 0.06718523 0.33865686
  0.39154032 0.80916242 0.14809688 0.10813525]
 [0.02647192 0.68539235 0.26308397 0.56533493 0.12337902 0.74221915
  0.64530073 0.48091463 0.37700761 0.05049265]
 [0.14217272 0.82710211 0.67073433 0.00102323 0.55183498 0.32002598
  0.84629269 0.06509777 0.26281462 0.64906044]
 [0.41351197 0.48839387 0.58339475 0.04892601 0.37553724 0.9767245
  0.1820088  0.87381273 0.34935743 0.06447287]
 [0.2189207  0.36300084 0.74500205 0.37932755 0.86767893 0.24420718
  0.48628615 0.84779028 0.97342814 0.06058671]
 [0.71872279 0.56276    0.56232699 0.96963091 0.91883828 0.17095411
  0.7

In [28]:
arr1 = np.ones((10,10))
arr1[1:-1,1:-1] = 0
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4])
print("Array:\n",arr1)

Array:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [30]:
arr1 = np.eye(3,3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr1 = np.random.randint(1,9,size=(5,3))
arr2 = np.random.randint(1,9,size=(3,2))
result = np.dot(arr1,arr2)
result

array([[68, 75],
       [43, 48],
       [52, 67],
       [28, 36],
       [45, 57]])

In [32]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
result = np.where((arr1 >= 3) & (arr1 <= 8), -1*arr1,arr1)
result

array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [33]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Array:\n",arr1)
result = np.around(arr1,1)
result

Array:
 [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]


array([[1.2, 2.7],
       [3.5, 5.2]])

In [34]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1, arr2)
result

array([4, 5, 6])

In [35]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [36]:
arr1 = np.random.randint(1,10,size=(10))
print("Array:\n",arr1)
result = np.sort(arr1)
result

Array:
 [8 5 9 2 8 9 6 4 4 2]


array([2, 2, 4, 4, 5, 6, 8, 8, 9, 9])

In [37]:
arr1 = np.zeros((5,5))
print("Array:\n",arr1)
arr2 = arr1 + np.arange(5)
arr2

Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [38]:
A = np.random.randint(0,5,size=5)
B = np.random.randint(0,5,size=5)
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [39]:
np.allclose(arr1, arr2)

False

In [40]:
arr1 = np.random.randint(1,10,size=10)
print(arr1)
result = np.where(arr1 == np.max(arr1) , 0,arr1)
result

[4 5 3 1 7 2 6 2 5 9]


array([4, 5, 3, 1, 7, 2, 6, 2, 5, 0])

In [41]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr1):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

In [42]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

(0, 0) index has 1 values
(0, 1) index has 2 values
(0, 2) index has 3 values
(1, 0) index has 4 values
(1, 1) index has 5 values
(1, 2) index has 6 values
(2, 0) index has 7 values
(2, 1) index has 8 values
(2, 2) index has 9 values


In [43]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array:\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array:
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [44]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.mean(arr1)
result

5.5

In [45]:
np.median(arr1)

5.5

In [46]:
np.std(arr1)

2.8722813232690143

In [47]:
from scipy.stats import mode
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = mode(arr1)
result

ModeResult(mode=1, count=1)

In [48]:
result = np.around(5.8758,2)
result

5.88

In [49]:
arr1 = np.array([[2,3],[3,4]])
result = np.linalg.inv(arr1)
result

array([[-4.,  3.],
       [ 3., -2.]])

In [50]:
x = np.array([1,2,3])
y = np.array([4,5,6])
result = np.cov(x,y)
result

array([[1., 1.],
       [1., 1.]])

In [51]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
arr1.shape
arr2 = np.reshape(arr1,(2,5,1))
arr2

[ 1  2  3  4  5  6  7  8  9 10]


array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [52]:
arr1 = np.random.randint(1,10,size=(1,2,3,4))
print(arr1)
arr2 = np.reshape(arr1 , (6,4))
print(arr2)

[[[[8 2 6 7]
   [2 2 5 2]
   [9 2 9 4]]

  [[6 5 2 6]
   [6 1 5 9]
   [7 8 5 1]]]]
[[8 2 6 7]
 [2 2 5 2]
 [9 2 9 4]
 [6 5 2 6]
 [6 1 5 9]
 [7 8 5 1]]


In [53]:
arr1 = np.zeros(10,dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
print("Array:\n",arr1)
arr1.shape

Array:
 [[1 2 3 4]
 [5 6 8 7]
 [3 4 5 6]]


(3, 4)