In [1]:
import numpy as np

In [2]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr1.nbytes

80

In [4]:
arr1 = np.zeros(10)
print(arr1)
arr1[4] = 1
arr1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [5]:
arr1 = np.arange(15,45)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [6]:
arr1[::-1]

array([44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28,
       27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [7]:
arr2 = list(reversed(arr1))
arr2

[44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [8]:
arr1 = np.random.randint(1,10,size=(2,2))
print("arr1:\n",arr1)
arr2 = np.random.randint(10,20,size=(2,2))
print("arr2:\n",arr2)

arr1:
 [[7 9]
 [3 9]]
arr2:
 [[12 12]
 [16 10]]


In [9]:
add = arr1 + arr2
add

array([[19, 21],
       [19, 19]])

In [10]:
sub = arr1 - arr2
sub

array([[ -5,  -3],
       [-13,  -1]])

In [11]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [12]:
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [13]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [14]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
mean_row = np.mean(arr1,axis=1)
print("Mean across row:",mean_row)
mean_col = np.mean(arr1,axis=0)
print("Mean across column:",mean_col)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean across row: [2. 5. 8.]
Mean across column: [4. 5. 6.]


In [15]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [16]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
arr1[:: , ::-1]

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [18]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
arr1[::-1]

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [19]:
result = np.nonzero([1,2,0,0,4,0])
result

(array([0, 1, 4], dtype=int64),)

In [20]:
arr1 = np.array([[1,2],[3,4]])
print("Array:\n",arr1)
result = np.linalg.det(arr1)
result

Array:
 [[1 2]
 [3 4]]


-2.0000000000000004

In [21]:
arr1 = np.array([[2,3],[3,9]])
print("Array:\n",arr1)
result = np.linalg.inv(arr1)
result

Array:
 [[2 3]
 [3 9]]


array([[ 1.        , -0.33333333],
       [-0.33333333,  0.22222222]])

In [22]:
arr1 = np.random.randint(1,10,size=30)
print(arr1)
result = np.mean(arr1)
result

[1 7 4 2 7 2 4 6 8 8 3 4 6 6 8 3 1 4 4 9 7 8 3 1 5 7 3 5 9 5]


5.0

In [23]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:",arr1)
result = np.where(arr1 > 5)
result

Array: [ 1  2  3  4  5  6  7  8  9 10]


(array([5, 6, 7, 8, 9], dtype=int64),)

In [24]:
arr1 = np.random.random((3,3,3))
arr1

array([[[0.30871958, 0.17651662, 0.70896988],
        [0.72918766, 0.40114083, 0.66805985],
        [0.59178752, 0.19973202, 0.10334938]],

       [[0.76572388, 0.85038294, 0.10411146],
        [0.16351984, 0.07963893, 0.97229294],
        [0.35201899, 0.40107085, 0.74394739]],

       [[0.67898073, 0.57393457, 0.64066891],
        [0.28299939, 0.52322304, 0.05769157],
        [0.51838856, 0.89401325, 0.66333712]]])

In [26]:
arr1 = np.random.rand(10,10)
print(arr1)
print("Maximum:",np.max(arr1))
print("Minimum:",np.min(arr1))

[[0.84819245 0.98096068 0.22553023 0.11912926 0.85648056 0.20947665
  0.51144921 0.49531112 0.475484   0.96133343]
 [0.85842454 0.89371052 0.32566502 0.68637297 0.37614762 0.94872481
  0.77336045 0.82618954 0.37641483 0.13257026]
 [0.43974752 0.35472612 0.93210507 0.33039237 0.65855585 0.26442956
  0.39636249 0.86791662 0.07146017 0.93875332]
 [0.34594283 0.12233409 0.1576505  0.43541012 0.55245427 0.44152617
  0.04225774 0.04277458 0.58467859 0.78195556]
 [0.73493617 0.25297417 0.1225552  0.08888518 0.20411409 0.6004829
  0.26572845 0.85305929 0.9744681  0.36020606]
 [0.20683881 0.85810397 0.730822   0.70812668 0.99516639 0.00672082
  0.32583525 0.45244409 0.12056099 0.37047343]
 [0.90111402 0.58970597 0.97031962 0.9510251  0.97282356 0.30109186
  0.09700573 0.87832844 0.6529764  0.39936562]
 [0.6257919  0.60614648 0.58494548 0.23528041 0.98016148 0.28951229
  0.84260551 0.53342955 0.96711017 0.31384983]
 [0.25231098 0.08982218 0.7620958  0.10195037 0.16918925 0.29079442
  0.87243053 

In [27]:
arr1 = np.ones((10,10))
arr1[1:-1,1:-1] = 0
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4])
print(arr1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [29]:
arr1 = np.eye(3,3)
print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
arr1 = np.random.randint(1,10,size=(5,3))
arr2 = np.random.randint(1,10,size=(3,2))
result = np.dot(arr1,arr2)
result

array([[37, 41],
       [86, 88],
       [71, 91],
       [37, 47],
       [23, 43]])

In [31]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
result = np.where((arr1 >= 3) & (arr1 <= 8), -1*arr1,arr1)
result

array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [32]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Array:",arr1)
result = np.around(arr1,1)
result

Array: [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]


array([[1.2, 2.7],
       [3.5, 5.2]])

In [33]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1,arr2)
result

array([4, 5, 6])

In [34]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [35]:
arr1 = np.random.randint(1,10,size=10)
print(arr1)
result = np.sort(arr1)
result

[8 5 9 9 6 4 9 9 5 8]


array([4, 5, 5, 6, 8, 8, 9, 9, 9, 9])

In [36]:
arr1 = np.zeros((5,5))
print(arr1)

result = arr1 + np.arange(5)
result

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [37]:
A = np.random.randint(0,5,size=5)
B = np.random.randint(0,5,size=5)
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [39]:
np.allclose(A,B)

False

In [40]:
arr1 = np.random.randint(1,10,size=10)
print("Array:",arr1)
result = np.where(arr1 == np.max(arr1),0,arr1)
result

Array: [7 6 9 1 9 5 9 8 8 5]


array([7, 6, 0, 1, 0, 5, 0, 8, 8, 5])

In [41]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr1):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

In [42]:
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

(0, 0, 0) index has 1 values
(0, 0, 1) index has 2 values
(0, 0, 2) index has 3 values
(0, 1, 0) index has 4 values
(0, 1, 1) index has 5 values
(0, 1, 2) index has 6 values
(0, 2, 0) index has 7 values
(0, 2, 1) index has 8 values
(0, 2, 2) index has 9 values


In [43]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array:\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array:
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [44]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
np.mean(arr1)

5.5

In [45]:
np.median(arr1)

5.5

In [46]:
arr1 = np.random.randint(1,10,size=(10))
print(arr1)
result = np.std(arr1)
result

[5 6 8 1 6 6 3 2 1 3]


2.3

In [47]:
from scipy.stats import mode
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = mode(arr1)
result

ModeResult(mode=1, count=1)

In [48]:
result = np.around(5.435,2)
result

5.44

In [49]:
arr1 = np.array([[2,3],[3,4]])
print(arr1)
result = np.linalg.inv(arr1)
result

[[2 3]
 [3 4]]


array([[-4.,  3.],
       [ 3., -2.]])

In [50]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.cov(x,y)

array([[1., 1.],
       [1., 1.]])

In [51]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
result = np.reshape(arr1,(2,5,1))
result

[ 1  2  3  4  5  6  7  8  9 10]


array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [52]:
arr1 = np.random.randint(1,20,size=(1,2,3,4))
print(arr1)
result = np.reshape(arr1,(6,4))
result

[[[[19 14 10  1]
   [18 10 13 12]
   [12  6  8  5]]

  [[ 4 11  8  2]
   [11  7 17  6]
   [ 9 17 10  1]]]]


array([[19, 14, 10,  1],
       [18, 10, 13, 12],
       [12,  6,  8,  5],
       [ 4, 11,  8,  2],
       [11,  7, 17,  6],
       [ 9, 17, 10,  1]])

In [53]:
arr1 = np.zeros(10,dtype=int)
print(arr1)

[0 0 0 0 0 0 0 0 0 0]


In [54]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
print(arr1)
arr1.shape

[[1 2 3 4]
 [5 6 8 7]
 [3 4 5 6]]


(3, 4)