In [1]:
import re
string = "Python and Machine Learning 7741 is syllabus of Data Science."
result = re.findall("[a-zA-Z0-9]",string)
result

['P',
 'y',
 't',
 'h',
 'o',
 'n',
 'a',
 'n',
 'd',
 'M',
 'a',
 'c',
 'h',
 'i',
 'n',
 'e',
 'L',
 'e',
 'a',
 'r',
 'n',
 'i',
 'n',
 'g',
 '7',
 '7',
 '4',
 '1',
 'i',
 's',
 's',
 'y',
 'l',
 'l',
 'a',
 'b',
 'u',
 's',
 'o',
 'f',
 'D',
 'a',
 't',
 'a',
 'S',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e']

In [2]:
string = "Python and Machine Learning is syllabus of data science and deep learning."
result = re.split(r"and",string)
result

['Python ',
 ' Machine Learning is syllabus of data science ',
 ' deep learning.']

In [3]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\bab*[a-z]*\b",str1)
result

['and']

In [5]:
sample_string = "There are 123 45 678 90 2345 67 12 345 6789 0123 three-digit"
result = re.findall(r"\b\d{3}\s\d{2}\b",sample_string)
result

['123 45', '678 90']

In [6]:
str1= "python and data pytthon science pythonnn pyyth annd pythh"
result = re.findall(r"p+",str1)
result

['p', 'p', 'p', 'p', 'p']

In [7]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
result

['INFORM', 'inform']

In [8]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py?",str1)
result

['py', 'py']

In [9]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [10]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"\b\w*[b]{2,3}\w*\b",str1)
result

['abbbs', 'abbbsolutely', 'abbrivation']

In [11]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [12]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [13]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+[_]",str1)
result

['Science_', 'Abbrivation_']

In [14]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [15]:
str1 = 'Suceess is a jurney not a desti9nation.'
result = re.findall(r"Suceess",str1)
result

['Suceess']

In [16]:
str1 = 'new begening of LIFE .'
result = re.findall(r"LIFE .",str1)
result

['LIFE .']

In [17]:
str1 = "today is the very lazy day"
result = re.findall(r"\w*z\w",str1)
result

['lazy']

In [18]:
str1 = "we have a lazy cat"
result = re.findall(r"[a-y]*z[a-y]",str1)
result

['lazy']

In [19]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [20]:
str1 = "9821 maya"
result = re.findall(r"^\d*",str1)
result

['9821']

In [21]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [22]:
str1="Python is required for data science version 3.2"
result = re.findall(r"\d\b",str1)
result

['3', '2']

In [23]:
str1 = "Exercises number 1, 12, 13, and 345 are important"
result = re.findall(r"[0-9]+",str1)
result

['1', '12', '13', '345']

In [24]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for word in Searched_words:
    result = re.findall(word,Sample_text)
    print(result)

['fox']
['dog']
[]


In [25]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search(r"fox",sample_text)
result

<re.Match object; span=(16, 19), match='fox'>

In [26]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [27]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
print(len(result))
result = re.search(r"exercises",Sample_text)
print(result)

3
<re.Match object; span=(7, 16), match='exercises'>


In [28]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","_",str1)
print(result)
result = re.sub(r"[_]"," ",result)
print(result)

The_quick_brown_fox_jumps_over_the_lazy_dog.
The quick brown fox jumps over the lazy dog.


In [29]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","",str1)
result

'Thequickbrownfoxjumpsoverthelazydog.'

In [30]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [31]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*",str1)
result

['and', 'every', 'evening']

In [32]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [33]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[,. ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [34]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[,. ]{2}",":",text)
result

'Python: is a general purpose interpreted.'

In [35]:
text ="""123 Python is a general-purpose, interpreted,
high-level programming language popularly used for
website development, data analytics 78 and automation."""

result = re.findall(r"\b\D{3,5}\b",text)
result

[' is a', 'high-', 'level', ' used', ' for\n', 'data ', ' and ']

In [1]:
import numpy as np

In [2]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr1.nbytes

80

In [4]:
arr1 = np.zeros(10)
print(arr1)
arr1[4] = 1
arr1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [5]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [6]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [8]:
arr2 = reversed(arr1)
list(arr2)

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [9]:
arr1 = np.random.randint(1,10,size=(2,2))
print("Array1:\n",arr1)
arr2 = np.random.randint(1,10,size=(2,2))
print("Array2:\n",arr2)

Array1:
 [[9 6]
 [1 8]]
Array2:
 [[3 3]
 [7 7]]


In [10]:
add1 = arr1 + arr2
add1

array([[12,  9],
       [ 8, 15]])

In [11]:
sub1 = arr1 - arr2
sub1

array([[ 6,  3],
       [-6,  1]])

In [12]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [13]:
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [14]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [15]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
result = np.mean(arr1,axis=1)
print("Mean across row:",result)
result = np.mean(arr1,axis=0)
print("Mean across column:",result)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean across row: [2. 5. 8.]
Mean across column: [4. 5. 6.]


In [16]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [17]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
arr1[:: , ::-1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [19]:
arr1[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [20]:
result = np.nonzero([1,2,0,0,4,0])
result

(array([0, 1, 4], dtype=int64),)

In [21]:
arr1 = np.array([[1,2],[3,4]])
print(arr1)
result = np.linalg.det(arr1)
result

[[1 2]
 [3 4]]


-2.0000000000000004

In [22]:
arr1 = np.array([[2,3],[3,9]])
print(arr1)
result = np.linalg.inv(arr1)
result

[[2 3]
 [3 9]]


array([[ 1.        , -0.33333333],
       [-0.33333333,  0.22222222]])

In [23]:
arr1 = np.random.randint(1,10,size=(30))
print(arr1)
result = np.mean(arr1)
result

[4 6 9 1 9 3 4 8 4 8 8 2 2 2 9 8 6 1 3 3 8 3 5 8 6 5 1 2 8 1]


4.9

In [24]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
result = np.where(arr1>5)
result

[ 1  2  3  4  5  6  7  8  9 10]


(array([5, 6, 7, 8, 9], dtype=int64),)

In [25]:
arr1 = np.random.random((3,3,3))
arr1

array([[[0.61392707, 0.41113097, 0.84246706],
        [0.05334586, 0.45084261, 0.44342078],
        [0.69726503, 0.02670052, 0.31233422]],

       [[0.67728973, 0.7770817 , 0.36452458],
        [0.14050502, 0.28137015, 0.76670071],
        [0.50559735, 0.61999189, 0.15037734]],

       [[0.8988207 , 0.44090183, 0.03734894],
        [0.99892274, 0.6338682 , 0.54115115],
        [0.56196844, 0.84601021, 0.24420561]]])

In [26]:
arr1 = np.random.rand(10,10)
print(arr1)
result = np.max(arr1)
result

[[0.99582083 0.26510204 0.7578072  0.2676346  0.20919233 0.55632685
  0.80128151 0.56517926 0.75205576 0.25534539]
 [0.73212112 0.15366562 0.5552384  0.34852721 0.57147571 0.64173848
  0.9421771  0.42406201 0.03095641 0.63728274]
 [0.64962839 0.55370044 0.63214788 0.27337765 0.22281644 0.01533995
  0.38658754 0.69748025 0.76230951 0.40264121]
 [0.56099408 0.38044489 0.20806523 0.13377999 0.87350966 0.71520398
  0.42453649 0.09502981 0.17448169 0.19399054]
 [0.59121192 0.67350172 0.26159048 0.69118282 0.97460897 0.95824044
  0.93969271 0.59315326 0.98989667 0.58473335]
 [0.94207076 0.01420047 0.84044886 0.62859208 0.58962378 0.33531278
  0.5405282  0.35351977 0.89038899 0.48930984]
 [0.76531415 0.9506205  0.37694615 0.56460663 0.19116928 0.04478073
  0.91115771 0.38672424 0.93339571 0.37199634]
 [0.3785535  0.6657266  0.59164942 0.47028717 0.95387602 0.50594168
  0.08828593 0.66959356 0.42415601 0.28320157]
 [0.76620746 0.08555244 0.99206404 0.31542255 0.32879087 0.61195366
  0.42224174

0.995820827931458

In [27]:
np.min(arr1)

0.005663290325277459

In [28]:
arr1 = np.ones((10,10))
arr1[1:-1,1:-1] = 0
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4])
arr1

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [30]:
arr1 = np.eye(3,3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr1 = np.random.randint(1,9, size=(5,3))
arr2 = np.random.randint(1,9, size=(3,2))
result = np.dot(arr1, arr2)
result

array([[44, 59],
       [68, 46],
       [38, 35],
       [48, 37],
       [98, 79]])

In [32]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
print(arr1)
result = np.where((arr1 >= 3) & (arr1 <= 8),-1*arr1,arr1)
result

[ 1  2  3  4  5  6  7  8 44  9 33  6  5 10]


array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [33]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print(arr1)
result = np.around(arr1)
result

[[1.215413  2.654139 ]
 [3.4513056 5.2141555]]


array([[1., 3.],
       [3., 5.]])

In [34]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1, arr2)
result

array([4, 5, 6])

In [35]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [36]:
arr1 = np.random.randint(1,10,size=10)
print(arr1)
result = np.sort(arr1)
result

[9 2 8 5 9 1 2 8 3 9]


array([1, 2, 2, 3, 5, 8, 8, 9, 9, 9])

In [37]:
arr1 = np.zeros((5,5))
print(arr1)
arr2 = arr1 + np.arange(5)
arr2

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [38]:
A = np.random.randint(0,5,size=5)
B = np.random.randint(0,5,size=5)
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [39]:
np.allclose(arr1, arr2)

False

In [40]:
arr1 = np.random.randint(1,10,size=10)
print(arr1)
result = np.where(arr1 == np.max(arr1), 0,arr1)
result

[6 7 1 9 2 3 1 4 6 4]


array([6, 7, 1, 0, 2, 3, 1, 4, 6, 4])

In [41]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr1):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

In [42]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

(0, 0) index has 1 values
(0, 1) index has 2 values
(0, 2) index has 3 values
(1, 0) index has 4 values
(1, 1) index has 5 values
(1, 2) index has 6 values
(2, 0) index has 7 values
(2, 1) index has 8 values
(2, 2) index has 9 values


In [43]:
arr1 = np.random.randint(1,10,size=(3,3))
print(f"Array:\n",arr1)
result = (arr1[arr1[:,2].argsort()])
result

Array:
 [[9 2 8]
 [2 4 6]
 [7 4 9]]


array([[2, 4, 6],
       [9, 2, 8],
       [7, 4, 9]])

In [44]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array:\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array:
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [45]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.mean(arr1)
result

5.5

In [46]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.median(arr1)
result

5.5

In [47]:
arr1 = np.random.randint(1,10,size =10)
result = np.std(arr1)
result

2.539685019840059

In [48]:
from scipy.stats import mode
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = mode(arr1)
result

ModeResult(mode=1, count=1)

In [49]:
result = np.around(5.4342,2)
result

5.43

In [50]:
arr1 = np.array([[2,3],[3,4]])
result = np.linalg.inv(arr1)
result

array([[-4.,  3.],
       [ 3., -2.]])

In [51]:
x = np.array([1,2,3])
y = np.array([4,5,6])
result = np.cov(x,y)
result

array([[1., 1.],
       [1., 1.]])

In [52]:
arr1 = np.array([1,1,2,2,3,4,5,6,7,8,9,6,4,3,6,7])
result = mode(arr1)[0]
result

6

In [53]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
arr1.shape
arr2 = np.reshape(arr1,(2,5,1))
arr2

[ 1  2  3  4  5  6  7  8  9 10]


array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [54]:
arr1 = np.random.randint(1,20,size=(1,2,3,4))
print(arr1)
arr2 = np.reshape(arr1,(6,4))
arr2

[[[[ 7 13  7 13]
   [19 12  7 18]
   [11 17 19  4]]

  [[15 11  4 18]
   [15  6 10 12]
   [ 8  2 18 17]]]]


array([[ 7, 13,  7, 13],
       [19, 12,  7, 18],
       [11, 17, 19,  4],
       [15, 11,  4, 18],
       [15,  6, 10, 12],
       [ 8,  2, 18, 17]])

In [55]:
arr1 = np.zeros(10,dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [56]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
print(arr1)
arr1.shape

[[1 2 3 4]
 [5 6 8 7]
 [3 4 5 6]]


(3, 4)