In [1]:
import re 
string = "Python and Machine Learning 7741 is syllabus of Data Science."
result = re.findall(r"[a-zA-Z0-9]",string)
if result:
    print("Contains characters")
else:
    print("No characters found")

Contains characters


In [2]:
string = "Python and Machine Learning is syllabus of data science and deep learning."
result = re.split(r"and",string)
result

['Python ',
 ' Machine Learning is syllabus of data science ',
 ' deep learning.']

In [4]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\bab*[a-z]*\b",str1)
result

['and']

In [5]:
sample_string = "There are 123 45 678 90 2345 67 12 345 6789 0123 three-digit"
result = re.findall(r"\b\d{3}\s\d{2}\b",sample_string)
result

['123 45', '678 90']

In [6]:
str1= "python and data pytthon science pythonnn pyyth annd pythh"
result = re.findall(r"p+",str1)
result

['p', 'p', 'p', 'p', 'p']

In [7]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
result

['INFORM', 'inform']

In [8]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py?",str1)
result

['py', 'py']

In [9]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [10]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"\b\w*[b]{2,3}\w*\b",str1)
result

['abbbs', 'abbbsolutely', 'abbrivation']

In [11]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [12]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [13]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [14]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [15]:
str1 = 'Suceess is a jurney not a desti9nation.'
result = re.findall(r"Suceess",str1)
result

['Suceess']

In [17]:
str1 = 'new begening of LIFE .'
result = re.findall(r"LIFE .",str1)
result

['LIFE .']

In [19]:
str1 = "today is the very lazy day"
result = re.findall(r"\b\w*[z].\b",str1)
result

['lazy']

In [2]:
import re
str1 = "we have a lazy cat"
result = re.findall(r"[a-y]*z[a-y]",str1)
result

['lazy']

In [3]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [5]:
str1 = "9821 maya"
result = re.findall(r"\d{1,}",str1)
result

['9821']

In [6]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [10]:
str1="Python is required for data science version 3.2"
result = re.findall(r"\d..\b",str1)
result

['3.2']

In [11]:
str1 = "Exercises number 1, 12, 13, and 345 are important"
result = re.findall(r"[0-9]+",str1)
result

['1', '12', '13', '345']

In [12]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for word in Searched_words:
    result = re.findall(word,Sample_text)
    print(result)

['fox']
['dog']
[]


In [13]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search(r"fox",sample_text)
print(result)

<re.Match object; span=(16, 19), match='fox'>


In [14]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [15]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
print(len(result))
result = re.search(r"exercises",Sample_text)
print(result)

3
<re.Match object; span=(7, 16), match='exercises'>


In [16]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","_",str1)
print(result)
result = re.sub(r"[_]","",result)
print(result)

The_quick_brown_fox_jumps_over_the_lazy_dog.
Thequickbrownfoxjumpsoverthelazydog.


In [17]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","",str1)
result

'Thequickbrownfoxjumpsoverthelazydog.'

In [18]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [19]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*",str1)
result

['and', 'every', 'evening']

In [20]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [21]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[,. ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [22]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[,. ]{2}",":",text)
result

'Python: is a general purpose interpreted.'

In [23]:
text ="""123 Python is a general-purpose, interpreted,
high-level programming language popularly used for
website development, data analytics 78 and automation."""

result = re.findall(r"\b\D{3,5}\b",text)
result

[' is a', 'high-', 'level', ' used', ' for\n', 'data ', ' and ']

In [1]:
import numpy as np
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
arr1.nbytes

80

In [3]:
arr1 = np.zeros(10)
arr1 
arr1[4] = 1 
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [4]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [5]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [6]:
result = list(reversed(arr1))
result

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [8]:
arr1 = np.random.randint(10,20,size=(2,2))
print("Array1 :\n",arr1)
arr2 = np.random.randint(20,30,size=(2,2))
print("Array2 :\n",arr2)

Array1 :
 [[12 16]
 [19 18]]
Array2 :
 [[26 25]
 [20 21]]


In [9]:
add = arr1 + arr2
add

array([[38, 41],
       [39, 39]])

In [10]:
sub1 = arr1 - arr2
sub1

array([[-14,  -9],
       [ -1,  -3]])

In [11]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [12]:
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [13]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [14]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mean_row = np.mean(arr1,axis=1)
print("mean_row :\n",mean_row)
mean_col = np.mean(arr1,axis=0)
print("mean_col :\n",mean_col)

mean_row :
 [2. 5. 8.]
mean_col :
 [4. 5. 6.]


In [15]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [16]:
arr1 = np.arange(9).reshape(3,3)
print("arr1 :\n",arr1)

arr1 :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("arr1 :\n",arr1)
arr1[:: , ::-1]


arr1 :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [18]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
arr1[::-1]

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [19]:
result = np.nonzero([1,2,0,0,4,0])
result

(array([0, 1, 4], dtype=int64),)

In [20]:
arr1 = np.array([[1,2],[3,4]])
print("Array:\n",arr1)
result = np.linalg.det(arr1)
result

Array:
 [[1 2]
 [3 4]]


-2.0000000000000004

In [21]:
arr1 = np.array([[2,3],[3,9]])
print("Array:\n",arr1)
result = np.linalg.inv(arr1)
result

Array:
 [[2 3]
 [3 9]]


array([[ 1.        , -0.33333333],
       [-0.33333333,  0.22222222]])

In [22]:
arr1 = np.random.randint(10,30,size=(30))
print("Array:\n",arr1)
result = np.mean(arr1)
result

Array:
 [10 26 23 23 19 19 15 20 16 11 22 15 16 20 21 23 25 16 13 14 27 22 25 16
 20 21 24 16 10 20]


18.933333333333334

In [23]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:\n",arr1)
result = np.where(arr1 > 5)
result

Array:
 [ 1  2  3  4  5  6  7  8  9 10]


(array([5, 6, 7, 8, 9], dtype=int64),)

In [24]:
arr1 = np.random.random((3,3,3))
print("Array:\n",arr1)

Array:
 [[[0.73270108 0.72402719 0.98941704]
  [0.82535175 0.65036759 0.71177355]
  [0.41889998 0.86963668 0.74488526]]

 [[0.21579368 0.34520066 0.50602003]
  [0.11558611 0.74484786 0.6539474 ]
  [0.87698842 0.29447042 0.70152613]]

 [[0.47548032 0.21630018 0.17502375]
  [0.56357073 0.59114329 0.2397674 ]
  [0.0669284  0.33299622 0.14751913]]]


In [25]:
arr1 = np.random.rand(10,10)
print("Array:\n",arr1)
result = np.max(arr1)
result

Array:
 [[0.45905014 0.78056234 0.05589051 0.02918809 0.3688544  0.32097062
  0.12884569 0.32111215 0.6478248  0.82034279]
 [0.8331973  0.9712659  0.77871551 0.8197925  0.28946006 0.25648816
  0.09154261 0.90317231 0.72984555 0.00603084]
 [0.6363631  0.20685244 0.86070016 0.7385614  0.62869833 0.30837191
  0.82676947 0.68826013 0.06127709 0.27184328]
 [0.1776687  0.47664165 0.47559298 0.17164661 0.26554762 0.25676048
  0.69920546 0.48083367 0.69519458 0.04941819]
 [0.0600249  0.28378623 0.26099442 0.10929278 0.09720211 0.07072975
  0.21913149 0.41887041 0.75678487 0.06384883]
 [0.61436169 0.40132531 0.97538105 0.67772692 0.90817641 0.51446867
  0.67083001 0.15749467 0.57274216 0.56658017]
 [0.64488636 0.63713958 0.82894056 0.96278211 0.55344417 0.80132355
  0.40361997 0.07204367 0.62515249 0.42336134]
 [0.31550865 0.37985757 0.57396069 0.89926929 0.21357829 0.32464229
  0.29183556 0.29416823 0.3074777  0.49146568]
 [0.07469995 0.18389807 0.7930634  0.50952836 0.29040155 0.66669675
  0.

0.975381049351017

In [26]:
result = np.min(arr1)
result

0.006030843384223439

In [27]:
arr1 = np.ones((10,10))
arr1[1:-1 , 1:-1] = 0 
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4])
arr1

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [29]:
arr1 = np.eye(3,3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
arr1 = np.random.randint(1,9,size=(5,3))
arr2 = np.random.randint(1,9,size=(3,2))
result = np.dot(arr1,arr2)
print("Array 1 :\n",arr1)
print("Array 2 :\n",arr2)
print("Multiplication array :\n",result)

Array 1 :
 [[6 4 7]
 [3 5 3]
 [6 1 4]
 [7 3 2]
 [8 5 5]]
Array 2 :
 [[8 2]
 [8 5]
 [8 2]]
Multiplication array :
 [[136  46]
 [ 88  37]
 [ 88  25]
 [ 96  33]
 [144  51]]


In [31]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
print("Array 1 :\n",arr1)
result = np.where((arr1 >= 3) & (arr1 <= 8) , arr1*-1,arr1)
result

Array 1 :
 [ 1  2  3  4  5  6  7  8 44  9 33  6  5 10]


array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [32]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Array 1 :\n",arr1)
result = np.around(arr1,1)
result

Array 1 :
 [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]


array([[1.2, 2.7],
       [3.5, 5.2]])

In [33]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
result = np.ceil(arr1)
result

array([[2., 3.],
       [4., 6.]])

In [34]:
result = np.floor(arr1)
result

array([[1., 2.],
       [3., 5.]])

In [35]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1,arr2)
result

array([4, 5, 6])

In [38]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [39]:
arr1 = np.random.randint(1,10,size=10)
print("Array:",arr1)
result = np.sort(arr1)
result

Array: [3 8 1 2 1 8 7 3 7 3]


array([1, 1, 2, 3, 3, 3, 7, 7, 8, 8])

In [40]:
arr1 = np.zeros((5,5))
print("Array:\n",arr1)
arr2 = arr1 + np.arange(5)
print("Array:\n",arr2)

Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Array:
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [41]:
arr1 = np.random.randint(0,5,size=5)
arr2 = np.random.randint(0,5,size=5)
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [42]:
arr1 = np.random.randint(0,5,size=5)
arr2 = np.random.randint(0,5,size=5)
result = np.allclose(arr1, arr2)
result

False

In [43]:
arr1 = np.random.randint(1,10,size=10)
print("Array:\n",arr1)
result = np.where((arr1 == np.max(arr1)),0,arr1)
result

Array:
 [8 3 7 1 9 9 3 6 8 3]


array([8, 3, 7, 1, 0, 0, 3, 6, 8, 3])

In [45]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr1):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

In [46]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

(0, 0, 0) index has 1 values
(0, 0, 1) index has 2 values
(0, 0, 2) index has 3 values
(0, 1, 0) index has 4 values
(0, 1, 1) index has 5 values
(0, 1, 2) index has 6 values
(0, 2, 0) index has 7 values
(0, 2, 1) index has 8 values
(0, 2, 2) index has 9 values


In [48]:
arr1 = np.random.randint(1,10,size=(3,3))
print("Array:\n",arr1)
result = (arr1[arr1[:,2].argsort()])
result

Array:
 [[4 8 3]
 [8 9 7]
 [3 8 7]]


array([[4, 8, 3],
       [8, 9, 7],
       [3, 8, 7]])

In [49]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array:\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array:
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [50]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.mean(arr1)
result

5.5

In [51]:
result = np.median(arr1)
result

5.5

In [52]:
result = np.std(arr1)
result

2.8722813232690143

In [53]:
from scipy.stats import mode
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = mode(arr1)
result

ModeResult(mode=1, count=1)

In [54]:
result = np.around(5.3245,2)
result

5.32

In [55]:
arr1 = np.array([[2,3],[3,4]])
print("Array:\n",arr1)
result = np.linalg.inv(arr1)
result

Array:
 [[2 3]
 [3 4]]


array([[-4.,  3.],
       [ 3., -2.]])

In [56]:
x = np.array([1,2,3])
y = np.array([4,5,6])
result = np.cov(x,y)
result

array([[1., 1.],
       [1., 1.]])

In [57]:
arr1 = np.array([1,1,2,2,3,4,5,6,7,8,9,6,4,3,6,7])
result = mode(arr1)
result

ModeResult(mode=6, count=3)

In [58]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:\n",arr1)
arr1.shape
arr2 = np.reshape(arr1,(2,5,1))
print("Array:\n",arr2)
arr2.ndim

Array:
 [ 1  2  3  4  5  6  7  8  9 10]
Array:
 [[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]


3

In [59]:
arr1 = np.random.randint(1,20,size=(1,2,3,4))
print("Array:\n",arr1)
print(arr1.ndim)
arr2 = np.reshape(arr1 , (6,4))
print("Array:\n",arr2)
print(arr2.ndim)

Array:
 [[[[ 4 19 12  8]
   [ 5  4  6  4]
   [15  9  8  2]]

  [[ 7  8 11  4]
   [16 10  9  6]
   [11  7 17  3]]]]
4
Array:
 [[ 4 19 12  8]
 [ 5  4  6  4]
 [15  9  8  2]
 [ 7  8 11  4]
 [16 10  9  6]
 [11  7 17  3]]
2


In [60]:
arr1 = np.zeros(10,dtype=int)
print("Array:\n",arr1)

Array:
 [0 0 0 0 0 0 0 0 0 0]


In [61]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
print("Array:",arr1)
print(arr1.shape)

Array: [[1 2 3 4]
 [5 6 8 7]
 [3 4 5 6]]
(3, 4)


In [1]:
import numpy as np 
import pandas as pd
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [2]:
list1 = [[1,2,3],[4,5,6]]
pd.DataFrame(list1)

0  1  2
0  1  2  3
1  4  5  6

In [3]:
df = pd.DataFrame(columns=list("ABC"),index=list("PQR"))
df

A    B    C
P  NaN  NaN  NaN
Q  NaN  NaN  NaN
R  NaN  NaN  NaN

In [4]:
df = pd.DataFrame(columns=list("ABC"),index=list("PQR"))
if df.isnull:
    print("Datframe is empty")
else:
    print("dataframe is not empty")

Datframe is empty


In [5]:
arr1 = np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr1)
df = pd.DataFrame(arr1)
df

Array:
 [[1 2 3]
 [4 5 6]]


0  1  2
0  1  2  3
1  4  5  6

In [6]:
list1 = [[1,2,3],[4,5,6]]
df = pd.DataFrame(list1)
df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
tuple1 = (1,2,3,4,5,6)
df = pd.DataFrame(tuple1)
df

0
0  1
1  2
2  3
3  4
4  5
5  6

In [8]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [9]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]
df = pd.DataFrame(l1,columns=list("ABC"))
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [10]:
df = pd.DataFrame(np.random.randint(1,10,size=(5,6)))
df

0  1  2  3  4  5
0  3  2  7  7  9  5
1  4  7  9  1  9  9
2  5  6  8  8  7  1
3  2  2  4  6  6  2
4  1  8  3  1  4  6

In [11]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
df = pd.DataFrame(arr1)
df

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [13]:
s1 = pd.Series([1,2,3,4,5,6])
print(s1)
s2 = s1.copy()
print(s2)
s2[0] = 50 
print("Original Series :\n",s1)
print("Copied Series :\n",s2)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
Original Series :
 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
Copied Series :
 0    50
1     2
2     3
3     4
4     5
5     6
dtype: int64


In [14]:
df = pd.DataFrame(np.full((4,5),6))
df

0  1  2  3  4
0  6  6  6  6  6
1  6  6  6  6  6
2  6  6  6  6  6
3  6  6  6  6  6

In [15]:
df["5"] = [1,2,3,4]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4

In [17]:
df.loc[4] = [1,2,3,4,5,6]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4
4  1  2  3  4  5  6

In [18]:
arr1 = np.random.randint(1,10,size=(4,4))
print(arr1)
df = pd.DataFrame(arr1,columns=list("ABCD"),index=list("PQRS"))
print(df)
df.rename({"P":"p","Q":"q","R":"r","S":"s"},axis=0,inplace=True)
df.rename({"A":"a","B":"b","C":"c","D":"d"},axis=1,inplace=True)
df

[[1 2 1 2]
 [7 1 3 7]
 [7 1 3 7]
 [5 3 6 5]]
   A  B  C  D
P  1  2  1  2
Q  7  1  3  7
R  7  1  3  7
S  5  3  6  5


a  b  c  d
p  1  2  1  2
q  7  1  3  7
r  7  1  3  7
s  5  3  6  5

In [19]:
for i in df.items():
    print(i)

('a', p    1
q    7
r    7
s    5
Name: a, dtype: int32)
('b', p    2
q    1
r    1
s    3
Name: b, dtype: int32)
('c', p    1
q    3
r    3
s    6
Name: c, dtype: int32)
('d', p    2
q    7
r    7
s    5
Name: d, dtype: int32)


In [20]:
for i in df.iterrows():
    print(i)

('p', a    1
b    2
c    1
d    2
Name: p, dtype: int32)
('q', a    7
b    1
c    3
d    7
Name: q, dtype: int32)
('r', a    7
b    1
c    3
d    7
Name: r, dtype: int32)
('s', a    5
b    3
c    6
d    5
Name: s, dtype: int32)


In [22]:
df = pd.DataFrame(np.random.randint(1,10,size=(4,4)))
print(df)
arr1 = df.values
arr1

   0  1  2  3
0  7  4  8  5
1  8  9  9  4
2  4  2  8  1
3  5  3  8  6


array([[7, 4, 8, 5],
       [8, 9, 9, 4],
       [4, 2, 8, 1],
       [5, 3, 8, 6]])

In [23]:
df = pd.DataFrame(np.random.randint(1,10,size=(4,4)))
print(df)
arr1 = df.values
arr1.tolist()

   0  1  2  3
0  9  5  4  4
1  1  9  5  3
2  5  8  2  7
3  2  3  6  7


[[9, 5, 4, 4], [1, 9, 5, 3], [5, 8, 2, 7], [2, 3, 6, 7]]

In [24]:
df

0  1  2  3
0  9  5  4  4
1  1  9  5  3
2  5  8  2  7
3  2  3  6  7

In [25]:
df.reset_index(drop=True)

0  1  2  3
0  9  5  4  4
1  1  9  5  3
2  5  8  2  7
3  2  3  6  7

In [26]:
df = pd.DataFrame(np.random.randint(1,10,size=(4,4)))
print(df)
print(df.shape[0])
print(df.shape[1])

   0  1  2  3
0  6  3  9  8
1  1  4  7  7
2  2  5  1  1
3  8  6  8  6
4
4


In [27]:
s1 = pd.Series(np.arange(10,20))
s2 = pd.Series(np.arange(20,30))
print(s1+s2)

0    30
1    32
2    34
3    36
4    38
5    40
6    42
7    44
8    46
9    48
dtype: int32


In [28]:
print(s1-s2)

0   -10
1   -10
2   -10
3   -10
4   -10
5   -10
6   -10
7   -10
8   -10
9   -10
dtype: int32


In [30]:
df = pd.read_excel("Sample1.xlsx")
df

Unnamed: 0 First Name   Last Name  Gender        Country  Age  \
0             1      Dulce       Abril  Female  United States   32   
1             2       Mara   Hashimoto  Female  Great Britain   25   
2             3     Philip        Gent    Male         France   36   
3             4   Kathleen      Hanner  Female  United States   25   
4             5    Nereida     Magwood  Female  United States   58   
..          ...        ...         ...     ...            ...  ...   
995         996       Roma  Lafollette  Female  United States   34   
996         997     Felisa        Cail  Female  United States   28   
997         998   Demetria       Abbey  Female  United States   32   
998         999     Jeromy        Danz    Male  United States   39   
999        1000   Rasheeda      Alkire  Female  United States   29   

           Date    Id  
0    15/10/2017  1562  
1    16/08/2016  1582  
2    21/05/2015  2587  
3    15/10/2017  3549  
4    16/08/2016  2468  
..          ...   ...  
995  15/10/2017  2654  
996  16/08/2016  6525  
997  21/05/2015  3265  
998  15/10/2017  3265  
999  16/08/2016  6125  

[1000 rows x 8 columns]

In [31]:
df.columns

Index(['Unnamed: 0', 'First Name', 'Last Name', 'Gender', 'Country', 'Age',
       'Date', 'Id'],
      dtype='object')

In [32]:
df[['First Name', 'Last Name']]

First Name   Last Name
0        Dulce       Abril
1         Mara   Hashimoto
2       Philip        Gent
3     Kathleen      Hanner
4      Nereida     Magwood
..         ...         ...
995       Roma  Lafollette
996     Felisa        Cail
997   Demetria       Abbey
998     Jeromy        Danz
999   Rasheeda      Alkire

[1000 rows x 2 columns]

In [33]:
df["Age"].mean()

33.26

In [34]:
df["Age"].min()

21

In [35]:
df["Age"].max()

58

In [36]:
df["Age"].sum()

33260

In [37]:
df = pd.read_csv("titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [38]:
df.groupby(df["Embarked"]).get_group("S")

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
..           ...       ...     ...   
883          884         0       2   
884          885         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   

                                             Name  Gender   Age  SibSp  Parch  \
0                         Braund, Mr. Owen Harris    male  22.0      1      0   
2                          Heikkinen, Miss. Laina  female   NaN      0      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1      0   
4                        Allen, Mr. William Henry    male   NaN      0      0   
6                         McCarthy, Mr. Timothy J    male  54.0      0      0   
..                                            ...     ...   ...    ...    ...   
883                 Banfield, Mr. Frederick James    male  28.0      0      0   
884                        Sutehall, Mr. Henry Jr    male  25.0      0      0   
886                         Montvila, Rev. Juozas    male  27.0      0      0   
887                  Graham, Miss. Margaret Edith  female  19.0      0      0   
888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500   NaN        S  
2    STON/O2. 3101282   7.9250   NaN        S  
3              113803  53.1000  C123        S  
4              373450   8.0500   NaN        S  
6               17463  51.8625   E46        S  
..                ...      ...   ...      ...  
883  C.A./SOTON 34068  10.5000   NaN        S  
884   SOTON/OQ 392076   7.0500   NaN        S  
886            211536  13.0000   NaN        S  
887            112053  30.0000   B42        S  
888        W./C. 6607  23.4500   NaN        S  

[644 rows x 12 columns]

In [40]:
arr1 = np.random.randint(1,10,size=(4,2))
df = pd.DataFrame(arr1)
print(df)
df.apply(np.sqrt)

   0  1
0  3  6
1  3  1
2  1  2
3  1  1


0         1
0  1.732051  2.449490
1  1.732051  1.000000
2  1.000000  1.414214
3  1.000000  1.000000

In [41]:
df = pd.DataFrame(np.random.randint(1,9,size=(3,4)))
df

0  1  2  3
0  3  3  7  1
1  8  8  5  2
2  6  3  2  4

In [42]:
df.apply(lambda x : x**2)

0   1   2   3
0   9   9  49   1
1  64  64  25   4
2  36   9   4  16

In [43]:
df = pd.read_csv("diabetes.csv")
df.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   
3      150             66             23       94  28.1   
4      150             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   52        1  
3                     0.167   21        0  
4                     2.288   33        1

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Glucose                   768 non-null    int64  
 1   BloodPressure             768 non-null    int64  
 2   SkinThickness             768 non-null    int64  
 3   Insulin                   768 non-null    int64  
 4   BMI                       768 non-null    float64
 5   DiabetesPedigreeFunction  768 non-null    float64
 6   Age                       768 non-null    int64  
 7   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 48.1 KB


In [45]:
df.describe()

Glucose  BloodPressure  SkinThickness     Insulin         BMI  \
count  768.000000     768.000000     768.000000  768.000000  768.000000   
mean   121.117188      69.076823      20.536458   79.799479   31.992578   
std     31.805091      19.367794      15.952218  115.244002    7.884160   
min      0.000000       0.000000       0.000000    0.000000    0.000000   
25%     99.000000      62.000000       0.000000    0.000000   27.300000   
50%    117.000000      72.000000      23.000000   30.500000   32.000000   
75%    142.000000      80.000000      32.000000  127.250000   36.600000   
max    199.000000     122.000000      99.000000  846.000000   67.100000   

       DiabetesPedigreeFunction         Age     Outcome  
count                768.000000  768.000000  768.000000  
mean                   0.471876   33.243490    0.348958  
std                    0.331329   11.758182    0.476951  
min                    0.078000   21.000000    0.000000  
25%                    0.243750   24.000000    0.000000  
50%                    0.372500   29.000000    0.000000  
75%                    0.626250   41.000000    1.000000  
max                    2.420000   81.000000    1.000000

In [46]:
data1 = {"NAME" : ["Rudranshi","Sanvi","Swati","Shiva"]}
df = pd.DataFrame(data1)
print(df)
df["NAME"].apply(lambda x : x.istitle())


        NAME
0  Rudranshi
1      Sanvi
2      Swati
3      Shiva


0    True
1    True
2    True
3    True
Name: NAME, dtype: bool

In [2]:
import numpy as np
import pandas as pd

In [4]:
d1 = {"Employee":["Saniya","Sara","Alexa","Jenny"]}
df = pd.DataFrame(d1)
print(df)
d2 = {"Saniya": "Software Developer" , "Sara":"Developer" , "Alexa":"Assistant"}
df["designation"] = df["Employee"].map(d2)
df

  Employee
0   Saniya
1     Sara
2    Alexa
3    Jenny


Employee         designation
0   Saniya  Software Developer
1     Sara           Developer
2    Alexa           Assistant
3    Jenny                 NaN

In [5]:
arr1 = np.random.randint(1,10,size=(5,5))
df = pd.DataFrame(arr1,columns=list("ABCDE"))
df

A  B  C  D  E
0  6  5  4  7  6
1  8  2  1  5  1
2  2  3  1  7  3
3  3  2  2  3  8
4  5  8  8  9  7

In [6]:
df["I"] = [1,2,3,4,5]
df

A  B  C  D  E  I
0  6  5  4  7  6  1
1  8  2  1  5  1  2
2  2  3  1  7  3  3
3  3  2  2  3  8  4
4  5  8  8  9  7  5

In [7]:
arr1 = np.random.randint(1,10,size=(5,5))
df = pd.DataFrame(arr1,columns=list("ABCDE"))
print(df)
df.insert(1,"H",[1,2,1,2,1])
df

   A  B  C  D  E
0  7  7  3  4  1
1  7  7  1  6  8
2  9  2  5  9  9
3  2  6  1  5  7
4  8  6  4  6  8


A  H  B  C  D  E
0  7  1  7  3  4  1
1  7  2  7  1  6  8
2  9  1  2  5  9  9
3  2  2  6  1  5  7
4  8  1  6  4  6  8

In [8]:
df.drop("A",axis=1,inplace=True)
df

H  B  C  D  E
0  1  7  3  4  1
1  2  7  1  6  8
2  1  2  5  9  9
3  2  6  1  5  7
4  1  6  4  6  8

In [9]:
df.drop(2 , axis=0,inplace=True)
df

H  B  C  D  E
0  1  7  3  4  1
1  2  7  1  6  8
3  2  6  1  5  7
4  1  6  4  6  8

In [10]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([4,5,6,7,8])
s11 = set(s1)
s22 = set(s2)
result = s11.symmetric_difference(s22)
result

{1, 2, 3, 6, 7, 8}

In [11]:
s1 = pd.Series([1,2,3,4,5])
print(s1)
print(s1.median())
print(s1.mean())
print(s1.quantile(0.25))
print(s1.quantile(0.75))

0    1
1    2
2    3
3    4
4    5
dtype: int64
3.0
3.0
2.0
4.0


In [12]:
df = pd.DataFrame(np.random.randint(10,50,size=(4,4)) , columns=list("CABD") , index=list("xzvs"))
df

C   A   B   D
x  39  43  44  11
z  38  27  19  19
v  11  28  39  27
s  47  44  11  19

In [13]:
df.sort_index()

C   A   B   D
s  47  44  11  19
v  11  28  39  27
x  39  43  44  11
z  38  27  19  19

In [14]:
df.sort_index(axis=1)

A   B   C   D
x  43  44  39  11
z  27  19  38  19
v  28  39  11  27
s  44  11  47  19

In [15]:
df.sort_values("D")

C   A   B   D
x  39  43  44  11
z  38  27  19  19
s  47  44  11  19
v  11  28  39  27

In [16]:
df = pd.DataFrame({"A" : [1,1,3,4,5],
                   "B" : [1,1,3,4,5],
                   "C" : [1,1,3,4,5],
                   "D" : [1,1,3,4,5]})

df

A  B  C  D
0  1  1  1  1
1  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [17]:
df.drop_duplicates()

A  B  C  D
0  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [18]:
data = {'Full Name': ['John Doe', 'Jane Smith', 'Bob Johnson']}
df = pd.DataFrame(data)
print(df)
df[['First Name', 'Last Name']] = df["Full Name"].str.split(expand=True)
df

     Full Name
0     John Doe
1   Jane Smith
2  Bob Johnson


Full Name First Name Last Name
0     John Doe       John       Doe
1   Jane Smith       Jane     Smith
2  Bob Johnson        Bob   Johnson