In [1]:
with open("deadshot.txt","r")as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing


In [2]:
with open("deadshot.txt","r")as f:
    result = f.readline()
    print(result)

Data Science:



In [4]:
text = """1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing"""
with open("deadshot.txt","a")as f:
    f.write(text)
    f.close()

In [5]:
with open("deadshot.txt","r")as f:
    result = f.readlines()
    final = result[-2:]
    print(final)

[' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing']


In [6]:
with open("deadshot.txt","r")as f:
    result = f.readlines()
    print(result)

['Data Science:\n', '    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge\n', '    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of \n', '    application domains.1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2n

In [7]:
with open("deadshot.txt","r")as f:
    result = f.readlines()
    print(len(result))

25


In [8]:
with open("deadshot.txt","r")as f:
    result = f.read()
    print(len(result))

964


In [9]:
import shutil
shutil.copy("deadshot.txt","Escobar.txt")


'Escobar.txt'

In [10]:
with open("Escobar.txt","r")as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing


In [11]:
from datetime import datetime

current_datetime = datetime.now()
print("Current datetime :",current_datetime)

current_year = current_datetime.year
print("Current year:",current_year)

month_of_year = current_datetime.strftime("%B")
print("Month of year:",month_of_year)

week_number = current_datetime.strftime("%U")
print("Week number:",week_number)

weekday = current_datetime.strftime("%A")
print("Week day:",weekday)

day_of_year = current_datetime.strftime("%j")
print("Day of year:",day_of_year)

day_of_month = current_datetime.strftime("%d")
print("Day of month:",day_of_month)

Current datetime : 2024-07-22 10:34:46.567956
Current year: 2024
Month of year: July
Week number: 29
Week day: Monday
Day of year: 204
Day of month: 22


In [12]:
year = int(input("Enter a year:"))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year")
else:
    print(f"{year} is not a leap year")

2026 is not a leap year


In [13]:
date_format = "jan 1 2014 2:43PM"
date1 = "%b %d %Y %I:%M%p"

result = datetime.strptime(date_format,date1)
print(result)

2014-01-01 14:43:00


In [14]:
from datetime import timedelta
current_datetime = datetime.today()
result = current_datetime + timedelta(days=-5)
print(current_datetime)
print(result)

2024-07-22 10:50:43.352743
2024-07-17 10:50:43.352743


In [15]:
result = datetime.today() + timedelta(days=-1)
print("Date of Yesterday:",result)
result = datetime.today() + timedelta(days=0)
print("Date of today:",result)
result = datetime.today() + timedelta(days=+1)
print("Date of tomorrow:",result)

Date of Yesterday: 2024-07-21 11:02:28.249254
Date of today: 2024-07-22 11:02:28.251842
Date of tomorrow: 2024-07-23 11:02:28.252352


In [16]:
current_datetime = datetime.today().date()
print("Date of today:",current_datetime)

Date of today: 2024-07-22


In [17]:
for i in range(5):
    result = current_datetime + timedelta(days=i)
    print(result)

2024-07-22
2024-07-23
2024-07-24
2024-07-25
2024-07-26


In [18]:
current_datetime = datetime.today()
print("Date of today:",current_datetime)
result = current_datetime.replace(microsecond=0)
print("Date of today:",result)

Date of today: 2024-07-22 11:18:34.477747
Date of today: 2024-07-22 11:18:34


In [19]:
with open("Abhishek.txt","w")as f:
    f.write("He is god owns soldier")
    f.close()

with open("Abhishek.txt","r")as f:
    result = f.read()
    print(result)
    f.close()

He is god owns soldier


In [21]:
import os
os.rename("Abhishek.txt","Abhishake.txt")

In [22]:
os.getcwd()

'd:\\Assignment'

In [23]:
os.listdir()

['.git',
 'Abhi.txt',
 'Abhishake.txt',
 'Adaboost_Ass.ipynb',
 'Assignment_1.ipynb',
 'Assignment_10.ipynb',
 'Assignment_11.ipynb',
 'Assignment_12.ipynb',
 'Assignment_2.ipynb',
 'Assignment_3.ipynb',
 'Assignment_4.ipynb',
 'Assignment_6.ipynb',
 'Assignment_7.ipynb',
 'Assignment_8.ipynb',
 'Assignment_9.ipynb',
 'Assignment_DT.ipynb',
 'Assignment_KNN.ipynb',
 'autos_dataset.csv',
 'Bengaluru_House_Data.csv',
 'Book2.csv',
 'Boston.csv',
 'deadshot.txt',
 'diabetes.csv',
 'Emp_data.csv',
 'Emp_Records.xlsx',
 'emp_test1.csv',
 'Escobar.txt',
 'heart.csv',
 'Iris.csv',
 'Linear_reg_theory.ipynb',
 'loan_data.csv',
 'Logistic_reg_assignment.ipynb',
 'movies_data.csv',
 'NLP_lec2.ipynb',
 'python_1.ipynb',
 'Python_2.ipynb',
 'python_3.ipynb',
 'Python_4.ipynb',
 'Python_5.ipynb',
 'README.md',
 'Restaurant_Reviews.tsv',
 'Sample1.xlsx',
 'Social_Network_Ads.csv',
 'student.csv',
 'titanic.csv',
 'weather.csv']

In [24]:
try:
    print("hello")
except:
    print("bye")

hello


In [1]:
import re
string = "Python and Machine Learning 7741 is syllabus of Data Science."
result = re.findall("[a-zA-Z0-9]",string)
result

['P',
 'y',
 't',
 'h',
 'o',
 'n',
 'a',
 'n',
 'd',
 'M',
 'a',
 'c',
 'h',
 'i',
 'n',
 'e',
 'L',
 'e',
 'a',
 'r',
 'n',
 'i',
 'n',
 'g',
 '7',
 '7',
 '4',
 '1',
 'i',
 's',
 's',
 'y',
 'l',
 'l',
 'a',
 'b',
 'u',
 's',
 'o',
 'f',
 'D',
 'a',
 't',
 'a',
 'S',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e']

In [3]:
string = "Python and Machine Learning is syllabus of data science and deep learning."
result = re.split(f"and",string)
result

['Python ',
 ' Machine Learning is syllabus of data science ',
 ' deep learning.']

In [4]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\bab*[a-z]*\b",str1)
result

['and']

In [5]:
sample_string = "There are 123 45 678 90 2345 67 12 345 6789 0123 three-digit"
result = re.findall(r"\b\d{3}\s\d{2}\b",sample_string)
result

['123 45', '678 90']

In [6]:
str1= "python and data pytthon science pythonnn pyyth annd pythh"
result = re.findall(r"p+",str1)
result

['p', 'p', 'p', 'p', 'p']

In [7]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
result

['INFORM', 'inform']

In [8]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py?",str1)
result

['py', 'py']

In [9]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [10]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"\b\w*[b]{2,3}\w*\b",str1)
result

['abbbs', 'abbbsolutely', 'abbrivation']

In [11]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [12]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [13]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [14]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [15]:
str1 = 'Suceess is a jurney not a desti9nation.'
result = re.findall(r"Suceess",str1)
result

['Suceess']

In [16]:
str1 = 'new begening of LIFE .'
result = re.findall(r"LIFE .",str1)
result

['LIFE .']

In [17]:
str1 = "today is the very lazy day"
result = re.findall(r"\w*z\w",str1)
result

['lazy']

In [18]:
str1 = "we have a lazy cat"
result = re.findall(r"[a-y]*z[a-y]",str1)
result

['lazy']

In [19]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [20]:
str1 = "9821 maya"
result = re.findall(r"^\d*",str1)
result

['9821']

In [21]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [23]:
str1="Python is required for data science version 3.2"
result = re.findall(r"\d..\b",str1)
result

['3.2']

In [24]:
str1 = "Exercises number 1, 12, 13, and 345 are important"
result = re.findall(r"\d+",str1)
result

['1', '12', '13', '345']

In [25]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for word in Searched_words:
    result = re.findall(word,Sample_text)
    print(result)

['fox']
['dog']
[]


In [26]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search(r"fox",sample_text)
result

<re.Match object; span=(16, 19), match='fox'>

In [27]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [28]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
print(len(result))
result = re.search(r"exercises",Sample_text)
result

3


<re.Match object; span=(7, 16), match='exercises'>

In [29]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","_",str1)
print(result)
result = re.sub("_"," ",result)
result

The_quick_brown_fox_jumps_over_the_lazy_dog.


'The quick brown fox jumps over the lazy dog.'

In [30]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","",str1)
result

'Thequickbrownfoxjumpsoverthelazydog.'

In [31]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [32]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*",str1)
result

['and', 'every', 'evening']

In [33]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [34]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[,. ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [35]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[,. ]{2}",":",text)
result

'Python: is a general purpose interpreted.'

In [36]:
text ="""123 Python is a general-purpose, interpreted,
high-level programming language popularly used for
website development, data analytics 78 and automation."""

result = re.findall(r"\b\D{3,5}\b",text)
result

[' is a', 'high-', 'level', ' used', ' for\n', 'data ', ' and ']

In [1]:
import numpy as np

In [2]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr1.nbytes

80

In [4]:
arr1 = np.zeros(10)
print(arr1)
arr1[4] = 1
arr1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [5]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [6]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [8]:
arr2 = reversed(arr1)
list(arr2)

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [9]:
arr1 = np.random.randint(1,10,size=(2,2))
print(arr1)
arr2 = np.random.randint(10,20,size=(2,2))
print(arr2)

[[9 9]
 [9 2]]
[[18 13]
 [19 12]]


In [10]:
add1 = arr1 + arr2
add1

array([[27, 22],
       [28, 14]])

In [11]:
sub1 = arr1 - arr2
sub1

array([[ -9,  -4],
       [-10, -10]])

In [12]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [13]:
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [14]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [15]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
mean_row = np.mean(arr1,axis=1)
print(mean_row)
mean_col = np.mean(arr1,axis=0)
print(mean_col)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2. 5. 8.]
[4. 5. 6.]


In [16]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [17]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
arr1[:: , ::-1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [19]:
arr1[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [20]:
result = np.nonzero([1,2,0,0,4,0])
result

(array([0, 1, 4], dtype=int64),)

In [21]:
arr1 = np.array([[1,2],[3,4]])
print("Array:\n",arr1)
result = np.linalg.det(arr1)
result

Array:
 [[1 2]
 [3 4]]


-2.0000000000000004

In [22]:
arr1 = np.array([[2,3],[3,9]])
print("Array:\n",arr1)
result = np.linalg.inv(arr1)
result

Array:
 [[2 3]
 [3 9]]


array([[ 1.        , -0.33333333],
       [-0.33333333,  0.22222222]])

In [23]:
arr1 = np.random.randint(1,10,size=(30))
print("Array:\n",arr1)
result = np.mean(arr1)
result

Array:
 [2 1 4 1 6 6 3 7 1 8 6 6 9 4 3 2 2 9 8 9 2 6 3 7 6 2 1 7 5 7]


4.766666666666667

In [24]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:\n",arr1)
result = np.where(arr1 > 5)
result

Array:
 [ 1  2  3  4  5  6  7  8  9 10]


(array([5, 6, 7, 8, 9], dtype=int64),)

In [25]:
arr1 = np.random.random((3,3,3))
print("Array:\n",arr1)

Array:
 [[[0.5493677  0.18867096 0.68593548]
  [0.27930608 0.1964231  0.1929316 ]
  [0.9857223  0.91325602 0.11619143]]

 [[0.55961291 0.6254     0.64711706]
  [0.85407301 0.43111839 0.80921256]
  [0.0913186  0.47504523 0.05283635]]

 [[0.69993922 0.28133106 0.06418335]
  [0.64257126 0.08834724 0.7267204 ]
  [0.80218982 0.39710841 0.70261883]]]


In [26]:
arr1 = np.random.rand(10,10)
print("Array:\n",arr1)
np.max(arr1)

Array:
 [[0.59791664 0.68511101 0.01903812 0.8377318  0.32981212 0.21231507
  0.33231889 0.20194551 0.18360985 0.22682391]
 [0.75216924 0.63940097 0.14300698 0.68197352 0.29223531 0.67829082
  0.51651242 0.72652685 0.40277477 0.41364493]
 [0.71891388 0.29970764 0.97518831 0.02203779 0.95944941 0.92868629
  0.2061183  0.95030133 0.3020561  0.60152192]
 [0.56407588 0.47578345 0.73276404 0.90414854 0.86966031 0.62146793
  0.94191346 0.163055   0.9931532  0.75985389]
 [0.70168911 0.4665259  0.11798187 0.45405084 0.27260098 0.72334475
  0.5368021  0.62980792 0.65433091 0.79661343]
 [0.08824558 0.96405137 0.28108268 0.78599749 0.43590025 0.70920519
  0.06356694 0.13065587 0.10062707 0.02438919]
 [0.52795071 0.78676696 0.30185463 0.67280545 0.54786202 0.15982858
  0.26583389 0.01449582 0.1915434  0.04015453]
 [0.56551616 0.62551872 0.32241348 0.71521521 0.17648647 0.70827614
  0.6521701  0.0227408  0.30020985 0.80330054]
 [0.288344   0.45746414 0.51473982 0.36689815 0.77436049 0.79224878
  0.

0.9931531969262645

In [27]:
np.min(arr1)

0.014495823426909915

In [28]:
arr1 = np.ones((10,10))
arr1[1:-1,1:-1] = 0
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4])
arr1

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [30]:
arr1 = np.eye(3,3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr1 = np.random.randint(1,10,size=(5,3))
arr2 = np.random.randint(1,10,size=(3,2))
result = np.dot(arr1, arr2)
result

array([[105,  93],
       [ 78,  88],
       [ 86,  93],
       [ 86,  80],
       [ 32,  33]])

In [32]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
print(arr1)
result = np.where((arr1 >= 3) & (arr1 <= 8) , -1*arr1 , arr1)
result

[ 1  2  3  4  5  6  7  8 44  9 33  6  5 10]


array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [33]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Array:\n",arr1)
result = np.around(arr1,1)
result

Array:
 [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]


array([[1.2, 2.7],
       [3.5, 5.2]])

In [34]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Array:\n",arr1)

Array:
 [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]


In [35]:
np.floor(arr1)

array([[1., 2.],
       [3., 5.]])

In [36]:
np.ceil(arr1)

array([[2., 3.],
       [4., 6.]])

In [37]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1, arr2)
result

array([4, 5, 6])

In [38]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [39]:
arr1 = np.random.randint(1,10,size=(10))
print(arr1)
result = np.sort(arr1)
result

[7 9 3 1 3 8 6 7 8 3]


array([1, 3, 3, 3, 6, 7, 7, 8, 8, 9])

In [40]:
arr1 = np.zeros((5,5))
print(arr1)
result = arr1 + np.arange(5)
result

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [41]:
arr1 = np.random.randint(0,5,size=(5))
arr2 = np.random.randint(0,5,size=(5))
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [42]:
result = np.allclose(arr1, arr2)
result

False

In [43]:
arr1 = np.random.randint(0,5,size=(5))
print(arr1)
print()
result = np.where(arr1 >= np.max(arr1) , 0 , arr1)
result

[2 4 3 2 0]



array([2, 0, 3, 2, 0])

In [44]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr1):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

In [45]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

(0, 0) index has 1 values
(0, 1) index has 2 values
(0, 2) index has 3 values
(1, 0) index has 4 values
(1, 1) index has 5 values
(1, 2) index has 6 values
(2, 0) index has 7 values
(2, 1) index has 8 values
(2, 2) index has 9 values


In [46]:
arr1 = np.random.randint(1,10,size=(3,3))
print("Array:\n",arr1)
result = (arr1[arr1[:,2].argsort()])
result

Array:
 [[7 1 4]
 [5 4 3]
 [6 1 6]]


array([[5, 4, 3],
       [7, 1, 4],
       [6, 1, 6]])

In [48]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array:\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array:
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [49]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.mean(arr1)
result

5.5

In [50]:
result = np.median(arr1)
result

5.5

In [51]:
result = np.std(arr1)
result

2.8722813232690143

In [52]:
from scipy.stats import mode
result = mode(arr1)
result

ModeResult(mode=1, count=1)

In [53]:
result = np.around(4.4324,2)
result

4.43

In [54]:
arr1 = np.array([[2,3],[3,4]])
print("Array:\n",arr1)
result = np.linalg.inv(arr1)
result

Array:
 [[2 3]
 [3 4]]


array([[-4.,  3.],
       [ 3., -2.]])

In [55]:
x = np.array([1,2,3])
y = np.array([4,5,6])
result = np.cov(x,y)
result

array([[1., 1.],
       [1., 1.]])

In [56]:
arr1 = np.array([1,1,2,2,3,4,5,6,7,8,9,6,4,3,6,7])
result = mode(arr1)[0]
result

6

In [57]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
result = np.reshape(arr1,(2,5,1))
result

[ 1  2  3  4  5  6  7  8  9 10]


array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [58]:
arr1 = np.random.randint(1,10,size=(1,2,3,4))
print("Array:\n",arr1)
result = np.reshape(arr1,(6,4))
result

Array:
 [[[[4 3 5 6]
   [5 5 6 3]
   [5 5 9 6]]

  [[2 2 5 9]
   [4 8 2 3]
   [4 8 2 6]]]]


array([[4, 3, 5, 6],
       [5, 5, 6, 3],
       [5, 5, 9, 6],
       [2, 2, 5, 9],
       [4, 8, 2, 3],
       [4, 8, 2, 6]])

In [59]:
arr1 = np.zeros(10,dtype=int)
print("Array:\n",arr1)

Array:
 [0 0 0 0 0 0 0 0 0 0]


In [60]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
print("Array:\n",arr1)
print(arr1.shape)

Array:
 [[1 2 3 4]
 [5 6 8 7]
 [3 4 5 6]]
(3, 4)
