In [1]:
import re

In [2]:
with open("Abhishek.txt","r")as f:
    result = f.read()
    print(result)

Data Science:
    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge
    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of 
    application domains.1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing1st:- Data Science
 2nd:- Machine Le

In [3]:
with open("Abhishek.txt","r")as f:
    result = f.readline()
    print(result)

Data Science:



In [4]:
text = """1st:- Data Science
 2nd:- Machine Learning
 3rd:- Deep Learning
 4th:- Natural Language Processing"""

with open("Abhishek.txt","a")as f:
    f.write(text)
    f.close()

In [5]:
with open("Abhishek.txt","r")as f:
    result = f.readlines()
    last_line = result[-2:]
    print(last_line)

[' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing']


In [6]:
with open("Abhishek.txt","r")as f:
    result = f.readlines()
    print(result)

['Data Science:\n', '    It is an Interdisciplinary field that uses Scientific methods, processes, algorithms and systems to extract knowledge\n', '    and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of \n', '    application domains.1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2nd:- Machine Learning\n', ' 3rd:- Deep Learning\n', ' 4th:- Natural Language Processing1st:- Data Science\n', ' 2n

In [7]:
with open("Abhishek.txt","r")as f:
    result = f.readlines()
    print(len(result))

34


In [8]:
with open("Abhishek.txt","r")as f:
    result = f.read()
    print(len(result))

1258


In [9]:
import shutil

shutil.copy("Abhishek.txt","Abhishake.txt")

'Abhishake.txt'

In [10]:
with open("Abhishake.txt","r")as f:
    result = f.read()
    print(len(result))

1258


In [11]:
from datetime import datetime

current_datetime = datetime.now()
print("Current date and time:",current_datetime)

current_year = current_datetime.year
print("Current year:",current_year)

month_of_year = current_datetime.strftime("%B")
print("Month of year:",month_of_year)

week_number = current_datetime.strftime("%U")
print("Week number of year:",week_number)

weekday = current_datetime.strftime("%A")
print("Weekday :",weekday)

day_of_year = current_datetime.strftime("%j")
print("Day of year:",day_of_year)

day_of_month = current_datetime.strftime("%d")
print("Day of month:",day_of_month)


Current date and time: 2024-09-10 08:59:26.339249
Current year: 2024
Month of year: September
Week number of year: 36
Weekday : Tuesday
Day of year: 254
Day of month: 10


In [12]:
year = int(input("Enter a year:"))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year")
else:
    print(f"{year} is not a leap year")

2004 is a leap year


In [13]:
date_format = "jan 1 2014 2:43PM"
date1 = "%b %d %Y %I:%M%p"
result = datetime.strptime(date_format,date1)
print(result)

2014-01-01 14:43:00


In [14]:
from datetime import timedelta

current_datetime = datetime.today()
result = current_datetime + timedelta(days=-5)
print(result)

2024-09-05 09:24:11.036601


In [15]:
result = datetime.today() + timedelta(days=-1)
print("Yesterdays date:",result)
result = datetime.today() + timedelta(days=0)
print("Todays date :",result)
result = datetime.today() + timedelta(days=+1)
print("Tomorrows date:",result)

Yesterdays date: 2024-09-09 09:25:43.831636
Todays date : 2024-09-10 09:25:43.832637
Tomorrows date: 2024-09-11 09:25:43.832637


In [16]:
current_datetime = datetime.today().date()
print(current_datetime)

2024-09-10


In [17]:
for i in range(5):
    result = current_datetime + timedelta(days=i)
    print(result)

2024-09-10
2024-09-11
2024-09-12
2024-09-13
2024-09-14


In [18]:
current_datetime = datetime.today()
print(current_datetime)

result = current_datetime.replace(microsecond=0)
print(result)

2024-09-10 09:43:08.115721
2024-09-10 09:43:08


In [19]:
result = datetime(2024, 8 ,12)
print(result)
day = result.strftime("%a %d %b %Y %U")
print(day)

2024-08-12 00:00:00
Mon 12 Aug 2024 32


In [20]:
import os
os.rename("Abhishake.txt","Abhishek1.txt")

In [21]:
os.getcwd()

'd:\\Assignment'

In [22]:
os.listdir()

['.git',
 '.vscode',
 'Abhishek.txt',
 'Abhishek1.txt',
 'Adaboost_Ass.ipynb',
 'Assignment_1.ipynb',
 'Assignment_10.ipynb',
 'Assignment_11.ipynb',
 'Assignment_12.ipynb',
 'Assignment_2.ipynb',
 'Assignment_3.ipynb',
 'Assignment_4.ipynb',
 'Assignment_6.ipynb',
 'Assignment_7.ipynb',
 'Assignment_8.ipynb',
 'Assignment_9.ipynb',
 'Assignment_DT.ipynb',
 'Assignment_KNN.ipynb',
 'autos_dataset.csv',
 'Bengaluru_House_Data.csv',
 'Book2.csv',
 'Boston.csv',
 'deadshot.txt',
 'diabetes.csv',
 'Emp_data.csv',
 'Emp_Records.xlsx',
 'emp_test1.csv',
 'heart.csv',
 'Iris.csv',
 'Linear_reg_theory.ipynb',
 'loan_data.csv',
 'Logistic_reg_assignment.ipynb',
 'movies_data.csv',
 'NLP_lec2.ipynb',
 'Pablo.txt',
 'python_1.ipynb',
 'Python_2.ipynb',
 'python_3.ipynb',
 'Python_4.ipynb',
 'Python_5.ipynb',
 'Python_6.ipynb',
 'Python_7.ipynb',
 'Python_8.ipynb',
 'python_9.ipynb',
 'README.md',
 'Restaurant_Reviews.tsv',
 'Sample1.xlsx',
 'Social_Network_Ads.csv',
 'student.csv',
 'titanic.csv'

In [23]:
try:
    print("hello")
except:
    print("Bye")

hello


In [1]:
import re

In [2]:
string = "Python and Machine Learning 7741 is syllabus of Data Science."
result = re.findall("[a-zA-Z0-9]",string)
result

['P',
 'y',
 't',
 'h',
 'o',
 'n',
 'a',
 'n',
 'd',
 'M',
 'a',
 'c',
 'h',
 'i',
 'n',
 'e',
 'L',
 'e',
 'a',
 'r',
 'n',
 'i',
 'n',
 'g',
 '7',
 '7',
 '4',
 '1',
 'i',
 's',
 's',
 'y',
 'l',
 'l',
 'a',
 'b',
 'u',
 's',
 'o',
 'f',
 'D',
 'a',
 't',
 'a',
 'S',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e']

In [3]:
string = "Python and Machine Learning is syllabus of data science and deep learning."
result = re.split(r"and",string)
result

['Python ',
 ' Machine Learning is syllabus of data science ',
 ' deep learning.']

In [4]:
str1='Python and Data Science Batch 2023'
result = re.findall(r"\bab*[a-z]*\b",str1)
result

['and']

In [5]:
sample_string = "There are 123 45 678 90 2345 67 12 345 6789 0123 three-digit"
result = re.findall(r"\b\d{3}\s\d{2}\b",sample_string)
result

['123 45', '678 90']

In [6]:
str1= "python and data pytthon science pythonnn pyyth annd pythh"
result = re.findall(r"p+",str1)
result

['p', 'p', 'p', 'p', 'p']

In [7]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
result

['INFORM', 'inform']

In [8]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py?",str1)
result

['py', 'py']

In [9]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [10]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"\b\w*[b]{2,3}\w*\b",str1)
result

['abbbs', 'abbbsolutely', 'abbrivation']

In [11]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [12]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [13]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [14]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [15]:
str1 = 'Suceess is a jurney not a desti9nation.'
result = re.findall(r"Suceess",str1)
result

['Suceess']

In [16]:
str1 = 'new begening of LIFE .'
result = re.findall(r"LIFE .",str1)
result

['LIFE .']

In [17]:
str1 = "today is the very lazy day"
result = re.findall(r"\w*z\w",str1)
result

['lazy']

In [18]:
str1 = "we have a lazy cat"
result = re.findall(r"[a-y]*z[a-y]",str1)
result

['lazy']

In [19]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [20]:
str1 = "9821 maya"
result = re.findall(r"^9",str1)
result

['9']

In [21]:
str1 = "9821 maya"
result = re.findall(r"^\d*",str1)
result

['9821']

In [22]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [23]:
str1="Python is required for data science version 3.2"
result = re.findall(r"\d\b",str1)
result

['3', '2']

In [24]:
str1 = "Exercises number 1, 12, 13, and 345 are important"
result = re.findall(r"[0-9]+",str1)
result

['1', '12', '13', '345']

In [26]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for word in Searched_words:
    result = re.findall(word,Sample_text)
    print(result)

['fox']
['dog']
[]


In [27]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search("fox",sample_text)
result

<re.Match object; span=(16, 19), match='fox'>

In [28]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [29]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
print(len(result))
result = re.search(r"exercises",Sample_text)
print(result)

3
<re.Match object; span=(7, 16), match='exercises'>


In [30]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","_",str1)
print(result)
result = re.sub(r"[_]"," ",str1)
print(result)

The_quick_brown_fox_jumps_over_the_lazy_dog.
The quick brown fox jumps over the lazy dog.


In [31]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","",str1)
print(result)

Thequickbrownfoxjumpsoverthelazydog.


In [32]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [33]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*",str1)
result

['and', 'every', 'evening']

In [34]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [35]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[,. ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [36]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[,. ]{2}",":",text)
result

'Python: is a general purpose interpreted.'

In [37]:
text ="""123 Python is a general-purpose, interpreted,
high-level programming language popularly used for
website development, data analytics 78 and automation."""

result = re.findall(r"\b\D{3,5}\b",text)
result

[' is a', 'high-', 'level', ' used', ' for\n', 'data ', ' and ']

In [1]:
import numpy as np

In [2]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr1.nbytes

80

In [4]:
arr1 = np.zeros(10)
print(arr1)
arr1[4] = 1
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [6]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [7]:
result = reversed(arr1)
list(arr1)

[15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45]

In [8]:
arr1 = np.random.randint(1,10,size=(2,2))
print("arr1:\n",arr1)
arr2 = np.random.randint(1,10,size=(2,2))
print("arr2:\n",arr2)

arr1:
 [[8 8]
 [8 2]]
arr2:
 [[1 3]
 [7 2]]


In [9]:
add1 = arr1 + arr2
add1

array([[ 9, 11],
       [15,  4]])

In [10]:
sub1 = arr1 - arr2
sub1

array([[7, 5],
       [1, 0]])

In [11]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [12]:
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [13]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [14]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array1:\n",arr1)
result = np.mean(arr1,axis=1)
print("Mean across row:",result)
result = np.mean(arr1,axis=0)
print("Mean across column:",result)

Array1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean across row: [2. 5. 8.]
Mean across column: [4. 5. 6.]


In [15]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [16]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
arr1[:: , ::-1]

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [18]:
arr1[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [19]:
result = np.nonzero([1,2,0,0,4,0])
result

(array([0, 1, 4], dtype=int64),)

In [20]:
arr1 = np.array([[1,2],[3,4]])
print("Array:\n",arr1)
result = np.linalg.det(arr1)
result

Array:
 [[1 2]
 [3 4]]


-2.0000000000000004

In [21]:
arr1 = np.array([[2,3],[3,9]])
print("Array:\n",arr1)
result = np.linalg.inv(arr1)
result

Array:
 [[2 3]
 [3 9]]


array([[ 1.        , -0.33333333],
       [-0.33333333,  0.22222222]])

In [22]:
arr1 = np.random.randint(1,10,size=(30))
print("Array:",arr1)
result = np.mean(arr1)
result

Array: [2 2 1 7 5 2 4 7 2 3 8 8 4 9 6 9 4 8 5 5 4 6 8 1 5 7 7 9 8 8]


5.466666666666667

In [23]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("array:\n",arr1)
arr2 = np.where(arr1>5)
print(arr2)

array:
 [ 1  2  3  4  5  6  7  8  9 10]
(array([5, 6, 7, 8, 9], dtype=int64),)


In [24]:
arr1 = np.random.random((3,3,3))
arr1

array([[[0.80042181, 0.6246056 , 0.20572009],
        [0.86840779, 0.23503064, 0.54542882],
        [0.98577812, 0.09325051, 0.51319221]],

       [[0.93863271, 0.50038801, 0.8240173 ],
        [0.47929381, 0.6338295 , 0.11239475],
        [0.3436931 , 0.67592373, 0.36397336]],

       [[0.01033536, 0.804228  , 0.96825003],
        [0.29874336, 0.47675233, 0.7678653 ],
        [0.1221137 , 0.03744465, 0.79493282]]])

In [25]:
arr1 = np.random.rand(10,10)
print("Array:\n",arr1)
result = np.max(arr1)
result

Array:
 [[0.79444525 0.08394643 0.36007886 0.50576652 0.54047939 0.35507455
  0.79299139 0.0555626  0.46871524 0.14221077]
 [0.55785976 0.65119085 0.20563506 0.23519738 0.28470101 0.27444445
  0.53844422 0.19083571 0.77971847 0.00789631]
 [0.62841188 0.51108207 0.18057125 0.02914652 0.46736269 0.60409922
  0.41121533 0.33030612 0.58205274 0.61804324]
 [0.22032663 0.02087588 0.75325864 0.80802116 0.08477352 0.39581567
  0.48911116 0.49062988 0.72310612 0.78256862]
 [0.88280037 0.93659672 0.99202489 0.13908647 0.20221298 0.06897259
  0.01176771 0.35261091 0.64202853 0.13066688]
 [0.50264401 0.94772334 0.26325506 0.17663933 0.14555608 0.04681247
  0.58266313 0.83991865 0.55686457 0.53960086]
 [0.65585307 0.02392691 0.76391467 0.31083804 0.19129122 0.14071074
  0.39276561 0.18465676 0.06549938 0.96882354]
 [0.33850933 0.95214329 0.00527046 0.75057035 0.54477305 0.4145659
  0.31559008 0.35697225 0.4095581  0.47633909]
 [0.47359585 0.44695175 0.72602746 0.31378831 0.7190031  0.11545867
  0.6

0.9920248889808284

In [26]:
np.min(arr1)

0.0052704603388180615

In [27]:
arr1 = np.ones((10,10))
arr1[1:-1,1:-1] = 0
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4])
arr1

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [29]:
arr1 = np.eye(3,3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
arr1 = np.random.randint(1,9,size=(5,3))
arr2 = np.random.randint(1,9,size=(3,2))
result = np.dot(arr1,arr2)
result

array([[75, 46],
       [54, 20],
       [33, 25],
       [26, 21],
       [31, 30]])

In [31]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
result = np.where((arr1>=3) & (arr1<=8),-1*arr1,arr1)
result

array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [32]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Array:\n",arr1)
result = np.around(arr1,1)
result

Array:
 [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]


array([[1.2, 2.7],
       [3.5, 5.2]])

In [33]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
np.ceil(arr1)

array([[2., 3.],
       [4., 6.]])

In [34]:
np.floor(arr1)

array([[1., 2.],
       [3., 5.]])

In [35]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1,arr2)
result

array([4, 5, 6])

In [36]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [37]:
arr1 = np.random.randint(1,10,size=10)
print(arr1)
result = np.sort(arr1)
result

[7 5 3 1 6 3 3 6 2 6]


array([1, 2, 3, 3, 3, 5, 6, 6, 6, 7])

In [38]:
arr1 = np.zeros((5,5))
print("Array:\n",arr1)
arr2 = arr1 + np.arange(5)
arr2

Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [39]:
arr1 = np.random.randint(0,5,size=5)
arr2 = np.random.randint(0,5,size=5)
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [40]:
np.allclose(arr1,arr2)

False

In [44]:
arr1 = np.random.randint(1,10,size=10)
print("Array:\n",arr1)
result = np.where((arr1==np.max(arr1)),0,arr1)
result

Array:
 [3 1 2 6 9 4 7 1 8 2]


array([3, 1, 2, 6, 0, 4, 7, 1, 8, 2])

In [45]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr1):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

In [46]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

(0, 0) index has 1 values
(0, 1) index has 2 values
(0, 2) index has 3 values
(1, 0) index has 4 values
(1, 1) index has 5 values
(1, 2) index has 6 values
(2, 0) index has 7 values
(2, 1) index has 8 values
(2, 2) index has 9 values


In [48]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array:\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array:
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [49]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
np.mean(arr1)

5.5

In [50]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
np.median(arr1)

5.5

In [51]:
arr1 = np.random.randint(1,10,size =10)
print(arr1)
np.std(arr1)

[6 5 9 5 2 6 4 8 5 2]


2.1354156504062622

In [52]:
from scipy.stats import mode
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
mode1 = mode(arr1)
mode1

ModeResult(mode=1, count=1)

In [53]:
result = np.around(5.3423,2)
result

5.34

In [54]:
arr1 = np.array([[2,3],[3,4]])
print("Array:\n",arr1)
np.linalg.inv(arr1)

Array:
 [[2 3]
 [3 4]]


array([[-4.,  3.],
       [ 3., -2.]])

In [55]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.cov(x,y)

array([[1., 1.],
       [1., 1.]])

In [56]:
arr1 = np.array([1,1,2,2,3,4,5,6,7,8,9,6,4,3,6,7])
result = mode(arr1)[0]
result

6

In [57]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
arr1.shape
arr2 = np.reshape(arr1,(2,5,1))
arr2

[ 1  2  3  4  5  6  7  8  9 10]


array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [58]:
arr1 = np.random.randint(1,20,size=(1,2,3,4))
print(arr1)
arr2 = np.reshape(arr1,(6,4))
arr2

[[[[18 11  9  2]
   [17 19 12 10]
   [ 3 19  8  3]]

  [[19 17  3  7]
   [ 5 18  1 10]
   [ 5  9  7 14]]]]


array([[18, 11,  9,  2],
       [17, 19, 12, 10],
       [ 3, 19,  8,  3],
       [19, 17,  3,  7],
       [ 5, 18,  1, 10],
       [ 5,  9,  7, 14]])

In [59]:
arr1 = np.zeros(10,dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
arr1.shape

(3, 4)

In [1]:
import numpy as np
import pandas as pd

In [2]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
list1 = [[1,2,3],[4,5,6]]
pd.DataFrame(list1)

0  1  2
0  1  2  3
1  4  5  6

In [4]:
df = pd.DataFrame(columns=list("ABC"),index=list("PQR"))
df

A    B    C
P  NaN  NaN  NaN
Q  NaN  NaN  NaN
R  NaN  NaN  NaN

In [5]:
df.isnull()

A     B     C
P  True  True  True
Q  True  True  True
R  True  True  True

In [6]:
if df.isnull:
    print("Dataframe is empty")
else:
    print("Dataframe is not empty")

Dataframe is empty


In [7]:
arr1 = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(arr1)
df

0  1  2
0  1  2  3
1  4  5  6

In [8]:
list1 = [[1,2,3],[4,5,6]]
df = pd.DataFrame(list1)
df

0  1  2
0  1  2  3
1  4  5  6

In [9]:
tuple1 = (1,2,3,4,5,6)
df = pd.DataFrame(tuple1)
df

0
0  1
1  2
2  3
3  4
4  5
5  6

In [10]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [11]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]
df = pd.DataFrame(l1,columns=list("ABC"))
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
df = pd.DataFrame(np.random.randint(1,10,size=(5,6)))
df

0  1  2  3  4  5
0  2  7  7  1  3  2
1  6  8  4  5  8  2
2  1  9  3  7  4  7
3  5  2  9  2  5  3
4  9  1  2  5  7  5

In [13]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(arr1)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [14]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [15]:
s1 = pd.Series([1,2,3,4,5,6])
print(s1)
s2 = s1.copy()
s2[0] = 50
print(s2)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
0    50
1     2
2     3
3     4
4     5
5     6
dtype: int64


In [17]:
df = pd.DataFrame(np.full((4,5),6))
df["5"] = [1,2,3,4]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4

In [18]:
df.loc[4] = [1,2,3,4,5,6]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4
4  1  2  3  4  5  6

In [19]:
arr1 = np.random.randint(1,10,size=(4,4))
df = pd.DataFrame(arr1,columns=list("ABCD"),index=list("PQRS"))
df.rename({"P":"p","Q":"q","R":"r","S":"s"},axis=0,inplace=True)
df.rename({"A":"a","B":"b","C":"c","D":"d"},axis=1,inplace=True)
df

a  b  c  d
p  2  9  5  2
q  2  9  9  4
r  2  9  6  8
s  5  8  2  7

In [20]:
for i in df.items():
    print(i)

('a', p    2
q    2
r    2
s    5
Name: a, dtype: int32)
('b', p    9
q    9
r    9
s    8
Name: b, dtype: int32)
('c', p    5
q    9
r    6
s    2
Name: c, dtype: int32)
('d', p    2
q    4
r    8
s    7
Name: d, dtype: int32)


In [21]:
for i in df.iterrows():
    print(i)

('p', a    2
b    9
c    5
d    2
Name: p, dtype: int32)
('q', a    2
b    9
c    9
d    4
Name: q, dtype: int32)
('r', a    2
b    9
c    6
d    8
Name: r, dtype: int32)
('s', a    5
b    8
c    2
d    7
Name: s, dtype: int32)


In [22]:
df = pd.DataFrame(np.random.randint(1,10,size=(4,4)))
print(df)
arr1 = df.values
arr1

   0  1  2  3
0  1  3  9  5
1  3  7  7  2
2  8  4  8  2
3  7  5  8  2


array([[1, 3, 9, 5],
       [3, 7, 7, 2],
       [8, 4, 8, 2],
       [7, 5, 8, 2]])

In [23]:
arr1.tolist()

[[1, 3, 9, 5], [3, 7, 7, 2], [8, 4, 8, 2], [7, 5, 8, 2]]

In [24]:
df

0  1  2  3
0  1  3  9  5
1  3  7  7  2
2  8  4  8  2
3  7  5  8  2

In [25]:
df.reset_index(drop=True)

0  1  2  3
0  1  3  9  5
1  3  7  7  2
2  8  4  8  2
3  7  5  8  2

In [26]:
df = pd.DataFrame(np.random.randint(1,10,size=(4,5)))
print(df)
df.shape[0]

   0  1  2  3  4
0  6  7  7  7  8
1  6  9  7  2  8
2  4  5  3  7  6
3  6  6  7  1  3


4

In [27]:
df.shape[1]

5

In [28]:
s1 = pd.Series(np.arange(50,60))
s2 = pd.Series(np.arange(25,35))
add1 = s1 + s2
add1

0    75
1    77
2    79
3    81
4    83
5    85
6    87
7    89
8    91
9    93
dtype: int32

In [29]:
sub1 = s1 - s2
sub1

0    25
1    25
2    25
3    25
4    25
5    25
6    25
7    25
8    25
9    25
dtype: int32

In [30]:
mul1 = s1 * s2
mul1

0    1250
1    1326
2    1404
3    1484
4    1566
5    1650
6    1736
7    1824
8    1914
9    2006
dtype: int32

In [31]:
div = s1 / s2
div

0    2.000000
1    1.961538
2    1.925926
3    1.892857
4    1.862069
5    1.833333
6    1.806452
7    1.781250
8    1.757576
9    1.735294
dtype: float64

In [32]:
df = pd.read_excel("Sample1.xlsx")
df

Unnamed: 0 First Name   Last Name  Gender        Country  Age  \
0             1      Dulce       Abril  Female  United States   32   
1             2       Mara   Hashimoto  Female  Great Britain   25   
2             3     Philip        Gent    Male         France   36   
3             4   Kathleen      Hanner  Female  United States   25   
4             5    Nereida     Magwood  Female  United States   58   
..          ...        ...         ...     ...            ...  ...   
995         996       Roma  Lafollette  Female  United States   34   
996         997     Felisa        Cail  Female  United States   28   
997         998   Demetria       Abbey  Female  United States   32   
998         999     Jeromy        Danz    Male  United States   39   
999        1000   Rasheeda      Alkire  Female  United States   29   

           Date    Id  
0    15/10/2017  1562  
1    16/08/2016  1582  
2    21/05/2015  2587  
3    15/10/2017  3549  
4    16/08/2016  2468  
..          ...   ...  
995  15/10/2017  2654  
996  16/08/2016  6525  
997  21/05/2015  3265  
998  15/10/2017  3265  
999  16/08/2016  6125  

[1000 rows x 8 columns]

In [33]:
df.columns

Index(['Unnamed: 0', 'First Name', 'Last Name', 'Gender', 'Country', 'Age',
       'Date', 'Id'],
      dtype='object')

In [34]:
df[['First Name', 'Last Name']]

First Name   Last Name
0        Dulce       Abril
1         Mara   Hashimoto
2       Philip        Gent
3     Kathleen      Hanner
4      Nereida     Magwood
..         ...         ...
995       Roma  Lafollette
996     Felisa        Cail
997   Demetria       Abbey
998     Jeromy        Danz
999   Rasheeda      Alkire

[1000 rows x 2 columns]

In [35]:
df["Age"].mean()

33.26

In [36]:
df["Age"].max()

58

In [37]:
df["Age"].min()

21

In [38]:
df["Age"].sum()

33260

In [39]:
df = pd.read_csv("titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1   
4                           Allen, Mr. William Henry    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [40]:
df.groupby(df["Embarked"]).get_group("S")

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
..           ...       ...     ...   
883          884         0       2   
884          885         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   

                                             Name  Gender   Age  SibSp  Parch  \
0                         Braund, Mr. Owen Harris    male  22.0      1      0   
2                          Heikkinen, Miss. Laina  female   NaN      0      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1      0   
4                        Allen, Mr. William Henry    male   NaN      0      0   
6                         McCarthy, Mr. Timothy J    male  54.0      0      0   
..                                            ...     ...   ...    ...    ...   
883                 Banfield, Mr. Frederick James    male  28.0      0      0   
884                        Sutehall, Mr. Henry Jr    male  25.0      0      0   
886                         Montvila, Rev. Juozas    male  27.0      0      0   
887                  Graham, Miss. Margaret Edith  female  19.0      0      0   
888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500   NaN        S  
2    STON/O2. 3101282   7.9250   NaN        S  
3              113803  53.1000  C123        S  
4              373450   8.0500   NaN        S  
6               17463  51.8625   E46        S  
..                ...      ...   ...      ...  
883  C.A./SOTON 34068  10.5000   NaN        S  
884   SOTON/OQ 392076   7.0500   NaN        S  
886            211536  13.0000   NaN        S  
887            112053  30.0000   B42        S  
888        W./C. 6607  23.4500   NaN        S  

[644 rows x 12 columns]

In [41]:
arr1 = np.random.randint(1,10,size=(4,2))
df = pd.DataFrame(arr1)
print(df)
df.apply(np.sqrt)

   0  1
0  6  5
1  6  4
2  2  1
3  7  3


0         1
0  2.449490  2.236068
1  2.449490  2.000000
2  1.414214  1.000000
3  2.645751  1.732051

In [42]:
df.apply(lambda x : x**2)

0   1
0  36  25
1  36  16
2   4   1
3  49   9

In [43]:
df = pd.read_csv("diabetes.csv")
df.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   
3      150             66             23       94  28.1   
4      150             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   52        1  
3                     0.167   21        0  
4                     2.288   33        1

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Glucose                   768 non-null    int64  
 1   BloodPressure             768 non-null    int64  
 2   SkinThickness             768 non-null    int64  
 3   Insulin                   768 non-null    int64  
 4   BMI                       768 non-null    float64
 5   DiabetesPedigreeFunction  768 non-null    float64
 6   Age                       768 non-null    int64  
 7   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 48.1 KB


In [45]:
df.describe()

Glucose  BloodPressure  SkinThickness     Insulin         BMI  \
count  768.000000     768.000000     768.000000  768.000000  768.000000   
mean   121.117188      69.076823      20.536458   79.799479   31.992578   
std     31.805091      19.367794      15.952218  115.244002    7.884160   
min      0.000000       0.000000       0.000000    0.000000    0.000000   
25%     99.000000      62.000000       0.000000    0.000000   27.300000   
50%    117.000000      72.000000      23.000000   30.500000   32.000000   
75%    142.000000      80.000000      32.000000  127.250000   36.600000   
max    199.000000     122.000000      99.000000  846.000000   67.100000   

       DiabetesPedigreeFunction         Age     Outcome  
count                768.000000  768.000000  768.000000  
mean                   0.471876   33.243490    0.348958  
std                    0.331329   11.758182    0.476951  
min                    0.078000   21.000000    0.000000  
25%                    0.243750   24.000000    0.000000  
50%                    0.372500   29.000000    0.000000  
75%                    0.626250   41.000000    1.000000  
max                    2.420000   81.000000    1.000000

In [46]:
df.tail()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763      101             76             48      180  32.9   
764      122             70             27        0  36.8   
765      121             72             23      112  26.2   
766      126             60              0        0  30.1   
767       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [47]:
data1 = {"NAME" : ["Rudranshi","Sanvi","Swati","Shiva"]}
df = pd.DataFrame(data1)
print(df)
df["NAME"].apply(lambda x : x.istitle())

        NAME
0  Rudranshi
1      Sanvi
2      Swati
3      Shiva


0    True
1    True
2    True
3    True
Name: NAME, dtype: bool

In [48]:
d1 = {"Employee":["Saniya","Sara","Alexa","Jenny"]}
df = pd.DataFrame(d1)
d2 = {"Saniya": "Software Developer" , "Sara":"Developer" , "Alexa":"Assistant"}
df["designation"] = df["Employee"].map(d2)
df

Employee         designation
0   Saniya  Software Developer
1     Sara           Developer
2    Alexa           Assistant
3    Jenny                 NaN

In [49]:
arr1 = np.random.randint(1,10,size=(5,5))
df = pd.DataFrame(arr1,columns=list("ABCDE"))
df

A  B  C  D  E
0  5  5  6  5  3
1  4  9  5  3  4
2  1  1  6  7  6
3  3  7  8  7  4
4  9  8  3  3  3

In [51]:
df["I"] = [1,2,3,4,5]
df

A  B  C  D  E  I
0  5  5  6  5  3  1
1  4  9  5  3  4  2
2  1  1  6  7  6  3
3  3  7  8  7  4  4
4  9  8  3  3  3  5

In [52]:
df.insert(1,"H",[1,2,1,2,1])
df

A  H  B  C  D  E  I
0  5  1  5  6  5  3  1
1  4  2  9  5  3  4  2
2  1  1  1  6  7  6  3
3  3  2  7  8  7  4  4
4  9  1  8  3  3  3  5

In [53]:
df.drop("A",axis=1,inplace=True)
df

H  B  C  D  E  I
0  1  5  6  5  3  1
1  2  9  5  3  4  2
2  1  1  6  7  6  3
3  2  7  8  7  4  4
4  1  8  3  3  3  5

In [54]:
df.drop(2,axis=0,inplace=True)
df

H  B  C  D  E  I
0  1  5  6  5  3  1
1  2  9  5  3  4  2
3  2  7  8  7  4  4
4  1  8  3  3  3  5

In [55]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([4,5,6,7,8])
s11 = set(s1)
s22 = set(s2)
result = s11.symmetric_difference(s22)
result

{1, 2, 3, 6, 7, 8}

In [56]:
s1 = pd.Series([1,2,3,4,5])
print("Median:",s1.median())
print("Minimum:",s1.min())
print("Maximum:",s1.max())
print("25th percentile:",s1.quantile(0.25))
print("75th percentile:",s1.quantile(0.75))

Median: 3.0
Minimum: 1
Maximum: 5
25th percentile: 2.0
75th percentile: 4.0


In [57]:
df = pd.DataFrame(np.random.randint(10,50,size=(4,4)) , columns=list("CABD") , index=list("xzvs"))
df

C   A   B   D
x  19  26  22  11
z  29  42  21  47
v  21  46  27  47
s  48  10  13  46

In [58]:
df.sort_index()

C   A   B   D
s  48  10  13  46
v  21  46  27  47
x  19  26  22  11
z  29  42  21  47

In [59]:
df.sort_index(axis=1)

A   B   C   D
x  26  22  19  11
z  42  21  29  47
v  46  27  21  47
s  10  13  48  46

In [60]:
df.sort_values("D")

C   A   B   D
x  19  26  22  11
s  48  10  13  46
z  29  42  21  47
v  21  46  27  47

In [61]:
df = pd.DataFrame({"A" : [1,1,3,4,5],
                   "B" : [1,1,3,4,5],
                   "C" : [1,1,3,4,5],
                   "D" : [1,1,3,4,5]})
df

A  B  C  D
0  1  1  1  1
1  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [62]:
df.drop_duplicates()

A  B  C  D
0  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [63]:
df.drop("A",axis=1,inplace=True)

In [64]:
df

B  C  D
0  1  1  1
1  1  1  1
2  3  3  3
3  4  4  4
4  5  5  5

In [65]:
data = {'Full Name': ['John Doe', 'Jane Smith', 'Bob Johnson']}
df = pd.DataFrame(data)
print(df)

df[['First Name', 'Last Name']] = df["Full Name"].str.split(expand=True)
print(df)

     Full Name
0     John Doe
1   Jane Smith
2  Bob Johnson
     Full Name First Name Last Name
0     John Doe       John       Doe
1   Jane Smith       Jane     Smith
2  Bob Johnson        Bob   Johnson
