In [1]:
import re

In [2]:
str1= "python and data pytthon science pythonnn pyyth annd pythh"
result = re.findall(r"p+",str1)
result

['p', 'p', 'p', 'p', 'p']

In [3]:
str1 = 'We can write INFORM in lowercase as inform'
result = re.findall(r"INFORM|inform",str1)
result

['INFORM', 'inform']

In [4]:
str1= " data science and pytthon science abbbss and pyt"
result = re.findall(r"py?",str1)
result

['py', 'py']

In [5]:
str1= "python and data pbbbtthon science pytbbbonnn and pyt"
result = re.findall(r"\b\w*[b]{3}\w*\b",str1)
result

['pbbbtthon', 'pytbbbonnn']

In [6]:
str1= "abbbs and data abbbsolutely science abbrivation and pyt"
result = re.findall(r"\b\w*[b]{2,3}\w*\b",str1)
result

['abbbs', 'abbbsolutely', 'abbrivation']

In [7]:
str1= "abbbs and data abbbsolutely or science an abbrivation and pyt"
result = re.findall(r"\b\w{3,5}\b",str1)
result

['abbbs', 'and', 'data', 'and', 'pyt']

In [8]:
str1= "abbbs and data abbbsolutely or science_ an abbrivation_ and pyt_"
result = re.findall(r"[a-z]+[_]",str1)
result

['science_', 'abbrivation_', 'pyt_']

In [9]:
str1= "Abbbs and Data Abbbsolutely or Science_ an Abbrivation_ and pyt_"
result = re.findall(r"[A-Z][a-z]+",str1)
result

['Abbbs', 'Data', 'Abbbsolutely', 'Science', 'Abbrivation']

In [10]:
str1= "data absorb Science and Abbrivation and pyt"
result = re.findall(r"\ba.+b\b",str1)
result

['absorb']

In [11]:
str1 = 'Suceess is a jurney not a desti9nation.'
result = re.findall(r"Suceess",str1)
result

['Suceess']

In [12]:
str1 = 'new begening of LIFE .'
result = re.findall(r"LIFE .",str1)
result

['LIFE .']

In [13]:
str1 = "today is the very lazy day"
result = re.findall(r"\w*z\w",str1)
result

['lazy']

In [14]:
str1 = "we have a lazy cat"
result = re.findall(r"[a-y]*z[a-y]",str1)
result

['lazy']

In [15]:
str1 = "RudrANSHI_12345_wadekar"
result = re.findall(r"\w{1,}",str1)
result

['RudrANSHI_12345_wadekar']

In [16]:
str1 = "9821 maya"
result = re.findall(r"^\d*",str1)
result

['9821']

In [17]:
ip_adress="216.008.904.196"
result = re.sub(r"\b0.","",ip_adress)
result

'216.8.904.196'

In [18]:
str1="Python is required for data science version 3.2"
result = re.findall(r"\d\b",str1)
result

['3', '2']

In [19]:
str1 = "Exercises number 1, 12, 13, and 345 are important"
result = re.findall(r"\d+",str1)
result

['1', '12', '13', '345']

In [20]:
Sample_text ='The quick brown fox jumps over the lazy dog.'
Searched_words ='fox', 'dog', 'horse'
for word in Searched_words:
    result = re.findall(word,Sample_text)
    print(result)

['fox']
['dog']
[]


In [21]:
sample_text ='The quick brown fox jumps over the lazy dog.'
result = re.search(r"fox",sample_text)
print(result)

<re.Match object; span=(16, 19), match='fox'>


In [22]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
result

['exercises', 'exercises', 'exercises']

In [23]:
Sample_text = 'Python exercises, PHP exercises, C# exercises'
result = re.findall(r"exercises",Sample_text)
print(len(result))
result = re.search(r"exercises",Sample_text)
print(result)

3
<re.Match object; span=(7, 16), match='exercises'>


In [26]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","[_]",str1)
print(result)
result = re.sub(r"[_]","",result)
result

The[_]quick[_]brown[_]fox[_]jumps[_]over[_]the[_]lazy[_]dog.


'The[]quick[]brown[]fox[]jumps[]over[]the[]lazy[]dog.'

In [27]:
str1 = 'The quick brown fox jumps over the lazy dog.'
result = re.sub(r"[ ]","",str1)
result

'Thequickbrownfoxjumpsoverthelazydog.'

In [28]:
str1= "python and data science pythonnn"
result = re.findall(r"[p]\w*",str1)
result

['python', 'pythonnn']

In [29]:
str1= "data science and python learning with begening every evening "
result = re.findall(r"\b[a,e]\w*",str1)
result

['and', 'every', 'evening']

In [30]:
str1 = "i am mrunal chaudhari ,my age is 24"
result = re.search(r"\d",str1)
result

<re.Match object; span=(33, 34), match='2'>

In [31]:
text ="""Python. is a general,purpose, interpreted."""
result = re.sub(r"[,. ]",":",text)
result

'Python::is:a:general:purpose::interpreted:'

In [32]:
text ="""Python., is a general purpose interpreted."""
result = re.sub(r"[,. ]{2}",":",text)
result

'Python: is a general purpose interpreted.'

In [33]:
text ="""123 Python is a general-purpose, interpreted,
high-level programming language popularly used for
website development, data analytics 78 and automation."""
result = re.findall(r"\b\D{3,5}\b",text)
result

[' is a', 'high-', 'level', ' used', ' for\n', 'data ', ' and ']

In [1]:
import numpy as np

In [2]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr1.nbytes

80

In [4]:
arr1 = np.zeros(10)
print(arr1)
arr1[4] = 1
arr1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [5]:
arr1 = np.arange(15,46)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [6]:
arr1[::-1]

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [8]:
arr2 = reversed(arr1)
list(arr2)

[45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15]

In [9]:
arr1 = np.random.randint(1,10,size=(2,2))
print("arr1 :\n",arr1)
arr2 = np.random.randint(10,20,size=(2,2))
print("arr2 :\n",arr2)

arr1 :
 [[6 8]
 [7 2]]
arr2 :
 [[15 14]
 [15 16]]


In [10]:
add1 = arr1 + arr2
add1

array([[21, 22],
       [22, 18]])

In [11]:
sub1 = arr1 - arr2
sub1

array([[ -9,  -6],
       [ -8, -14]])

In [12]:
arr1 = np.array([1.3,1.8,2.3,3.9,1,4,1.9,9,.3])
arr1.round()

array([1., 2., 2., 4., 1., 4., 2., 9., 0.])

In [13]:
np.floor(arr1)

array([1., 1., 2., 3., 1., 4., 1., 9., 0.])

In [14]:
np.ceil(arr1)

array([2., 2., 3., 4., 1., 4., 2., 9., 1.])

In [15]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mean_row = np.mean(arr1,axis=1)
print("Mean row: ",mean_row)
mean_col = np.mean(arr1,axis=0)
print("Mean column: ",mean_col)

Mean row:  [2. 5. 8.]
Mean column:  [4. 5. 6.]


In [17]:
list1 = [0,30,45,60,90]
result = np.deg2rad(list1)
result

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [18]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr1)
arr1[:: , ::-1]

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [20]:
print("Array:\n",arr1)
arr1[::-1]

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [21]:
result = np.nonzero([1,2,0,0,4,0])
result

(array([0, 1, 4], dtype=int64),)

In [22]:
arr1 = np.array([[1,2],[3,4]])
print("Array:\n",arr1)
result = np.linalg.det(arr1)
result

Array:
 [[1 2]
 [3 4]]


-2.0000000000000004

In [23]:
arr1 = np.array([[1,2],[3,4]])
print("Array:\n",arr1)
result = np.linalg.inv(arr1)
result

Array:
 [[1 2]
 [3 4]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [24]:
arr1 = np.random.randint(1,10,size=(30))
print("Array:\n",arr1)
result = np.mean(arr1)
result

Array:
 [2 1 5 9 9 4 6 9 4 9 9 4 7 1 7 9 2 7 1 9 9 1 7 7 6 7 3 9 6 4]


5.766666666666667

In [25]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:\n",arr1)
result = np.where(arr1 > 5)
result

Array:
 [ 1  2  3  4  5  6  7  8  9 10]


(array([5, 6, 7, 8, 9], dtype=int64),)

In [26]:
arr1 = np.random.random((3,3,3))
arr1

array([[[0.32875764, 0.71513747, 0.29484518],
        [0.17936533, 0.00807091, 0.20601486],
        [0.92902262, 0.30944116, 0.08835122]],

       [[0.773526  , 0.00376974, 0.63239143],
        [0.84774233, 0.80748857, 0.28904745],
        [0.79350665, 0.74964332, 0.40354038]],

       [[0.19979577, 0.01172885, 0.93079204],
        [0.08703772, 0.17922896, 0.04944275],
        [0.76056961, 0.29004157, 0.04040826]]])

In [27]:
arr1 = np.random.rand(10,10)
print("Array:\n",arr1)
print(np.max(arr1))
print(np.min(arr1))

Array:
 [[0.45682126 0.17114655 0.29805147 0.56195245 0.56376326 0.85755339
  0.17129428 0.20880677 0.46310791 0.5137336 ]
 [0.68093984 0.64538467 0.13300986 0.53522825 0.24610047 0.35485416
  0.0950659  0.52506621 0.16056512 0.05001169]
 [0.77490163 0.99361575 0.24669237 0.4536274  0.06841772 0.51154733
  0.47804647 0.77925045 0.47891349 0.05980325]
 [0.6021134  0.15424003 0.94319708 0.48278949 0.06718523 0.33865686
  0.39154032 0.80916242 0.14809688 0.10813525]
 [0.02647192 0.68539235 0.26308397 0.56533493 0.12337902 0.74221915
  0.64530073 0.48091463 0.37700761 0.05049265]
 [0.14217272 0.82710211 0.67073433 0.00102323 0.55183498 0.32002598
  0.84629269 0.06509777 0.26281462 0.64906044]
 [0.41351197 0.48839387 0.58339475 0.04892601 0.37553724 0.9767245
  0.1820088  0.87381273 0.34935743 0.06447287]
 [0.2189207  0.36300084 0.74500205 0.37932755 0.86767893 0.24420718
  0.48628615 0.84779028 0.97342814 0.06058671]
 [0.71872279 0.56276    0.56232699 0.96963091 0.91883828 0.17095411
  0.7

In [28]:
arr1 = np.ones((10,10))
arr1[1:-1,1:-1] = 0
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
arr1 = np.zeros((5,5),dtype=int)
np.fill_diagonal(arr1[1:],[1,2,3,4])
print("Array:\n",arr1)

Array:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [30]:
arr1 = np.eye(3,3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr1 = np.random.randint(1,9,size=(5,3))
arr2 = np.random.randint(1,9,size=(3,2))
result = np.dot(arr1,arr2)
result

array([[68, 75],
       [43, 48],
       [52, 67],
       [28, 36],
       [45, 57]])

In [32]:
arr1 = np.array([1,2,3,4,5,6,7,8,44,9,33,6,5,10])
result = np.where((arr1 >= 3) & (arr1 <= 8), -1*arr1,arr1)
result

array([ 1,  2, -3, -4, -5, -6, -7, -8, 44,  9, 33, -6, -5, 10])

In [33]:
arr1 = np.array([[1.215413,2.654139],[3.4513056,5.2141555]])
print("Array:\n",arr1)
result = np.around(arr1,1)
result

Array:
 [[1.215413  2.654139 ]
 [3.4513056 5.2141555]]


array([[1.2, 2.7],
       [3.5, 5.2]])

In [34]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
result = np.intersect1d(arr1, arr2)
result

array([4, 5, 6])

In [35]:
arr1 = np.linspace(0,1,10)[1:-1]
arr1

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

In [36]:
arr1 = np.random.randint(1,10,size=(10))
print("Array:\n",arr1)
result = np.sort(arr1)
result

Array:
 [8 5 9 2 8 9 6 4 4 2]


array([2, 2, 4, 4, 5, 6, 8, 8, 9, 9])

In [37]:
arr1 = np.zeros((5,5))
print("Array:\n",arr1)
arr2 = arr1 + np.arange(5)
arr2

Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [38]:
A = np.random.randint(0,5,size=5)
B = np.random.randint(0,5,size=5)
if np.equal == True:
    print("Both arrays are equal")
else:
    print("Both arrays are not equal")

Both arrays are not equal


In [39]:
np.allclose(arr1, arr2)

False

In [40]:
arr1 = np.random.randint(1,10,size=10)
print(arr1)
result = np.where(arr1 == np.max(arr1) , 0,arr1)
result

[4 5 3 1 7 2 6 2 5 9]


array([4, 5, 3, 1, 7, 2, 6, 2, 5, 0])

In [41]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(arr1):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

In [42]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for index,value in np.ndenumerate(arr1):
    print(f"{index} index has {value} values")

(0, 0) index has 1 values
(0, 1) index has 2 values
(0, 2) index has 3 values
(1, 0) index has 4 values
(1, 1) index has 5 values
(1, 2) index has 6 values
(2, 0) index has 7 values
(2, 1) index has 8 values
(2, 2) index has 9 values


In [43]:
arr1 = np.array([[4,3,1],[5,8,9],[3,4,5]])
print("Array:\n",arr1)
arr1[[0,2]] = arr1[[2,0]]
arr1

Array:
 [[4 3 1]
 [5 8 9]
 [3 4 5]]


array([[3, 4, 5],
       [5, 8, 9],
       [4, 3, 1]])

In [44]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.mean(arr1)
result

5.5

In [45]:
np.median(arr1)

5.5

In [46]:
np.std(arr1)

2.8722813232690143

In [47]:
from scipy.stats import mode
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
result = mode(arr1)
result

ModeResult(mode=1, count=1)

In [48]:
result = np.around(5.8758,2)
result

5.88

In [49]:
arr1 = np.array([[2,3],[3,4]])
result = np.linalg.inv(arr1)
result

array([[-4.,  3.],
       [ 3., -2.]])

In [50]:
x = np.array([1,2,3])
y = np.array([4,5,6])
result = np.cov(x,y)
result

array([[1., 1.],
       [1., 1.]])

In [51]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
arr1.shape
arr2 = np.reshape(arr1,(2,5,1))
arr2

[ 1  2  3  4  5  6  7  8  9 10]


array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [52]:
arr1 = np.random.randint(1,10,size=(1,2,3,4))
print(arr1)
arr2 = np.reshape(arr1 , (6,4))
print(arr2)

[[[[8 2 6 7]
   [2 2 5 2]
   [9 2 9 4]]

  [[6 5 2 6]
   [6 1 5 9]
   [7 8 5 1]]]]
[[8 2 6 7]
 [2 2 5 2]
 [9 2 9 4]
 [6 5 2 6]
 [6 1 5 9]
 [7 8 5 1]]


In [53]:
arr1 = np.zeros(10,dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
arr1 = np.array([[1,2,3,4],[5,6,8,7],[3,4,5,6]])
print("Array:\n",arr1)
arr1.shape

Array:
 [[1 2 3 4]
 [5 6 8 7]
 [3 4 5 6]]


(3, 4)

In [1]:
import numpy as np
import pandas as pd

In [2]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
list1 = [[1,2,3],[4,5,6]]
pd.DataFrame(list1)

0  1  2
0  1  2  3
1  4  5  6

In [4]:
df = pd.DataFrame(columns=list("ABC"),index=list("PQR"))
df

A    B    C
P  NaN  NaN  NaN
Q  NaN  NaN  NaN
R  NaN  NaN  NaN

In [6]:
if df.isnull:
    print("Dataframe is empty")
else:
    print("Dataframe is not empty")

Dataframe is empty


In [7]:
arr1 = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(arr1)
df

0  1  2
0  1  2  3
1  4  5  6

In [8]:
list1 = [[1,2,3],[4,5,6]]
df = pd.DataFrame(list1)
df

0  1  2
0  1  2  3
1  4  5  6

In [9]:
tuple1 = (1,2,3,4,5,6)
df = pd.DataFrame(tuple1)
df

0
0  1
1  2
2  3
3  4
4  5
5  6

In [10]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [11]:
l1 = [[1,2,3],[4,5,6],[7,8,9]]
df = pd.DataFrame(l1,columns=list("ABC"))
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
df = pd.DataFrame(np.random.randint(1,10,size=(5,6)))
df

0  1  2  3  4  5
0  1  9  7  6  3  2
1  1  2  6  3  4  1
2  3  2  8  9  4  5
3  8  2  3  8  2  2
4  5  4  9  5  6  7

In [13]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(arr1)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [14]:
dict1 = {"name" : ["hindvi","ovi","rudu"] , "marks" : [80,70,90]}
df = pd.DataFrame(dict1)
df

name  marks
0  hindvi     80
1     ovi     70
2    rudu     90

In [15]:
s1 = pd.Series([1,2,3,4,5])
print(s1)
s2 = s1.copy()
s2[0] = 50
print("Original Series :\n",s1)
print("Copied Series :\n",s2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
Original Series :
 0    1
1    2
2    3
3    4
4    5
dtype: int64
Copied Series :
 0    50
1     2
2     3
3     4
4     5
dtype: int64


In [16]:
df = pd.DataFrame(np.full((4,5),6))
print(df)

   0  1  2  3  4
0  6  6  6  6  6
1  6  6  6  6  6
2  6  6  6  6  6
3  6  6  6  6  6


In [17]:
df["5"] = [1,2,3,4]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4

In [19]:
df.loc[4] = [1,2,3,4,5,6]
df

0  1  2  3  4  5
0  6  6  6  6  6  1
1  6  6  6  6  6  2
2  6  6  6  6  6  3
3  6  6  6  6  6  4
4  1  2  3  4  5  6

In [20]:
arr1 = np.random.randint(1,10,size=(4,4))
df = pd.DataFrame(arr1,columns=list("ABCD"),index=list("PQRS"))
df.rename({"A":"a","B":"b","C":"c","D":"d"},axis=1,inplace=True)
df.rename({"P":"p","Q":"q","R":"r","S":"s"},axis=0,inplace=True)
df

a  b  c  d
p  5  4  7  9
q  2  5  9  5
r  4  5  6  6
s  4  4  2  8

In [21]:
for i in df.items():
    print(i)

('a', p    5
q    2
r    4
s    4
Name: a, dtype: int32)
('b', p    4
q    5
r    5
s    4
Name: b, dtype: int32)
('c', p    7
q    9
r    6
s    2
Name: c, dtype: int32)
('d', p    9
q    5
r    6
s    8
Name: d, dtype: int32)


In [22]:
for i in df.iterrows():
    print(i)

('p', a    5
b    4
c    7
d    9
Name: p, dtype: int32)
('q', a    2
b    5
c    9
d    5
Name: q, dtype: int32)
('r', a    4
b    5
c    6
d    6
Name: r, dtype: int32)
('s', a    4
b    4
c    2
d    8
Name: s, dtype: int32)


In [23]:
df

a  b  c  d
p  5  4  7  9
q  2  5  9  5
r  4  5  6  6
s  4  4  2  8

In [25]:
arr1 = df.values
arr1

array([[5, 4, 7, 9],
       [2, 5, 9, 5],
       [4, 5, 6, 6],
       [4, 4, 2, 8]])

In [26]:
arr1.tolist()

[[5, 4, 7, 9], [2, 5, 9, 5], [4, 5, 6, 6], [4, 4, 2, 8]]

In [27]:
df

a  b  c  d
p  5  4  7  9
q  2  5  9  5
r  4  5  6  6
s  4  4  2  8

In [28]:
df.reset_index(drop=True)

a  b  c  d
0  5  4  7  9
1  2  5  9  5
2  4  5  6  6
3  4  4  2  8

In [29]:
df = pd.DataFrame(np.random.randint(10,20,size=(4,5)))
print(df)
print(df.shape[0])
print(df.shape[1])

    0   1   2   3   4
0  14  14  12  14  15
1  11  17  17  13  10
2  12  19  13  13  10
3  15  16  13  18  13
4
5


In [30]:
s1 = pd.Series(np.arange(50,60))
s2 = pd.Series(np.arange(25,35))
print(s1+s2)
print(s1-s2)
print(s1*s2)
print(s1/s2)

0    75
1    77
2    79
3    81
4    83
5    85
6    87
7    89
8    91
9    93
dtype: int32
0    25
1    25
2    25
3    25
4    25
5    25
6    25
7    25
8    25
9    25
dtype: int32
0    1250
1    1326
2    1404
3    1484
4    1566
5    1650
6    1736
7    1824
8    1914
9    2006
dtype: int32
0    2.000000
1    1.961538
2    1.925926
3    1.892857
4    1.862069
5    1.833333
6    1.806452
7    1.781250
8    1.757576
9    1.735294
dtype: float64


In [31]:
df = pd.read_excel("Sample1.xlsx")
df.head()

Unnamed: 0 First Name  Last Name  Gender        Country  Age        Date  \
0           1      Dulce      Abril  Female  United States   32  15/10/2017   
1           2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016   
2           3     Philip       Gent    Male         France   36  21/05/2015   
3           4   Kathleen     Hanner  Female  United States   25  15/10/2017   
4           5    Nereida    Magwood  Female  United States   58  16/08/2016   

     Id  
0  1562  
1  1582  
2  2587  
3  3549  
4  2468

In [32]:
df.columns

Index(['Unnamed: 0', 'First Name', 'Last Name', 'Gender', 'Country', 'Age',
       'Date', 'Id'],
      dtype='object')

In [33]:
df[['First Name', 'Last Name']]

First Name   Last Name
0        Dulce       Abril
1         Mara   Hashimoto
2       Philip        Gent
3     Kathleen      Hanner
4      Nereida     Magwood
..         ...         ...
995       Roma  Lafollette
996     Felisa        Cail
997   Demetria       Abbey
998     Jeromy        Danz
999   Rasheeda      Alkire

[1000 rows x 2 columns]

In [34]:
df["Age"].mean()

33.26

In [35]:
df["Age"].median()

32.0

In [36]:
df["Age"].min()

21

In [37]:
df["Age"].max()

58

In [38]:
df = pd.read_csv("titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1   
4                           Allen, Mr. William Henry    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [39]:
df.groupby(df["Embarked"]).get_group("S")

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
..           ...       ...     ...   
883          884         0       2   
884          885         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   

                                             Name  Gender   Age  SibSp  Parch  \
0                         Braund, Mr. Owen Harris    male  22.0      1      0   
2                          Heikkinen, Miss. Laina  female   NaN      0      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1      0   
4                        Allen, Mr. William Henry    male   NaN      0      0   
6                         McCarthy, Mr. Timothy J    male  54.0      0      0   
..                                            ...     ...   ...    ...    ...   
883                 Banfield, Mr. Frederick James    male  28.0      0      0   
884                        Sutehall, Mr. Henry Jr    male  25.0      0      0   
886                         Montvila, Rev. Juozas    male  27.0      0      0   
887                  Graham, Miss. Margaret Edith  female  19.0      0      0   
888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500   NaN        S  
2    STON/O2. 3101282   7.9250   NaN        S  
3              113803  53.1000  C123        S  
4              373450   8.0500   NaN        S  
6               17463  51.8625   E46        S  
..                ...      ...   ...      ...  
883  C.A./SOTON 34068  10.5000   NaN        S  
884   SOTON/OQ 392076   7.0500   NaN        S  
886            211536  13.0000   NaN        S  
887            112053  30.0000   B42        S  
888        W./C. 6607  23.4500   NaN        S  

[644 rows x 12 columns]

In [40]:
arr1 = np.random.randint(1,10,size=(4,2))
df = pd.DataFrame(arr1)
print(df)
df.apply(np.sqrt)

   0  1
0  5  7
1  9  2
2  4  3
3  3  8


0         1
0  2.236068  2.645751
1  3.000000  1.414214
2  2.000000  1.732051
3  1.732051  2.828427

In [41]:
df.apply(lambda x : x**2)

0   1
0  25  49
1  81   4
2  16   9
3   9  64

In [42]:
df.apply(lambda x : x**3)

0    1
0  125  343
1  729    8
2   64   27
3   27  512

In [43]:
df = pd.read_csv("diabetes.csv")
df.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   
3      150             66             23       94  28.1   
4      150             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   52        1  
3                     0.167   21        0  
4                     2.288   33        1

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Glucose                   768 non-null    int64  
 1   BloodPressure             768 non-null    int64  
 2   SkinThickness             768 non-null    int64  
 3   Insulin                   768 non-null    int64  
 4   BMI                       768 non-null    float64
 5   DiabetesPedigreeFunction  768 non-null    float64
 6   Age                       768 non-null    int64  
 7   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 48.1 KB


In [45]:
df.describe()

Glucose  BloodPressure  SkinThickness     Insulin         BMI  \
count  768.000000     768.000000     768.000000  768.000000  768.000000   
mean   121.117188      69.076823      20.536458   79.799479   31.992578   
std     31.805091      19.367794      15.952218  115.244002    7.884160   
min      0.000000       0.000000       0.000000    0.000000    0.000000   
25%     99.000000      62.000000       0.000000    0.000000   27.300000   
50%    117.000000      72.000000      23.000000   30.500000   32.000000   
75%    142.000000      80.000000      32.000000  127.250000   36.600000   
max    199.000000     122.000000      99.000000  846.000000   67.100000   

       DiabetesPedigreeFunction         Age     Outcome  
count                768.000000  768.000000  768.000000  
mean                   0.471876   33.243490    0.348958  
std                    0.331329   11.758182    0.476951  
min                    0.078000   21.000000    0.000000  
25%                    0.243750   24.000000    0.000000  
50%                    0.372500   29.000000    0.000000  
75%                    0.626250   41.000000    1.000000  
max                    2.420000   81.000000    1.000000

In [46]:
df.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   
3      150             66             23       94  28.1   
4      150             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   52        1  
3                     0.167   21        0  
4                     2.288   33        1

In [47]:
df.tail()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763      101             76             48      180  32.9   
764      122             70             27        0  36.8   
765      121             72             23      112  26.2   
766      126             60              0        0  30.1   
767       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [48]:
data1 = {"NAME" : ["Rudranshi","Sanvi","Swati","Shiva"]}
df = pd.DataFrame(data1)
df["NAME"].apply(lambda x : x.istitle())

0    True
1    True
2    True
3    True
Name: NAME, dtype: bool

In [49]:
d1 = {"Employee":["Saniya","Sara","Alexa","Jenny"]}
df = pd.DataFrame(d1)
d2 = {"Saniya": "Software Developer" , "Sara":"Developer" , "Alexa":"Assistant"}
df["Designation"] = df["Employee"].map(d2)
df

Employee         Designation
0   Saniya  Software Developer
1     Sara           Developer
2    Alexa           Assistant
3    Jenny                 NaN

In [50]:
arr1 = np.random.randint(1,10,size=(5,5))
df = pd.DataFrame(arr1,columns=list("ABCDE"))
df

A  B  C  D  E
0  2  2  6  1  2
1  5  3  9  2  7
2  1  6  6  5  8
3  5  8  1  5  5
4  9  2  5  3  5

In [51]:
df["I"] = [1,2,3,4,5]
df

A  B  C  D  E  I
0  2  2  6  1  2  1
1  5  3  9  2  7  2
2  1  6  6  5  8  3
3  5  8  1  5  5  4
4  9  2  5  3  5  5

In [52]:
df.insert(1,"H",[1,2,1,2,1])
df

A  H  B  C  D  E  I
0  2  1  2  6  1  2  1
1  5  2  3  9  2  7  2
2  1  1  6  6  5  8  3
3  5  2  8  1  5  5  4
4  9  1  2  5  3  5  5

In [53]:
df.drop("A",axis=1,inplace=True)
df

H  B  C  D  E  I
0  1  2  6  1  2  1
1  2  3  9  2  7  2
2  1  6  6  5  8  3
3  2  8  1  5  5  4
4  1  2  5  3  5  5

In [54]:
df.drop(2,axis=0,inplace=True)
df

H  B  C  D  E  I
0  1  2  6  1  2  1
1  2  3  9  2  7  2
3  2  8  1  5  5  4
4  1  2  5  3  5  5

In [55]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([4,5,6,7,8])
s11 = set(s1)
s22 = set(s2)
result = s11.symmetric_difference(s22)
result

{1, 2, 3, 6, 7, 8}

In [56]:
s1 = pd.Series([1,2,3,4,5])
print("Median:",s1.median())
print("Mean:",s1.mean())
print("25th percentile:",s1.quantile(0.25))
print("75th percentile:",s1.quantile(0.75))
print("Minimum:",s1.min())
print("Maximum:",s1.max())

Median: 3.0
Mean: 3.0
25th percentile: 2.0
75th percentile: 4.0
Minimum: 1
Maximum: 5


In [57]:
df = pd.DataFrame(np.random.randint(10,50,size=(4,4)) , columns=list("CABD") , index=list("xzvs"))
df

C   A   B   D
x  49  43  20  46
z  45  26  12  21
v  37  13  39  48
s  28  38  46  27

In [58]:
df.sort_index()

C   A   B   D
s  28  38  46  27
v  37  13  39  48
x  49  43  20  46
z  45  26  12  21

In [59]:
df.sort_index(axis=1)

A   B   C   D
x  43  20  49  46
z  26  12  45  21
v  13  39  37  48
s  38  46  28  27

In [60]:
df.sort_values("D")

C   A   B   D
z  45  26  12  21
s  28  38  46  27
x  49  43  20  46
v  37  13  39  48

In [61]:
df = pd.DataFrame({"A" : [1,1,3,4,5],
                   "B" : [1,1,3,4,5],
                   "C" : [1,1,3,4,5],
                   "D" : [1,1,3,4,5]})
df

A  B  C  D
0  1  1  1  1
1  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [62]:
df.drop_duplicates()

A  B  C  D
0  1  1  1  1
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5

In [63]:
data = {'Full Name': ['John Doe', 'Jane Smith', 'Bob Johnson']}
df = pd.DataFrame(data)
df[["First Name","Last Name"]] = df["Full Name"].str.split(expand=True)
df

Full Name First Name Last Name
0     John Doe       John       Doe
1   Jane Smith       Jane     Smith
2  Bob Johnson        Bob   Johnson

Write a Python function to find the union of two lists, without using any built-in functions.
Expected output:
list1=[1, 2, 3, 4], 
list2=[3, 4, 5, 6]) returns [1, 2, 3, 4, 5, 6]

In [8]:
list1 = [1,2,3,4]
list2 = [3,4,5,6]
result = list(filter(lambda x : x in list1 , list2))
result

[3, 4]

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1   
4                           Allen, Mr. William Henry    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            180
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
df["Age"].fillna(df["Age"].mean(),inplace=True)
df["Age"].isna().sum()

0

In [6]:
movie_dict = {"Movies":["Interstellar","Avengers","Dhoom","Interstellar"],
"Genre":["fiction","Fiction","Comedy","fiction"],
"Actors":["American","French","Indian","American"]}
index_labels = ["a","b","c","d"]
df = pd.DataFrame(movie_dict,index=index_labels)
df

Movies    Genre    Actors
a  Interstellar  fiction  American
b      Avengers  Fiction    French
c         Dhoom   Comedy    Indian
d  Interstellar  fiction  American

In [7]:
df.head(3)

Movies    Genre    Actors
a  Interstellar  fiction  American
b      Avengers  Fiction    French
c         Dhoom   Comedy    Indian

In [8]:
df = pd.read_csv("titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [9]:
df.loc[:1 , ["Name","Age","Gender"]]

Name   Age  Gender
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female

In [10]:
df.loc[[0,1,3,5,7,9] , ["Name","Age","Gender"]]

Name   Age  Gender
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   NaN  female
5                                   Moran, Mr. James   NaN    male
7                     Palsson, Master. Gosta Leonard   2.0    male
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0  female

In [11]:
df.isna()

PassengerId  Survived  Pclass   Name  Gender    Age  SibSp  Parch  \
0          False     False   False  False   False  False  False  False   
1          False     False   False  False   False  False  False  False   
2          False     False   False  False   False   True  False  False   
3          False     False   False  False   False   True  False  False   
4          False     False   False  False   False   True  False  False   
..           ...       ...     ...    ...     ...    ...    ...    ...   
886        False     False   False  False   False  False  False  False   
887        False     False   False  False   False  False  False  False   
888        False     False   False  False   False   True  False  False   
889        False     False   False  False   False  False  False  False   
890        False     False   False  False   False  False  False  False   

     Ticket   Fare  Cabin  Embarked  
0     False  False   True     False  
1     False  False  False     False  
2     False  False   True     False  
3     False  False  False     False  
4     False  False   True     False  
..      ...    ...    ...       ...  
886   False  False   True     False  
887   False  False  False     False  
888   False  False   True     False  
889   False  False  False     False  
890   False  False   True     False  

[891 rows x 12 columns]

In [12]:
df.isna().sum().to_dict()

{'PassengerId': 0,
 'Survived': 0,
 'Pclass': 0,
 'Name': 0,
 'Gender': 0,
 'Age': 180,
 'SibSp': 0,
 'Parch': 0,
 'Ticket': 0,
 'Fare': 0,
 'Cabin': 687,
 'Embarked': 2}

In [13]:
df.isnull().sum().to_dict()

{'PassengerId': 0,
 'Survived': 0,
 'Pclass': 0,
 'Name': 0,
 'Gender': 0,
 'Age': 180,
 'SibSp': 0,
 'Parch': 0,
 'Ticket': 0,
 'Fare': 0,
 'Cabin': 687,
 'Embarked': 2}

In [14]:
df.dropna()

PassengerId  Survived  Pclass  \
1              2         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
21            22         1       2   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name  Gender   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
21                               Beesley, Mr. Lawrence    male  34.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
21       0    248698  13.0000          D56        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[182 rows x 12 columns]

In [15]:
df = pd.read_csv("titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [16]:
df.isna().sum().sum()

869

In [17]:
df["Age"].fillna(40,inplace=True)
df["Age"].isna().sum()

0

In [18]:
df = pd.read_csv("titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [19]:
df["Age"].fillna(df["Age"].mean(), inplace=True)
df["Age"].isna().sum()

0

In [20]:
df = pd.read_csv("titanic.csv")
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [21]:
result = df["Age"].isna().to_numpy().nonzero()
result

(array([  2,   3,   4,   5,  17,  19,  26,  28,  29,  31,  32,  36,  42,
         45,  46,  47,  48,  55,  64,  65,  76,  77,  82,  87,  95, 101,
        107, 109, 121, 126, 128, 140, 154, 158, 159, 166, 168, 176, 180,
        181, 185, 186, 196, 198, 201, 214, 223, 229, 235, 240, 241, 250,
        256, 260, 264, 270, 274, 277, 284, 295, 298, 300, 301, 303, 304,
        306, 324, 330, 334, 335, 347, 351, 354, 358, 359, 364, 367, 368,
        375, 384, 388, 409, 410, 411, 413, 415, 420, 425, 428, 431, 444,
        451, 454, 457, 459, 464, 466, 468, 470, 475, 481, 485, 490, 495,
        497, 502, 507, 511, 517, 522, 524, 527, 531, 533, 538, 547, 552,
        557, 560, 563, 564, 568, 573, 578, 584, 589, 593, 596, 598, 601,
        602, 611, 612, 613, 629, 633, 639, 643, 648, 650, 653, 656, 667,
        669, 674, 680, 692, 697, 709, 711, 718, 727, 732, 738, 739, 740,
        760, 766, 768, 773, 776, 778, 783, 790, 792, 793, 815, 825, 826,
        828, 832, 837, 839, 846, 849, 859, 863, 868

In [22]:
female = df.groupby(df["Gender"]).get_group("female")
female

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
880          881         1       2   
882          883         0       3   
885          886         0       3   
887          888         1       1   
888          889         0       3   

                                                  Name  Gender   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female   NaN      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
880      1            230433  26.0000   NaN        S  
882      0              7552  10.5167   NaN        S  
885      5            382652  29.1250   NaN        Q  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  

[314 rows x 12 columns]

In [23]:
s = df.groupby(df["Embarked"]).get_group("S")
s

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
..           ...       ...     ...   
883          884         0       2   
884          885         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   

                                             Name  Gender   Age  SibSp  Parch  \
0                         Braund, Mr. Owen Harris    male  22.0      1      0   
2                          Heikkinen, Miss. Laina  female   NaN      0      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   NaN      1      0   
4                        Allen, Mr. William Henry    male   NaN      0      0   
6                         McCarthy, Mr. Timothy J    male  54.0      0      0   
..                                            ...     ...   ...    ...    ...   
883                 Banfield, Mr. Frederick James    male  28.0      0      0   
884                        Sutehall, Mr. Henry Jr    male  25.0      0      0   
886                         Montvila, Rev. Juozas    male  27.0      0      0   
887                  Graham, Miss. Margaret Edith  female  19.0      0      0   
888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500   NaN        S  
2    STON/O2. 3101282   7.9250   NaN        S  
3              113803  53.1000  C123        S  
4              373450   8.0500   NaN        S  
6               17463  51.8625   E46        S  
..                ...      ...   ...      ...  
883  C.A./SOTON 34068  10.5000   NaN        S  
884   SOTON/OQ 392076   7.0500   NaN        S  
886            211536  13.0000   NaN        S  
887            112053  30.0000   B42        S  
888        W./C. 6607  23.4500   NaN        S  

[644 rows x 12 columns]

In [24]:
df = pd.read_csv("diabetes.csv")
df.head(3)

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             50             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   52        1

In [25]:
df.loc[ : , ["Age","Outcome","BMI","Glucose"]]

Age  Outcome   BMI  Glucose
0     50        1  33.6      148
1     31        0  26.6       85
2     52        1  23.3      183
3     21        0  28.1      150
4     33        1  43.1      150
..   ...      ...   ...      ...
763   63        0  32.9      101
764   27        0  36.8      122
765   30        0  26.2      121
766   47        1  30.1      126
767   23        0  30.4       93

[768 rows x 4 columns]

In [26]:
df.reindex(["Age","Outcome","BMI","Glucose"],axis=1)

Age  Outcome   BMI  Glucose
0     50        1  33.6      148
1     31        0  26.6       85
2     52        1  23.3      183
3     21        0  28.1      150
4     33        1  43.1      150
..   ...      ...   ...      ...
763   63        0  32.9      101
764   27        0  36.8      122
765   30        0  26.2      121
766   47        1  30.1      126
767   23        0  30.4       93

[768 rows x 4 columns]

In [28]:
df = pd.read_csv("student.csv")
df

id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [29]:
df.loc[35] = [36 , "Honny" , "five" ,45 , "male"]
df

id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female
35  36        Honny   five    45    male

In [30]:
df.drop((df.loc[(df["mark"] < 50)]).index)

id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [31]:
df.iloc[[5],]

id       name class  mark gender
5   6  Alex John  Four    55   male

In [32]:
df.iloc[:5]

id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [33]:
class1 = {class1 : len(class1) for class1 in df["class"]}
class1

{'Four': 4,
 'Three': 5,
 'Fifth': 5,
 'Five': 4,
 'Six': 3,
 'Seven': 5,
 'Nine': 4,
 'Eight': 5,
 'five': 4}

In [34]:
df["name"] = df["name"].apply(lambda x : x.swapcase())
df

id         name  class  mark  gender
0    1     jOHN dEO   Four    75  female
1    2     mAX rUIN  Three    85    male
2    3       aRNOLD  Three    55    male
3    4   kRISH sTAR   Four    60  female
4    5    jOHN mIKE   Four    60  female
5    6    aLEX jOHN   Four    55    male
6    7  mY jOHN rOB  Fifth    78    male
7    8       aSRUID   Five    85    male
8    9      tES qRY    Six    78    male
9   10     bIG jOHN   Four    55  female
10  11       rONALD    Six    89  female
11  12        rECKY    Six    94  female
12  13          kTY  Seven    88  female
13  14         bIGY  Seven    88  female
14  15     tADE rOW   Four    88    male
15  16        gIMMY   Four    88    male
16  17        tUMYU    Six    54    male
17  18        hONNY   Five    75    male
18  19        tINNY   Nine    18    male
19  20       jACKLY   Nine    65  female
20  21   bABBY jOHN   Four    69  female
21  22       rEGGID  Seven    55  female
22  23        hEROD  Eight    79    male
23  24    tIDDY nOW  Seven    78    male
24  25     gIFF tOW  Seven    88    male
25  26       cRELEA  Seven    79    male
26  27     bIG nOSE  Three    81  female
27  28    rOJJ bASE  Seven    86  female
28  29  tESS pLAYED  Seven    55    male
29  30    rEPPY rED    Six    79  female
30  31  mARRY tOEEY   Four    88    male
31  32    bINN rOTT  Seven    90  female
32  33    kENN rEIN    Six    96  female
33  34     gAIN tOE  Seven    69    male
34  35   rOWS nOUMP    Six    88  female
35  36        hONNY   five    45    male

In [35]:
df["name"] = df["name"].apply(lambda x : x.lower())
df

id         name  class  mark  gender
0    1     john deo   Four    75  female
1    2     max ruin  Three    85    male
2    3       arnold  Three    55    male
3    4   krish star   Four    60  female
4    5    john mike   Four    60  female
5    6    alex john   Four    55    male
6    7  my john rob  Fifth    78    male
7    8       asruid   Five    85    male
8    9      tes qry    Six    78    male
9   10     big john   Four    55  female
10  11       ronald    Six    89  female
11  12        recky    Six    94  female
12  13          kty  Seven    88  female
13  14         bigy  Seven    88  female
14  15     tade row   Four    88    male
15  16        gimmy   Four    88    male
16  17        tumyu    Six    54    male
17  18        honny   Five    75    male
18  19        tinny   Nine    18    male
19  20       jackly   Nine    65  female
20  21   babby john   Four    69  female
21  22       reggid  Seven    55  female
22  23        herod  Eight    79    male
23  24    tiddy now  Seven    78    male
24  25     giff tow  Seven    88    male
25  26       crelea  Seven    79    male
26  27     big nose  Three    81  female
27  28    rojj base  Seven    86  female
28  29  tess played  Seven    55    male
29  30    reppy red    Six    79  female
30  31  marry toeey   Four    88    male
31  32    binn rott  Seven    90  female
32  33    kenn rein    Six    96  female
33  34     gain toe  Seven    69    male
34  35   rows noump    Six    88  female
35  36        honny   five    45    male

In [36]:
list1 = ['Amir ',' Ashwin',' Bhakti ',' Amol','Aishwarya ','Satyam ']
s1 = pd.Series(list1)
s1

0         Amir 
1        Ashwin
2       Bhakti 
3          Amol
4    Aishwarya 
5       Satyam 
dtype: object

In [37]:
s1 = s1.apply(lambda x : x.strip())
s1

0         Amir
1       Ashwin
2       Bhakti
3         Amol
4    Aishwarya
5       Satyam
dtype: object

In [38]:
s1.to_numpy().tolist()

['Amir', 'Ashwin', 'Bhakti', 'Amol', 'Aishwarya', 'Satyam']

In [39]:
data = {'year': [1700, 1850, 2000, 2300, 1950]}
df = pd.DataFrame(data)

result = df[(df["year"] >= 1800) & (df["year"] <= 2200)]
result

year
1  1850
2  2000
4  1950

In [41]:
df1 = pd.DataFrame(np.random.randint(1,10,(3,3)),columns=list('ABC'),index=list('pqr'))
df2 = pd.DataFrame(np.random.randint(100,1000,(4,4)),columns=list('ABCD'),index=list('pqrs'))
df1

A  B  C
p  2  9  3
q  6  2  7
r  7  5  1

In [42]:
df2

A    B    C    D
p  877  719  781  313
q  468  966  629  669
r  290  235  874  829
s  496  553  871  979

In [44]:
pd.concat([df1,df2])

A    B    C      D
p    2    9    3    NaN
q    6    2    7    NaN
r    7    5    1    NaN
p  877  719  781  313.0
q  468  966  629  669.0
r  290  235  874  829.0
s  496  553  871  979.0

In [45]:
pd.concat([df1,df2],axis=1)

A    B    C    A    B    C    D
p  2.0  9.0  3.0  877  719  781  313
q  6.0  2.0  7.0  468  966  629  669
r  7.0  5.0  1.0  290  235  874  829
s  NaN  NaN  NaN  496  553  871  979

In [46]:
df1=pd.DataFrame({"Name":["Aarathi","Veena","Lakshmipriya","Sriyan"],
"Age":[23,54,34,67],
"Location":["Pune","Bangalore","Pune","Kochi"]})
df2=pd.DataFrame({"Name":["Aara","Anupama","Robin","Dilsha","Ramya"],
"Age":[23,54,34,67,45],
"Maths":[34,45,50,49,46],
"English":[50,49,48,34,89],
"Hindi":[40,45,50,34,67]})
df3=pd.DataFrame({"Name":["Aarathi","Veena","Sriyan","Dilsha","Arohi"],
"Salary":[80000,70000,90000,780000,90000]})
df1

Name  Age   Location
0       Aarathi   23       Pune
1         Veena   54  Bangalore
2  Lakshmipriya   34       Pune
3        Sriyan   67      Kochi

In [47]:
df2

Name  Age  Maths  English  Hindi
0     Aara   23     34       50     40
1  Anupama   54     45       49     45
2    Robin   34     50       48     50
3   Dilsha   67     49       34     34
4    Ramya   45     46       89     67

In [48]:
df3

Name  Salary
0  Aarathi   80000
1    Veena   70000
2   Sriyan   90000
3   Dilsha  780000
4    Arohi   90000

In [49]:
concat_df = pd.concat([df1,df2])
concat_df

Name  Age   Location  Maths  English  Hindi
0       Aarathi   23       Pune    NaN      NaN    NaN
1         Veena   54  Bangalore    NaN      NaN    NaN
2  Lakshmipriya   34       Pune    NaN      NaN    NaN
3        Sriyan   67      Kochi    NaN      NaN    NaN
0          Aara   23        NaN   34.0     50.0   40.0
1       Anupama   54        NaN   45.0     49.0   45.0
2         Robin   34        NaN   50.0     48.0   50.0
3        Dilsha   67        NaN   49.0     34.0   34.0
4         Ramya   45        NaN   46.0     89.0   67.0

In [50]:
result = pd.merge(concat_df,df3,on="Name")
result

Name  Age   Location  Maths  English  Hindi  Salary
0  Aarathi   23       Pune    NaN      NaN    NaN   80000
1    Veena   54  Bangalore    NaN      NaN    NaN   70000
2   Sriyan   67      Kochi    NaN      NaN    NaN   90000
3   Dilsha   67        NaN   49.0     34.0   34.0  780000

In [51]:
df1 = pd.DataFrame({"Name":["Aarathi","Veena","Lakshmipriya","Amit","Sriyan"],
"ID_card":['BSL004','BSL006','BSL010','BSL003','BSL007'],
"Physics":[94,86,73,96,75],
"Cemistry":[85,91,89,78,81]})
df2 = pd.DataFrame({"Name":["Aarathi","Veena","Manoj","Lakshmipriya","Sriyan"],
"ID_card":['BSL001','BSL005','BSL009','BSL008','BSL002'],
"Maths":[88,72,69,97,45],
"Biology":[98,75,86,61,64]})
df1

Name ID_card  Physics  Cemistry
0       Aarathi  BSL004       94        85
1         Veena  BSL006       86        91
2  Lakshmipriya  BSL010       73        89
3          Amit  BSL003       96        78
4        Sriyan  BSL007       75        81

In [52]:
df2

Name ID_card  Maths  Biology
0       Aarathi  BSL001     88       98
1         Veena  BSL005     72       75
2         Manoj  BSL009     69       86
3  Lakshmipriya  BSL008     97       61
4        Sriyan  BSL002     45       64

In [53]:
result = pd.merge(df1,df2,on="Name",suffixes=["_df1","_df2"])
result

Name ID_card_df1  Physics  Cemistry ID_card_df2  Maths  Biology
0       Aarathi      BSL004       94        85      BSL001     88       98
1         Veena      BSL006       86        91      BSL005     72       75
2  Lakshmipriya      BSL010       73        89      BSL008     97       61
3        Sriyan      BSL007       75        81      BSL002     45       64

In [54]:
result = pd.merge(df1,df2,on="Name",how="left",suffixes=["_df1","_df2"])
result

Name ID_card_df1  Physics  Cemistry ID_card_df2  Maths  Biology
0       Aarathi      BSL004       94        85      BSL001   88.0     98.0
1         Veena      BSL006       86        91      BSL005   72.0     75.0
2  Lakshmipriya      BSL010       73        89      BSL008   97.0     61.0
3          Amit      BSL003       96        78         NaN    NaN      NaN
4        Sriyan      BSL007       75        81      BSL002   45.0     64.0

In [55]:
result = pd.merge(df1,df2,on="Name",how="right",suffixes=["_df1","_df2"])
result

Name ID_card_df1  Physics  Cemistry ID_card_df2  Maths  Biology
0       Aarathi      BSL004     94.0      85.0      BSL001     88       98
1         Veena      BSL006     86.0      91.0      BSL005     72       75
2         Manoj         NaN      NaN       NaN      BSL009     69       86
3  Lakshmipriya      BSL010     73.0      89.0      BSL008     97       61
4        Sriyan      BSL007     75.0      81.0      BSL002     45       64

In [56]:
english_df = pd.DataFrame({'Name':['Amir','Salman','Maaz','Tanvir','Fahad'],
'Surname':['Arkar','Mulla','Surve','Kadvekar','Antule'],
'Marks':[94,86,91,93,88]})
maths_df = pd.DataFrame({'Name':['Amir','Salman','Maaz','Tanvir','Fahad'],
'Surname':['Khan','Mulla','Hafiz','Kadvekar','Shaikh'],
'Marks':[91,89,93,87,84]})
english_df

Name   Surname  Marks
0    Amir     Arkar     94
1  Salman     Mulla     86
2    Maaz     Surve     91
3  Tanvir  Kadvekar     93
4   Fahad    Antule     88

In [57]:
maths_df

Name   Surname  Marks
0    Amir      Khan     91
1  Salman     Mulla     89
2    Maaz     Hafiz     93
3  Tanvir  Kadvekar     87
4   Fahad    Shaikh     84

In [58]:
result = pd.merge(english_df,maths_df,how="inner",on=["Name","Surname"],suffixes=["_eng","_math"])
result

Name   Surname  Marks_eng  Marks_math
0  Salman     Mulla         86          89
1  Tanvir  Kadvekar         93          87

In [59]:
physics_df = pd.DataFrame({'Name_1':['Amir','Salman','Maaz','Karim','Fahad'],
'Surname':['Arkar','Mulla','Surve','Kadvekar','Antule'],
'Marks':[94,86,91,93,88]})
chemistry_df = pd.DataFrame({'Name_2':['Asif','Salman','Maaz','Tanvir','Fahad'],
'Surname':['Khan','Mulla','Hafiz','Rawal','Shaikh'],
'Marks':[91,89,93,87,84]})
physics_df

Name_1   Surname  Marks
0    Amir     Arkar     94
1  Salman     Mulla     86
2    Maaz     Surve     91
3   Karim  Kadvekar     93
4   Fahad    Antule     88

In [60]:
chemistry_df

Name_2 Surname  Marks
0    Asif    Khan     91
1  Salman   Mulla     89
2    Maaz   Hafiz     93
3  Tanvir   Rawal     87
4   Fahad  Shaikh     84

In [61]:
result = pd.merge(physics_df,chemistry_df,how="inner",left_on="Name_1",right_on="Name_2",
                  suffixes=["_1","_2"])
result

Name_1 Surname_1  Marks_1  Name_2 Surname_2  Marks_2
0  Salman     Mulla       86  Salman     Mulla       89
1    Maaz     Surve       91    Maaz     Hafiz       93
2   Fahad    Antule       88   Fahad    Shaikh       84

In [62]:
df = pd.read_csv("movies_data.csv")
df.head(3)

star_rating                     title content_rating  genre  duration  \
0          9.3  The Shawshank Redemption              R  Crime       142   
1          9.2             The Godfather              R  Crime       175   
2          9.1    The Godfather: Part II              R  Crime       200   

                                         actors_list  
0  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1    [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...

In [64]:
result = df.sort_values("duration",ignore_index=True,ascending=False)
result

star_rating                              title content_rating      genre  \
0            7.8                             Hamlet          PG-13      Drama   
1            8.2                 Gone with the Wind              G      Drama   
2            8.4        Once Upon a Time in America              R      Crime   
3            8.3  Lagaan: Once Upon a Time in India             PG  Adventure   
4            7.9               The Ten Commandments       APPROVED  Adventure   
..           ...                                ...            ...        ...   
974          8.1                          Duck Soup         PASSED     Comedy   
975          8.4                            The Kid      NOT RATED     Comedy   
976          8.1        The Cabinet of Dr. Caligari        UNRATED      Crime   
977          8.0                Battleship Potemkin        UNRATED    History   
978          8.0                             Freaks        UNRATED      Drama   

     duration                                        actors_list  
0         242  [u'Kenneth Branagh', u'Julie Christie', u'Dere...  
1         238  [u'Clark Gable', u'Vivien Leigh', u'Thomas Mit...  
2         229  [u'Robert De Niro', u'James Woods', u'Elizabet...  
3         224  [u'Aamir Khan', u'Gracy Singh', u'Rachel Shell...  
4         220  [u'Charlton Heston', u'Yul Brynner', u'Anne Ba...  
..        ...                                                ...  
974        68    [u'Groucho Marx', u'Harpo Marx', u'Chico Marx']  
975        68  [u'Charles Chaplin', u'Edna Purviance', u'Jack...  
976        67  [u'Werner Krauss', u'Conrad Veidt', u'Friedric...  
977        66  [u'Aleksandr Antonov', u'Vladimir Barsky', u'G...  
978        64  [u'Wallace Ford', u'Leila Hyams', u'Olga Bacla...  

[979 rows x 6 columns]

In [65]:
result = df["duration"].max()
result

242

In [66]:
result = df["duration"].min()
result

64

In [67]:
result = df.loc[(df["genre"] == "Action") | (df["genre"] == "Crime")].reset_index(drop=True)
result

star_rating                                            title  \
0            9.3                         The Shawshank Redemption   
1            9.2                                    The Godfather   
2            9.1                           The Godfather: Part II   
3            9.0                                  The Dark Knight   
4            8.9                                     Pulp Fiction   
..           ...                                              ...   
255          7.4                                  La Femme Nikita   
256          7.4                                         The Rock   
257          7.4                              Law Abiding Citizen   
258          7.4  Master and Commander: The Far Side of the World   
259          7.4                                      Wall Street   

    content_rating   genre  duration  \
0                R   Crime       142   
1                R   Crime       175   
2                R   Crime       200   
3            PG-13  Action       152   
4                R   Crime       154   
..             ...     ...       ...   
255              R  Action       118   
256              R  Action       136   
257              R   Crime       109   
258          PG-13  Action       138   
259              R   Crime       126   

                                           actors_list  
0    [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1      [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2    [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3    [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4    [u'John Travolta', u'Uma Thurman', u'Samuel L....  
..                                                 ...  
255  [u'Anne Parillaud', u'Marc Duret', u'Patrick F...  
256   [u'Sean Connery', u'Nicolas Cage', u'Ed Harris']  
257  [u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']  
258  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...  
259  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...  

[260 rows x 6 columns]

In [68]:
city_df = pd.DataFrame({'Name':['Amir','Shaibaz','Suhel','Fahad','Adil','Muzaffar','Shuaib','Asif','Awez','Muzammil'],
'City':['Georgia','California','Los Angeles','California','Los Angeles','Georgia','Los Angeles',
'California','Los Angeles','California']})
city_df

Name         City
0      Amir      Georgia
1   Shaibaz   California
2     Suhel  Los Angeles
3     Fahad   California
4      Adil  Los Angeles
5  Muzaffar      Georgia
6    Shuaib  Los Angeles
7      Asif   California
8      Awez  Los Angeles
9  Muzammil   California

In [69]:
city_df.groupby(city_df["City"]).size().reset_index(name = "Number of people")

City  Number of people
0   California                 4
1      Georgia                 2
2  Los Angeles                 4

In [70]:
df = pd.read_csv("Bengaluru_House_Data.csv")
df.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [71]:
df.fillna(0)

area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II   
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society total_sqft  bath  balcony   price  
0          2 BHK  Coomee        1056   2.0      1.0   39.07  
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00  
2          3 BHK        0       1440   2.0      3.0   62.00  
3          3 BHK  Soiewre       1521   3.0      1.0   95.00  
4          2 BHK        0       1200   2.0      1.0   51.00  
...          ...      ...        ...   ...      ...     ...  
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00  
13316      4 BHK        0       3600   5.0      0.0  400.00  
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00  
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00  
13319      1 BHK        0        550   1.0      1.0   17.00  

[13320 rows x 9 columns]

In [72]:
df = pd.DataFrame({'col1':[1,4,3,4,5],
'col2':[4,5,6,7,8],
'col3':[7,8,9,0,1]})
df

col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1

In [73]:
result = df.drop([0,2,4])
result

col1  col2  col3
1     4     5     8
3     4     7     0

In [1]:
input_string = input("Enter a string:")
for i in input_string:
    print(i)

A
b
h
i
s
h
e
k


In [2]:
string = "Machine Learning"
result = len(string)
result

16

In [3]:
string = "Machine Learning"
count1 = 0
for i in string:
    count1 += 1
count1

16

In [4]:
sentence = "This is orange juice"
keyword = "orange"

if keyword in sentence:
    print(f"{keyword} in sentence")
else:
    print(f"{keyword} not in sentence")

orange in sentence


In [5]:
input_string = input("Enter a string:")
vowels = "aeiou"
consonants = "bcdfghjklmnpqrstvwxyz"
digits = "0123456789"
vowel_count = 0 
consonant_count = 0
digit_count = 0
whitespace_count = 0 
for i in input_string:
    if i.lower() in vowels:
        vowel_count += 1
    elif i.lower() in consonants:
        consonant_count += 1
    elif i in digits:
        digit_count += 1
    elif i.isspace():
        whitespace_count += 1
print("Vowels count : ", vowel_count)
print("Consonant count : ", consonant_count)
print("Digit count : ", digit_count)
print("Whitespace count : ", whitespace_count)

Vowels count :  7
Consonant count :  10
Digit count :  4
Whitespace count :  2


In [6]:
input_string = input("Enter a string:")
uppercase_count = 0 
lowercase_count = 0 
special_count = 0
numeric_count = 0
for i in input_string:
    if i.islower():
        lowercase_count += 1
    elif i.isupper():
        uppercase_count += 1
    elif i.isdigit():
        numeric_count += 1
    else:
        special_count += 1
print("Upper case count: ", uppercase_count)
print("Lower case count: ",lowercase_count)
print("Special count: ",special_count)
print("Number of digits: ",numeric_count)

Upper case count:  1
Lower case count:  7
Special count:  1
Number of digits:  4


In [7]:
input_string = "Hello,have a good day"
vowels = "aeiouAEIOU"
new_string = ""
for i in input_string:
    if i.isalpha() and i in vowels:
        new_string += i
print("original string:",input_string)
print("New string with consonants deleted:",new_string)

original string: Hello,have a good day
New string with consonants deleted: eoaeaooa


In [8]:
input_string = input("Enter a string:")
index = int(input("Enter the index of the character to be removed:"))

if index < 0 or index > len(input_string):
    print("Invalid index")
else:
    new_string = input_string[:index] + input_string[index + 1:]
    print("Original string: ", input_string)
    print("New string with index removed: ", new_string)

Original string:  Abhishek
New string with index removed:  Abhshek


In [9]:
input_string = input("Enter a string:")
if len(input_string) < 2:
    print("String should have at least two characters")
else:
    new_string = input_string[-1] + input_string[1:-1] + input_string[0]
    print("Original string: ", input_string)
    print("String with first and last characters exchanged: ", new_string)

Original string:  Abhishek
String with first and last characters exchanged:  kbhisheA


In [10]:
s = str(input("Enter a string: "))
word = ""
for i in s:
    word = i
    count1 = s.count(word)
    print(f"In the gievn string {word} has been repeated {count1} times")

In the gievn string A has been repeated 1 times
In the gievn string b has been repeated 1 times
In the gievn string h has been repeated 2 times
In the gievn string i has been repeated 1 times
In the gievn string s has been repeated 1 times
In the gievn string h has been repeated 2 times
In the gievn string e has been repeated 1 times
In the gievn string k has been repeated 1 times


In [11]:
s = str(input("Enter a string:"))
ss = s.split()
for i in ss:
    if i in ss:
        ss.count(i)
        print(f"{i} : {s.count(i)}")
    else:
        print("Word is not repeated")        

Abhishek : 1
Wakchaure : 1


In [12]:
input_string = input("Enter a string:")
result = input_string[-10:]
result

' Wakchaure'

In [13]:
input_string = input("Enter a string:")
uppercase_count = 0
for i in input_string[:4]:
    if i.isupper():
        uppercase_count += 1
if uppercase_count >= 2:
    result = input_string.upper()
    print("Uppercase string:", result)
else:
    print("No conversion required")

No conversion required


In [14]:
input_string = "32.054,23"
result = input_string.replace(".","*").replace(",",".").replace("*",",")
result

'32,054.23'

In [15]:
input_string = input("Enter a string:")
char_count = {}
for i in input_string:
    if i in char_count:
        print("First repeated character:",i)
        break
    char_count[i] = 1
else:
    print("No repeated character found")

First repeated character: h


In [16]:
input_string = input("Enter a string:")
even_count = 0 
odd_count = 0

for i in input_string:
    if i.isdigit():
        num = int(i)
        if num % 2 == 0:
            even_count += 1
        else:
            odd_count += 1
print("Even numbers count :",even_count)
print("odd number count :",odd_count)

Even numbers count : 3
odd number count : 4


In [17]:
input_string = input("Enter a string:")
if input_string.isdigit() == True:
    print("String contains only digits")
else:
    print("String contains alphanumeric characters")

String contains alphanumeric characters


In [18]:
a = "Abhishek"
k = []
for i in a:
    if a.index(i)%2!=0:
        k.append(i)
k

['b', 'i', 'k']

In [19]:
input_string = input("Enter a string:")
if len(input_string)%5==0:
    result = input_string[::-1]
    print(result)
else:
    print("Length is not a multiple of 5")

Length is not a multiple of 5


In [21]:
input_string = str(input("Enter a string:"))
result = []
for i in input_string:
    if i not in result:
        result.append(i)
result

['A', 'b', 'h', 'i', 's', 'e', 'k']

In [22]:
num = eval(input("Enter a number:"))
for i in range(0,num+1):
    print(i*i)

0
1
4
9
16
25
36
49
64
81
100


In [23]:
num = eval(input("Enter a number:"))
for i in range(0,num+1):
    print(i*i*i)

0
1
8
27
64
125
216
343
512
729
1000


In [24]:
num = eval(input("Enter a number:"))
for i in range(2,num):
    if num % i == 0:
        print("Not prime")
        break
    else:
        print("Prime")
        break
    

Prime


In [1]:
list1 = [1,2,3,4,5]
max(list1)

5

In [2]:
list1 = [1,2,3,4,5]
max1 = list1[0]
for i in list1:
    if i > max1:
        largest = i
    else:
        largest = max1
largest

5

In [3]:
list1 = [4,5,8,9,5,3,7]
list1.sort()
list1[-1]

9

In [4]:
list1 = [4,5,6,3,8]
list1.sort(reverse=True)
list1[0]

8

In [5]:
list1 = [1,2,3,4,5]
list1[-1:] + list1[1:-1] + list1[:1]

[5, 2, 3, 4, 1]

In [6]:
list1 = [1,2,3,4,5]
list1[0],list1[1] = list1[1],list1[0]
list1

[2, 1, 3, 4, 5]

In [7]:
list1 = [1,2,3,4,5]
list1.reverse()
list1

[5, 4, 3, 2, 1]

In [8]:
list1 = [1,2,3,4,5]
result = reversed(list1)
list(result)

[5, 4, 3, 2, 1]

In [9]:
list1 = [1,2,1,2,1,1,1,3,4,4]
list1.count(1)

5

In [10]:
list1 = [1,2,1,2,1,1,1,3,4,4]
num = 1
count1 = 0
for i in list1:
    if i == num:
        count1 += 1
count1 

5

In [11]:
list1 = [1,2,3,4,5]
sum1 = 0
for i in list1:
    sum1 += i
sum1

15

In [12]:
list1 = [1,2,3,4,5]
mul = 1
for i in list1:
    mul *= i
mul

120

In [13]:
list1 = [1,2,3,4,5]
len(list1)

5

In [14]:
list1 = [1,2,3,4,5]
print(range(len(list1)))

range(0, 5)


In [15]:
list1 = [1,2,3,4,5]
count1 = 0
for i in list1:
    count1 += 1
count1

5

In [16]:
list1 = [1,2,3,4,5]
smallest = list1[2]
for i in range(len(list1)):
    if list1[i] <= smallest:
        smallest = list1[i]
smallest

1

In [17]:
list1 = [1,2,3,4,5]
largest = list1[1]
for i in range(len(list1)):
    if list1[i] >= largest:
        largest = list1[i]
largest

5

In [19]:
list1 = []
num = int(input("How many numbers you want in the list?"))
for i in range(num):
    item = int(input("Enter the number you want in the list:"))
    list1.append(item)
print(list1)

num1 = int(input("Enter the number you want to remove from list:"))
for i in range(len(list1)):
    if num1 == list1[i]:
        list1.remove(num1)
        print("Deleted number from the list:",num1)
        print(list1)
        break
    else:
        print("Number not found in the list")

[1, 2, 3]
Number not found in the list
Deleted number from the list: 2
[1, 3]


In [20]:
list1 = [2,5,6,12]
list2 = []
for i in list1:
    list2.append(i**2)
list2

[4, 25, 36, 144]

In [21]:
list1 = [2,5,6,12]
list2 = []
list2 = [(i**2) for i in list1]
list2

[4, 25, 36, 144]

In [22]:
even_numbers = []
odd_numbers = []
for i in range(0,152):
    if i % 2 == 0:
        even_numbers.append(i)
    else:
        odd_numbers.append(i)
print("Even numbers: ", even_numbers)
print("*"*380)
print("Odd numbers: ", odd_numbers)

Even numbers:  [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150]
********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Odd numbers:  [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127

In [23]:
even_numbers = []
even_count = 0 
odd_numbers = []
odd_count = 0
for i in range(0,152):
    if i % 2 == 0:
        even_numbers.append(i)
        even_count += 1
    else:
        odd_numbers.append(i)
        odd_count += 1
print("Even numbers:", even_numbers)
print("*"*500)
print("Even count of numbers:", even_count)
print()
print()
print("Odd numbers:", odd_numbers)
print("*"*500)
print("Odd count of numbers:", odd_count)

Even numbers: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150]
********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Even count of numbers: 76


Odd numbers: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61

In [24]:
l1=[1,2,3,"hello","welcome",4.12,5.35]
int_list = []
string_list = []
float_list = []
for i in l1:
    if type(i) == int:
        int_list.append(i)
    elif type(i) == float:
        float_list.append(i)
    elif type(i) == str:
        string_list.append(i)
print("Integer list: ", int_list)
print()
print("Float list: ", float_list)
print()
print("String list: ", string_list)

Integer list:  [1, 2, 3]

Float list:  [4.12, 5.35]

String list:  ['hello', 'welcome']


In [25]:
l1=[1,2,3,4]
l2=[4,5,6,7]
l1.extend(l2)
l1

[1, 2, 3, 4, 4, 5, 6, 7]

In [26]:
l1=[10, 2, 4, 5, 6, 2, 9, 1, 7, 5, 4, 11, 30]
result = sorted(l1,reverse=True)
result[2]

10

In [27]:
l1=[1,2,3,4,1,2,3,4]
l2 = {}
for i in l1:
    if i in l2:
        l2[i] += 1
    else:
        l2[i] = 1
l2

{1: 2, 2: 2, 3: 2, 4: 2}

In [28]:
l1=[[1,2,3,4],1,2,3,4]
l2=[1,2,3,4]
if l2 in l1:
    print("L2 is subset of l1")
else:
    print("L2 is not a subset of l1")

L2 is subset of l1


In [29]:
l1=[10,20,30,40]
l2=[10,20,30,50]
result = set(l1) & set(l2)
result

{10, 20, 30}

In [30]:
l1=[[1,2,3],[4,5,6],[7,8,9]]
from itertools import chain
result = list(chain(*l1))
result

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
tuple1 = (2,5,3,1,6,8,4)
result = sorted(tuple1)
result

[1, 2, 3, 4, 5, 6, 8]

In [32]:
l1 = [11, 33, 50]
for i in l1:
    print(i,end="")

113350

In [33]:
l1 = [1]
if l1 == []:
    print("List is empty")
else:
    print("List is not empty")

List is not empty


In [34]:
l1=[1,2,3]
l2=[4,5,6]
l1+l2

[1, 2, 3, 4, 5, 6]

In [35]:
l1=[1,2,3,1,2,3,4,5,6,4,5,6]
l1.count(1)

2

input = my name is adam 
 
output = ym eman si mada
 

In [2]:
input1 = "my name is adam"
final = input1.split()
print(final)

['my', 'name', 'is', 'adam']


In [6]:
list1 = []
for i in final:
    item = i[::-1]
    list1.append(item)
result = " ".join(list1)
result

'ym eman si mada'

In [2]:
key_value={'l':11,'o':89,'a':88,'d':42,'p':5}
result = dict(sorted(key_value.items(),key=lambda x : x[0]))
result

{'a': 88, 'd': 42, 'l': 11, 'o': 89, 'p': 5}

In [3]:
dt = {'aa':44, 'bb':6, 'cc':3,'dd':12}
result = dict(sorted(dt.items(),key=lambda x : x[1]))
result

{'cc': 3, 'bb': 6, 'dd': 12, 'aa': 44}

In [4]:
dt = {'aa':44, 'bb':6, 'cc':3,'dd':12}
result = dt.values()
sum(result)

65

In [5]:
dt = {'aa':44, 'bb':6, 'cc':3,'dd':12}
sum1 = 0
for i in dt.values():
    sum1 += i
sum1

65

In [6]:
test_dict = {"Arushi": 22, "Mani": 21, "Haritha": 21}
del test_dict["Mani"]
test_dict

{'Arushi': 22, 'Haritha': 21}

In [8]:
test_dict = {"Arushi": 22, "Mani": 21, "Haritha": 21}
test_dict.pop("Arushi")
test_dict

{'Mani': 21, 'Haritha': 21}

In [9]:
d1= {"Arushi": 22, "Mani": 21, "Haritha": 21,'Leena':32}
d2={'aa':44, 'bb':6, 'cc':3,'dd':12}
result = {**d1,**d2}
result

{'Arushi': 22,
 'Mani': 21,
 'Haritha': 21,
 'Leena': 32,
 'aa': 44,
 'bb': 6,
 'cc': 3,
 'dd': 12}

In [10]:
d1= {"Arushi": 22, "Mani": 21, "Haritha": 21,'Leena':32}
d2={'aa':44, 'bb':6, 'cc':3,'dd':12}
result = {**d2,**d1}
result

{'aa': 44,
 'bb': 6,
 'cc': 3,
 'dd': 12,
 'Arushi': 22,
 'Mani': 21,
 'Haritha': 21,
 'Leena': 32}

In [11]:
d1= {"Arushi": 22, "Mani": 21, "Haritha": 21,'Leena':32}
d2={'aa':44, 'bb':6, 'cc':3,'dd':12}
d1.update(d2)
d1

{'Arushi': 22,
 'Mani': 21,
 'Haritha': 21,
 'Leena': 32,
 'aa': 44,
 'bb': 6,
 'cc': 3,
 'dd': 12}

In [12]:
d1= {"Arushi": 22, "Mani": 21, "Haritha": 21,'Leena':32}
d2={'aa':44, 'bb':6, 'cc':3,'dd':12}
d2.update(d1)
d2

{'aa': 44,
 'bb': 6,
 'cc': 3,
 'dd': 12,
 'Arushi': 22,
 'Mani': 21,
 'Haritha': 21,
 'Leena': 32}

In [13]:
def calc(percent):
    if percent >= 90:
        return "A+"
    elif 80 <= percent < 90:
        return "A"
    elif 70 <= percent < 80:
        return "B"
    elif 60 <= percent < 70:
        return "C"
    elif 50 <= percent < 60:
        return "D"
    else:
        return "Fail"
def main():
    total_marks = 0
    np_of_subjects = int(input("Enter the number of subjects:"))

    for i in range(np_of_subjects):
        marks = eval(input("Enter the marks of the subject:"))
        total_marks += marks

    average_percent = total_marks / np_of_subjects
    grade = calc(average_percent)
    print(f"Percentage recieved by the student is : {average_percent}")
    print(f"Grade recieved by Student is :{grade}")

if __name__ == "__main__":
    main()

Percentage recieved by the student is : 60.0
Grade recieved by Student is :C


In [14]:
words = ["listen", "silent", "enlist", "hello", "world", "act", "cat", "dog", "god"]
anagram_dict = {}
for word in words:
    sorted_words = " ".join(sorted(word))

    if sorted_words in anagram_dict:
        anagram_dict[sorted_words].append(word)
    else:
        anagram_dict[sorted_words] = [word]
anagram_dict.values()

dict_values([['listen', 'silent', 'enlist'], ['hello'], ['world'], ['act', 'cat'], ['dog', 'god']])

In [15]:
def check_bin(num1,num2):
    binary_1 = bin(num1)[2:]
    binary_2 = bin(num2)[2:]

    return sorted(binary_1) == sorted(binary_2)
num1 = 10
num2 = 20
if check_bin(num1,num2):
    print(f"The Binary representation of {num1} and {num2} are anagrams")
else:
    print(f"The Binary representation of {num1} and {num2} are not anagrams")

The Binary representation of 10 and 20 are not anagrams


In [16]:
from collections import Counter
def largest(words):
    words_count = Counter("".join(sorted(word)) for word in words)

    result = max(words_count.values(),default=0)

    return result
word_list = ["listen", "silent", "enlist", "dog", "god", "good"]
final = largest(word_list)
final

3

In [17]:
list1 = [1, 1, 1, 5, 5, 3, 1, 3, 3, 1,4, 4, 4, 2, 2, 2, 2]
freq = {}
for i in list1:
    if i in freq:
        freq[i] += 1
    else:
        freq[i] = 1
freq

{1: 5, 5: 2, 3: 3, 4: 3, 2: 4}

In [18]:
tups = [("akash", 10), ("gaurav", 12), ("anand", 14), 
    ("suraj", 20), ("akhil", 25), ("ashish", 30)]
dict1 = {}
for key,value in tups:
    dict1[key] = value

dict1

{'akash': 10,
 'gaurav': 12,
 'anand': 14,
 'suraj': 20,
 'akhil': 25,
 'ashish': 30}

In [19]:
tups = [("akash", 10), ("gaurav", 12), ("anand", 14), 
    ("suraj", 20), ("akhil", 25), ("ashish", 30)]
result = dict(tups)
result

{'akash': 10,
 'gaurav': 12,
 'anand': 14,
 'suraj': 20,
 'akhil': 25,
 'ashish': 30}

In [20]:
numbers = [2, 3, 4, 5, 6]

result = [(num , num**3) for num in numbers]
result

[(2, 8), (3, 27), (4, 64), (5, 125), (6, 216)]

In [21]:
tuples_list = [(2, 8), (3, 27), (1, 1), (5, 125), (4, 64)]

result = sorted(tuples_list,key=lambda x : x[1])
result

[(1, 1), (2, 8), (3, 27), (4, 64), (5, 125)]

In [1]:
subject_marks = [("English",88) , ("Science",90) , ("Maths",97) , ("Social sciences",82)]
result = sorted(subject_marks,key=lambda x : x[1])
result

[('Social sciences', 82), ('English', 88), ('Science', 90), ('Maths', 97)]

In [2]:
list1 = [{"name" : "Nandini" , "age" : 20} ,
        {"name" : "Manjeet" , "age" : 20} ,
        {"name" : "Nikhil" , "age" : 19}]

result = sorted(list1,key=lambda x : x["age"])
result

[{'name': 'Nikhil', 'age': 19},
 {'name': 'Nandini', 'age': 20},
 {'name': 'Manjeet', 'age': 20}]

In [3]:
list1 = [{"name" : "Nandini" , "age" : 20} ,
        {"name" : "Manjeet" , "age" : 20} ,
        {"name" : "Nikhil" , "age" : 19}]

result = sorted(list1,key=lambda x : x["age"],reverse=True)
result

[{'name': 'Nandini', 'age': 20},
 {'name': 'Manjeet', 'age': 20},
 {'name': 'Nikhil', 'age': 19}]

In [4]:
input_numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

result = [(lambda x : x**2)(num) for num in input_numbers]
result

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [5]:
input_numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

result = [(lambda x : x**3)(num) for num in input_numbers]
result

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [6]:
result = lambda x : True if x.startswith("P") else False
print(result("Python"))

True


In [7]:
result = lambda x : True if x.startswith("P") else False
print(result("NLP"))

False


In [8]:
result = (lambda string : string.isdigit())(string = "12344")
result

True

In [9]:
result = (lambda string : string.isdecimal())(string = "1234")
result

True

In [10]:
result = (lambda string : string.isnumeric())(string = "1234")
result

True

In [11]:
num = 9
f1 = 0
f2 = 1
print(f1,f2,end=" ")
for i in range(2,num):
    f3 = f1 + f2
    f1,f2 = f2,f3
    print(f3,end=" ")

0 1 1 2 3 5 8 13 21 

In [12]:
list1 = [1,2,3,4]
list2 = [3,4,5,6]
result = list(filter(lambda x : x in list1,list2))
result

[3, 4]

In [14]:
list1 = [-1,2,-3,5,7,8,9,-10]
result = lambda list1 : [x for x in list1 if x >= 0] + [x for x in list1 if x < 0]
result(list1)

[2, 5, 7, 8, 9, -1, -3, -10]

In [15]:
array_nums = [1,2,3,5,7,8,9,10]
result = len(list(filter(lambda x : x%2!=0,array_nums)))
result

5

In [16]:
array_nums = [1,2,3,5,7,8,9,10]
result = len(list(filter(lambda x : x%2==0,array_nums)))
result

3

In [17]:
list1 = [1,2,3]
list2 = [4,5,6]
result = list(map(lambda x1,x2 : x1+x2,list1,list2))
result

[5, 7, 9]

In [18]:
list1 = [13,26,38,39,57,15,17]
result = list(filter(lambda x : (x%13==0 or x%19==0),list1))
result

[13, 26, 38, 39, 57]

In [19]:
texts = ["php" , "w3r" , "Python" , "abcd" ,"Java" , "aaa"]

result = list(filter(lambda x : (x=="".join(reversed(x))),texts))
result

['php', 'aaa']

In [20]:
from collections import Counter
texts = ["bcda","abce","cbda","cbea","adcb"]
str1 = "abcd"
result = list(filter(lambda x : (Counter(str1) == Counter(x)),texts))
result

['bcda', 'cbda', 'adcb']

In [21]:
list1 = [2,3,4,5]
result = list(map(lambda x : x*5,list1))
result

[10, 15, 20, 25]

In [22]:
list1 = [-1,-2,3,4]
result = list(filter(lambda list1 : list1 > 0,list1))
sum(result)

7

In [23]:
list1 = [-1,-2,3,4]
result = list(filter(lambda list1 : list1 < 0,list1))
sum(result)

-3

In [24]:
result = lambda list1 : list1 == sorted(list1)
sample_list_1 = [1, 2, 3, 4, 5]
sample_list_2 = [5, 3, 1, 4, 2]
result(sample_list_1)

True

In [25]:
result(sample_list_2)

False

In [26]:
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [2,4,6,8]
result = list(filter(lambda x : x not in list2,list1))
result

[1, 3, 5, 7, 9, 10]

In [27]:
tuple_str = (("223","ABCD","33") , ("1416","EFGH","55") , ("2345","WERT","34"))
result = tuple(map(lambda x : (int(x[0]),int(x[2])),tuple_str))
result

((223, 33), (1416, 55), (2345, 34))

In [28]:
nums = [3,4,5,8,0,3,8,5,0,3,1,5,2,3,4,2]
result = dict(map(lambda x : (x,list(nums).count(x)),nums))
result

{3: 4, 4: 2, 5: 3, 8: 2, 0: 2, 1: 1, 2: 2}

In [30]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]
result = list(map(lambda x1,x2,x3 : x1+x2+x3,l1,l2,l3))
result

[12, 15, 18]

In [31]:
l1 = ["yellow","blue","tricolor"]
result = list(map(list,l1))
result

[['y', 'e', 'l', 'l', 'o', 'w'],
 ['b', 'l', 'u', 'e'],
 ['t', 'r', 'i', 'c', 'o', 'l', 'o', 'r']]

In [32]:
l1 = [12,15,18]
result = list(map(lambda x : x**2,l1))
result

[144, 225, 324]

In [33]:
list1 = [1, 2, 3, 4, 5]
list2 = [5, 4, 3, 2, 1]

result = list(map(lambda x,y : x+y,list1,list2))
result

[6, 6, 6, 6, 6]

In [34]:
list1 = [1, 2, 3, 4, 5]
list2 = [5, 4, 3, 2, 1]

result = list(map(lambda x,y : x-y,list1,list2))
result

[-4, -2, 0, 2, 4]

In [35]:
int_list = [1, 2, 3, 4, 5]

# Given tuple of integers
int_tuple = (6, 7, 8, 9, 10)

result = list(map(lambda x : str(x),int_list))
result

['1', '2', '3', '4', '5']

In [36]:
result = list(map(lambda x : str(x),int_tuple))
result

['6', '7', '8', '9', '10']

In [37]:
num_array = [1, 2, 3, 4, 5]
result = sum(map(lambda x : x,num_array))
result

15

In [38]:
list1 = [1, 2, 3, 4, 5]
list2 = [1, 2, 4, 8, 9]

result = sum(map(lambda x,y : x == y,list1,list2))
result

2

In [39]:
str1 = ["python","machine","learning"]
result = list(map(list,str1))
result

[['p', 'y', 't', 'h', 'o', 'n'],
 ['m', 'a', 'c', 'h', 'i', 'n', 'e'],
 ['l', 'e', 'a', 'r', 'n', 'i', 'n', 'g']]

In [40]:
list_tup = [("python","machine"),("learning","data science")]
result = list(map(" ".join,list_tup))
result

['python machine', 'learning data science']

In [41]:
l1 = [1,2,3]
l2 = [1,2,4,5,6]
result = list(filter(lambda x : x not in l1,l2))
result

[4, 5, 6]

In [42]:
l1 = [1,2,3]
l2 = [1,2,4,5,6]
result = list(filter(lambda x : x in l1,l2))
result

[1, 2]

In [43]:
l1 = [1,2,3]
result = list(filter(lambda x : x%2!=0,l1))
result

[1, 3]

In [44]:
l1 = [1,2,3]
result = list(filter(lambda x : x%2==0,l1))
result

[2]